### ISSUE TITLE
"1 Update Available" and "Update" button after installing all updates

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1001]
The OS Updates item still shows as having an update after all updates have been installed.

**Comment by bigfatbird** [comment]
Probably related: I had an update for ephemeral for me, but was only updateable via command line. Appcenter recognized there was an update, but didn't let me update it and did not show the update. 
The Icon displayed one update available, it went away after I installed the updates via terminal.

**Comment by davidmhewitt** [comment]
A fix for this issue has been merged in #1129.
