### ISSUE TITLE
AppCenter opening automatically on startup

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#1005]
Looks like this regression has popped up. AppCenter launches when the new session begins instead of remaining silent

**Comment by davidmhewitt** [comment]
I'm not able to reproduce this on a reboot or login&logout with AppCenter installed from git checkout, build and install. Is that how it's installed on your computer?

**Comment by danrabbit** [comment]
Must have been something weird on my install. I can't reproduce anymore either. oops.
