### ISSUE TITLE
Handle flatpakref files

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#1006]
We should probably facilitate sideloading of flatpakref files with some kind of warning about apps from untrusted sources

**Comment by cassidyjames** [comment]
When we talked about this in the past we said we could have a lightweight standalone app that handled it. I don't think the whole app store needs to handle sideloading, but something small and lightweight kind of like Eddy but for Flatpak refs could work.

**Comment by cassidyjames** [comment]
Oh yeah and I mocked up a dialog in code at https://github.com/cassidyjames/agents

**Comment by danrabbit** [comment]
Hey that's a great mockup! If it seems like it would be easier to use libflatpak in a standalone app, I'm all for keeping things modular

**Comment by cassidyjames** [comment]
Closing as out of scope since we now have github.com/elementary/sideload
