### ISSUE TITLE
Misaligned Update All button

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#1008]
Somewhere along the line, some extra margin was added somewhere:

![Screenshot from 2019-05-28 09 58 38@2x](https://user-images.githubusercontent.com/7277719/58496733-4efa8e00-812f-11e9-9c53-c9778f25cd14.png)

**Comment by danrabbit** [comment]
It's actually odd because while updating the buttons change size and realign. There's probably some simplification that can be done here with the styling. Probably offloading some styling to the page class instead of adding or removing classes to the button itself

**Comment by jtrees** [comment]
This is a regression, by the way. It does not happen on Loki.
