### ISSUE TITLE
Differentiate between "OS Updates" and "Other"

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1015]
Right now anything without proper appdata gets lumped into "Operating System Updates," whether it's part of the OS or not. This could lead to a user thinking they're updating the OS itself but actually also installing a new version of a third-party tool.

Here's an example of Slack being included as an "OS Update," and there's no way for me to exclude it from this update if I want to keep the OS itself up to date.

![Screenshot from 2019-06-12 18 20 19@2x](https://user-images.githubusercontent.com/611168/59395011-1ff33780-8d3f-11e9-8052-091882008f9f.png)

**Comment by tintou** [comment]
Where does it come from? We just can't support everything from PPAs (as we also discourage users from using it) so it's gonna stay like this for the PPAs as they haven't enabled DEP11.
There is a slack snap too but this one shouldn't appear as OS-updates

**Comment by isantop** [comment]
I think I agree here. This could happen regardless of whether a user adds PPAs or not (as one can still install packages from the Ubuntu archive through the command line), and that could lead to a misleading update experience. Good design is honest, after all.

**Comment by cassidyjames** [comment]
@tintou right so if it doesn't have proper data, it should be relegated to an "other" category and we should **only** use the OS Updates category for things we actually have data for, and/or things that for sure come from a specific source (our PPA).

**Comment by danirabbit** [comment]
Gonna close this since all PackageKit updates are now considered part of operating system updates and we expect folks to install apps via Flatpak
