### ISSUE TITLE
Long AppData lines resize window

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1023]
Seeing this on recent GIMP update:

![image](https://user-images.githubusercontent.com/611168/60130560-b4549580-9754-11e9-9e5e-debb7eb49998.png)

Not sure if this is a regression or if it's always been this way.

**Comment by cassidyjames** [comment]
It looks like in the [original appdata](https://gitlab.gnome.org/GNOME/gimp/blob/master/desktop/org.gimp.GIMP.appdata.xml.in.in#L78) it's multi-line inside a `<p>` tag, so maybe #1013 is related?

**Comment by isantop** [comment]
I think we found and fixed this in Pop_Shop as so here: https://github.com/pop-os/shop/blob/pop-rebase/src/Widgets/AppContainers/InstalledPackageRowGrid.vala#L60

**Comment by cassidyjames** [comment]
@isantop can you not access the [label_widget](https://valadoc.org/gtk+-3.0/Gtk.Expander.label_widget.html) directly?

**Comment by cassidyjames** [comment]
It looks like this is compounded by the button stack on the right being huge; it might be homogeneous with the app title? I'm continuing to investigate and should have a fix soon.
