### ISSUE TITLE
Update size is no longer helpful with Flatpak

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1030]
Showing the (potential maximum) size of to-be-installed packages still can make sense, but showing the size for updates is almost always wrong, and wrong by an order of magnitude or more due to the way Flatpak does diff-based updates. 

I think we should either remove download size information for updates, or better expose that this is a maximum, worst-case-scenario estimate but that the true size is likely to be much, much, much lower. We discussed this at the Metered Data hackfest and as of then there was no way to get a more accurate download estimate, because the client and server negotiate the diff on demand afaik.

**Comment by danrabbit** [comment]
Yeah this is interesting. My first instinct is to say that users probably wouldn't be upset about a transaction using less data than expected, only if it used more or they're unable to make an informed choice about how much could be used.

I guess there is a bit of an issue here in that users could be discouraged from running an update when they actually have enough data to download it, but I feel like displaying nothing would probably yield the same result: users not installing updates for fear of going over their limits

**Comment by cassidyjames** [comment]
@danrabbit yeah the problem here is that several updates will say they're multiple-GBs in size when in reality they are just a couple of MBs. That's a HUGE difference in bandwidth and time commitment for installing, and it's to the point that I have to remind myself to actively ignore those numbers. If we're giving totally garbage data that has to be ignored, I honestly think showing nothing would be better.

An alternative would be to append an info button with a tooltip/popover that says something like,

> Estimated max download size possible. Because AppCenter only downloads the changes, the actual size is likely to be significantly smaller.

…but that feels really explain-y for a failing of the system to be able to accurately give the user a number.

**Comment by danrabbit** [comment]
What about a qualifier like:
```
< 350 MB
```
or
```
Up to 350 MB
```
And then maybe a tooltip?

Or is that totally stupid when the numbers are like
```
< 15 GB
```

**Comment by cassidyjames** [comment]
@danrabbit yeah I guess, what's a "big" update? I think that's really hard to know, because users might have wildly varying definitions of that. I think it would be safer to just always display it.

**Comment by danrabbit** [comment]
@cassidyjames Sorry I didn't mean we should add some kind of conditional in code, I meant does it make sense to display a label "< 350 MB" or "Up to 350 MB" instead of "350 MB"

**Comment by cassidyjames** [comment]
@danrabbit ah yeah I think "Up to" would be the most clear.
