### ISSUE TITLE
Show more release notes for each app

### ISSUE THREAD

**Issue by jlnr** [elementary/appcenter#1033]
The web preview lets users read release notes for all updates: https://appcenter.elementary.io/com.github.lainsce.notejot/

But in AppCenter itself I only see the changes for the last update. It would be great to see what's happening in an app without opening a web browser.

**Comment by cassidyjames** [comment]
The intent in AppCenter is/was to show notes for updates from the current installed version through the latest version. I'm not 100% sure if that materialized without looking at the code, but I agree always showing at least a few releases behind expanders wouldn't be a bad idea.
