### ISSUE TITLE
Corrupted screenshot cache can prevent any screenshots from loading

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1047]
Not sure what happened, but at some point screenshots stopped loading for me; they would just spin and spin forever. Deleting `~/.cache/io.elementary.appcenter/screenshots/` resolved it.

**Comment by davidmhewitt** [comment]
I'll close this as it sounds like this was the issue where it would stop working after it went over 100MB which we've fixed in #1350
