### ISSUE TITLE
Cancel button different size and alignment

### ISSUE THREAD

**Issue by D0J0P** [elementary/appcenter#1052]
When installing an app, the button goes from "free" or the suggested price to "cancel" if you want to cancel the install. The Cancel button is a different size and alignment than the free or price button as you can see:
![Screenshot from 2019-07-31 00 29 31](https://user-images.githubusercontent.com/19495660/62184181-e1cfc880-b32a-11e9-802e-f7afb804c37d.png)

**Comment by danrabbit** [comment]
This was fixed in a previous update
