### ISSUE TITLE
 AppCenter is taking infos from the official repo, not from the .deb?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/appcenter#1053]
@cassidyjames @danrabbit 
I installed a manual installation of the secure p2p communication solution Jami.
Via terminal followed the instructions as described here: https://jami.net/download-jami-linux/
And I encounter the same problem that was discussed by users and developers.
See https://git.jami.net/savoirfairelinux/ring-client-gnome/issues/986
But unfortunately the problem could not be solved.
My question now: What could be the reason from your elementary OS/AppCenter perspective?
And how can it be solved?

**Comment by cassidyjames** [comment]
AppCenter doesn't have its own logic for app data, it simply uses the AppStream standard. It would appear your .deb is using the same package name as the Zoom package—the Zoom package's AppData likely includes something like a `provides` field for that package name, leading AppStream to associate the two.

**Comment by 4jNsY6fCVqZv** [comment]
@cassidyjames Thanks for getting back!

Can you schange Zoom to Ring/Jami please? Otherwise it confuses me and doesn't do justice to Jami as a GNU project either. :smile:

But what I don't understand according to your argumentation: I have installed an additional package source. See the linked installation guide for the terminal. Why should AppCenter get its data from AppStream instead of the installation source itself when displaying the information about this package? Applications menu and Plank are displaying it correctly by the way.

**Comment by cassidyjames** [comment]
We don't provide or modify packages' AppData, so there's nothing for us to change. It's up to the actual package maintainers from Debian or Ubuntu. 

AppCenter is built to use AppStream and is not really designed to handle sideloaded `.deb` files, especially those with conflicting package names. Implementing Debian-package-specific information sources would be a large amount of work, and would be moving backwards from our goal of supporting sideloading via more modern and safe formats like Flatpak.

**Comment by 4jNsY6fCVqZv** [comment]
My expectation as a user is that AppCenter would work with the information from all extra sources if they were set up and an app was installed. Jami is also updated regularly by this additional source.

As you can see from the linked discussion, the developers have tried AppCenter, while GNOME Software has no problems. What makes GNOME Software different here? What would make it difficult for AppCenter to improve this behavior?

You're addressing the resource issue. This is very important for all areas of activity. Unfortunately, not all developers feel like constantly changing the supported formats or adding additional ones and then maintaining them. And then there is no Flatpak.

So what do you advise me to do?

**Comment by cassidyjames** [comment]
GNOME Software is much larger, more complex, slower, etc. because it does not just rely on AppStream—it apparently grabs information from other sources like apt or the Debian packages themselves. However, that's not the design of AppCenter. 

Developers don't need to "constantly chang[e] the supported formats". AppCenter has always supported apps with AppStream installed from the official repos and from the curated AppCenter repository. Nothing there is changing. Sideloading is not and has never been supported by AppCenter. A Debian package sharing a package name with a repository package (without providing its own AppStream data) is an issue with that package. 

The fact that there is not a Flatpak for Jami is also not directly an AppCenter concern—Flatpak is the supported sideloading format for elementary OS moving forward, and is the preferred format for most desktop Linux OSes moving forward as well. You're free to continue sideloading debs or whatever, but AppCenter is not going to be changed to cater to special cases like this.

**Comment by 4jNsY6fCVqZv** [comment]
I'm all with you on this one. Thank you for your evaluation! 

What can I do if I still want to see an improvement? Did I understand correctly that the Jami developers can simply place real info in an AppStream data file and just don't do that?

Sorry, it's very technical for me right now. I'm not so well versed yet.

**Comment by mmstick** [comment]
Software centers grab all their information from appstream metadata. Package repositories provide their appstream metadata separate from the packages themselves, concatenated as one large file that's downloaded along with package lists. These lists are generated by stripping the appstream metadata from packages when they are being built for the repository.

Therefore, it's up to the developers of each application, or the people responsible for creating the packaging for the applications, to write the correct information in their appstream metadata files. Software centers only read the metadata their given.

**Comment by 4jNsY6fCVqZv** [comment]
@mmstick Thank you for your support!

This is the related appdata file in the Jami Client project.
https://git.jami.net/savoirfairelinux/ring-client-gnome/blob/master/jami-gnome.appdata.xml Everything's correct as far as I can tell.

Unfortunately, that's not what AppCenter makes of it.

![Ring cleaned](https://user-images.githubusercontent.com/46536067/62398096-02409280-b578-11e9-811e-d9e777c57627.png)

![Ring2 cleaned](https://user-images.githubusercontent.com/46536067/62398076-f654d080-b577-11e9-9690-0f6ea6774474.png)

**Comment by Conan-Kudo** [comment]
> GNOME Software is much larger, more complex, slower, etc. because it does not just rely on AppStream—it apparently grabs information from other sources like apt or the Debian packages themselves. However, that's not the design of AppCenter.

This should not actually be true. @hughsie has more or less rewired GNOME Software to rely almost exclusively on AppStream data. Stuff that has no AppStream metadata will not show up in GNOME Software either, usually. The only exception I'm currently aware of is the snap backend for GNOME Software. Both the PackageKit and Flatpak backends rely on it.

**Comment by 4jNsY6fCVqZv** [comment]
@conan-kudo What does your hint mean for the solution of my issue?

**Comment by 4jNsY6fCVqZv** [comment]
@mmstick do you have time to look at it again? The package itself uses the correct metadata. However, AppCenter takes the information from an old package, which is probably in the Ubuntu repository.
