### ISSUE TITLE
Others app from developer not balanced in AppCenter

### ISSUE THREAD

**Issue by NathanBnm** [elementary/appcenter#1054]
When I translate the app title "Find Files Conflicts" from @artemanufrij  into French it becomes become "Détecteur de conflits de fichiers". I did not find any shorter way to translate it.

The problem is that AppCenter seems not to be optimized for long App names. Here is the result in this section:

![image](https://user-images.githubusercontent.com/45366162/62410175-90516300-b5e2-11e9-8036-f539c4cdbf77.png)

The columns aren't balanced anymore, I think it's looking weird.

**Comment by danrabbit** [comment]
We now set these columns to be homogeneous in Gtk, so this has been fixed :)
