### ISSUE TITLE
Extensions look like they're not installed

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1059]
Reported in the community Slack, and confirmed on my machine.

![image](https://user-images.githubusercontent.com/611168/63128604-947e6880-bf72-11e9-95d2-8a6f78a7c270.png)

**Comment by danrabbit** [comment]
This is the case for all extensions. It doesn't look like any extensions properly reflect their install state

**Comment by davidmhewitt** [comment]
As far as I know, this was always broken, it's just more noticeable now that AppStream is fixed so we see more than one extension per package and we have AppStream data for more plugs.

However, I've just had a look at fixing this and while AppCenter will need some work, the AppStream data that AppCenter is getting isn't in a good enough state for this to work properly anyway.

I'm not sure if all of the plugs have got the correct RDNNs yet, but once they have, we'll need Cody to update https://github.com/elementary/appstream-data , as a lot of the AppData in there is currently of the old `io.elementary.switchboard-plug-xxxx` format. This causes AppStream to not be able to match the XML with the repository version (that contains the package name) and we can't look up if the package is installed or not.
