### ISSUE TITLE
Paying an app after installing and using it shows a hanging status bar

### ISSUE THREAD

**Issue by wout** [elementary/appcenter#1061]
I just paid for apps I have been using regularly. They were already installed on my system and at the latest version. So I think the app store is showing a progress bar even though nothing needs to be installed.

![image](https://user-images.githubusercontent.com/107324/63215394-0fd44b80-c126-11e9-958e-e891c0b46173.png)

**Comment by cassidyjames** [comment]
@wout can you still reproduce this?

**Comment by wout** [comment]
@cassidyjames Just checked and now it works. After paying, there still is a statusbar but it quickly goes from 0 to 100 and then diappears.
