### ISSUE TITLE
AppCenter opens every time logging in

### ISSUE THREAD

**Issue by FernandoGarcia** [elementary/appcenter#1063]
Hi!

In latest version available in daily ppa which configuration is starting App center automatically?

Previously this command worked to stop auto start.

```
cp /etc/xdg/autostart/io.elementary.appcenter-daemon.desktop ~/.config/autostart/
echo "X-GNOME-Autostart-enabled=false" | tee -a ~/.config/autostart/io.elementary.appcenter-daemon.desktop
```

It also doesn't worked now:

```
cd /etc/xdg/autostart/
sudo mv io.elementary.appcenter-daemon.desktop io.elementary.appcenter-daemon.desktop.bak
```
Best regards.

**Comment by Blast-City** [comment]
I think it's the Applications menu that it is making Appcenter start. I have the io.elementary.appcenter-daemon.desktop and Appcenter doesn't start at login, but as soon as I press the Applications menu button it starts.

This is making it impossible to stop Appcenter from checking updates automatically.

**Comment by davidmhewitt** [comment]
Can the people experiencing this issue see whether the file `/usr/share/dbus-1/services/io.elementary.appcenter.service` exists on their system? If so, did you install AppCenter by building it from source at any point?

**Comment by Blast-City** [comment]
> Can the people experiencing this issue see whether the file `/usr/share/dbus-1/services/io.elementary.appcenter.service` exists on their system? If so, did you install AppCenter by building it from source at any point?

I have that file on my system, but unlike OP I can make AppCenter not autostart by adding the line X-GNOME-Autostart-enabled=false on the io.elementary.appcenter-daemon.desktop file. AppCenter was installed by default with the OS.

**Comment by FernandoGarcia** [comment]
> Can the people experiencing this issue see whether the file `/usr/share/dbus-1/services/io.elementary.appcenter.service` exists on their system? If so, did you install AppCenter by building it from source at any point?

Yes, with this content:

```
[D-BUS Service]
Name=io.elementary.appcenter
Exec=/usr/bin/io.elementary.appcenter -s
```
As I told I have instaled from daily PPA.

**Comment by Admiral-Irony** [comment]
I am experiencing this issue as well, with a stock install. AppCenter doesn't open every time I start up, but seems to occur if I've opened a program from the Applications menu within the first minute or two of startup.

I have not built AppCenter from source. The /usr/share/dbus-1/services/io.appcenter.service file does exist, with this text:

`[D-BUS Service]                                                                  
Name=io.elementary.appcenter                                                     
Exec=/usr/bin/io.elementary.appcenter -s`
