### ISSUE TITLE
Add ability to install Flatpaks for the whole system

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1074]
Right now it looks like Flatpaks are always user installations. That seems like a sane default, but I could see a case where an admin wants to install an app across the whole system for all users.

Edit: this is determined by how the remote is added (i.e. `system` or `user`), not when installing; i.e. you cannot install an app from a system remote as a user installation, and vice versa. See #1115 for more details there.

Since this really overlaps with that issue but that one is more precise, I think I'll close this as a duplicate.

**Comment by danrabbit** [comment]
I wonder if we want to only expose this for admin users or expose this for all users and just ask for an admin to authenticate (so that a user an ask an admin to do this easily)?

**Comment by cassidyjames** [comment]
@danrabbit oh yeah duh, could expose for all users for sure; polkit ftw.

**Comment by TingPing** [comment]
I do recommend reading `/usr/share/polkit-1/actions/org.freedesktop.Flatpak.policy` btw.

Flatpak tries to make as many things as is safe not require admin. So for example an admin is required to install a system wide app but any user can then update it.

**Comment by cassidyjames** [comment]
@TingPing right, I understand that. The feature of actually initially installing the system-wide app is what this issue is about, though, which requires admin.

**Comment by cassidyjames** [comment]
Note that https://github.com/elementary/appcenter/pull/1092 changed how Flatpak works, but this is still relevant.

**Comment by cassidyjames** [comment]
This is actually determined by how the remote is added (i.e. `system` or `user`), not when installing; i.e. you cannot install an app from a system remote as a user installation, and vice versa. See #1115 for more details there.

Since this really overlaps with that issue but that one is more precise, I think I'll close this as a duplicate of #1115.
