### ISSUE TITLE
Flag for Flatpak-only

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1076]
@sysrich had expressed interest at GUADEC in using a Flatpak-only AppCenter for a project he was working on. It could be useful to provide a flag to disable the PackageKit backend and only talk to Flatpak.

**Comment by Conan-Kudo** [comment]
If the AppCenter backends (PackageKit and Flatpak) were structured as plugins, it'd be very easy to just partition it out and ship variations that have it and don't have it. This is how GNOME Software and Plasma Discover do it, and that makes it a lot easier to deal with the variation without building it differently each time.

**Comment by tetebueno** [comment]
In order to mitigate this in the meantime, is there a way te tell if an application is being offered by Flatpak in plain sight?

**Comment by cassidyjames** [comment]
@tetebueno currently if the app is only offered via Flatpak (or the non-Flatpak source has a non-matching ID, meaning we can't associating them), you can see an `(i)` icon next to the install size because Flatpak sizes are estimates that don't fully take into account the diff-based nature of their downloads. It's not ideal (or intended to be the way to identify Flatpaks), but it works at the moment.

Fixing #233 might also help better expose the source when only one exists.
