### ISSUE TITLE
Upgrade from Deb to Flatpak

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#1088]
We need some kind of migration path from deb packages to flatpaks.

The only thing we can really do here is check AppIDs and hope they're the same from the deb to the flatpak (this is unfortunately not the case for many uncurated debs).

It sounds like we want to upgrade only like sources. So AppCenter debs to AppCenter Flatpaks and Uncurated debs to Uncurated Flatpaks but not AppCenter Debs to Uncurated Flatpaks.

Another pitfall to watch out for is we don't want to upgrade our patched default-app debs to uncurated flatpaks.

We can probably enforce the gsettings migration flag in AppCenter flatpaks, so we could do those upgrades ~automatically~ without fanfare. But for uncurated flatpaks, we probably want to warn users that they may lose some data in the migration.

**Comment by cassidyjames** [comment]
Something @davidmhewitt pointed out we have to be really careful about is access to user data; i.e. if an app used to store data in `~/Presentations`, we either have to make sure devs are competent enough to request that in their Flatpak, and/or double-check that on AppCenter submissions ourselves.

**Comment by danrabbit** [comment]
I'm going to close this since we're handling this in packaging for 1st party apps and the last release of AppCenter that used deb packages is unsupported
