### ISSUE TITLE
Native SIP support

### ISSUE THREAD

**Issue by rajsardhara** [elementary/appcenter#1090]
I've been using elementary for the last two years for work and personal use and so far no complains, Hoping to add native support/client for SIP and that would be great.

Thank you,

**Comment by cassidyjames** [comment]
elementary does not publish the apps in AppCenter, it's a third-party marketplace like the Apple App Store or Google Play Store. As such, I'm closing this as out of scope for this repo. But I agree, that would be nice for someone to develop!
