### ISSUE TITLE
Support to add multiple clocks

### ISSUE THREAD

**Issue by rajsardhara** [elementary/appcenter#1102]
Request to add a feature to add multiple clocks like ubuntu.

Thank you,

## Prerequisites
- [ ] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Existing work**

**Describe alternatives you've considered**

**Additional context**

**Comment by danrabbit** [comment]
Closing as a duplicate of https://github.com/elementary/wingpanel-indicator-datetime/issues/5
