### ISSUE TITLE
Prompt for a reboot or silently restart daemon after updating AppCenter itself

### ISSUE THREAD

**Issue by danirabbit** [elementary/appcenter#1113]
I can't remember where it is that we have to flip that reboot required bit, but we either need to always do that for all AppCenter updates or we need to have a mechanism for AppCenter to restart itself after an update.

Users are confused about having to restart since AppCenter runs in the background and they're not sure why they don't get new features after closing and reopening AppCenter

**Comment by cassidyjames** [comment]
I think I'd prefer to restart the daemon after the AppCenter window is closed, but prompting for a reboot could also be a quicker/easier fix. We'd need to fix #1048 for that to work, though.

**Comment by janxkoci** [comment]
You mean rebooting computer? Please no.

**Comment by cassidyjames** [comment]
@janxkoci it would never reboot without explicit user action, but some updates do in fact need a reboot to start using the new code. So we already have a built-in prompt to reboot to see the latest code.

**Comment by janxkoci** [comment]
That's just kernel AFAIK. I'm just worried about the word "require". I really don't envy this (to/from? i dunno :smile: ) my windows friends..

**Comment by cassidyjames** [comment]
@janxkoci I've clarified the title to reflect two proposed options we have.

**Comment by 4jNsY6fCVqZv** [comment]
Hmm, when I look at https://github.com/elementary/wingpanel/issues/263, I wonder if there are any other components in the system that would need a silent  restart or obvious reboot prompt?

**Comment by danirabbit** [comment]
Closing since all PackageKit updates happen offline now
