### ISSUE TITLE
Also display applications from systemwide Flatpak remotes

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/appcenter#1115]
Currently, due to the decision we made that AppCenter would only handle flatpaks for the user, rather than systemwide, we only display applications configured in user remotes.

The default/old instructions on the flathub website for adding the flathub remote adds it systemwide by default:
`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`

Therefore, anyone who has configured flathub in that way won't see flathub applications in AppCenter. However, the first time you install a flathub application with Sideload, the flathub remote would be added for the user and make it appear in AppCenter too.

I think potentially things could get quite complex if we include systemwide remotes too. I guess we'd have to de-duplicate them and prioritise any user ones. Then any remotes that are configured for the system but not the user would be included too.

I'm also not sure what happens if you instruct flatpak to install an application for the user from a systemwide remote. I imagine it works fine, but this will also need testing.

**Comment by davidmhewitt** [comment]
Note that this is somewhat different from #1074 which describes the desired ability to be able to _install_ apps for all users of the system, not see applications configured in systemwide remotes.

**Comment by cassidyjames** [comment]
Is it possible to install an app from a system remote as a user? i.e. if Flathub is added system-wide, can I still choose to just install GIMP from Flathub on my account i.e. from the CLI? If so, we should minimally show apps from system remotes and allow user installation without any additional design needed.

**Comment by isantop** [comment]
It doesn't appear that applications can be installed as a user from a system remote:

```
 1  %  flatpak install flathub lmms     
Looking for matches…
Found ref ‘app/io.lmms.LMMS/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: ^C%                                                         16:34  ~  Downloads 
 1  %  flatpak install flathub lmms --user
Looking for matches…
error: No remote refs found similar to ‘flathub’
```

**Comment by cassidyjames** [comment]
Alright yeah if that's the case, I'd say de-dupe between user/system remotes and prefer user installations, and polkit prompt on system installations.

**Comment by cassidyjames** [comment]
@davidmhewitt would it make sense to just treat system vs user remotes as separate remotes, and use the existing combobox on app listings to differentiate between them?

**Comment by davidmhewitt** [comment]
I've already spent some time looking into this, just haven't had chance to write up my findings yet.

As @isantop says, it isn't possible to install a user app from a system remote, or a system app from a user remote. I've proven this isn't just a flatpak CLI limitation too by trying this via the API. When you think about it, it makes sense, because when you remove a remote, it makes you remove all of the apps that were installed from that remote too. So it makes sense to not muddy the water by allowing cross installing.

I think it would be quite difficult to build it in a way where we can just have a checkbox that selects whether to install systemwide or not as we'd have to handle all the cases of the remote only being added for the user/system and the user wanting the other case, thereby adding duplicate remotes (which we probably want to avoid where possible).

The design gets a bit tricky if we de-dupe system/user remotes and prefer the user remote too. If I have flathub added twice, both for the system and the user and I've installed an app from the system remote. When I go on that apps page in AppCenter, it shows as uninstalled because we're showing the user remote by default?

Adding system remotes to the dropdown is certainly the easiest solution technically, but I fear it's making something that's already semi-complicated more complicated.

**Comment by cassidyjames** [comment]
@davidmhewitt yeah I can see how this complexity can balloon pretty quickly and I agree we need to think it through. I think a fallback order could be agreed upon which makes sense, though. For example, preferring them in this order in both lists and the source combobox:

1. Installed version (#1029): if it's installed, we almost certainly always want to show this listing
2. Curated version: if the same app is coming from a curated and non-curated source, we'd prefer the user go with the curated one
3. Flatpak version (#1082): we want to encourage users to move towards better packaging formats, so preferring Flatpak over non-Flatpak makes sense
4. Other versions: I think this would be non-curated, non-installed deb packages

**Comment by cassidyjames** [comment]
@isantop I think that ordering would also satisfy [this](https://github.com/orgs/pop-os/projects/12#card-29383200), assuming `Pop_APT` is marked as curated in your fork.

**Comment by isantop** [comment]
I believe we disable the curation codepaths in the meson options (we don't draw any curated vs. non-curated distinctions)

**Comment by cassidyjames** [comment]
@isantop eh, we would already like to do some amount of remote prioritizing as we've gotten feedback from users who installed Flatpak themselves pre-Sideload and are wondering why things aren't showing up. It could also be useful for admins who do actually want to graphically install apps for all users on the system, i.e. a parent managing a family machine.
