### ISSUE TITLE
Unable to Update Flatpak app

### ISSUE THREAD

**Issue by Akzel94** [elementary/appcenter#1116]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
AppCenter shows a badge in my dock indicating an update is available, however, there seems to be nothing to update under the Installed tab. Running `flatpak update` from the terminal shows that LibreOffice has an update available, but I'm unable to do so in AppCenter.

Flatpak runtimes have updated fine, showing under OS Updates as expected.

### To Reproduce
1. Run `flatpak update` in terminal
2. Check for any flatpak apps that have an update available
3. See if flatpak can be updated via AppCenter

### Screenshots or screen recordings

![Screenshot from 2019-11-01 12 38 44](https://user-images.githubusercontent.com/26857149/68042422-39266180-fca9-11e9-9944-1f494dc5af09.png)

## Platform Information
![Screenshot from 2019-11-01 13-17-02](https://user-images.githubusercontent.com/26857149/68042736-04ff7080-fcaa-11e9-8d10-68aa7c8eb53b.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

**Comment by cassidyjames** [comment]
How did you originally install LibreOffice?

**Comment by Akzel94** [comment]
I installed LibreOffice through AppCenter.

Flathub had been added by installing Fractal with Sideload.

**Comment by Akzel94** [comment]
OK, I have no idea what caused the issue to begin with, but it seems to have fixed itself now. The LibreOffice update is now showing up in AppCenter normally.
