### ISSUE TITLE
Add feedback to the 'Check for update' app action

### ISSUE THREAD

**Issue by Akryum** [elementary/appcenter#1121]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
When using the 'Check for update' app action, if there is no update, the user doesn't get any feedback if the check was successful (nothing happens).

**Describe the solution you'd like**
A notification or UI element explaining to the user that no updates are available at this time. Maybe also animate the loading indicator during the check in the AppCenter window header.

**Existing work**
On Windows 10:

Checking for update:
![image](https://user-images.githubusercontent.com/2798204/68071237-e025fe80-fd78-11e9-8b9b-01f5a15b61e0.png)
(Checking for updates in progress...)

No updates found:
![image](https://user-images.githubusercontent.com/2798204/68071244-e9af6680-fd78-11e9-816a-5906f7b26474.png)
(You are up-to-date, Last check: Today, 1PM)

**Describe alternatives you've considered**

**Additional context**

**Comment by cassidyjames** [comment]
If I'm not mistaken, that button should immediately open AppCenter to the updates page. Are you not seeing that behavior?

**Comment by Akryum** [comment]
Yes, but then nothing happens 😸

**Comment by cassidyjames** [comment]
Ah, I gotcha. I thought this report was filed against the switchboard plug, not AppCenter. I'm open to ideas. :smile:
