### ISSUE TITLE
Updates - No badge displayed in the dock 

### ISSUE THREAD

**Issue by Angedestenebres** [elementary/appcenter#1127]
As said in the title, I have no badge in the dock (I noticed that yesterday for the first time):

![Capture d’écran de 2019-11-05 19-35-39](https://user-images.githubusercontent.com/21110485/68236447-7a9a7200-0005-11ea-9518-b6446f3b1f60.png)

However, I have a badge in the appcenter.

**Comment by davidmhewitt** [comment]
I've tracked this down to an issue in Granite and opened a PR there to fix the issue:
https://github.com/elementary/granite/pull/333

**Comment by Angedestenebres** [comment]
Issue fixed, so I close it :)
