### ISSUE TITLE
Empty installed apps

### ISSUE THREAD

**Issue by terrakok** [elementary/appcenter#1128]
After updating AppCenter application It shows empty list of installed applications:
![Снимок экрана от 2019-11-06 12-11-35](https://user-images.githubusercontent.com/3532155/68284453-9f86f780-008e-11ea-9463-c148712b99cd.png)  

Main screen works as expected:  
![Снимок экрана от 2019-11-06 12-16-09](https://user-images.githubusercontent.com/3532155/68284854-42d80c80-008f-11ea-81c3-5aedee1c2894.png)

### Expected behavior
Full list of my installed applications

## Platform Information
![Снимок экрана от 2019-11-06 12-13-20](https://user-images.githubusercontent.com/3532155/68284597-d826d100-008e-11ea-8a03-d346ec1c93f5.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by Angedestenebres** [comment]
Hey :)

Did you try to use "check new update" to see if the page stays like that?
It already happens on my side too but only during few seconds.

**Comment by terrakok** [comment]
I restarted PC few times but problem is here

**Comment by terrakok** [comment]
I solved it:
 - kill silent appcenter process
 - reinstall it
