### ISSUE TITLE
Make non-curated warning specific to each remote

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1132]
It might make sense to be able to hide the non-curated warning per-remote, i.e. if I trust Ubuntu and Flathub but not another remote. I think we'd need to:

- [ ] better expose the remote in the dialog
- [ ] change the wording of the checkbox label
- [ ] implement a way of remembering which remotes warnings are ignored for in GSettings

**Comment by cassidyjames** [comment]
>#### Install non-curated app from Hlatfub?
>“KootRit” is not curated by elementary and has not been reviewed for security, privacy, or system integration. It is distributed by HlatFub.
>
>- It may not receive bug fix or feature updates
>- It may access or change system or personal files without permission
>
>- [x] Show non-curated warnings for HlatFub

**Comment by danrabbit** [comment]
Closing since we removed the non-curated warning dialog
