### ISSUE TITLE
Update notification should replace the old one

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#1148]
It's possible to end up with a case where you have multiple notifications in the notifications indicator that say things like:

5 updates available
4 updates available
3 updates available

To avoid this situation, we should make sure to use the replace functionality of the notification server

**Comment by cassidyjames** [comment]
From duplicate issue:
>**Supply IDs for notification categories**
>
>For example:
>
>`io.elementary.appcenter.updates` for new updates
>`("io.elementary.appcenter.%s").printf (app_id)` for when a specific app is installed
>
>The goal being that when notifications are saved in the notifications indicator, they get replaced properly. We shouldn't have a bunch of "Updates available" notifications, just the latest one.

**Comment by rohitpaulk** [comment]
I don't think this is an issue with appcenter, looks like a duplicate of https://github.com/elementary/wingpanel-indicator-notifications/issues/9. 

The notification code **does** use IDs: https://github.com/elementary/appcenter/blob/be0945360ddb1d541b691c902ac368a2afa6482b/src/Core/Client.vala#L78 

To verify, I ran that code in a loop with IDs enabled and set to `null`: 

**With IDs** (current behaviour): 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3893573/79901986-57864200-842e-11ea-8f07-abb91944a453.gif)

**Without IDs**:

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/3893573/79901923-3f162780-842e-11ea-8b12-77728fc8f44c.gif)

**Comment by danrabbit** [comment]
Oh yup, you're right. Looks like this is only an issue in the indicator then. Thanks for investigating!
