### ISSUE TITLE
App Center shows badge when updates are available but number is always "0"

### ISSUE THREAD

**Issue by asiral** [elementary/appcenter#1149]
A month or so ago, I suspect, the App Center started showing me a badge with "0" when I have updates.  The number of updates are never shown anymore.  Otherwise, App Center still shows when  I have updates by at least showing a badge show this is not severe but hopefully an easy fix.
![Screenshot from 2019-11-28 09 52 15](https://user-images.githubusercontent.com/2885971/69780646-43af1a80-11c5-11ea-8cb7-85ba72dccec8.png)
![Screenshot from 2019-11-28 09 52 08](https://user-images.githubusercontent.com/2885971/69780647-43af1a80-11c5-11ea-845e-c25a1ff29646.png)

**Comment by queeup** [comment]
#1136

**Comment by ryonakano** [comment]
Closing as duplicate of #1136
