### ISSUE TITLE
Don't show "Open" for compulsory-for-desktop items

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#1151]
Since these are likely shell components, it's a bit weird:

![Screenshot from 2019-12-02 12 21 22@2x](https://user-images.githubusercontent.com/7277719/69992364-58a9e780-14fe-11ea-961a-a5025746faee.png)

**Comment by cassidyjames** [comment]
We should hide it for compulsory apps unless the app has an explicit [`launchable` tag](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-launchable), that way we can have compulsory apps like Switchboard still be openable from AppCenter.

**Comment by TingPing** [comment]
The wingpanel shouldn't be a `desktop-application` type in its appdata so that would be a clear indication its not launchable.

**Comment by danrabbit** [comment]
That's a much better way to determine this. Thanks @TingPing !
