### ISSUE TITLE
The part of the app description "What's new" should refer to the current version, not to the previous version

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/appcenter#1152]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
When I look at the app description in AppCenter, I would expect that I have last what the changes of the last update brought with them. 
I just read the given example so that AppCenter tells me what version 3.2 is, but not 3.2.1.
And basically asked: Is the idea here a history of recent versions? Or always the changes of the last version? The first could easily become confusing.

**EDIT** There's the same issue for Calendar.
For Camera and Switchboard Date & Time there are no changelogs yet.

### Expected behavior
See what's new in version 3.2.1!
The diffs of https://github.com/elementary/appcenter/releases would be nice here!
Or is the metadata just not up to date yet?

### Screenshots or screen recordings
![Screenshot](https://user-images.githubusercontent.com/46536067/70132812-d5fb6680-167c-11ea-905a-863e94dc6966.png)

- [x] I'm using the latest released stable version

**Comment by jeremypw** [comment]
I assume the intention is to show the latest major changes rather than just translation updates and obscure minor fixes that tend to go in minor releases. Perhaps there could be dropdowns for each releaseback to the last major release.

**Comment by cassidyjames** [comment]
This is actually a different issue; we don't currently get perfectly up-to-date AppStream data from our packages yet, because PPAs do not support AppStream. We generate it on the side and ship it as a package update for now, but that means it's not always perfect. There is an issue open elsewhere to improve that process though I can't find it at the moment.

**Comment by 4jNsY6fCVqZv** [comment]
@cassidyjames Today's AppCenter update to version 3.2.4 unfortunately still shows the AppData Infos from the 3.2 release.
What could you imagine to change in your infrastructure to make updates more transparent and to show the users what really changes with the current release?
