### ISSUE TITLE
The 'What's New' details sometimes overlap the 'Other Apps' details

### ISSUE THREAD

**Issue by yerbestpal** [elementary/appcenter#1157]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
When on an applications AppCenter page, sometimes the 'What's New' details, which detail the changelog of the latest application update, overlap the 'Other Apps' footer found below. After some time, the problem seems to corrects its self, but it does create an ugly situation as well as a minor inconvenience.

![AppCenter Bug screenshot](https://i.imgur.com/WamIBBL.png)

### To Reproduce
1. Go to 'AppCenter'
2. Click on 'any application page'
3. Scroll down to 'bottom of application page'
4. See bug

### Expected behavior
The graphical issue should not be present. The latest changelog should display correctly whilst respecting the boundaries of the footer.

## Platform Information
![elementaryOS About dialog](https://i.imgur.com/5OqnTG4.png)

Please check what applies:
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
While this report specifies Hera, I have in fact noticed it for as long as AppCenter has been around. I should have filed the bug ages ago.

**Comment by 4jNsY6fCVqZv** [comment]
My observations are:
- The bug occurred before the Hera release.
- I can reproduce it at will.
- It seems that the issue occurs only after the first start of AppCenter after system start. In the following I can close&open AppCenter without experiencing the same issue again. But that would be a point that requires further observation.

**Comment by yerbestpal** [comment]
@4jNsY6fCVqZv those are points I should have been more clear about. Thanks for posting.

**Comment by cassidyjames** [comment]
I presume this is what #928 was trying to describe? :smile: It looks to be something we're hitting in GTK itself, but someone more experienced in GTK/Vala development than myself might know better/how to work around it.

**Comment by 4jNsY6fCVqZv** [comment]
Is this something for which an issue should be created in the GTK GitLab if that's where the root cause is? Maybe as an alternative to the workaround idea.

**Comment by yerbestpal** [comment]
That might be a safe assumption. Unfortunately I am not the person for that, having basically no GTK experience. Hopefully someone picks it up though.

**Comment by yerbestpal** [comment]
I wonder if this is the same bug?
![bug1](https://user-images.githubusercontent.com/15250241/91646372-56050000-ea46-11ea-8442-bdf671a59653.png)

**Comment by danirabbit** [comment]
This was fixed :)
