### ISSUE TITLE
Acabao de instalar de 0, elementary OS 5.1 y tengo problemas con las actualizaciones.

### ISSUE THREAD

**Issue by makgiber1984** [elementary/appcenter#1158]
Este es el fallo que da nada mas entrar a la tienda de apps, o al darle a buscar actualizaciones, desde el panel info.
![Captura de pantalla de 2019-12-07 13-20-30](https://user-images.githubusercontent.com/58627957/70374585-5f689e00-18f4-11ea-88d5-cfd29d5958c5.png)

E: Fallo al obtener http://es.archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  409  Conflict [IP: 104.19.139.75 80]
E: El repositorio «http://es.archive.ubuntu.com/ubuntu bionic-updates InRelease» no está firmado.
W: No se puede actualizar de un repositorio como este de forma segura y por tanto está deshabilitado por omisión.
W: Vea la página de manual apt-secure(8) para los detalles sobre la creación de repositorios y la configuración de usuarios.
E: http://es.archive.ubuntu.com/ubuntu bionic-updates InRelease is not (yet) available (409  Conflict [IP: 104.19.139.75 80])
E: Fallo al obtener http://es.archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  409  Conflict [IP: 104.19.139.75 80]
E: El repositorio «http://es.archive.ubuntu.com/ubuntu bionic-backports InRelease» no está firmado.
W: No se puede actualizar de un repositorio como este de forma segura y por tanto está deshabilitado por omisión.
W: Vea la página de manual apt-secure(8) para los detalles sobre la creación de repositorios y la configuración de usuarios.
E: http://es.archive.ubuntu.com/ubuntu bionic-backports InRelease is not (yet) available (409  Conflict [IP: 104.19.139.75 80])

**Comment by joaop9425** [comment]
Hello, I am a user of ElementaryOS since version 5, and already had this problem, solved like this:
sudo rm <problematic-PPA-repository-name> .list *

Sorry for my lousy English, I'm Brazilian and I'm still studying the language.

**Comment by davidmhewitt** [comment]
The original issue looked like a temporary problem with the Ubuntu mirrors:
"is not (yet) available"

I believe this should have resolved itself, so I'll close the issue. Please add further details (preferably in English) if you are still experiencing the issue.
