### ISSUE TITLE
MDB_BAD_VALSIZE error

### ISSUE THREAD

**Issue by derena** [elementary/appcenter#1161]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
When i open the AppCenter i only see a few apps in store. I tried sudo apt update it doesn't work. I also tried to purge and install appcenter again but nothing changed.

I can't see the apps that i have already installed from appcenter and it doesn't update the list cache, i guess.

## Platform Information
 - OS: elementary OS
 - OS Version: 5.1 Hera
 - Hardware info:
 Intel® Core™ i5-4200U CPU @ 1.60GHz
 Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 09)
 NVIDIA Corporation GK208M [GeForce GT 730M] (rev a1)
 4 GB RAM

Please check what applies:
- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

## Additional context

**emre@emre-Lenovo-IdeaPad-U530-Touch:~$** io.elementary.appcenter %U

** (io.elementary.appcenter:26710): CRITICAL **: 00:26:43.326: PackageKitBackend.vala:163: Unable to add data: MDB_BAD_VALSIZE: Unsupported size of key/DB name/data, or wrong DUPFIXED size

** (io.elementary.appcenter:26710): WARNING **: 00:26:43.437: FlatpakBackend.vala:448: Errors found in flatpak appdata, some components may be incomplete/missing: Unable to add data: MDB_BAD_VALSIZE: Unsupported size of key/DB name/data, or wrong DUPFIXED size

** (io.elementary.appcenter:26710): CRITICAL **: 00:26:50.901: PackageKitBackend.vala:163: Unable to add data: MDB_BAD_VALSIZE: Unsupported size of key/DB name/data, or wrong DUPFIXED size

** (io.elementary.appcenter:26710): WARNING **: 00:26:51.076: FlatpakBackend.vala:448: Errors found in flatpak appdata, some components may be incomplete/missing: Unable to add data: MDB_BAD_VALSIZE: Unsupported size of key/DB name/data, or wrong DUPFIXED size

**Comment by queeup** [comment]
What language are you using on your elementary OS? I suspect about locale problem. I have similar issue (probably same issue like yours): https://github.com/elementary/triage/issues/6

**Comment by derena** [comment]
I am using Turkish language.

**Comment by cassidyjames** [comment]
This should be resolved now, according to #1182.
