### ISSUE TITLE
Showing same apps since installation

### ISSUE THREAD

**Issue by enescaglayan** [elementary/appcenter#1162]
I would like to download Gparted, eddy and apps like that but it shows that it "doesnt exist". I even ran "sudo apt update" then reboot but still no. Probably a duplicate issue but I really need help.

**Comment by enescaglayan** [comment]
I sent command which is claimed to be show all apps: appstreamcli search a | wc -l

The result is:
Unable to add data: MDB_BAD_VALSIZE: Unsupported size of key/DB name/data, or wrong DUPFIXED size
0

**Comment by queeup** [comment]
Probably you are not using elementary OS in English right?
https://github.com/elementary/triage/issues/6 & #1161

**Comment by enescaglayan** [comment]
True, I am from Turkish, also the issue i gave up above is also from a Turkish guy.

**Comment by enescaglayan** [comment]
Closing issue now because its duplicate.
