### ISSUE TITLE
Appcenter  Applications do not appear

### ISSUE THREAD

**Issue by safak45x** [elementary/appcenter#1163]
No applications appear in Turkish language settings
![Ekran görüntüsü - 2019-12-23 13 53 29](https://user-images.githubusercontent.com/59151376/71354251-63e7b480-258c-11ea-8f30-dd400cf4e587.png)
![Ekran görüntüsü - 2019-12-23 13 53 58](https://user-images.githubusercontent.com/59151376/71354258-6813d200-258c-11ea-9d8c-e83c1374d54f.png)

I found the solution like this, but I want to use Turkish

![Screenshot from 2019-12-23 13 58 04](https://user-images.githubusercontent.com/59151376/71354303-8c6fae80-258c-11ea-80e3-65d3935a4f9d.png)
![Screenshot from 2019-12-23 13 58 34](https://user-images.githubusercontent.com/59151376/71354307-8ed20880-258c-11ea-8e19-e651c83a6129.png)

I'm sorry if there are typos I've used

**Comment by enescaglayan** [comment]
Duplicate issue please check if issue has been posted here before making the issue!

**Comment by safak45x** [comment]
diger çözüm yöntemlerini denedim olmadı neredeyse herseyi denedim hatta işletim sistemini tekrar yukledim yine aynı sorun olustu

**Comment by enescaglayan** [comment]
herkez yaşıyor sorunu Türkiye'den tek sen değil 5 10 kişi sorun açtı böyle tek çözüm sistemi İngilizceye almak yada yeni sürümü beklemek merak etme bizi yok saymazlar büyük ihtimal

**Comment by safak45x** [comment]
Tamam o zaman tek yapmamız gereken beklemek olucak umarım görmezden gelmezler bizi

**Comment by enescaglayan** [comment]
possible duplicate of [https://github.com/elementary/triage/issues/6](url)

**Comment by cassidyjames** [comment]
@enescaglayan indeed, duplicate of #elementary/triage#6
