### ISSUE TITLE
Error Failed to Fetch Updates

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [elementary/appcenter#1167]
E: The repository 'http://ppa.launchpad.net/mc3man/xerus-media/ubuntu bionic Release' does not have a Release file.

**Comment by Envel-Nikita-Gutsenkov** [comment]
initially, everything worked fine and the problem appeared after a few days.

**Comment by vjr** [comment]
That PPA really does not appear to have bionic section at the moment.

**Comment by Envel-Nikita-Gutsenkov** [comment]
> That PPA really does not appear to have bionic section at the moment.

how to fix it?

**Comment by davidmhewitt** [comment]
Remove the mc3man/xerus-media PPA you have added. This is not a problem with AppCenter, it's a problem with that PPA.
