### ISSUE TITLE
Missing updates

### ISSUE THREAD

**Issue by 1di9** [elementary/appcenter#1173]
I'm running Elementary Os Hera and I noticed that the app center no longer reports the presence of updates neither of the applications nor of the system.
the only way to get updates is to use the terminal.
What can I do?

**Comment by davidmhewitt** [comment]
If you are still experiencing this issue, could you please run the following in the terminal to get some debug information from AppCenter:
```
killall io.elementary.appcenter
G_MESSAGES_DEBUG=all io.elementary.appcenter
```

Please add the logs from the terminal to this issue.

**Comment by davidmhewitt** [comment]
I'm going to close this issue due to age.

OP, or anyone else experiencing the same issue, please add the logs requested above to this issue to help us track this down and I'll re-open.

**Comment by 1di9** [comment]
I’ve sent log 2 days ago… Da: David HewittInviato: martedì 14 aprile 2020 18:01A: elementary/appcenterCc: 1di9; AuthorOggetto: Re: [elementary/appcenter] Missing updates (#1173) I'm going to close this issue due to age.OP, or anyone else experiencing the same issue, please add the logs requested above to this issue to help us track this down and I'll re-open.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by davidmhewitt** [comment]
Please open the GitHub issue and attach the logs here, we haven't received any logs and the last message you sent has been formatted really badly by GitHub.

**Comment by 1di9** [comment]
This is the logs from the terminal to this issue.
[Terminal log.txt](https://github.com/elementary/appcenter/files/4479608/Terminal.log.txt)
