### ISSUE TITLE
Multi-source awareness

### ISSUE THREAD

**Issue by ryanprior** [elementary/appcenter#1179]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Describe the solution you'd like**

Apps and packages in the App Center clearly display their source, not just their author(s). For example, suppose I have four text editors installed through the App Center and I search my installed packages for "text editor":
- Code appears at the top, from the "elementary App Center" source
- Sublime Text appears next, under the "FlatHub" source
- Emacs then appears under the "us.archive.ubuntu.com" source
- Finally, VS Code appears under the "packages.microsoft.com (deb)" source

In a "software sources" settings manager, the user can select one or more sources that they would like to prioritize when showing apps (installed, or when searching) in the App Center. By default, only the elementary App Center would be prioritized.

It is easy for a user to tell where they installed something from, and we could perhaps use this area to include more info about the source, like security sandbox and elementary curation status.

**Existing work**

The current solution is to separate things into three sources: "curated" (elementary apps), "flatpak (non-curated)," and 
"uncurated", everything else.

#609 discusses collapsing the latter category by default, especially if there are available apps in the former. 

**Describe alternatives you've considered**

Right now my process to find out where an application came from looks like this:
1. locate application launcher file
2. find name of executable, perhaps indicating a Flatpak app
3. if still unsure, run `type <executable name>` to find a path, perhaps indicating a Snap app
4. if still unsure, run `ls -l <executable path>` and follow all symlinks, if any, to find the real path
5. run `dpkg -S <real executable path>`, perhaps indicating the name of a Debian package
6. if it's a Debian package, run `apt show <package name>` to find the origin of the package
7. if all that fails, cry

That's not a great UX and App Center could provide a dramatically better one!

**Comment by cassidyjames** [comment]
I think there's significant overlap with #1140. I also don't think it's within the scope of AppCenter to create a new "software sources settings manager" interface and have fiddly user-determined prioritization rules for software remotes. I do agree that exposing the source could be useful, as covered in #1140.

**Comment by ryanprior** [comment]
I see the "incomplete" status, please let me know if I can help with any research or info to make this issue more useful.

**Comment by danrabbit** [comment]
I'm inclined to agree with Cass here. AppInfo pages already offer a way to select sources for a particular component and #1140 seems to cover disambiguating for search. I don't think we want to add settings to manage software sources in AppCenter.

Closing as duplicate/design conflict
