### ISSUE TITLE
Thank You 

### ISSUE THREAD

**Issue by safak45x** [elementary/appcenter#1182]
Elementary os AppCenter applications, the team now looks in a healthy way thank you
Turkish Version
![2020-01-23 16 15 32 ekran görüntüsü](https://user-images.githubusercontent.com/59151376/72987647-e79af800-3dfb-11ea-8ac7-81ff27bf000d.png)

**Comment by safak45x** [comment]
> Elementary os AppCenter applications, the team now looks in a healthy way thank you
Turkish version
> ![2020-01-23 16 15 32 ekran görüntüsü](https://user-images.githubusercontent.com/59151376/72987647-e79af800-3dfb-11ea-8ac7-81ff27bf000d.png)

**Comment by cassidyjames** [comment]
Glad to see it's resolved!
