### ISSUE TITLE
Blurry icon of “Check for Updates” in the context menu of AppCentre when using the Pixel Doubled scaling factor

### ISSUE THREAD

**Issue by KomalleanaByzantis** [elementary/appcenter#1189]
# Prerequisites
- [x] I have searched open and closed issues for duplicates.

# Describe the bug

A blurry update icon appears in the context menu of the AppCentre icon in the Dock when using the Pixel Doubled scaling factor.

## To reproduce

1. Open Display Settings.
2. Change the scaling factor to Pixel Doubled.
3. Right click the AppCentre icon in the Dock.
4. A blurry icon is displayed next to the “Check for Updates” item.

## Expected behaviour

I expect a clear, sharp icon.

## Screenshots or screen recordings

![](https://i.imgur.com/QlrbTK8.png)

# Platform information

Operating system: elementary OS
Version: 5.1 Hera

- [ ] I am using the latest version from GitHub which I have manually compiled
- [x] I am using the latest released stable version

System image used during the installation: elementaryos-5.1-stable.20191202.iso
Memory: 8 gigabytes
Disk space: ~10 gigabytes

Computer name: essai
Language: French
Keyboard: English (US) - English (Dvorak intl., with dead keys)
Location: Paris

The testing system is installed on a small partition on a ThinkPad T470 laptop. Aside from specifying the language, keyboard, location, initial user, computer name, and the specific partition in which to install the system, all of the default settings were used during the installation. No Internet connection was used during the installation. The only system-wide changes which have been made after the installation are that the system is able to connect to the Internet via a wireless connection and that [Screen Recorder](https://appcenter.elementary.io/com.github.mohelm97.screenrecorder/) has been installed via AppCentre.

# Additional context

Before the error was reproduced, the following steps were followed:

1. All system components were updated via the blue “Update All” button in AppCentre.
2. A new administrator user named “Essai” or “Essai 2” was created with the password “komalleana”.
3. The current user was logged out and the new user was logged in.
4. The old user was deleted, the screen resolution was set to 800x600 at 60 Hz, tap clicking was disabled, and the touchpad pointer speed was set to the maximal value.
5. The computer was rebooted.
6. The test user was logged in.

**Comment by danrabbit** [comment]
This is a bug in the dock, Plank. AppCenter only supplies the name of the icon. it's up to Plank to render it correctly.

Closing as "out of scope". You can report issues against Plank in launchpad here: https://bugs.launchpad.net/plank
