### ISSUE TITLE
False updates alerts.

### ISSUE THREAD

**Issue by wedsonlopes** [elementary/appcenter#1193]
the Appcenter shows a false positive red icon on dock that indicates new updates available. but there is not.

**Comment by davidmhewitt** [comment]
To anyone experiencing this issue, can you please get some debug logs from AppCenter by running the following in the terminal and pasting the output here:

```
killall io.elementary.appcenter
G_MESSAGES_DEBUG=all io.elementary.appcenter
```

**Comment by danrabbit** [comment]
Closing since OP has not responded with more information. Please feel free to reopen if more information is provided
