### ISSUE TITLE
apps in app center cant download or install how to fix?

### ISSUE THREAD

**Issue by beidzot** [elementary/appcenter#1195]
i try to download quilter from app center but it always give me errors

![Screenshot from 2020-01-30 20 46 46](https://user-images.githubusercontent.com/59545597/73451186-fce6c800-43a1-11ea-8d7f-7916ffd811d2.png)

**Comment by cassidyjames** [comment]
It looks like you have a pretty customized setup here. Have you added a daily PPA or some other third-party PPA by chance? Are you still seeing this issue?

**Comment by davidmhewitt** [comment]
I'm able to install Quilter from AppCenter without any issues, we haven't received any more reports about this and OP hasn't replied with any additional details to be able to diagnose this issue, so I'll close this.

OP, if you're still experiencing this issue, please let us know the additional details requested.
