### ISSUE TITLE
AppCenter crashes mid-update when there are both Flatpak and regular updates

### ISSUE THREAD

**Issue by matfantinel** [elementary/appcenter#1197]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
When AppCenter shows available updates and among them are Flatpak updates, clicking on "Update All" makes AppCenter crash before the whole update is complete.

I only noticed this when there were Flatpak runtime updates amongst "Operating System Updates". I couldn't reproduce if this happens with Flatpak apps as well.

When clicking "Update All", no password is requested, which I guess means Flatpaks are being updated first. However, when the Flatpak updates are finished, AppCenter closes instead of requesting a password to update the "normal" packages. When I open it again, I can see that there are still remaining packages to update, and running "Update All" again works as intended, since there's no mix of Flatpak/regular packages anymore.

The only Flatpak remote I have installed is Flathub, added automatically by Sideload when running a .flatpakref file.

### To Reproduce
1. Open AppCenter's "Installed" tab
2. Check if updates contain both Flatpak and regular updates
3. Click on "Update All"
4. AppCenter will not request sudo password and will close after a while

### Expected behavior
I believe password should be requested immediatelly if there is a package update that requires it, even if Flatpak updates are done first. Also, AppCenter should not crash when updating.

## Platform Information

 - OS: elementary OS
 - OS Version : Hera
 - Hardware info: Dell XPS 9570 (i7-8750H, 16GB RAM, NVidia 1050ti)

- [x] I'm using the latest released stable version

**Comment by cassidyjames** [comment]
Ah, I had seen this crash before but wasn't sure how to reproduce it. Thank you for tracking that down and reporting it!

**Comment by matfantinel** [comment]
@cassidyjames no problem! If I can help with testing that would be no problem. I have some updates pending right now that I can hold off that would likely trigger the bug.

I know how to compile AppCenter if needed. Just ping me here or on Slack
