### ISSUE TITLE
Error Installing Palette

### ISSUE THREAD

**Issue by LukeGaudreau** [elementary/appcenter#1199]
When attempting to install Palette from AppCenter, I receive the following error:

`E: https://packages.elementary.io/appcenter bionic/main amd64 com.github.cassidyjames.palette amd64 3.1.5 is not (yet) available (Redirection from https to 'http://packages.elementary.io/appcenter/pool/main/c/com.github.cassidyjames.palette/com.github.cassidyjames.palette3.1.5-e3f9b4.deb' is forbidden [IP: 104.28.4.44 443])`

This is a fresh install of 5.1.2

**Comment by Nikoos** [comment]
Hello,

This issue seems identical to the following #1200 

Regards,

**Comment by cassidyjames** [comment]
This was a temporary server configuration issue and should be resolved.
