### ISSUE TITLE
AppCenter: updates not being installed

### ISSUE THREAD

**Issue by marc0olo** [elementary/appcenter#1201]
## Describe the bug
The AppCenter says there are new updates available. When trying to update them by providing the password for the sudo-user nothing happens.

I found somebody that has the same problem reported on stackexchange providing a screenshot:
- https://elementaryos.stackexchange.com/a/22286

### Expected behavior
Updates should be installed.

## Platform Information
![image](https://user-images.githubusercontent.com/8124114/73973642-45166500-4923-11ea-95f3-896e5ad324a8.png)

**Comment by davidmhewitt** [comment]
It would be helpful if you could provide a list or a screenshot of the updates that are pending and failing to install or the output of any error messages (if any are given).

**Comment by marc0olo** [comment]
the list in the second screenshot is growing as NO update is being executed. it seems like the updates are being loaded from cache but then nothing happens.

do you need any logs? where can I find them?

![image](https://user-images.githubusercontent.com/8124114/74470701-4dc8e700-4e9f-11ea-989e-70fc0eae7542.png)

![image](https://user-images.githubusercontent.com/8124114/74470745-5e795d00-4e9f-11ea-89cc-5e6d1623d6a5.png)

**Comment by davidmhewitt** [comment]
You can get logs from AppCenter by first killing any running/background instances by running the following in the terminal:
`killall io.elementary.appcenter`

Then run AppCenter with the command `G_MESSAGES_DEBUG=all io.elementary.appcenter`.

Try performing the updates again while AppCenter is running in the terminal like this, then copy and paste any logs from the terminal.

**Comment by marc0olo** [comment]
@davidmhewitt I get the following message in the log when clicking on "Aktualisieren" (Update):
```
(io.elementary.appcenter:7953): PackageKit-DEBUG: 06:55:23.764: adding state 0x55fcf8c8e6f0
(io.elementary.appcenter:7953): PackageKit-DEBUG: 06:55:23.765: role now update-packages
(io.elementary.appcenter:7953): PackageKit-DEBUG: 06:55:23.781: using frontend gnome
(io.elementary.appcenter:7953): PackageKit-DEBUG: 06:55:23.781: using socket in /tmp/gpk-30337_bbecbbdb.socket
(io.elementary.appcenter:7953): PackageKit-DEBUG: 06:55:23.829: emit transaction-list-changed
(io.elementary.appcenter:7953): PackageKit-DEBUG: 06:55:24.574: remove state 0x55fcf8c8e6f0
(io.elementary.appcenter:7953): PackageKit-DEBUG: 06:55:24.616: emit transaction-list-changed

** (io.elementary.appcenter:7953): WARNING **: 06:55:24.616: Package.vala:465: Operation failed for package Betriebssystemaktualisierungen - The following packages have unmet dependencies:
  winehq-stable: Hängt ab von: wine-stable (= 5.0.0~bionic)
```
The update is then being cancelled immediately.

**Comment by marc0olo** [comment]
mhhh, after outcommenting `deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main` in `/etc/apt/sources.list` I was able to update

seems like this problems isn't specifically related to the AppCenter but for unexperienced users this scenario is horrible

**Comment by cassidyjames** [comment]
@marc0olo …which is why we don't include facilities to install third-party repositories out of the box, heavily discourage their use, and heavily encourage safer, more modern app distribution via Flatpak. If someone goes around that and adds a broken repository to their OS, there's only so much we can do.

**Comment by davidmhewitt** [comment]
Closing as this was not an issue with AppCenter, `apt` on the command line would have struggled to resolve this too due to a broken repository setup.
