### ISSUE TITLE
App Center always shows pending Flatpak update

### ISSUE THREAD

**Issue by seandjones92** [elementary/appcenter#1204]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
App Center always shows pending Flatpak update even after the update is applied. I have tried rebooting per the solution posted for issue #1116 but the behavior persists.

![Screenshot from 2020-02-08 17-38-34](https://user-images.githubusercontent.com/17571045/74094151-e0c9e180-4a99-11ea-8a3c-21362b42ea99.png)

![Screenshot from 2020-02-08 17-39-08](https://user-images.githubusercontent.com/17571045/74094159-f808cf00-4a99-11ea-96ee-8139bc153437.png)

If I select "Update" in the App Center UI the update returns to a pending state. The same behavior is seen when attempting to apply the update via CLI. 

```
$ flatpak update 
Looking for updates…


        ID                                  Branch  Op  Remote   Download
 1. [✗] org.freedesktop.Platform.openh264   19.08   i   flathub  593.6 kB / 593.4 kB

Warning: org.freedesktop.Platform.openh264 not installed
Installation complete.
```

### To Reproduce
1. Go to Flathub in your browser
2. Find an application and click the "Install" button
3. Allow install to finish and allow App Center to check for updates

### Expected behavior
I would expect the update to apply successfully and to no longer show as pending or for the App 

### Logs
Logs gathered with `journalctl /usr/bin/io.elementary.appcenter`

```
Feb 08 17:02:47 stinkpad io.elementary.appcenter[8456]: libostree pull from 'flathub' for appstream2/x86_64 complete
                                                        security: GPG: summary+commit http: TLS
                                                        non-delta: meta: 2 content: 0
                                                        transfer: secs: 0 size: 814 bytes
Feb 08 17:02:49 stinkpad io.elementary.appcenter[8456]: libostree pull from 'flathub' for appstream2/x86_64 complete
                                                        security: GPG: summary+commit http: TLS
                                                        delta: parts: 1 loose: 1
                                                        transfer: secs: 1 size: 56.6 kB
Feb 08 17:02:49 stinkpad io.elementary.appcenter[8456]: user: Pulled appstream2/x86_64 from flathub
Feb 08 17:03:11 stinkpad io.elementary.a[8456]: gtk_stack_get_child_by_name: assertion 'name != NULL' failed
Feb 08 17:03:11 stinkpad io.elementary.a[8456]: Duplicate child name in GtkStack: (null)
Feb 08 17:04:12 stinkpad io.elementary.a[8456]: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 17
Feb 08 17:04:22 stinkpad io.elementary.a[8456]: Package.vala:465: Operation failed for package Eddy - Operation was cancelled
Feb 08 17:04:27 stinkpad io.elementary.a[8456]: Package.vala:465: Operation failed for package Eddy - Operation was cancelled
Feb 08 17:14:53 stinkpad io.elementary.a[8456]: gtk_stack_get_child_by_name: assertion 'name != NULL' failed
Feb 08 17:14:53 stinkpad io.elementary.a[8456]: Duplicate child name in GtkStack: (null)
Feb 08 17:21:36 stinkpad io.elementary.a[8456]: gtk_stack_get_child_by_name: assertion 'name != NULL' failed
Feb 08 17:21:36 stinkpad io.elementary.a[8456]: Duplicate child name in GtkStack: (null)
Feb 08 17:39:05 stinkpad io.elementary.a[8456]: gtk_stack_get_child_by_name: assertion 'name != NULL' failed
Feb 08 17:39:05 stinkpad io.elementary.a[8456]: Duplicate child name in GtkStack: (null)
Feb 08 17:45:48 stinkpad io.elementary.appcenter[8456]: libostree pull from 'flathub' for runtime/org.freedesktop.Platform.openh264/x86_64/19.08 complete
                                                        security: GPG: summary+commit http: TLS
                                                        non-delta: meta: 1 content: 0
                                                        transfer: secs: 0 size: 592 bytes
Feb 08 17:45:49 stinkpad io.elementary.appcenter[8456]: user: Pulled runtime/org.freedesktop.Platform.openh264/x86_64/19.08 from flathub
Feb 08 17:45:49 stinkpad io.elementary.a[8456]: FlatpakBackend.vala:818: Flatpak installation failed: While trying to apply extra data: runtime/org.freedesktop.Platform/x86_64/19.08 not installed
Feb 08 17:45:53 stinkpad io.elementary.a[8456]: gtk_stack_get_child_by_name: assertion 'name != NULL' failed
Feb 08 17:45:53 stinkpad io.elementary.a[8456]: Duplicate child name in GtkStack: (null)
Feb 08 17:45:55 stinkpad io.elementary.appcenter[8456]: libostree pull from 'flathub' for runtime/org.freedesktop.Platform.openh264/x86_64/19.08 complete
                                                        security: GPG: summary+commit http: TLS
                                                        non-delta: meta: 1 content: 0
                                                        transfer: secs: 0 size: 592 bytes
Feb 08 17:45:56 stinkpad io.elementary.appcenter[8456]: user: Pulled runtime/org.freedesktop.Platform.openh264/x86_64/19.08 from flathub
Feb 08 17:45:56 stinkpad io.elementary.a[8456]: FlatpakBackend.vala:818: Flatpak installation failed: While trying to apply extra data: runtime/org.freedesktop.Platform/x86_64/19.08 not installed
```

## Platform Information
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

![Screenshot from 2020-02-08 17-49-08](https://user-images.githubusercontent.com/17571045/74094244-626e3f00-4a9b-11ea-9b47-9e62d5a43243.png)

**Comment by seandjones92** [comment]
Tried running through the steps located [here](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/886#note_247819760) but the issue persists

> **Step1**
> flatpak install org.freedesktop.Platform/x86_64/19.08
> **Step2**
> flatpak uninstall --unused
> **Step3**
> flatpak update
> NOTE: in the latest step maybe the system update some packages and ask for download what you need and YES. After update the new packages run again
> flatpak update
> Then reboot.

**Comment by ryonakano** [comment]
I've faced this issue when I installed DFeet (Flatpak version) and seen the same error message `Warning: org.freedesktop.Platform.openh264 not installed`.

**Comment by davidmhewitt** [comment]
So if the flatpak CLI command is showing that there's a pending update and can't install it, and AppCenter does the same thing, it's not really a problem with AppCenter. Reading through the linked freedesktop-sdk issue report seems to indicate its been a problem for a while and they're working on a fix.

As far as I can tell though, this issue has been resolved for me recently. Is anyone still seeing this after running updates?

**Comment by ryonakano** [comment]
I still face this issue whenever installing Flatpak DFeet. Once I remove it, the issue seems to have gone.

**Comment by technicallyblue** [comment]
I found the solution here: https://github.com/flatpak/flatpak/issues/3197

flatpak install org.freedesktop.Platform/x86_64/19.08
then,
flatpak install org.freedesktop.Platform.openh264
