### ISSUE TITLE
Update - Firefox loses all settings (language, prefered seach engine etc...)

### ISSUE THREAD

**Issue by Angedestenebres** [elementary/appcenter#1210]
As said in the title and tried on two computers, everytime you update Firefox, you lose the selected language & the search engine.
After checking, this issue doesn't happen in other distribution : Linux Mint or Fedora.

In my case, I use it in French with Qwant as default search engine. It works fine until I get an update in AppCenter.
After all updates, I get a Firefox up to date but in english with Google as defaut browser.

I guess a part of this issue is linked to this issue : https://github.com/elementary/appcenter/issues/254

In fact, the AppCenter doesn't manage language packages and we have to install it manually in command lines in terminal or by using Synaptic.
For firefox, in options, we can configure the language but it doesn't install the package `firefox-locale-xx`so it will lose that in the next update, see below a screenshot of Synaptic about language package:

![image](https://user-images.githubusercontent.com/21110485/74586748-123b3380-4feb-11ea-8367-f8f68548189e.png)

It could be great to take in account the installation of language packages directly in AppCenter because for people not comfortable with computer, it's really hard to manage and they don't understand why they lose their settings.

Thanks in advance for your support.

**Comment by Angedestenebres** [comment]
Also linked to this issue: https://github.com/elementary/appcenter/issues/895

**Comment by NathanBnm** [comment]
Same issue here

**Comment by Angedestenebres** [comment]
Hey :cat: 

I confirm all is fine with the language package installed.
Tried Today and Language and even search engine have been kept.

So, could you please include this in the next updates of appcenter?

**Comment by Yofiel** [comment]
I'm having the same problem. Also, LibreOffice is missing gtk package(s) and by default it's looking like a old Windows app.

**Comment by cassidyjames** [comment]
@Yofiel the LibreOffice issue is up to the maintainers of LibreOffice (or the packagers at Ubuntu) to fix, as we don't control the LibreOffice package at all.

**Comment by NathanBnm** [comment]
@Yofiel try to install LibreOffice following https://wiki.ubuntu.com/LibreOffice
If you still have some issues you should contact them directly.

**Comment by Yofiel** [comment]
@cassidyjames , thanks for explaining 👍 
@NathanBnm , I installed the Flatpak version, much easier.

**Comment by danrabbit** [comment]
I'm kind of inclined to close this as "Out of scope" since langpacks are an Ubuntuism that are out of our control and Firefox is now available as a Flatpak, but I'd be interested in hearing from @davidmhewitt about the feasibility of installing langpacks. My guess is that it's not really doable without creating some kind of heuristic to try to guess package names which will often fail. But I'd be happy to be proven wrong

**Comment by ovz93br43v7** [comment]
Firefox as flatpak is not a good solution for example when using keepass + keepass-browser addon.
