### ISSUE TITLE
Clicking on "Update" starts the update but then abruptly stops

### ISSUE THREAD

**Issue by vikasnataraja** [elementary/appcenter#1235]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
In the app center, clicking on the `Update` button starts the progress bar (loading cache, downloading, starting) but then abruptly stops. Clicking multiple times doesn't help either.
(see screen capture)

### To Reproduce
This is the first time this has happened so this might just be a one-time thing.
1. Go to App Center
2. Click on any app with an available update
3. Click on Update

### Expected behavior

Clicking on update should update the app.
### Screenshots or screen recordings

![app_center](https://user-images.githubusercontent.com/46734097/77583010-f5c1cf00-6ea5-11ea-8790-cd1a7b5fae54.gif)

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by davidmhewitt** [comment]
If you are still experiencing this issue, could you run AppCenter with debug logging by running the following commands in the terminal:
```
killall io.elementary.appcenter
G_MESSAGES_DEBUG=all io.elementary.appcenter
```

Then if you could try to update again and post the debug messages to this issue.

Thanks!

**Comment by vikasnataraja** [comment]
I forgot to update this issue but it was resolved a day later seemingly on its own. I rebooted my computer but that didn't resolve it but I checked back the next day and everything was smooth again. I am a little hesitant to close the issue since I don't know the cause of this issue.

**Comment by davidmhewitt** [comment]
Thanks for the update!

I'm going to close the issue as it's not something we can actively reproduce.

However, if you find you're experiencing the issue again. Please use the commands above to get some debug logs and attach them to the issue and I'll be happy to re-open and discuss.

Thanks again!
