### ISSUE TITLE
Display bug for Suggested / Recently updated apps

### ISSUE THREAD

**Issue by NathanBnm** [elementary/appcenter#1238]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
I opened the AppCenter to make an update (I received a notification), I clicked on the "Installed" tab but the AppCenter wasn't completely loaded so I had to go back to the main view before reloading the "Installed" view and the "Suggested" and "Recently updated" apps sections were broken.

Resizing the window makes this temporary back to normal, but when going back to the original of the window when the bug appeared then it's still there.

This is fixed after reloading the AppCenter.

### To Reproduce
Steps to reproduce the behavior (seems very hazardous, I didn't succeed to reproduce it):
1. Open AppCenter (I think for the first time after startup)
2. Click fast on "Installed" view (before AppCenter has been loaded completly)
3. Go back to the main view

### Expected behavior
The view should be displayed as usual.

### Screenshots or screen recordings
![image](https://user-images.githubusercontent.com/45366162/77892661-3d17d900-7273-11ea-91f3-92731df12715.png)

### Logs
Not applicable.

## Platform Information
![image](https://user-images.githubusercontent.com/45366162/77893385-23c35c80-7274-11ea-89e1-a6d37340aa85.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

## Additional context
Not applicable.

**Comment by danirabbit** [comment]
This is a pretty old issue, probably an old Gtk bug. I can't reproduce this. Please reopen if this can be reproduced on OS 7
