### ISSUE TITLE
Supply IDs for notification categories

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#1242]
For example:

`io.elementary.appcenter.updates` for new updates
`("io.elementary.appcenter.%s").printf (app_id)` for when a specific app is installed

The goal being that when notifications are saved in the notifications indicator, they get replaced properly. We shouldn't have a bunch of "Updates available" notifications, just the latest one.

**Comment by davidmhewitt** [comment]
Related: #1148

**Comment by cassidyjames** [comment]
Ah, yeah gonna mark it as a duplicate of #1148 since that's effectively the same and predates it. :smile:
