### ISSUE TITLE
Translation bug for the AppCenter in french (install non-curated app)

### ISSUE THREAD

**Issue by roxfr** [elementary/appcenter#1247]
Hi,
I noticed a translation bug for the AppCenter (see image below).
Regards,
roxfr

![Elementary_OS_5 1 3_-_Bug_traduction_centre_applications_01](https://user-images.githubusercontent.com/52124613/78454032-c5441700-7695-11ea-975b-7ac48f239926.png)

Specs :
Windows 10 + VirtualBox 6.1 [Version 6.1.4 r136177 (Qt5.6.2)]
elementaryos-5.1-stable.20200204 (elementary OS 5.1.3 Hera)

**Comment by roxfr** [comment]
NonCuratedWarningDialog.vala : is it translated ?

**Comment by tintou** [comment]
Merci @roxfr une correction est en cours pour ajouter les nombreux fichiers manquants :)

**Comment by roxfr** [comment]
> 
> 
> Merci @roxfr une correction est en cours pour ajouter les nombreux fichiers manquants :)

Ok ça roule ;-)
 
Petite question : 
Quelle est la traduction en français de "non-curated app", s'il te plaît ?
- application non organisée (suivant google traduction),
- application non suivie,
- application non sélectionnée,
- application non signée ?
