### ISSUE TITLE
appcenter not working

### ISSUE THREAD

**Issue by kulafur12** [elementary/appcenter#1250]
the appcenter is not pulling up at all. i tried updating using the terminal but it still not pulling up even after a couple of restart.

**Comment by davidmhewitt** [comment]
What is the result of running the following in the terminal?
`G_MESSAGES_DEBUG=all io.elementary.appcenter`

**Comment by kulafur12** [comment]
well. it came back after using windows for a while (I'm on dual boot). thanks, I'll keep the command for future use.
