### ISSUE TITLE
Password authentication pop up glitches

### ISSUE THREAD

**Issue by kmattis1** [elementary/appcenter#1263]
Whenever I go to install or update an app in the appcenter the password authentication input popup glitches and bounces all over the screen. This just started and was working fine yesterday. I am on the most recent build of the os and app. running 5.1.3 Hera GTK 3.22.30.

Any help or fixes would be amazing

**Comment by davidmhewitt** [comment]
If possible, could you run AppCenter from the terminal with the following commands and paste the output into this issue after reproducing the issue:

```
killall io.elementary.appcenter
G_MESSAGES_DEBUG=all io.elementary.appcenter
```

**Comment by danrabbit** [comment]
Closing since OP hasn't responded. Feel free to reopen if more information is given
