### ISSUE TITLE
Appcenter ("The package id's '' are not valid") Error , and ("Failed to Fetch Updates") 

### ISSUE THREAD

**Issue by LightningBender0** [elementary/appcenter#1281]
I tried reinstalling Elementary OS But those two errors keeps hunting me and i searched everywhere for ways to fix this problem but i couldn't find anything the first error it's always sent to me when i try to download eddy or any other system application not every application though but i cant get to download eddy or other application because of that problem and the second error is always sent to me when i open appcenter any time , when i tried elementary os before installing it there were no problems but when i installed it i got those errors Pls Help 
![Screenshot from 2020-04-23 03-27-45](https://user-images.githubusercontent.com/63694847/80049147-73fbaa80-8512-11ea-9b22-4d4f98ac65d3.png)
![Screenshot from 2020-04-23 03-28-32](https://user-images.githubusercontent.com/63694847/80049202-8d045b80-8512-11ea-98f2-ca2c70f7a1f1.png)

**Comment by davidmhewitt** [comment]
Can you please show the details for the second error? There's a small triangle to click to get more information.

**Comment by danrabbit** [comment]
Closing since OP hasn't responded. Please feel free to Reopen if more information is provided
