### ISSUE TITLE
App center is freezing quickly just after open it and doesn't downloading flatpak aps

### ISSUE THREAD

**Issue by diegomagela** [elementary/appcenter#1282]
My app center is freezing constantly, just after open it. I have a i7 2.7GHz, 4 cores, and 16 Gb ram. So I think it isn't my laptop the problem. It is also doesn't downloading flatpak apps. I just wait 1h+ I not even asked permission to download. Curated apps it download. Does anyone knows what could be wrong?

**Comment by cassidyjames** [comment]
@diegomagela Flatpak apps don't require permission to install since they are only installed under your user, not the whole system. But I'm not sure what the other issues you're seeing could be.

**Comment by danirabbit** [comment]
A branch was merged not long ago to unblock the UI when AppCenter first loads, so closing as fixed :)
