### ISSUE TITLE
appcentre not opening

### ISSUE THREAD

**Issue by himanshubarpete** [elementary/appcenter#1294]

**Comment by davidmhewitt** [comment]
Please try and provide more information in bug reports. Even including which OS you're running helps us a little bit.

Does this happen all the time? Does it still happen after a reboot?

What happens if you try to start appcenter from the terminal with the following command:
```
io.elementary.appcenter
```

**Comment by davidmhewitt** [comment]
I'm going to close this issue as no further information was provided. Please provide more information if you are still experiencing this issue.
