### ISSUE TITLE
I can't update

### ISSUE THREAD

**Issue by serdenci** [elementary/appcenter#1295]
Error message;

W: '/etc/apt/sources.list.d/' dizinindeki 'spotify.list.save' dosyası geçersiz bir dosya uzantısı olduğu için yok sayılıyor
W: '/etc/apt/sources.list.d/' dizinindeki 'google-chrome.list.save' dosyası geçersiz bir dosya uzantısı olduğu için yok sayılıyor
W: '/etc/apt/sources.list.d/' dizinindeki 'appcenter.list.save' dosyası geçersiz bir dosya uzantısı olduğu için yok sayılıyor
W: '/etc/apt/sources.list.d/' dizinindeki 'elementary.list.save' dosyası geçersiz bir dosya uzantısı olduğu için yok sayılıyor
W: '/etc/apt/sources.list.d/' dizinindeki 'anydesk-stable.list.save' dosyası geçersiz bir dosya uzantısı olduğu için yok sayılıyor
W: '/etc/apt/sources.list.d/' dizinindeki 'patches.list.save' dosyası geçersiz bir dosya uzantısı olduğu için yok sayılıyor
W: İmza doğrulama sırasında bir hata meydana geldi. Depo güncel değil ve önceki indeks dosyaları kullanılacak. GPG hatası: http://deb.anydesk.com all InRelease: The following signatures were invalid: EXPKEYSIG 18DF3741CDFFDE29 philandro Software GmbH <info@philandro.com>
E: http://deb.anydesk.com all InRelease is not (yet) available (The following signatures were invalid: EXPKEYSIG 18DF3741CDFFDE29 philandro Software GmbH <info@philandro.com>)

**Comment by ryonakano** [comment]
I guess this should be a temporary network issue or due to added PPAs. Reopen if you're still facing this issue.
