### ISSUE TITLE
Title text is shortened even though I have a large display and the AppCenter window is maximized

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/appcenter#1299]
This is how it looks to me with the last stable elementary OS 5.1.4 Hera and without any modifications.

![Screenshot](https://user-images.githubusercontent.com/46536067/80969752-a0180500-8e09-11ea-9b62-57b14d047b3d.png)

**Comment by danrabbit** [comment]
This is intentional. There is a maximum column width.

Closing as “design conflict”

**Comment by 4jNsY6fCVqZv** [comment]
Could you imagine increasing the maximum column width at least so that the default text is visible?
As I said, the window is maximized and also the screen resolution is not too low.
Otherwise, it doesn't look very aesthetically pleasing to me.

**Comment by danrabbit** [comment]
This only occurs while the progressbar is showing. That would be addressed by https://github.com/elementary/appcenter/issues/1292

**Comment by 4jNsY6fCVqZv** [comment]
That irritates me a little. You closed this issue initially because of a design conflict. And at this point, it will still be resolved? https://github.com/elementary/appcenter/issues/1292
