### ISSUE TITLE
[$25] Restart Required should be an infobar not a header

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#130]
At the moment the Restart Required messaging in the updates view is a list header. Instead it should be an infobar at the top of the view

**Comment by codygarver** [comment]
There is a bounty for this issue [on Bountysource](https://www.bountysource.com/issues/43200147-restart-required-should-be-an-infobar-not-a-header).

**Comment by Philip-Scott** [comment]
@donadigo: if you could solve as well #131 with this it would be great for testing :)

**Comment by davidmhewitt** [comment]
Closed via #175
