### ISSUE TITLE
Non-Flathub remote applications not showing

### ISSUE THREAD

**Issue by tetebueno** [elementary/appcenter#1302]
After adding a Flatpak remote and installing an application from it, no applications are shown from that remote in AppCenter.

### To Reproduce
1. Add remote `flatpak remote-add --if-not-exists winepak https://dl.winepak.org/repo/winepak.flatpakrepo`
2. Install application `flatpak install -y winepak com.blizzard.StarCraft2`
3. Open AppCenter...

### Expected behavior
[Applications from that remote](https://github.com/winepak/applications) should be shown.

### Screenshots or screen recordings
![Screenshot from 2020-05-06 18 39 23](https://user-images.githubusercontent.com/9064236/81231133-08f9ab80-8fc9-11ea-8bbb-260efe827324.png)

### Logs
N / A

## Platform Information
![image](https://user-images.githubusercontent.com/9064236/81231225-30e90f00-8fc9-11ea-9c65-b595aafbcff5.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
Maybe this is not the expected behaviour, but after searching for what or how to do this, I found no information. Please, close if this is not valid.

**Comment by cassidyjames** [comment]
AppCenter currently only handles user Flatpaks, not system ones as it's safer and doesn't require root. There are plans to display system Flatpaks as well (https://github.com/elementary/appcenter/issues/1115), but until then you'll need to add the remote as a user remote instead or manage its apps from the Flatpak CLI.
