### ISSUE TITLE
Appcenter : Failed to Fetch Updates

### ISSUE THREAD

**Issue by BangDjaja** [elementary/appcenter#1341]
Appcenter -> Failed to Fetch Updates ->
E : The repository 'http://packages.elementary.io/appcenter hera Release' does not have a Release file.
W: Updating from such a repository can't be done securely, and is therefore disabled by default.
W: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/elementary-os/stable/ubuntu hera Release' does not have a Release file.
W: Updating from such a repository can't be done securely, and is therefore disabled by default.
W: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/elementary-os/os-patches/ubuntu hera Release' does not have a Release file.
W: Updating from such a repository can't be done securely, and is therefore disabled by default.
W: See apt-secure(8) manpage for repository creation and user configuration details

**Comment by davidmhewitt** [comment]
Something has replaced the contents of your sources files with some incorrect values, there is a post on the support pages here that describes you issue and how to fix it:

https://elementaryos.stackexchange.com/questions/23906/failed-to-fetch-updates-popping-up-on-app-center-and-cannot-install-apps
