### ISSUE TITLE
Clicking updates badge itself should navigate to updates tab

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#1344]
The red badge itself in the AppCenter window (not the one in the dock) doesn't respond to clicks. We should probably pack this in an eventbox or make it a button or something and make sure it does respond to clicks

**Comment by internetman420** [comment]
I would really love it if it was possible to click "Install updates" from the notifications. I would also really like to set a "Download & install updates automatically", like in ubuntu(?), and then just be prompted with a password when needed. This has probably been discussed before, but I can't really see the case for NOT making this an option (or really the default). With more or less daily updates this can be abit annoying for users imho.

Maybe this would be logical to include in the "Get started"-dialog one gets upon fresh install?

**Comment by danrabbit** [comment]
@internetman420 please file two separate issues for these feature requests. It is not possible to track multiple features in one report
