### ISSUE TITLE
вечная загрузка 

### ISSUE THREAD

**Issue by srakken** [elementary/appcenter#1352]
appcenter зависает при долгом использовании пк и неневозможно ничего установить так как он вечно пытается установить\обновить и не дает отменить 
> appcenter freezes when using the PC for a long time and it is impossible to install anything since it always tries to install / update and does not allow to cancel

**Comment by cassidyjames** [comment]
There has been a lot of work addressing performance and reliability over the last few months, so I'm going to close this. If there's more information about this still being an issue in up-to-date AppCenter, we can re-open.
