### ISSUE TITLE
AppCenter showed me an update two hours ago, although it looks like there was no new release

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/appcenter#1370]
This was an update for switchboard-plug-applications, which I could perform normally and which even showed me an update badge and a notification before. But both https://github.com/elementary/switchboard-plug-applications/releases and https://releases.elementary.io/ tell me that there is no new version. Why is that? I am irritated!

I use the latest stable and unmodified version of Hera.

**Comment by danrabbit** [comment]
There was a change to packaging, but no new release was made of the component itself.

This is not a bug

**Comment by 4jNsY6fCVqZv** [comment]
Thanks, that solves the puzzle for me!
Is it important that this kind of packaging change is delivered before the next update of the component itself?
