### ISSUE TITLE
UX issues with the spin busy indicator

### ISSUE THREAD

**Issue by megatux** [elementary/appcenter#1373]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

The spin "busy" indicator position, next to the search text box, is confusing because it is not related to the search action per se, but for other _background_ actions like installing a package, updating packages information (and possible other things hidden to the user).
It'd be nice if it is moved somewhere else.

### To Reproduce
Steps to reproduce the behaviour:
1. Open App Centre
2. See spinning animation
3. Enter a search text
4. See how this search does not produce a spinning animation

## Platform Information
- elementary OS 5.1.5 Hera

**Comment by danirabbit** [comment]
This was fixed in #1919
