### ISSUE TITLE
App center update notifications

### ISSUE THREAD

**Issue by NomadValle** [elementary/appcenter#1375]
Just started noticing that App Center keeps notifying me that I have updates, but when I go in there, there are no updates available. I've run an update command in terminal and have restarted. It still notifies me.

Dell Latitude e7450
Dual-Core Intel® Core™ i5-5300U CPU @ 2.30GHz
Intel Corporation HD Graphics 5500 (rev 09)
16.3 GB memory
234.7 GB storage (SATA SSD)

Thank you.

**Comment by marco4mp** [comment]
Seems the same problem as #1372 

Did you try `flatpak update` ?
That worked for me.

**Comment by NomadValle** [comment]
Hi. Yes I did see that after I posted this. It did work. I forgot to close this issue.
Thank you. I'll close out the issue.
