### ISSUE TITLE
Don't show alternate sources if app is curated

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1380]
Need to make sure this would make sense i.e. if we move the remotes as part of #233. But I wonder: if an app ID has a curated result, is there really a reason we want to expose the same ID from non-curated remotes? 

People might be choosing a non-curated remote to try to get around pay-what-you-can if they don't really know what they're doing, or thinking that "Flathub" = "more updates" even though it doesn't necessarily mean that when the app is curated and the developer is directly pushing updates to AppCenter.

**Comment by danrabbit** [comment]
Going to close this since I don't think we should be artificially limiting remotes that a user has chosen to add. If developers are publishing their apps on Flathub for free then that's up to them :shrug:
