### ISSUE TITLE
App impossible to unsinstall

### ISSUE THREAD

**Issue by gg2tok** [elementary/appcenter#1385]
Hi,

I tried to uninstall the Music app, but I got an error message "Uninstall Failure...." I attached the screenshot.
![Capture d'écran du 2020-07-19 17 35 14](https://user-images.githubusercontent.com/68509204/87879170-5ba00c80-c9e9-11ea-979e-6f6a470f7159.png)
It seems that he might mix the words music and musique (second is french indeed) but it might be a fake reason.
Thanks for any help.
Cheers.
gl

**Comment by danirabbit** [comment]
I'm not sure what caused the original issue here but Music is a Flatpak now and it can be uninstalled so closing as fixed :sweat_smile:
