### ISSUE TITLE
App Center Not Working

### ISSUE THREAD

**Issue by abdoKa** [elementary/appcenter#1387]
i can't lunch AppCenter

**Comment by cassidyjames** [comment]
@abdoKa how are you trying to open it? Is there any error displayed? Does it work after rebooting, or is it reproducibly non-openable?

**Comment by DStoyanoff** [comment]
Hello,
I have the same issue. Installed Elementary few days ago. The AppCenter was working, but then stopped. Maybe I did something to break it, but I can't find any information online that could fix it.
Thanks in advance!

**Comment by cassidyjames** [comment]
I believe this particular issue was resolved in the screenshot loading code. If that's incorrect or it re-appears, we can re-open this.
