### ISSUE TITLE
Appcenter and some other apps lnot working very pathetic to use elementary OS

### ISSUE THREAD

**Issue by deepak-archer** [elementary/appcenter#1393]
Appcenter and some other apps not working very pathetic to use elementary OS applicaations like bibus etc are asking for permissions but after entering password none of the apps is opening or doing anything. they become irresponsive type.

**Comment by BellemareMederic** [comment]
not very polite and missing basic information. 
please ref to https://elementary.io/fr/docs/code/reference#reporting-bugs

**Comment by cassidyjames** [comment]
Agreed with @BellemareMederic. If you have problems with specific apps, those issues would need to be reported to those app authors. If you can provide more information about what is not working for you in AppCenter itself, we can re-open and attempt to address it. But as is, there is not enough information here to do anything.
