### ISSUE TITLE
Missing software version for app from non-flatpak source

### ISSUE THREAD

**Issue by brownphotographic** [elementary/appcenter#1394]
**Problem**
For apps from some sources (non-flatpak), the software version on the detail page is missing. It appears to be present only at the bottom of the detail view for flatpak sources. for other sources, there is nothing.

![Screenshot from 2020-08-18 08 32 44](https://user-images.githubusercontent.com/23298495/90514898-d0bd4980-e12f-11ea-8425-cea26b4cc8b3.png)
![Screenshot from 2020-08-18 08 33 35](https://user-images.githubusercontent.com/23298495/90514908-d450d080-e12f-11ea-8ac6-9202b4b6d7aa.png)

**Comment by danirabbit** [comment]
Ah yeah this is expected. If the app doesn't provide changelog information there's nothing we can do about that. All apps published in the AppCenter backend are required to have changelogs, so this is an issue with the app or the alt store it's from and can't be fixed in AppCenter
