### ISSUE TITLE
"AppCenter" wrongly labeled in German translation

### ISSUE THREAD

**Issue by ErikTschierschke** [elementary/appcenter#1395]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
AppCenter seems to be wrongly labeled in the German translation.

Instead of just "_AppCenter_" it says "_" AppCenter" zum Übersetzungskatalog hinzufügen_" which roughly means "add AppCenter to translation catalogue" in any location.

### Expected behavior

AppCenter should just be labeled "_AppCenter_".

### Screenshots or screen recordings

![screenshot1](https://user-images.githubusercontent.com/56506427/90733295-a05ee200-e2cc-11ea-8166-1f2ac6768fc4.png)

![screenshot2](https://user-images.githubusercontent.com/56506427/90733419-d00dea00-e2cc-11ea-94b7-47e59d9b0a1f.png)

![screenshot3](https://user-images.githubusercontent.com/56506427/90733429-d308da80-e2cc-11ea-8496-cd013f48f19e.png)
## Platform Information

![version](https://user-images.githubusercontent.com/56506427/90734397-807bee00-e2cd-11ea-93ad-cbe5624389fb.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by davidmhewitt** [comment]
Hi, thanks for reporting this!

Translations are handled at https://l10n.elementary.io/

It looks like someone has already fixed this particular mistake: https://github.com/elementary/appcenter/commit/094d715a3077abbce3b6dbf76267ab5610c5d706

I'll close this issue as there is nothing to do other than wait for the next update of AppCenter.
