### ISSUE TITLE
Firefox from Ubuntu repos shows as "Unknown Origin (non-curated)"

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1404]
Not sure why, but I don't see it with other apps in the repos.

**Comment by dar5hak** [comment]
I observed it too, but thought it could be because I also have another, non-curated Firefox (Dev Edition) installed, and that may have confused the AppCenter.

**Comment by danrabbit** [comment]
We aren't manually shipping Firefox AppData anymore, so I guess this is fixed yay
