### ISSUE TITLE
cannot remove AppCenter from Dock

### ISSUE THREAD

**Issue by treasuretron** [elementary/appcenter#1412]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

I searched open issues in this repo for "dock" and nothing seemed like it covered this.

## Describe the bug

AppCenter gets re-added to the dock upon wake from sleep

### To Reproduce
1. right-click AppCenter in the dock and select "Keep in dock"
2. right-click again and de-select "Keep in Dock" (it goes away from dock)
3. close lid of thinkpad
4. open thinkpad, login, AppCenter is back in the dock.

### Expected behavior
AppCenter does not reappear in dock

### Logs

happy to grab logs, not sure which would be relevant here.

## Platform Information

![Screenshot from 2020-09-23 16-15-13](https://user-images.githubusercontent.com/679113/94064805-339da280-fdb8-11ea-8e9d-2c64bd29a67f.png)

Please check what applies:
-->
- [ ] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version (unsure, maybe?)

## Additional context
thanks!

**Comment by cassidyjames** [comment]
@treasuretron is AppCenter showing a badge for updates? The dock will show apps that are running in the background _and_ displaying dock badges.

**Comment by treasuretron** [comment]
@cassidyjames sometimes it shows a badge for updates and sometimes it shows a 0. Is it always running in the background? When I select 'keep in dock' and then unselect it, it goes away. Apps that are currently running don't disappear from the dock by unselecting keep in dock.

**Comment by cassidyjames** [comment]
The zero-update issue has been resolved and seems like it's the root cause of concern here. Yes, AppCenter is running in the background because it needs to in order to check and prompt for updates—that's why it shows in the dock when there's a non-zero number of updates to be installed.

**Comment by treasuretron** [comment]
The issue I'm describing is not related to zero updates as far as I understand. It's confusing that App Center can be removed from the dock but will be inexplicably re-added to the dock. Perhaps this is a feature request to be able to not have the App Center in the dock ever unless it is running in the foreground. An app updates background process shouldn't re-add App Center to the dock.

**Comment by cassidyjames** [comment]
@treasuretron when AppCenter is "inexplicably" shown on the dock, is it showing an update badge?

**Comment by treasuretron** [comment]
sometimes yes, often it will have an update badge of 0
