### ISSUE TITLE
Audacious won't start

### ISSUE THREAD

**Issue by DinoHasagic** [elementary/appcenter#1422]
elementary OS Release 5.1.7 Hera 64-bit , Audacious wont start, ver 3.9 and 3.10 work perfectly , after not good 4.05 , try to back on old 3.9 or 3.10 , but cant manage to start app at ALL ,try all combination install/uninstall  ,via terminal or APP CENTER..without default audio player !!!
![Selection_274](https://user-images.githubusercontent.com/65661475/94876436-f12f3200-0457-11eb-8187-0feba61f0e72.jpg)
![Selection_275](https://user-images.githubusercontent.com/65661475/94876501-19b72c00-0458-11eb-8c68-743637c0beb9.jpg)

**Comment by danrabbit** [comment]
Audacious is not made by elementary. You will need to file an issue report with the developer who makes it.

Closing as "out of scope" since this doesn't appear to be an issue with AppCenter
