### ISSUE TITLE
Libreoffice version in AppCenter is by default too old

### ISSUE THREAD

**Issue by Hacime** [elementary/appcenter#1423]
## Prerequisites
- [yes] I have searched open and closed issues for duplicates.

## Describe the bug
When installing Libreoffice in AppCenter with a fresh elementary os installation it installs version 6.0.... which is way too old.
If I want to install an update-to-date version of Libreoffice I have to install it from flathub.org .
As a first time user it takes time to figure this out. I think it would be better if the Libreoffice in the AppCenter would be up-to-date.

Maybe an **alternative solution** could be to include flathub.org as a source for AppCenter out of the box.
I have to download and install 1 app from flathub to add it as a source. Out of the box would be easier for first time users.

### To Reproduce
1. Go to AppCenter (with a new elementary os installation)
2. Search for Libreoffice
3. Install
4. Check version

### Expected behavior
Install latest version of libreoffice.

### Screenshots or screen recordings
---

### Logs
---

## Platform Information
 - OS: elementary os 
 - OS Version 5.1.7
 - Hardware info: Intel Core i5, 4GB RAM, 128GB SSD
 - I'm using the latest released stable version

## Additional context
---

**Comment by danrabbit** [comment]
Uncurated apps come from the Ubuntu repos and don't get regular updates. These packages are not maintained by elementary. This is explained in the warning dialog when installing uncurated apps.

Closing because this is not an issue with AppCenter. It's an inherent part of Ubuntu's package policy
