### ISSUE TITLE
Hide apps from the Ubuntu repos

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#1432]
We've discussed this several times, so I wanted to make sure it's been tracked.

At this point I think it's become fairly clear that users are not getting a good experience from apps in the Ubuntu repos. We frequently here about poor experiences with Libreoffice (primarily because of the way it's packaged) and many other popular cross platform apps are several versions out of date.

To set expectations about these apps, we tried introducing a dialog that made it explicitly clear that these apps may not receive updates and aren't maintained by elementary. This did not go over well. It seems like most people don't read the contents of the dialog and they're very upset that we would throw a warning about apps they feel are well trusted

So, it seems like the best option for many of these apps is not to offer them in AppCenter at all. Especially as most of them are available as Flatpak. It would generally be a better experience for our users to get the latest version of cross platform apps from outside of AppCenter than to try to rework setting expectations for apps in the Ubuntu repos.

**Comment by Bjargar** [comment]
how would that affect to newcomers?
