### ISSUE TITLE
Use appdata key for suggested price [$25]

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#144]
Create a custom appdata key to allow developers to choose a suggested price

**Comment by btkostner** [comment]
`x-appcenter-suggested-price` sound good?

**Comment by danrabbit** [comment]
Yee

**Comment by Philip-Scott** [comment]
@btkostner will the `x-appcenter-suggested-price` be in cents? 

@danrabbit This will just set the initial price, right? It won't add any style classes to the buttons (Suggested action to $5 if the price is $5?)

**Comment by btkostner** [comment]
Yes it will.

**Comment by danrabbit** [comment]
Right. No additional style classes should be necessary

**Comment by davidmhewitt** [comment]
For future reference, the merged branch that got merged for this expects `x-appcenter-suggested-price` to be an integer amount of dollars rather than cents.
