### ISSUE TITLE
Automatically install Flatpak updates

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1446]
See #288 for some context, but we should consider automatically installing Flatpak updates on non-metered networks.

UX to be determined, i.e. whether or not there is a preference for it, and if so, where that would be.

**Comment by cassidyjames** [comment]
My instinct is that there _should_ be a preference somewhere, especially as we don't really have a good flow for setting metered connections (you have to dig into the advanced connection settings, and it's not pretty or obvious). I can look at reviving my UI prototype of a menu for AppCenter that we were working on for AppCenter for Everyone. Perhaps a modelbutton with a switch there would be fine.

**Comment by jmc-88** [comment]
My unsolicited 2 cents: a preference should probably exist, not just for metered connections but also for storage consumption (Flatpak packages can be quite large, and potentially grow over time, so the user may want to be in control of what gets updated and when).

**Comment by vchernin** [comment]
GNOME software on Fedora auto updates Flatpaks out of the box, there is a toggle to disable it. Seemingly it tries to not do so when on metered connections. This update preferences menu is accessed via the hamburger menu (top right).
![image](https://user-images.githubusercontent.com/38842733/122651729-a8a3cb80-d0ef-11eb-8732-d2bfd482341f.png)

**Comment by marmeladapk** [comment]
+1 for preference, as e.g. updating Firefox flatpak while it's running causes unavoidable prompt to restart browser.
