### ISSUE TITLE
Throw toast when app is installed

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1455]
## Problem

When you install an app from a list view, it installs… and then nothing happens and there's no way to open it from that view. You either have to click through to the app listing an hit "Open" there, or go to your Applications menu. When AppCenter is not focused and an app is installed, a notification is thrown, at least—but nothing happens when it is focused.

## Proposal

We throw an in-app toast notification when an app is installed, with a handy action to open the app. This could either just be in list views, or globally in the app.

## Prior Art

We throw a system notification when an app is done installing, but only when the app is unfocused. I'm not sure what GNOME, macOS App Store, and Windows Store do off the top of my head.

**Comment by hanaral** [comment]
I don't think that a toast is suitable here, I thought toasts were for more formal small messages. I would not associate an app I download myself with a system function. I'd expect a notification with a colour icon and name, whether the app is focused or not, maybe even have a persistent notification with a progress bar.

**Comment by cassidyjames** [comment]
@hanaral not sure what you mean by "formal small messages." Toasts are for in-app notifications, full stop. Additionally, we tend to not throw system notifications when an app is focused, as those notifications tend to be more useful when you've navigated away from the app and want to return to it. If you're browsing AppCenter and installing apps, then AppCenter throwing an in-app toast to let you know your in-app action has completed makes a lot of sense to me.

(This almost makes me wonder if there should be a way to abstract the in-app toast vs. system notification based on whether the app is focused or not, and implement that in Granite or something… but that's beside the point for now.)

**Comment by hanaral** [comment]
@cassidyjames I personally associate toasts with basic yes/no sorts of functions (like as you mentioned with Camera’s video saved toast)
While I get _why_ it could be suitable for the AppCenter, I still think that something with more personality and colour would be expected of installing an app. 
If you aren’t budging on this, would it be possible to have the emblem-ok-symbolic icon to the right of the text in the toast? This would probably achieve some level of visually communicating the action without the need for a colour icon.
