### ISSUE TITLE
Firmware updates

### ISSUE THREAD

**Issue by adarnimrod** [elementary/appcenter#1459]
It would be nice to have firmware updates in the AppCenter.

## Problem
Firmware updates aren't visible and can't be applied from the AppCenter. 

## Proposal
Not a lot to say here, refresh the list from LVFS, list updates and apply them.

## Prior Art
Gnome Software and KDE Discover already have such functionality using fwupd.

**Comment by meisenzahl** [comment]
Should be handled in the About Plug

https://github.com/elementary/switchboard-plug-about/issues/123
