### ISSUE TITLE
AppCenter Does Not Open Unless First Time After Boot

### ISSUE THREAD

**Issue by kdwk** [elementary/appcenter#1463]
## What Happened

First time after boot: AppCenter opens correctly, functions properly
Every time after that: AppCenter refuses to open, cursor spins for a while, then returns to normal cursor. In Terminal, executing 'io.elementary.appcenter' yields nothing

## Expected Behavior

AppCenter should open correctly every time

## Steps to Reproduce

1. Reboot
2. Open AppCenter
3. Close AppCenter
4. Try to open AppCenter, will not open
5. Try to execute 'io.elementary.appcenter', yields nothing

### Logs

Executing 'io.elementary.appcenter' does not produce even a single line.
Executing 'gdb io.elementary.appcenter' does not produce anything useful to my knowledge. AppCenter still wouldn't run.

## Platform Information

elementary OS 5.1.7 Hera
appcenter/bionic,now 3.5.1+r2605+pkg97~ubuntu5.1.7.1 amd64 [installed,automatic]

**Comment by cassidyjames** [comment]
@kdwk I cannot reproduce this on an elementary OS 5.1 install with AppCenter 3.5.1. Are you still seeing this? If AppCenter is already running, `io.elementary.appcenter` will open or focus the window without any extra output—so it _sounds_ like it's running but not showing the window somehow. Do you have multiple displays, is it on a different workspace, etc.?

**Comment by kdwk** [comment]
Problem resolved. Appcenter now opens normally
