### ISSUE TITLE
Feature Request: Make flatpak optional.

### ISSUE THREAD

**Issue by darkshram** [elementary/appcenter#1469]
## Problem
Flatpak is very cool, but I would rather have AppCenter to manage and show only native applications and manage flatpak apps only with flatpak tool.

## Proposal
Provide  a build option to disable flatpak or a config option to disable flatpak backend.

## Prior Art
GNOME Control Center provides a build option to enable/disable flatpak.

**Comment by danrabbit** [comment]
I'm inclined to close this as "Design Conflict". Flatpak is the native package format for apps for elementary OS >= 6.0. We're moving away from managing apps via packagekit. It's highly likely we will only show Flatpak apps in AppCenter in the near future
