### ISSUE TITLE
AppCenter doesn't open on first login after fresh install in Daily image

### ISSUE THREAD

**Issue by hanaral** [elementary/appcenter#1472]
## What Happened
Logging in for the first time on the current daily image does not allow you to open AppCenter for whatever reason.

## Expected Behavior
AppCenter opens

## Steps to Reproduce

1. Install newest daily
2. Setup and log in
3. Try to open appcenter

## Platform Information
elementary OS 6 Daily

**Comment by danirabbit** [comment]
This doesn't seem to be the case anymore :)
