### ISSUE TITLE
Resizing AppCenter is slow when in the Installed tab

### ISSUE THREAD

**Issue by eliocamp** [elementary/appcenter#1474]
## What Happened

Resizing the AppCenter "installed" window is slow and choppy.

Video:

https://user-images.githubusercontent.com/8617595/104458640-6ac3d980-558a-11eb-9b44-1d44dd105269.mp4

## Expected Behavior

Resizing should be as smooth as any other window.

## Steps to Reproduce

1. Open AppCenter
2. Go to the Installed tab
3. Try to resize

## Platform Information

![image](https://user-images.githubusercontent.com/8617595/104458878-b5ddec80-558a-11eb-9d34-f77b7b92e2e6.png)

**Comment by hanaral** [comment]
I cannot reproduce this at all on Odin Daily apart from the performance hit during and after the updated apps are loaded. If you have access to the Odin ISO image, I would recommend going in to the demo session and try testing it there aswell.

**Comment by danirabbit** [comment]
As far as I can tell this has been fixed!
