### ISSUE TITLE
Unable to pay, unhelpful information

### ISSUE THREAD

**Issue by ayoungethan** [elementary/appcenter#1480]
## What Happened
Tried to purchase Clipped for the suggested $1. Payment fails:
card 1: 
"There was a problem processing your payment: This card does not support this kind of transaction. Please try again with a different card." 

What is "this kind of transaction?"

card 2:
"There was a problem processing your payment: Unable to complete the transaction. Please contact your bank for further information."

That's it -- out of cards. Can't pay for apps.

## Expected Behavior
I expected the payment to go through with one card or the other. I know for a fact that both are valid. I use them regularly.

I also expected a useful error message instead of vague language:
1.  What is "this kind of transaction?"
2.  What exactly is "a problem?"

## Steps to Reproduce

1. Open AppCenter
2. Navigate to Clipped
3. Attempt to purchase via credit card for $1

### Logs
Let me know if there are any relevant logs for me to collect for this issue.

## Platform Information
Hera 5.1.7

**Comment by janxkoci** [comment]
Is Stripe (the service handling payments) available in your country? I know they are not everywhere.

**Comment by ayoungethan** [comment]
I just paid for two apps using my card, and the 3rd app is giving me the message again: 

"There was a problem processing your payment: This card does not support this kind of transaction. Please try again with a different card."

Something weird is going on here.

@janxkoci Yes, I live in the US, the availability of Stripe is not the issue.

**Comment by ayoungethan** [comment]
If this is happening to other eOS users, then it could be a lot of money that developers aren't receiving for a technical reason. I want to support these apps that I use, but I can't!

**Comment by hezral** [comment]
i'm a developer and all my apps have this issue as well. i tested on my end with 3 different cards, all the same. 
i know Stripe works in my country as i have linked to buymecoffee and it works there. 

anyone can help here?

![image](https://user-images.githubusercontent.com/762735/132145265-aec24c3b-cb00-4aa9-b924-d57cbab21366.png)

**Comment by ayoungethan** [comment]
Yes, I believe this is a critical issue, especially since one of the core
missions of eOS (as I understand it) is to demonstrate and pioneer how open
source can be effectively monetized and support OSS developers and further
development in alignment with the OS community's core values. It really,
really, needs a reliable and accessible payment gateway. Otherwise,  "No
margin, no mission."

**Comment by cassidyjames** [comment]
Closing this because it seems to be an issue of incorrect Stripe keys inserted into AppData, and there's not really anything we can do in the AppCenter client about that. Please see the specific issues on the apps above.

**Comment by janxkoci** [comment]
Hi @cassidyjames, and what about the "unhelpful information" part of the issue?

**Comment by danrabbit** [comment]
@janxkoci the amount of information we get back from the payment processor and the amount of information they get from your bank is limited intentionally for security reasons and to prevent fraud

**Comment by ayoungethan** [comment]
This still seems like a premature dead end. I understand closing this bug, but this still seems to be an issue somewhere. Is this an upstream bug?

What can people do to avoid the "incorrect Stripe keys inserted into AppData" issue? IE, who (or what) is "inserting incorrect keys into AppData," where, how, and why? should this be a bug report opened elsewhere in the ecosystem? 

For example, Are app developers doing something wrong? If so, is it an issue of providing clear and accurate payment documentation for app developers?

**Comment by cassidyjames** [comment]
@ayoungethan yes, app developers were inserting incorrect Stripe keys in their AppData. As a result, we have:

- updated developer documentation (https://github.com/elementary/docs/pull/112 and https://github.com/elementary/docs/pull/157)
- revamped the [developer dashboard](https://developer.elementary.io) with very clear step-by-step instructions and the required Stripe key
- reached out to affected developers

Closing this is hardly premature, as we've been constantly working on and fixing the various facets of this issue over the past year. :smile:

**Comment by janxkoci** [comment]
Well, if you scroll up, there is not a single **"This issue was mentioned in ..."** - so we couldn't possibly know there was all that work happening :smiley: 

Sorry for bugging, nice job there :blush:
