### ISSUE TITLE
Going back from OS Updates to Installed list prevents using mouse in list

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1482]
## What Happened

If I'm checking out the details of an update by clicking on its listing

![@2x](https://user-images.githubusercontent.com/611168/106952202-078f1800-66ee-11eb-882d-a95aaa1782b3.png)

and then go back to the Installed list, the list loses focus, and I'm somehow prevented from using my mouse in the view.

![Screenshot from 2021-02-04 13-37-07@2x](https://user-images.githubusercontent.com/611168/106952689-a7e53c80-66ee-11eb-828f-25ddb7c48b61.png)

I can use the arrow keys to regain focus and select things, but the list doesn't respond to mouse clicks. I wonder if this is a regression from #1436, and/or could be an issue in Handy itself?

## Expected Behavior

Going back works as expected, the list stays focused, and I can use my mouse to select items in the list.

## Steps to Reproduce

1. Open AppCenter
2. Go to the Installed view
3. Click a listing (i.e. OS Updates)
4. Click the "Installed" back button at the top-left

Sometimes it takes going back and forth a few times for it to trigger, but once it triggers, it seems to be very reproducible.

### Logs

None at the moment, but can provide if it's useful.

## Platform Information

- elementary OS 6 Early Access (20210202 ISO, up-to-date as of now)
- AppCenter master

**Comment by danrabbit** [comment]
I can reproduce this. It only seems to occur once the list is done loading. I can't reproduce it while updates are being refreshed.

I can also confirm that the issue is reproducable with #1436 and later, but not the commit directly before
