### ISSUE TITLE
No Curated List but Default Apps

### ISSUE THREAD

**Issue by oVerde** [elementary/appcenter#1484]
## What Happened
Can't find any previously installed Curated App on the store any more

## Expected Behavior
When searching for Clipped/Screenrec, it should appear in the list

## Steps to Reproduce

Be me
1. install elementary OS 6 Early Access,
2. open App Center
3. search Clipped (or Screenrec)
4. no Clipped (or Screenrec) is found

### Logs
No log

## Platform Information
* elementary OS 6 Early Access
* App Center 3.5.1

**Comment by danrabbit** [comment]
This is expected and explicitly noted at builds.elementary.io before you download
