### ISSUE TITLE
App info body text has different background colour than AppCenter's

### ISSUE THREAD

**Issue by hanaral** [elementary/appcenter#1488]
## What Happened

The background colour of the main body text for app pages and library updates is different from the background white colour the AppCenter has

## Expected Behavior

Text has same bg as rest of AppCenter

## Steps to Reproduce

1. Go to any AppCenter listing
2. Scroll down to the main body text

![Screenshot from 2021-02-11 10-19-30](https://user-images.githubusercontent.com/58219504/107624765-3f004600-6c53-11eb-89c1-ee2a78077abe.png)

## Platform Information

elementary OS 6 Daily, Mesa graphics

**Comment by ryonakano** [comment]
Can confirm this, it's more obvious in dark style.

**Comment by cassidyjames** [comment]
Thanks, I kept forgetting to file this. 😅

**Comment by danrabbit** [comment]
I believe this has been resolved. I can't reproduce it anymore
