### ISSUE TITLE
granite >= 6.0.0 required

### ISSUE THREAD

**Issue by hellisabove** [elementary/appcenter#1498]
In order to compile appcenter I need granite version 6.0.0 but on the github repo of granite the latest version released is 5.5.0. Where can I get it on Ubuntu 20.04?

**Comment by ryonakano** [comment]
If you're using Odin Daily, it's already available on your system. If you're on Hera, compile and install the latest master of Granite first and then compile AppCenter.

**Comment by hellisabove** [comment]
I'm on ubuntu 20.10 and I solved it by compiling it from source but Thanks for info for the future.
