### ISSUE TITLE
application center closes within seconds of starting

### ISSUE THREAD

**Issue by gac982** [elementary/appcenter#1500]
Hello I have this problem with the elementary application center, when I open the application after 3 seconds it closes I ran it through the terminal and it threw me the following error:

---
> ** (io.elementary.appcenter:12085): CRITICAL **: 16:28:35.665: ComponentValidator.vala:37: Using .blacklist files is deprecated and will be removed in next version, please use .hiddenapps instead
Violación de segmento

OS: elementary OS 5.1.7 Hera x86_64 
Host: Inspiron 3421 
Kernel: 5.4.45-050445-generic 
Shell: bash 4.4.20 
Resolution: 1366x768, 1366x768 
DE: Pantheon 
WM: Mutter(Gala) 
Terminal: io.elementary.t 
CPU: Intel Pentium 2117U (2) @ 1.800GHz 
GPU: Intel HD Graphics 2500 
Memory: 2708MiB / 5843MiB 

---

I hope you can help me, I already have several months with this failure, thanks

**Comment by danirabbit** [comment]
Hey thanks for reporting this issue. OS 5.1.7 is no longer receiving bug fix updates. Please upgrade to OS 6.1 and see if this issue is still reproduceable for you.

Closing as "incomplete" until we can verify that the issue still exists on an up-to-date system
