### ISSUE TITLE
Completely redesigned UI

### ISSUE THREAD

**Issue by Suzie97** [elementary/appcenter#1504]
![image](https://user-images.githubusercontent.com/68198116/111858321-0ba18d00-895e-11eb-879e-a94c331faa4c.png)

I found this is AppCenter UI design by Alecadd on his Dribble portfolio.

Is there any chance that something similar to this can be the AppCenter UI??

**Comment by hanaral** [comment]
I've always thought the idea of a sidebar would be nice, as it seperates the tabs and categories better. For example, the home page could be replaced with the 'most popular' or even something like the iOS 11 AppStore redesign that added the 'Stories' view.
I personally think that regardless of what gets decided, there should be a 'story' like section with curated articles every so often written by or about developers and their apps.

**Comment by Henryws** [comment]
That looks so cool! One note is that the Home, recently updated, most popular should probably be at the top where home and installed usually would be. Remove the authors tab, it takes up space and should show on an app's page instead of on the home page

**Comment by stsdc** [comment]
I think showing Featured authors is a cool thing, because it's humanizes software development.

**Comment by Suzie97** [comment]
Can anyone tell me if this issue can be moved to the discussions section. Because while creating it, I was not aware that AppCenter has discussions. 

There is already an on going idea on the discussions section. We can merge the two

**Comment by danrabbit** [comment]
Indeed, this is more appropriate for discussions. Please post any and all mockups on the discussion thread here: https://github.com/elementary/appcenter/discussions/1467

Closing this issue report since it's not a single self-contained actionable item, but rather an open-ended discussion
