### ISSUE TITLE
No sliding animation

### ISSUE THREAD

**Issue by kdwk** [elementary/appcenter#1514]
## What Happened

The first time I click on a category after opening AppCenter, there is no sliding animation.

https://user-images.githubusercontent.com/39268094/113977192-ca254300-9874-11eb-8458-f57034b047a4.mp4

## Expected Behavior

The app category page should slide from right to left

## Steps to Reproduce

1. Quit AppCenter
2. Open AppCenter
3. Click on a category

## Platform Information

![Screenshot from 2021-04-08 13-53-56](https://user-images.githubusercontent.com/39268094/113977217-d27d7e00-9874-11eb-80f7-b714675c8d03.png)

**Comment by danrabbit** [comment]
This should be fixed with #1769 and #1851
