### ISSUE TITLE
Front page broken

### ISSUE THREAD

**Issue by kdwk** [elementary/appcenter#1515]
## What Happened

Icons and text on the front page of AppCenter partially hidden
![Screenshot from 2021-04-08 14-28-00](https://user-images.githubusercontent.com/39268094/113978767-ede98880-9876-11eb-989d-501d21438c16.png)

## Expected Behavior

![Screenshot from 2021-04-08 14-30-26](https://user-images.githubusercontent.com/39268094/113978797-f9d54a80-9876-11eb-9eed-b65573968da7.png)

## Steps to Reproduce

Unknown. Cannot be systematically reproduced.

### Logs

Could not obtain logs because a systematic way of reproducing the issue is not yet known.

## Platform Information

![Screenshot from 2021-04-08 13-53-56](https://user-images.githubusercontent.com/39268094/113979137-7405cf00-9877-11eb-8cad-a9d66d85db8a.png)

**Comment by cassidyjames** [comment]
We rewrote this in #1662 and #1648, so it shouldn't be an issue any more.
