### ISSUE TITLE
Sliding animations not correct

### ISSUE THREAD

**Issue by kdwk** [elementary/appcenter#1517]
## What Happened

In category view, I can click on apps to view its information. However, sometimes the it slides from left to right instead of right to left. This issue is observed in 'maths, science and engineering' only at the moment.

https://user-images.githubusercontent.com/39268094/114126586-4a0de480-992b-11eb-80b8-2d0d8eb98b89.mp4

## Expected Behavior

The sliding animation should be from right to left

https://user-images.githubusercontent.com/39268094/114126695-893c3580-992b-11eb-8b7f-99e05d1206d5.mp4

## Steps to Reproduce

1. Open AppCenter
2. Click on the 'math, science and engineering' category
3. Try clicking on apps

## Platform Information

![Screenshot from 2021-04-08 13-53-56](https://user-images.githubusercontent.com/39268094/114126778-ab35b800-992b-11eb-98cf-372ae907ce89.png)

**Comment by cassidyjames** [comment]
Thanks for reporting this! However, I cannot reproduce it; is it possible you clicked around in the "Other apps by" section at the bottom of an app's page, first? That would be the only way I think this would confuse the order of the stack.

**Comment by kdwk** [comment]
I cannot reproduce this issue either after I restart AppCenter. In fact, there are lots of mysterious issues that happened to me frequently enough to be annoying, but not frequently enough that I can properly reproduce and document it. A lot of them are not consistent at all, sometimes they'll come up and sometimes they'll not, sometimes they'll come up and disappear within the same session. They come up in different places. It's all very strange.

**Comment by kdwk** [comment]
https://user-images.githubusercontent.com/39268094/114291273-b702b500-9ab8-11eb-8c5c-8787423ccf56.mp4

See, right after I wrote the previous comment it happened again with a different app. Just to prove that I didn't click on anything in the 'Other apps by' section I returned to the main page first

**Comment by kdwk** [comment]
https://user-images.githubusercontent.com/39268094/114291330-1e206980-9ab9-11eb-811c-5379d4c41faa.mp4

And... right after I wrote _that_ I caught it again. This video is recorded without reopening AppCenter after the previous video. This time I tested it in another category, and this time it affected multiple apps in the same category.

I can deduce one thing: the problem, if it appears, cannot be solved by returning to the main page and entering the category again

**Comment by kdwk** [comment]
https://user-images.githubusercontent.com/39268094/114291541-d7cc0a00-9aba-11eb-8f40-d3530dead685.mp4

Here it is again

**Comment by hanaral** [comment]
@cassidyjames I can reproduce it; try going to any of the elementary app's pages and continuously navigating to other listings from the same creator (in this case elementary, so via any of the 'other apps by elementary' at the bottom of the page)
