### ISSUE TITLE
Attempt to recover from Flatpak issues

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1523]
## Problem

If Flatpak gets into a state where it needs to be repaired (e.g. if an install was interrupted), AppCenter fails to install or update Flatpaks until `flatpak repair` is run (mentioned in #1234 and https://github.com/pop-os/shop/issues/248#issuecomment-778692701)

## Proposal

AppCenter should attempt to recover from Flatpak issues by automatically repairing.

## Prior Art

I'm not sure if GNOME Software or KDE Discover do anything special in this situation.

**Comment by davidmhewitt** [comment]
There aren't any repair methods exposed in the public libflatpak API so achieving this would likely be a case of asking if they can be (or why they shouldn't be), or running `flatpak repair` as a subprocess (which wouldn't really be the preferred solution)

**Comment by cassidyjames** [comment]
@davidmhewitt ah, that makes sense. Yeah I think it's worth asking Flatpak devs if they can/should be exposed, as I understand our current options are to silently error (like now), throw a dialog asking the user to run Terminal commands (eww), or spawning a subprocess (also eww).

**Comment by hanaral** [comment]
I think `flatpak repair` should have an indication on whether it's running or not since it disables your ability to open any apps (and can also take a very long time if you have lots of app and/or are on an HDD)

**Comment by danirabbit** [comment]
I think this should be considered fixed with #1983 since we now offer a Flatpak repair option as a subprocess
