### ISSUE TITLE
Two flatpak updates that don't update (EOS 6 public beta)

### ISSUE THREAD

**Issue by KarkanAlzwayed** [elementary/appcenter#1530]
There are two updates in the app center that don't want to update nor go away:
2 components with updates:
 • io.elementary.Platform Flatpak runtime
 • io.elementary.Sdk Flatpak runtime
Every time I click to update them, the progress bar starts for a brief second then stops, but they don't update. Thought a reboot would fix it, but it doesn't.

Edit1: the issue is now gone for me. Looks like it was fixed. I'll keep an eye out for it. 

Edit2: The issue seems to have come back with another flatpak package that refuses to install from both the app center and terminal. On the app center, it just flashes the update bar real quick then doesn't update. On the terminal, this is what I get after running `flatpak update`

```
Looking for updates…


        ID                                Branch          Op         Remote            Download
 1. [✗] io.elementary.Sdk.Locale          daily           u          appcenter         1.0 kB / 331.0 MB

Warning: While pulling runtime/io.elementary.Sdk.Locale/x86_64/daily from remote appcenter: Commit 6926f698875060832b0d052af45bed701366ec1d501fba0643f37427a5970a0d: GPG verification enabled, but no signatures found (use gpg-verify=false in remote config to disable)
Updates complete.

```

Edit3: Today May 15th 2021, the issue is gone now.

**Comment by EmyrB** [comment]
Same issue here too, but when I try to update flatpak from command line I get this error too
`Warning: Commit metadata for runtime/org.freedesktop.Platform.GL.default/x86_64/20.08 not matching expected metadata
Installation complete.`

I've tried flatpak update --apstream and flatpak repair --user but no avail.
Here is the output of flatpak update -v
1.	   	org.freedesktop.Platform.GL.default	20.08	i	appcenter	< 487.1 MB

Proceed with these changes to the system installation? [Y/n]: y
Installing…                                                                                                 F: Calling system helper: GetRevokefsFd
F: Calling system helper: GetRevokefsFd
F: flatpak_dir_pull: Using commit 2b69e7370fd5bd740716e9f9cec7ac7cd53fdb6f1f647055a6ca0c40bde4cb4f for pull of ref runtime/org.freedesktop.Platform.GL.default/x86_64/20.08 from remote appcenter

Installing…                        0%  0 bytes/s
Installing… ▍                      2%
Installing… ████████████████████ 100%F: Calling system helper: CancelPull
F: Calling system helper: CancelPull
Warning: Commit metadata for runtime/org.freedesktop.Platform.GL.default/x86_64/20.08 not matching expected metadata
Installation complete.                                                                                        
F: appcenter:x86_64 appstream age 1342 is less than ttl 86400

**Comment by RedBearAK** [comment]
Running AppCenter from a terminal, I see the same error as in the post above when trying to install the "stuck" Flatpak updates: 

```
** (io.elementary.appcenter:13996): WARNING **: 12:22:32.593: FlatpakBackend.vala:1225: Flatpak installation failed: Commit metadata for runtime/org.freedesktop.Platform.GL.default/x86_64/20.08 not matching expected metadata
```

And the same errors as above if I try to update Flatpak in the terminal. The same exact commit hash number too.

**Comment by lilvadim** [comment]
The issue seems to be gone away?

**Comment by pierrers-design** [comment]
> The issue seems to be gone away?

Yep the issue is gone for me !

**Comment by RedBearAK** [comment]
@lilvadim 

Checked my eOS VM and there were a bunch of new updates waiting. Installed them all and rebooted and the Flatpak package problem doesn't appear to be coming back. It would always reappear after letting the AppCenter check for updates. But I've done a few reboots and let AppCenter check for updates several times and the Flatpak package bug is not showing up for me anymore. 

Looks like something fixed it.

**Comment by meisenzahl** [comment]
If someone can reproduce it, please comment and then we can reopen.

**Comment by KarkanAlzwayed** [comment]
Issue is gone now. I've updated my original comment.

**Comment by EmyrB** [comment]
Can confirm, that this issue has gone for me too.

**Comment by KarkanAlzwayed** [comment]
> The issue seems to be gone away?

It is back again today, but this time with one package. I have update the original comment.

**Comment by KarkanAlzwayed** [comment]
> If someone can reproduce it, please comment and then we can reopen.

It is back again today, but this time with one package. I have update the original comment.

**Comment by nielsvl95** [comment]
I also got this issue today. It is for the ' io.elementary.Platform.Locale Flatpak runtime'.
When trying to update in the terminal I get a signing error. You can see it in the screenshot below.
![Schermafdruk van 2021-05-23 16-17-52](https://user-images.githubusercontent.com/66212886/119264206-74b5b300-bbe2-11eb-9f08-2a38802bc151.png)

**Comment by KarkanAlzwayed** [comment]
@meisenzahl I'm also getting that exact message

**Comment by cassidyjames** [comment]
These were expected issues as we rebuilt the Flatpak server. They should be resolved.
