### ISSUE TITLE
Lack of Information

### ISSUE THREAD

**Issue by dougie80** [elementary/appcenter#1531]
Love Elementary as I am new to it, I like the way you are bringing the not so tech savvy Linux users (like me).

Would like to suggest two improvement features for the Appcenter.

1) Reviews on the apps amount of reviews and a 0-5 star review after download.
2) Size of the app in MB

thanks

**Comment by danrabbit** [comment]
Thanks for your feedback!

Reviews are already filed as a wishlist item here: https://github.com/elementary/appcenter/issues/25

AppCenter already shows the download size below the install button. It may take a couple seconds for the download size to be calculated:

![Screenshot from 2021-05-14 07 55 59@2x](https://user-images.githubusercontent.com/7277719/118280879-d8750900-b489-11eb-8813-3a9692e026a3.png)
