### ISSUE TITLE
Add navigate back using 'Esc' key.

### ISSUE THREAD

**Issue by lilvadim** [elementary/appcenter#1534]
## Problem
No ability to navigate back using `Escape` key.
## Proposal
I suggest to make `Esc` key doing the same action as back button (e.g. `← Audio` on this screenshot).
![Screenshot from 2021-05-16 14-17-26](https://user-images.githubusercontent.com/32203382/118388934-7961f080-b651-11eb-8e5f-64d18005df46.png)

**Comment by danrabbit** [comment]
I don't think we have a precedent for using esc to navigate back. There are some elements like dialogs or popovers that I believe can be dismissed with esc but I believe our standard back shortcut is alt + left

**Comment by danirabbit** [comment]
Gonna close this since no other app uses `esc` as a back navigation shortcut and this would introduce an inconsistency in navigation
