### ISSUE TITLE
Handle Flatpak channels

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1538]
## Problem

Apps in the AppCenter remote may have `master` and `stable` channels. Right now it's not obvious or configurable for which channel you'll get when you install an app (e.g. Calculator). 

## Proposal

We should be able to default to a stable branch when installing, and possibly offer an option for other channels in the remote combobox.

## Prior Art

We show multiple remotes in the combobox, but would need to expand that to channels.

**Comment by kdwk** [comment]
I think AppCenter needs to be a little clearer to the end users what exactly do the different channels mean. I still remember entering Linux from Windows or macOS, and being extremely confused about software management. A typical Windows and macOS user is unlikely to understand the concept of repositories or channels, especially those named 'AppCenter master' or something. 'What does that even mean?' the user would reasonably ask. To them, an app store is just an app store. You go on the app store and click the 'Install' button. AppCenter should be as simple as that. I suggest that AppCenter default to stable of the AppCenter Flatpak repo, and then add a toggle in System Settings that says something like 'Show development branches' or 'Show experimental versions of apps'.

**Comment by cassidyjames** [comment]
Oops, duplicate of #1369
