### ISSUE TITLE
Failed to update “Operating System Updates” in EOS 6 Beta

### ISSUE THREAD

**Issue by rahayon** [elementary/appcenter#1540]
## What Happened
When i update my system from app center then shows error "Failed to update “Operating System Updates”
Failed to update “Operating System Updates”

**Error:**
The following packages have unmet dependencies:
  pantheon-online-accounts-plugin-lastfm: Depends: switchboard-plug-online-accounts (= 2.0.1+r925+pkg63~daily~ubuntu6.1) but 3.0.0+r65+pkg65~daily~ubuntu6.1 is to be installed
  pantheon-online-accounts-plugin-fastmail: Depends: switchboard-plug-online-accounts (= 2.0.1+r925+pkg63~daily~ubuntu6.1) but 3.0.0+r65+pkg65~daily~ubuntu6.1 is to be installed
  pantheon-online-accounts-plugin-mail: Depends: switchboard-plug-online-accounts (= 2.0.1+r925+pkg63~daily~ubuntu6.1) but 3.0.0+r65+pkg65~daily~ubuntu6.1 is to be installed

**Screenshot**
![Screenshot from 2021-06-10 07 24 27](https://user-images.githubusercontent.com/33887458/121450541-c4a3c080-c9bd-11eb-9331-5e96a7577b3a.png)
![Screenshot from 2021-06-10 07 26 25](https://user-images.githubusercontent.com/33887458/121450545-c66d8400-c9bd-11eb-939a-efcef285da92.png)

**Comment by cassidyjames** [comment]
There were packaging changes due to the beta nature; you should be able to resolve this from Terminal by running:

```sh
sudo apt update && sudo apt dist-upgrade -y
``

**Comment by matagyula** [comment]
Cheers Cassidy, worked like a charm.
I am really enjoying the beta btw :)
