### ISSUE TITLE
Changelog not showing

### ISSUE THREAD

**Issue by shawn1thompson** [elementary/appcenter#1550]
## What Happened

AppCenter shows what appears to be changes that were made to apps a while back and doesn't show current changes.

## Expected Behavior

AppCenter should show current changes for apps being updated.

## Steps to Reproduce

1. Open AppCenter
2. Click installed after refresh finishes.
3. Notice old changes

## Platform Information

OS 6 Odin Beta 2

**Comment by danrabbit** [comment]
This is expected since you're running a pre-release and changelogs haven't been updated yet since there isn't a new release yet :) This will be automatically resolved when releases are made in the stable version
