### ISSUE TITLE
Banner shadow sometimes incorrect

### ISSUE THREAD

**Issue by kdwk** [elementary/appcenter#1554]
## What Happened

![Screenshot from 2021-07-20 11-38-23](https://user-images.githubusercontent.com/39268094/126258293-24ef59f3-2c35-4646-984f-3131337e927b.png)

This only happens occasionally. There appears to be an undersized hard barrier constricting the purple shadow of the banner.

## Expected Behavior

![Screenshot from 2021-07-20 11-40-26](https://user-images.githubusercontent.com/39268094/126258378-934eb2af-34aa-4f83-864a-4f016a0d329e.png)

## Steps to Reproduce

Cannot be reliably reproduced. Keep hovering over the banner until it happens.

## Platform Information

AppCenter 3.6.0+r2907+pkg100~daily~ubuntu6.1

**Comment by cassidyjames** [comment]
We rewrote banners in #1662, so this is solved :sweat_smile:
