### ISSUE TITLE
Can't perform updates

### ISSUE THREAD

**Issue by JhohannesK** [elementary/appcenter#1584]
The app center fails to update system apps

**Comment by marbetschar** [comment]
Which elementary OS you are using? Not sure if you've heard it already - OS 6 is out:
https://blog.elementary.io/elementary-os-6-odin-released/

Not sure, but maybe the AppCenter error is related...

**Comment by JhohannesK** [comment]
So this means I have to do reinstallation to upgrade to odin

**Comment by marbetschar** [comment]
Yes. Upgrading to Odin through AppCenter is not possible. A fresh installation is a requirement.

**Comment by JhohannesK** [comment]
Ok, thanks for the clarification.

**Comment by marbetschar** [comment]
Your welcome. Gonna close this issue for now - feel free to reopen if needed.
