### ISSUE TITLE
Mention sideloading on empty search results

### ISSUE THREAD

**Issue by MauricioGlz** [elementary/appcenter#1587]
## Problem
When users search for apps on App Center and the application is not found on the oficial repositories, a simple message of not found is shown, this does not solve the user problem of installing the searched app. 

## Proposal
I believe that showing a message like "We dont have the <app_name> but it might be available on flathub (link to flathub)" in stead of saying the user that the app is not found is way more usable and friendly. While more advanced users know about flathub elementary focus market are more begginers, and for the most part, begginers do not know what flathub or flatpaks are.

**Comment by cassidyjames** [comment]
Honestly I think if we were going this far to suggest Flathub, we'd just include it out of the box. But the latter is blocked until we can make more technical security and privacy guarantees by moving to Wayland, so I don't see this happening.

**Comment by danrabbit** [comment]
I wonder if it's worth including some kind of language referencing sideload or some kind of recommendation for folks to search outside of the store?

**Comment by MauricioGlz** [comment]
Well I don't see the point of using flatpak if you are not going to allow it anyway.

As @danrabbit suggests maybe just mention a way to get more apps it is going to be way better than just tell the user that the search was useless.

**Comment by cassidyjames** [comment]
@danrabbit yeah I suppose we could use similar language to what we use in Onboarding. It just really feels like we're going out of our way to not include Flathub while also directing users there at every turn. It makes me wonder if we can just include it and adjust language so we're doing the same amount of disclaiming (or more!) while also making it easier to discover those non curated apps.

**Comment by danrabbit** [comment]
@cassidyjames im not sure we necessarily need to link to FlatHub, but we could say something about being able to side load Flatpak apps so it's at least a bit more clear there for folks who know what that means or something to Google

I think now that we're no longer showing Deb apps we can work on showing permissions more clearly and maybe there is a pathway to including FlatHub in a responsible way? But without going into that, it could still be an improvement just to mention that there is a way to get apps other than what's in the store and hopefully steer people towards Flatpak and not Deb packages or something

**Comment by cassidyjames** [comment]
@danrabbit sounds reasonable, let's reopen this with that more specific scope.

**Comment by MauricioGlz** [comment]
> @cassidyjames im not sure we necessarily need to link to FlatHub, but we could say something about being able to side load Flatpak apps so it's at least a bit more clear there for folks who know what that means or something to Google
> 
> I think now that we're no longer showing Deb apps we can work on showing permissions more clearly and maybe there is a pathway to including FlatHub in a responsible way? But without going into that, it could still be an improvement just to mention that there is a way to get apps other than what's in the store and hopefully steer people towards Flatpak and not Deb packages or something

Love you guys, thanks for reopen this, I'm sure that by a little thinking this can be figured out.

**Comment by MauricioGlz** [comment]
This may be already on consideration, but a toggle or checkbox to enable flathub on the security settings with a tag like "Use external source for apps" and inform the user abaut the risk of that, so it can confirm or denegate the use of that "external soruce".

This is just a suggestion, as fas I can go is that, so I will keep thinking on oher ways 😁

**Comment by MauricioGlz** [comment]
@cassidyjames Kind of off topic question, but I need to know to be able to help a little more (if possible), I'm a web front-end developer and designer (UI/UX) and I know that every system has their own way to reach users, do you have guidelines for the copy's?

**Comment by Gabriel-p** [comment]
> Honestly I think if we were going this far to suggest Flathub, we'd just include it out of the box.

**Yes!**

> But the latter is blocked until we can make more technical security and privacy guarantees by moving to Wayland, so I don't see this happening.

What are these guarantees? Could they not be addressed adding a warning/disclaimer and just letting the user decide if they are comfortable with the possible issues?

**Comment by cassidyjames** [comment]
@MauricioGlz we have the Human Interface Guidelines: https://docs.elementary.io/hig/reference/text

**Comment by MauricioGlz** [comment]
> @MauricioGlz we have the Human Interface Guidelines: https://docs.elementary.io/hig/reference/text

Great, thanks I'll take a look and try to give some copy's ideas.

**Comment by MauricioGlz** [comment]
Here are some ideas:

- No apps found. You can enable more apps on the security settings.
- No apps found. We don't have the app you're looking for, you can enable other sources (link to security settings).
- Want more results? Try using sideload for get more apps.
- No apps found. Sideload can load flathub apps for you.
- No apps found. Learn more about sideload here (link to blog post/webpage explaingn flathub and their risk/consecuences)

**Comment by cassidyjames** [comment]
Ooh, I kind of like the last option, but I'd have to write a blog post first. :wink: Maybe that's something to work towards, but we can provide _some_ copy here to start.
