### ISSUE TITLE
AppCenter searches 

### ISSUE THREAD

**Issue by anujsr12** [elementary/appcenter#1611]
## What Happened

searches not working
it showing only those app which are pre installed only in appcenter

## Steps to Reproduce

1.
2.
3.

**Comment by anujsr12** [comment]
resolve it

**Comment by cassidyjames** [comment]
@anujsr12 it sounds like you might be hitting this issue in the FAQ: https://github.com/elementary/os/wiki/elementary-OS-6-Odin-FAQ#is-appcenter-empty-where-are-the-apps

Let me know if you're seeing a different issue.
