### ISSUE TITLE
Card check is too strict [$50]

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#162]
The current card number check appears to be hitting false negatives; i.e. my personal Visa debit card is not seen as valid. We might be too strict or have a bug with the client-side validation.

**Comment by Philip-Scott** [comment]
Ohhh, it might only approve Credit cards and not debit. I'll check it out later doing the weekend

**Comment by cassidyjames** [comment]
A card I've tested locally passes the Luhn check, but is rejected by the code in AppCenter. It looks like we have a bug. It might be better to disable the Luhn check for now until we can be sure it's accurate.

**Comment by cassidyjames** [comment]
There is a bounty on this issue at [Bountysource](https://www.bountysource.com/issues/43408940-card-check-is-too-strict).
