### ISSUE TITLE
Cycle banner through newest 5 apps [$25]

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#164]
Now that I know we have at least 2 apps I can see that it stays on the newest one forever. We should instead cycle through a small set like the newest 5

---
There is a bounty on this issue in [Bountysource](https://www.bountysource.com/issues/43413149-cycle-banner-through-newest-5-apps)

**Comment by Philip-Scott** [comment]
Carousel style, or should it maybe grab a random one on load?

**Comment by donadigo** [comment]
I guess this should be a carousel. Otherwise the user would have no way to check other newest apps.

**Comment by Philip-Scott** [comment]
@danrabbit Didn't we sketch out a section for the newest apps between the Banner and the Categories?
