### ISSUE TITLE
Wifi card driver in AppCenter doesn't work ThinkPad t15 gen 2 (Intel(R) Wi-Fi 6 AX210)

### ISSUE THREAD

**Issue by VasilyevAA** [elementary/appcenter#1640]
Hi, guys!
This [solution](https://github.com/elementary/appcenter/issues/1603) doesn't work for me, but I've found another way
I execute this command, reboot pc and wifi works
`sudo mv /usr/lib/firmware/iwlwifi-ty-a0-gf-a0.pnvm  /usr/lib/firmware/iwlwifi-ty-a0-gf-a0.bak`

More info:
https://askubuntu.com/questions/1360175/intel-wifi-5-ax210-wifi-not-working-after-update?answertab=votes#tab-top

**Comment by davidmhewitt** [comment]
> This [solution](https://github.com/elementary/appcenter/issues/1603) doesn't work for me

Yes, that issue and the workarounds in it are about Broadcom WiFi chipsets, you have an Intel one.

The link you posted has a link to a bug in the Linux kernel tracker:
https://bugzilla.kernel.org/show_bug.cgi?id=212371#c13

As this is a bug in the Linux kernel and not in AppCenter, I'll close this issue. Hopefully this will be resolved in future kernel upgrades.

I'm glad you were able to find a workaround!
