### ISSUE TITLE
Office category label is not centered

### ISSUE THREAD

**Issue by D0J0P** [elementary/appcenter#1642]
## What Happened

The "Office" is not centered

![Screenshot from 2021-08-31 20 30 35](https://user-images.githubusercontent.com/19495660/131593042-ae419615-cca1-4eaa-8ce1-f8c0a897fe32.png)

## Expected Behavior

That it would be centered

## Steps to Reproduce

1.
2.
3.

## Platform Information

elementary OS 6 Odin

**Comment by danirabbit** [comment]
This was resolved recently
