### ISSUE TITLE
Rework AppStream update descriptions on Installed tab

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1654]
## Problem

Squeezing the update descriptions between the app's info and action buttons makes it hard to squeeze down to smaller sizes (e.g. for tiling), and feels awkward.

## Proposal

We may want to consider moving this data to a dialog (like GNOME Software), move it below the other columns (like the Pop!_Shop fork), or remove it entirely since it's also on the AppInfoView.

## Prior Art

GNOME Software has it in a dialog, Pop!_Shop moves it below the icon/action buttons.

**Comment by danirabbit** [comment]
This was fixed in the previous release. Update info is now shown in a dialog box
