### ISSUE TITLE
[$50] Don't display update progress bar when "waiting" or "finished"

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#166]
In the updates view, we should only display a progress bar when it's an app that's being updated. If its state is waiting or finished, we don't need a progress bar or label.

**Comment by codygarver** [comment]
There is a bounty for this issue [on Bountysource](https://www.bountysource.com/issues/43420386-don-t-display-update-progress-bar-when-waiting-or-finished).

**Comment by Philip-Scott** [comment]
Maybe we should remove the label as removing it would only leave us with a cancel button with no explanation of what's going on
