### ISSUE TITLE
Homepage scrolls horizontally at small sizes

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1665]
## What Happened

Noticed when working on #1662 but is present in master. When you resize the window to a small size (e.g. the minimum), it looks like the Recently Updated flowbox is making the page scroll horizontally.

## Expected Behavior

The contents adapt to smaller widths and don't overflow

## Steps to Reproduce

1. Open AppCenter
2. Resize the width down horizontally
3. See the scrollbar

## Platform Information

OS 6 with AppCenter from master

**Comment by danrabbit** [comment]
Fixed in 1694
