### ISSUE TITLE
fails to compile with -Dhomepage=false since PR#1662

### ISSUE THREAD

**Issue by decathorpe** [elementary/appcenter#1666]
```
../src/Views/AbstractView.vala:35.55-35.93: warning: Access to possible `null'. Perform a check or use an unsafe cast.
                    if (child is Views.AppInfoView && (child as Views.AppInfoView).to_recycle) {
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/Homepage.vala:324.36-324.50: error: The name `banner_carousel' does not exist in the context of `AppCenter.Homepage.banner_timeout_start._lambda165_'
            var new_index = (uint) banner_carousel.position + 1;
                                   ^^^^^^^^^^^^^^^
../src/Views/Homepage.vala:325.29-325.43: error: The name `banner_carousel' does not exist in the context of `AppCenter.Homepage.banner_timeout_start._lambda165_'
            var max_index = banner_carousel.n_pages - 1; // 0-based index
                            ^^^^^^^^^^^^^^^
../src/Views/Homepage.vala:327.17-327.31: error: The name `banner_carousel' does not exist in the context of `AppCenter.Homepage.banner_timeout_start._lambda165_'
            if (banner_carousel.position >= max_index) {
                ^^^^^^^^^^^^^^^
../src/Views/Homepage.vala:331.13-331.27: error: The name `banner_carousel' does not exist in the context of `AppCenter.Homepage.banner_timeout_start._lambda165_'
            banner_carousel.switch_child (new_index, Granite.TRANSITION_DURATION_OPEN);
            ^^^^^^^^^^^^^^^
Compilation failed: 4 error(s), 1 warning(s)
```

Looks like `banner_timeout_start` and `banner_timeout_stop` might need to be ifdefed like some other parts of the `src/Views/Homepage.vala` file?

**Comment by cassidyjames** [comment]
@decathorpe ah yeah I forgot to test with that flag. That makes sense. I do wonder, what's the intent of this flag, though? Would it make more sense to have a flag that determines whether there's a concept of "curated" apps, instead, and if that's false, we could not filter the homepage carousels by "curated"? That way you'd still get a nice homepage with whatever apps are available e.g. from Flathub or the distro's repos.

**Comment by decathorpe** [comment]
The original reason for having that flag was that the carousel showed curated apps from "houston" even if they weren't available, i.e. appcenter repository not enabled or RPM based distros.

With Odin, this is better, because those apps are at least shipped as distro-agnostic flatpaks, but still, the appcenter flatpak remote won't be enabled OOTB anywhere but on elementary OS.

It would be great if the carousel only showcased apps that were actually available to install, and in that case, I would enable it for Fedora builds again.

**Comment by cassidyjames** [comment]
@decathorpe as-is in master the carousel only pulls from local sources, anyway. So if those apps don't exist, it simply doesn't expand (and there's no remote API hit). I'll propose a fix regardless.
