### ISSUE TITLE
homepage carousel and "recently updated" broken unless "appcenter" flatpak remote is present

### ISSUE THREAD

**Issue by decathorpe** [elementary/appcenter#1680]
I tried re-enabling the homepage feature for Fedora builds of AppCenter, but I encountered a weird issue. If I only dropped `-Dhomepage=false`, then nothing changed, except that appcenter now logged a lot of error messages:

```
(io.elementary.appcenter:3731): Handy-CRITICAL **: 22:42:59.170: hdy_carousel_box_get_nth_child: assertion 'n < hdy_carousel_box_get_n_pages (self)' failed
```

And every few seconds, this one:

```
(io.elementary.appcenter:3731): Handy-CRITICAL **: 22:50:30.149: hdy_carousel_box_scroll_to: assertion 'HDY_IS_CAROUSEL_BOX (self)' failed
```

Additionally, no carousel or "recently updated" section is installed on the homepage unless I add the `appcenter` flatpak remote on the system. Then, restarting appcenter, those sections appear, and the first error message disappears (which makes me think that the code doesn't like it when the carousel has zero pages, or something like that). Removing the flatpak remote again and restarting AppCenter makes both sections disappear from the homepage again.

On Fedora, I cannot install third-party repositories for users, so it would be great if AppCenter would keep basic functionality even if the flatpak remote was not set up.

---

This happens in AppCenter from git master, compiled with `-Dcurated=false -Dpayments=false`, on Fedora 34 and 35.

**Comment by cassidyjames** [comment]
Right, the homepage intentionally features curated AppCenter apps. This is why in #1666 I mentioned it may be worth dropping the `hompage` flag and only using `curated`, since this depends on curated apps existing. Alternatively we could modify the `get_native_packages_by_release_date ()` method to react to the `curated` flag which would make this pull in any available packages for the banner and recently-updated section.

**Comment by decathorpe** [comment]
> I mentioned it may be worth dropping the hompage flag and only using curated, since this depends on curated apps existing.

Uhm, that's what I did? I compiled with `-Dhomepage=true -Dcurated=false -Dpayments=false` and got this strange behaviour.

**Comment by cassidyjames** [comment]
@decathorpe sorry, I mean it may be worth us dropping the flag from existence entirely. :sweat_smile: But I do think this would be the ideal approach, as it would give you (and potentially Pop! and whoever else) a nice banner and recently-updated carousel:

>Alternatively we could modify the get_native_packages_by_release_date () method to react to the curated flag which would make this pull in any available packages for the banner and recently-updated section.

**Comment by decathorpe** [comment]
Ah, now I understand. Yeah that would be perfect. The "categories-only" view without the carousel and recently-updated / curated section is very bare-bones ... so having the carousel and recently-updated sections display non-curated apps would be great
