### ISSUE TITLE
misleading "Unknown Origin (non-curated)" origin for official distribution packages

### ISSUE THREAD

**Issue by decathorpe** [elementary/appcenter#1688]
On distributions like Fedora that don't really have an "upstream distro", basically all official repository content could be considered first-party / "curated" applications, since they come from the exact same vendor that the user installed the entire OS from.

Currently, this leads to very misleading presentation of any applications from official repositories that are *also* available for installation as a flatpak:

- "Unknown Origin (non-curated)" is displayed next to the application name and version in the "Installed" tab:

![Screenshot from 2021-09-16 21-55-12](https://user-images.githubusercontent.com/12836693/133684222-eb501f61-3f8f-4aed-9dcd-21f376400158.png)

This seems to only affect applications that can be installed from more than one source. If the distribution package is the only source, no "Unknown Origin" tag is attached for some reason.

- the dropdown menu for available application sources on application detail pages is misleading, and lists the official distro repository as "Unknown Origin", whereas **any** named flatpak remote looks way more trustworthy, even though the "native" distro repository is - in most cases - the "more official" / better maintained / supported choice:

![Screenshot from 2021-09-16 21-55-16](https://user-images.githubusercontent.com/12836693/133677573-10747d21-f763-4513-bef3-f918d81ecae5.png)

Additionally, it would be trivial for a "malicious" application to add a `flatpak --user` remote that has a very official-sounding name, which would then look like the most authoritative source in that dropdown - instead of the repository that's set up by the system and which cannot be modified without root privileges.

**Comment by kdwk** [comment]
Correct me if I’m wrong, but my understanding is that Fedora repo apps are not ‘curated’ in the sense that apps are not vetted to work consistently on certain platforms. For example, a Qt app added to the Fedora repos may work flawlessly on the Fedora KDE Plasma spin, but not on the flagship Gnome Workstation, or the Pantheon DE. Some apps don’t support Wayland (only works on X), some don’t support Pipewire, etc. Some are legacy RPM apps. If Fedora apps are to be curated to the same extent as elementary AppCenter apps, they’ll have to start a curation for a specific set of configurations (e.g. Wayland, Gnome, Pipewire) and I imagine they would do it for the flagship Gnome Workstation first.

**Comment by decathorpe** [comment]
That's an impossibly high bar to clear for most applications, and nobody is vetting thousands of applications, and not even for Fedora Workstation. The only applications that fit your definition of "curated"  are the applications that are installed by default - but if those are the only acceptable applications, what do you need an app store for? :D

In reality, no application maintainer can verify that their application works on all combinations of {GNOME,KDE Plasma,XFCE,Cinnamon,LXDE,LXQt,MATE,SOAS,i3}{X11,Wayland(where applicable)} (yeah, all of those are officially available on Fedora variants). Applications usually set `OnlyShowIn=foo` or `NoShowIn=foo` key in their .desktop files if they are known only to work or not to work on specific desktop environments. But this metadata is not available from appstream, so appcenter can't use it, can it?

> Some apps don’t support Wayland (only works on X)

Sure, but until Pantheon supports Wayland, it'll run on X11, even on Fedora (I can't do magic, sorry)

> some don’t support Pipewire, etc.

Pipewire aims to provide 100% API compatibility with PulseAudio so that's not a problem either. In fact, PipeWire has been the default for Pantheon since Fedora 34+, and nobody even noticed.

> Some are legacy RPM apps.

What is this supposed to mean?

**Comment by decathorpe** [comment]
Side note: On elementary OS, the "official" APT repository source (the launchpad PPA repo) is shown as "elementary updates", so did some digging: There's some hardcoded string matching going on, and if the string for the repository name doesn't match any expected value, it's shown as "Unknown Origin (non-curated)":

https://github.com/elementary/appcenter/blob/master/src/Core/Package.vala#L329

I suppose I can patch this downstream to expect "fedora-" prefixes instead of "ubuntu-" prefixes. 🤷🏼‍♂️

**Comment by decathorpe** [comment]
Yup, I fixed this with a downstream patch. Matching against "ubuntu-*" repository names only makes sense on elementary OS and Pop!_OS, I guess.
