### ISSUE TITLE
Swipe-left gesture doesn't work correctly

### ISSUE THREAD

**Issue by Sav22999** [elementary/appcenter#1699]
## What Happened

New gestures in AppStore don't work, in fact if you swipe-left (with two fingers) appears the "moving" icon, even if you are not in the screenshot area

## Expected Behavior

It should work as "go back", such as in the whole system

## Steps to Reproduce

1. Go to AppStore
2. Open an app
3. Try "Swipe-left" with two fingers
4. **It doesn't work!**

## Platform Information

Elementary OS 6 (Odin)

**Comment by danrabbit** [comment]
This was fixed in #1769
