### ISSUE TITLE
Crash when an app doesn't have a description

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1700]
### What Happened?

With `curated` set to `false`, apparently apps from other remotes can have no description. So we get a crash:

```
(io.elementary.appcenter:7793): GLib-CRITICAL **: 09:55:49.009: g_strsplit: assertion 'string != NULL' failed
```

### Steps to Reproduce

1. Have the Flathub remote
2. Compile with `-Dcurated=false`
3. Try to open AppCenter

It can be hit or miss depending on what was most recently updated in the Flathub remote, but it's possible to get a segfault

### Expected Behavior

No segfault lol

### OS Version

6.x (Odin)

### Software Version

Compiled from git

### Log Output

```shell
(io.elementary.appcenter:7793): GLib-CRITICAL **: 09:55:49.009: g_strsplit: assertion 'string != NULL' failed
```

**Comment by benhaotang** [comment]
Hi, I still experience this with 7.1 Horus with appcenter version 7.4.0, tried recompile from github still don't work.

output in terminal 

(io.elementary.appcenter:40638): GLib-CRITICAL **: 12:52:05.747: g_strsplit: assertion 'string != NULL' failed
zsh: segmentation fault  io.elementary.appcenter

can you tell me what should I do or how can I remove the flatpak remote?
