### ISSUE TITLE
Install org.gnome.fileroller will waiting forever

### ISSUE THREAD

**Issue by loaden** [elementary/appcenter#1737]
### What Happened?

If have an system flatpak repo, e.g.

> loaden@yuchen:~$ flatpak remotes --columns=name,priority,url
Name        Priority URL
appcenter   1        https://flatpak.elementary.io/repo
flathub     1        https://mirror.sjtu.edu.cn/flathub
freedesktop 1        https://dl.flathub.org/repo/
flathub     1        https://mirror.sjtu.edu.cn/flathub

then org.gnome.fileroller will exist in two repo, like this

> 正在选中未选择的软件包 org.gnome.fileroller。
准备解压 .../org.gnome.fileroller_3.40.0-0+pkg4~ubuntu6.1_all.deb  ...
正在解压 org.gnome.fileroller (3.40.0-0+pkg4~ubuntu6.1) ...
正在设置 org.gnome.fileroller (3.40.0-0+pkg4~ubuntu6.1) ...
Remotes found with refs similar to ‘org.gnome.FileRoller//stable’:

   1) ‘appcenter’ (system)
   2) ‘flathub’ (system)

Which do you want to use (0 to abort)? [0-2]:  
进度：[ 60%] [################################################################............................................] 

If this happened in command line (terminal), then user can choice what is he need.
But in AppCenter, they just waiting forever.

### Steps to Reproduce

always.

### Expected Behavior

It shoud auto choice the appcenter repo.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by danrabbit** [comment]
Fixed in packaging! Thanks for reporting this
