### ISSUE TITLE
Description Texts Broken

### ISSUE THREAD

**Issue by enderger** [elementary/appcenter#1749]
Currently, on my system the display of app description texts fails to redraw when scrolling and generally suffers from visual artifacting. The changelog texts appear to be unaffected.

EDIT: This only appears to happen if you use a different stylesheet (I was using the "mint" stylesheet)

#### Steps to Reproduce
1. Open the AppCentre
2. View any app
3. Attempt to scroll past the description

#### Screenshot
![appcentre-glitches](https://user-images.githubusercontent.com/36283171/141169833-fb7a26dc-a222-41d7-8832-d6629144bace.png)

#### System Details
OS: Elementary OS 6
Kernel:  `Linux #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64`
GPU: NVIDIA GeForce MX250

#### Additional Details
- The font may need to be changed, I'm using the FiraCode Nerd Font for my system
- This may only work on certain NVIDIA GPUs, I'm not sure though

**Comment by danirabbit** [comment]
Closing since this is probably an issue with a custom stylesheet
