### ISSUE TITLE
Don't show compulsory packages in categories

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#1758]
### What Happened?

Compulsory packages like Wingpanel are shown in categories. This is not strictly speaking an app and shouldn't be shown while browsing

### Steps to Reproduce

Open Accessories, see Wingpanel

### Expected Behavior

Wingpanel should not appear while browsing categories

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by cassidyjames** [comment]
I'm not sure it's the fact that WingPanel is compulsory that means we should hide it, but the fact that its appdata incorrectly says it's a desktop app (when it's really a shell component). Even if we said the System Settings app was compulsory, I think you'd want it to show in categories? 

See: https://github.com/elementary/wingpanel/pull/421
