### ISSUE TITLE
Include "Amusement" in Games

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#1761]
### Problem

There are currently no games out of the box, but there are a couple of "Amusement" apps that currently only show in Accessories

### Proposal

Showing "Amusement" apps in Games would make it not totally empty and give these apps a place to go

**Comment by cassidyjames** [comment]
Yeah I think this would be fine. Idk if there's a more fun name like "Games & Fun" or something :shrug:

**Comment by cassidyjames** [comment]
OMG how did I miss "Fun & Games " lol
