### ISSUE TITLE
Cannot maximize window on 1920x1080 screen

### ISSUE THREAD

**Issue by aral** [elementary/appcenter#1774]
### What Happened?

1. Moved AppCenter to 1920x1080 screen
2. Hit the Maximize button

Nothing happened.

### Steps to Reproduce

1. Move AppCenter to 1920x1080 screen
2. Hit the Maximize button

### Expected Behavior

It should maximise.

AppCenter should be able to display responsively on lower resolution displays (although I’m not sure I’d classify 1080 as lower resolution).

Additional use cases, beyond being usable for people with lower resolution displays:
 
  - Being able to show off AppCenter in video streams (which are still mostly at 1080 resolution)

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
n/a
```

### Hardware Info

n/a

**Comment by ChildishGiant** [comment]
I can't replicate this on my end

**Comment by cassidyjames** [comment]
@aral I can't reproduce this, either. Can you share:
- Scaling factor (under System Settings → Displays → Scaling factor)
- Text size (System Settings → Desktop → Text → Size)

**Comment by aral** [comment]
Hmm, very odd, I can no longer reproduce. Closing. Will reopen if I encounter it again and provide the info you requested @cassidyjames
