### ISSUE TITLE
Downloading paid apps for free(via terminal)

### ISSUE THREAD

**Issue by nintendoit** [elementary/appcenter#1775]
### What Happened?

I used terminal to install akira and succeded installing it free.

### Steps to Reproduce

1.I used terminal to install akira, so I used `flatpak install akira`...
2.choosed between appcenter(system) and appcenter(user)...(It does not matter,any of them works)
3.Installed it by flatpak, avoiding the price fees.

### Expected Behavior

The terminal should have told  `Unable to install.Looks like a paid app.Go to the appcenter to pay for the app.` 

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by danrabbit** [comment]
This is what the eventual purpose of https://github.com/elementary/flatpak-authenticator is. Right now, payments are done completely client side in the AppCenter app, so the Flatpak command line has no concept of paid or unpaid apps. Eventually, you'll get a graphical prompt for payment whether you install from Terminal, AppCenter, or even on another distro

**Comment by danrabbit** [comment]
Gonna close this for AppCenter since this needs to be solved in the remote/flatpak/etc and there's nothing we can do in the AppCenter app itself
