### ISSUE TITLE
Pull apt updates less frequently?

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#1776]
### Problem

Fetching updates from apt is slow and takes a long time. Most of the time when we're opening AppCenter, we really only want to see new apps, which are all from Flatpak

### Proposal

Perhaps we should make sure to only fetch Flatpak updates when we open AppCenter and keep apt updates just to the daily timer

**Comment by cassidyjames** [comment]
This makes sense to me. Only caveat I'd have is if we'd want to add a manual refresh button to trigger an apt update, e.g. in the case of a critical security update (it would be hard to tell users, "Just wait for tomorrow and then it'll prompt you" when the status quo is "just open AppCenter and update.").

**Comment by AI-ien** [comment]
Isn't that the task for Appcenter daemon to fetch updates in background so when you open Appcenter you don't need to wait for updates?

Another option would be to make slight design changes by adding third tab 'updates' where on select updates are rechecked.

**Comment by SubhadeepJasu** [comment]
> This makes sense to me. Only caveat I'd have is if we'd want to add a manual refresh button to trigger an apt update, e.g. in the case of a critical security update (it would be hard to tell users, "Just wait for tomorrow and then it'll prompt you" when the status quo is "just open AppCenter and update.").

I am cool with that. A manual refresh button or change the update button to "Check for updates" when the update information is outdated.
