### ISSUE TITLE
Color glitches when update

### ISSUE THREAD

**Issue by AI-ien** [elementary/appcenter#1779]
### What Happened?

There are two visible issues with color (see picture):

1. When click on update button a square is painted from button to the left inside banner
2. When click on update button update header textbox in next page is always auto selected making it appear in colored background

Theme accent color Grape.

### Steps to Reproduce

Just open AppCenter and update apps

### Expected Behavior

Shouldn't be any colorization.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

![Screenshot from 2021-11-30 14-26-18](https://user-images.githubusercontent.com/33252703/144049251-f739a45a-020e-47c9-969d-298c59ceb579.png)

**Comment by danirabbit** [comment]
I'm not able to reproduce this issue with the latest release on OS 7 RC. I believe this has been fixed
