### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by cellsite60** [elementary/appcenter#1781]
Found a typo in the description of Starfish in the appcenter!
See image below.

![screenshot(1)](https://user-images.githubusercontent.com/83919459/144411056-16dbbef2-8e90-4cb9-8579-6bd4abb2eb3d.png)

**Comment by ryonakano** [comment]
Hi, thanks for your reporting but this should be fixed in the Starfish itself, not in AppCenter. Please submit this issue from https://github.com/starfish-app/Starfish/issues/new.

Closing as "out of scope"
