### ISSUE TITLE
Add gnome-disk-utility and gnome-system-monitor to appcenter

### ISSUE THREAD

**Issue by Radical4ever** [elementary/appcenter#1782]
### Problem

There's no program to manage system processes and a program to manage disks and format/create them. 

### Proposal

i propose adding these 2 programs to the Appcenter repo. so if we need those we could jus install them from the AppCenter and not by CLI. that's the alternative solution i could find to get them

**Comment by joeljose350** [comment]
Those apps haven't been designed according to the [elementary OS Human Interface Guidelines](https://docs.elementary.io/hig/) so they would look out of place on Pantheon. So I'm not sure if the elementary OS devs would be keen on adding them to the AppCenter, but they are really useful apps that a lot of people would need.

**Comment by mathessaricci** [comment]
I think this is ok. Since the pdf reader is a default app and at the same time doesn't follow the eOS HIG

**Comment by danirabbit** [comment]
I'm going to close this since elementary doesn't package non-default 3rd party apps. The best way to get GNOME apps on elementary OS is by sideloading from Flathub.org
