### ISSUE TITLE
Don't show flatpak runtimes as system updates

### ISSUE THREAD

**Issue by ChildishGiant** [elementary/appcenter#1786]
### Problem

![image](https://user-images.githubusercontent.com/13716824/144704476-85679f56-9869-44ec-88c0-7b2b3c6a5399.png)
![image](https://user-images.githubusercontent.com/13716824/144704482-137a9b9a-854e-4157-bc6f-aa75f510c3ea.png)

Currently flatpak runtimes are shown as system updates but in reality it's just a flatpak app being updated. This is confusing to the user.

### Proposal

These updates should be bundled with the updates for the relevant apps, in this case showing 5 total updates, with no OS updates.

**Comment by danirabbit** [comment]
This was fixed in #1956
