### ISSUE TITLE
Problem executing scripts APT::Update::Post-Invoke

### ISSUE THREAD

**Issue by agrawalsourav98** [elementary/appcenter#1809]
### What Happened?

When checking for updates using appcenter the appcenter shows `Failed to Fetch Updates` dialog.

`E: Problem executing scripts APT::Update::Post-Invoke '/usr/local/bin/checkgitupdates update'
E: Sub-process returned an error code`

The post scripts run fine with apt when I run `apt update`

### Steps to Reproduce

1. Add a script for `APT::Update::Post-Invoke`
2. Run check for updates in appcenter

### Expected Behavior

Appcenter should behave as `apt` while checking for updates from repositories

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
** (io.elementary.appcenter:61077): CRITICAL **: 07:43:34.080: Client.vala:148: Update_cache: Refesh cache async failed - E: Problem executing scripts APT::Update::Post-Invoke '/usr/local/bin/checkgitupdates update'
E: Sub-process returned an error code
```

**Comment by tintou** [comment]
It looks like you've added that post-invoke script yourself, appcenter it is probably a permission issue on your side as running updates on AppCenter is not the same as using apt regarding the permissions. You might want to check your system logs (with `journalctl -b`) to understand what is happening.

**Comment by agrawalsourav98** [comment]
Yep, checked the system logs, I was trying to get the current user trying to execute the code from the program environment but there was no `USER` key in environment. So, that was causing this error. Is there some other way to get the user? Like as what user does appcenter try to run updates?
