### ISSUE TITLE
There are no new apps on Appcenter

### ISSUE THREAD

**Issue by MathewFreddickRiddle** [elementary/appcenter#1824]
### What Happened?

Hello!
When I open the Appcenter there are no new apps, just see the installed ones.
![Captura de pantalla de 2022-03-20 09-45-42](https://user-images.githubusercontent.com/70706948/159163863-4cde2b3d-7864-468c-b8c6-1a811451e5cd.png)

Also, I recieve an error when I open it.
![Captura de pantalla de 2022-03-20 10-10-46](https://user-images.githubusercontent.com/70706948/159163889-f25aa219-6a80-49c5-8783-47244cd1b496.png)

### Steps to Reproduce

1. I opened the Appcenter.
2. Wainting untill load the updates.
3. Recieved the error.

### Expected Behavior

With the uninstalled apps and without error messages.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by MathewFreddickRiddle** [comment]
I also add the errors (in Spanish):
W: El objetivo Packages (main/binary-amd64/Packages) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo Packages (main/binary-all/Packages) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo Translations (main/i18n/Translation-es_ES) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo Translations (main/i18n/Translation-es) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo Translations (main/i18n/Translation-es_ES.UTF-8) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo Translations (main/i18n/Translation-en) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo DEP-11 (main/dep11/Components-amd64.yml) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo DEP-11 (main/dep11/Components-all.yml) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo DEP-11-icons-small (main/dep11/icons-48x48.tar) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo DEP-11-icons (main/dep11/icons-64x64.tar) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo DEP-11-icons-hidpi (main/dep11/icons-64x64@2.tar) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo DEP-11-icons-large (main/dep11/icons-128x128.tar) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo CNF (main/cnf/Commands-amd64) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo CNF (main/cnf/Commands-all) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: Omitiendo el uso del fichero configurado «main/binary-i386/Packages» ya que el repositorio «https://download.mono-project.com/repo/ubuntu stable-focal InRelease» no admite la arquitectura «i386»
W: El objetivo Packages (main/binary-amd64/Packages) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo Packages (main/binary-all/Packages) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo Translations (main/i18n/Translation-es_ES) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo Translations (main/i18n/Translation-es) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo Translations (main/i18n/Translation-es_ES.UTF-8) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo Translations (main/i18n/Translation-en) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo DEP-11 (main/dep11/Components-amd64.yml) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo DEP-11 (main/dep11/Components-all.yml) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo DEP-11-icons-small (main/dep11/icons-48x48.tar) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo DEP-11-icons (main/dep11/icons-64x64.tar) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo DEP-11-icons-hidpi (main/dep11/icons-64x64@2.tar) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo DEP-11-icons-large (main/dep11/icons-128x128.tar) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo CNF (main/cnf/Commands-amd64) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
W: El objetivo CNF (main/cnf/Commands-all) está configurado varias veces en /etc/apt/sources.list.d/google-chrome.list:3 y /etc/apt/sources.list.d/google.list:1
E: El repositorio «http://ppa.launchpad.net/danielrichter2007/grub-customizer/ubuntu focal Release» no tiene un fichero de Publicación.
W: No se puede actualizar de un repositorio como este de forma segura y por tanto está deshabilitado por omisión.
W: Vea la página de manual apt-secure(8) para los detalles sobre la creación de repositorios y la configuración de usuarios.
E: El repositorio «http://ppa.launchpad.net/kirillshkrogalev/ffmpeg-next/ubuntu focal Release» no tiene un fichero de Publicación.
W: No se puede actualizar de un repositorio como este de forma segura y por tanto está deshabilitado por omisión.
W: Vea la página de manual apt-secure(8) para los detalles sobre la creación de repositorios y la configuración de usuarios.
E: El repositorio «http://ppa.launchpad.net/leaeasy/dde/ubuntu focal Release» no tiene un fichero de Publicación.
W: No se puede actualizar de un repositorio como este de forma segura y por tanto está deshabilitado por omisión.
W: Vea la página de manual apt-secure(8) para los detalles sobre la creación de repositorios y la configuración de usuarios.
E: El repositorio «http://ppa.launchpad.net/noobslab/deepin-sc/ubuntu focal Release» no tiene un fichero de Publicación.
W: No se puede actualizar de un repositorio como este de forma segura y por tanto está deshabilitado por omisión.
W: Vea la página de manual apt-secure(8) para los detalles sobre la creación de repositorios y la configuración de usuarios.
E: El repositorio «http://ppa.launchpad.net/ubuntu-wine/ppa/ubuntu focal Release» no tiene un fichero de Publicación.
W: No se puede actualizar de un repositorio como este de forma segura y por tanto está deshabilitado por omisión.
W: Vea la página de manual apt-secure(8) para los detalles sobre la creación de repositorios y la configuración de usuarios

**Comment by danrabbit** [comment]
It looks like you are unable to fetch updates because several of the external software sources you've added are no longer maintained. You'll need to revert changes to your software sources. I highly recommend against adding PPAs for this reason.

Closing since this is an issue with a broken software sources list and not an issue with AppCenter
