### ISSUE TITLE
Now Im getting this issue, it also says Failed to Fetch Updates but has a different Detail...

### ISSUE THREAD

**Issue by Faaiqishere** [elementary/appcenter#1826]
: GPG error: https://packages.microsoft.com/repos/edge stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
E: The repository 'https://packages.microsoft.com/repos/edge stable InRelease' is not signed.
W: Updating from such a repository can't be done securely, and is therefore disabled by default.
W: See apt-secure(8) manpage for repository creation and user configuration details.
E: https://packages.microsoft.com/repos/edge stable InRelease is not (yet) available (The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF)

**Comment by tintou** [comment]
It seems like you've added the Microsoft Edge repository yourself.
Please make sure that you've added the GPG key as per https://www.omgubuntu.co.uk/2021/01/how-to-install-edge-on-ubuntu-linux#CLI-Method
