### ISSUE TITLE
Appcenter closing on it's own

### ISSUE THREAD

**Issue by Turkioo04** [elementary/appcenter#1829]
I've downloaded the latest version of Elementary OS v6.1 & installed it in an old laptop that used to have **win 7 (Acer - Aspire TimelineX)**. The OS works fine but to some issues:
1- AppCenter: every time i open the app it opens and start showing the app store then suddenly stops working and closes in it's own in mere seconds!
2- Any other app i have same issue but to some few.
3- Any app i download via CLI works fine.
So how i can fix this issue? Thanks in advance

**Comment by jeremypw** [comment]
Possibly related to this bug: `https://github.com/elementary/appcenter/issues/1656`? I have occasionally seen AppCenter close unexpectedly but not all the time. Are resources on your machine limited (e.g. memory or swap space?).  You could try running `appcenter` under `gdb` to get a backtrace of the crash and compare the trace shown in issue #1656.

**Comment by Turkioo04** [comment]
Hi Jeremypw,
For the resources nope i am not using much (just VS code & chrome [two tabs]), & as i mentioned my laptop is an old one which i change the harddesk to SSD & it has 12GB RAM.

I did the following: apt show Appcenter (version)
![Appcenter version](https://user-images.githubusercontent.com/11798820/161515600-33a48ad3-71e1-4f45-ac9a-aee6a901d6d8.jpg)
Then i run it under gdb & got the following:
![Appcenter under gdp](https://user-images.githubusercontent.com/11798820/161515943-b026ffb8-da4d-4883-9b27-3bf48b8c486d.png)
And when i run it under gdb the app opens and then freezes short after:
![Run it under gdp with run command](https://user-images.githubusercontent.com/11798820/161516762-3870d789-d749-4f5b-89a1-2bdd438d2088.png)
So any idea how to fix this issue?
Thanks in advance

**Comment by jeremypw** [comment]
Looks like a flatpak related issue.  Are you running on Ubuntu rather than elementary? In that case you may not have the necessary flatpak infrastructure installed (Ubuntu used snap). You could try installing flatpak and setting up remote for flathub and the elementary repo (`sudo flatpak remote-add --if-not-exists https://flatpak.elementary.io/repo.flatpakrepo`)

**Comment by Turkioo04** [comment]
Still i have a problem, i get the following error "error: LOCATION must be specified
![Screenshot from 2022-04-29 14-35-08](https://user-images.githubusercontent.com/11798820/165937462-02e39851-4971-4db9-b5d7-8656de55a7a5.png)
"

**Comment by meisenzahl** [comment]
Fixed by https://github.com/elementary/appcenter/pull/2053
