### ISSUE TITLE
Better german translation for the term 'Paid Apps'

### ISSUE THREAD

**Issue by Soljanka** [elementary/appcenter#1848]
### What Happened?

The current german translation for the term 'Paid Apps' is 'Erworbene Anwendungen' which roughly translates to 'Apps that you already paid for / Apps that you already bought'. As you can see this is kinda misworded. A more accurate translation would be 'Kostenpflichtige Anwendungen'.

### Steps to Reproduce

1. Use German as your region and language
2. Open the AppCenter and open any category
3. The german term for 'Paid Apps' is 'Erworbene Anwendungen'

### Expected Behavior

The term is misworded; a more accurate german translation would be 'Kostenpflichtige Anwendungen'

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by tintou** [comment]
It has been fixed in the sources [a while ago](https://github.com/elementary/appcenter/commit/3c88caf601ada78dc832dce1fa58c8cf39109119) and will be available in the next release of AppCenter
