### ISSUE TITLE
Elementary OS 6.1 system related content doesn't update

### ISSUE THREAD

**Issue by veiszgabor79** [elementary/appcenter#1850]
### What Happened?

Downloads the content, then reports error, saying 
Error while installing package: cannot copy the opened data to this (rough translation from different language)
 

### Steps to Reproduce

App Center
Load updates
Error
Tried from Terminal:
sudo apt update
sudo apt upgrade
Terminal tells that there are dependencies, and gives advise to run this:
apt --fix-broken install
Then this message comes:
 : /var/lib/dpkg/lock-frontend zárolási fájl nem nyitható meg - open (13: Access Denied)    ----Rough translation
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

### Expected Behavior

Finish the updates.

### OS Version

6.x (Odin)

### Software Version

Older release (I have not run all updates)

### Hardware Info

HP ProBook 640 G1
Dual Core i5 4300M Cpu 2.6Ghz
7,7Gb RAM
Firmware up to date

**Comment by danirabbit** [comment]
Closing since system updates are no longer handled in AppCenter
