### ISSUE TITLE
Add "Copy Link" function

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#190]
To easily share apps over the internets, copy the `appstream://` link to the clipboard

**Comment by cassidyjames** [comment]
Now that we have the appcenter.elementary.io server up, I think we should copy that URL instead.

**Comment by cassidyjames** [comment]
:moneybag: $15 bounty https://www.bountysource.com/issues/43630542-add-copy-link-function

**Comment by cassidyjames** [comment]
Design-wise, this should probably be another item in the footer titled "Copy Link" or something, next to the "Homepage", "Report a Problem", etc. links. Probably with a "link" symbolic icon. :smile: And throw a toast on successful copy that says something like "Link copied to clipboard".
