### ISSUE TITLE
viber

### ISSUE THREAD

**Issue by Aristos67** [elementary/appcenter#1941]
### What Happened?

viber from appcenter doesnt launch

### Steps to Reproduce

i install viber from appcenter but it doesnt launch

### Expected Behavior

i install viber from appcenter but it doesnt launch

### OS Version

5.x (Hera)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
Hey, thanks for reporting this issue. Support for 3rd party apps is provided by those app authors. It looks like this is the Viber support page: https://help.viber.com/en/

Closing since elementary is unable to solve issues related to 3rd party apps.
