### ISSUE TITLE
Wonky category icons in Horus Early Access

### ISSUE THREAD

**Issue by dar5hak** [elementary/appcenter#1953]
### What Happened?

I launched AppCenter on Horus Early Access, build 20221203.

![IMG_20221204_003948](https://user-images.githubusercontent.com/8205055/205458136-ea43bdae-3025-49b2-b786-abcc3b5f46ea.png)

- The icon for Office category is misaligned. It's slightly lower than it should be.
- The icon for Universal Access category is too small.

Tested with AppCenter maximized on my 1920×1080 display.

### Steps to Reproduce

1. Open AppCenter.

### Expected Behavior

The icons should be in the correct size and position.

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Acer Nitro monitor, 1920×1080, the only display in use by the system. (My laptop display, 1366×768, was disabled.)

**Comment by danirabbit** [comment]
Ah I think I know what's happening here. It looks like it's using the 16px icons from the system even though there's 48px icons gresourced. We could solve that by using a unique namespace here so we make sure we're using the provided icons instead

**Comment by dar5hak** [comment]
@danirabbit Hmm, seems like the gresourced icon itself is 16px.

https://github.com/elementary/appcenter/blob/3bb4adfa95fe419f82da544756647c83592067d2/data/icons/applications-accessibility-symbolic.svg?short_path=8e833d7#L10-L13

**Comment by danirabbit** [comment]
@dar5hak I proposed a branch here: https://github.com/elementary/appcenter/pull/1954

**Comment by dar5hak** [comment]
Thanks, Dani! These are looking good.

Do you also think the Office icon in the screenshot above needs some vertical adjustment? I mean, technically it is centered, but visually it looked a bit off. Could be just me.
