### ISSUE TITLE
Label is hidden in restart infobar

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#196]
well that's awkward
![screenshot from 2017-04-02 13 01 01](https://cloud.githubusercontent.com/assets/7277719/24590596/7f1192ec-17a4-11e7-9f38-a59288261e4f.png)

**Comment by donadigo** [comment]
Reproduce steps? Or just happening randomly?

**Comment by danrabbit** [comment]
Just ran my OS updates. My guess is that it's because of this line

`client.bind_property ("restart-required", infobar, "no-show-all", BindingFlags.INVERT_BOOLEAN | BindingFlags.SYNC_CREATE);`

Afaik, infobar is in a revealer so the visible should toggle the state of that revealer

**Comment by donadigo** [comment]
Yeah, that's probably a problem with `no_show_all`, a removal will most likely resolve this problem. This could be also checked with Gtk Inspector.
