### ISSUE TITLE
flatpak update error with MESA package in eOS 7

### ISSUE THREAD

**Issue by Kazekage-Gaara** [elementary/appcenter#1986]
### Discussed in https://github.com/elementary/appcenter/discussions/1985

<div type='discussions-op-text'>

<sup>Originally posted by **Kazekage-Gaara** February  4, 2023</sup>
Hello, since yesterday I installed ElementaryOS 7 and I performed an update just installed the system. But I always have a pending update in the application center apparently a flatpak package. When I try from the terminal running the flatpak update command, I get the following error:

Error: Error pulling from repo: While loading runtime/org.freedesktop.Platform.GL.default/x86_64/22. 08 from the remote freedesktop repository: fsck 6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d.dirtree: No such metadata object 6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d.dirtree

When I run the flatpak repair command it returns;
error: No such metadata object 6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d.dirtree

Apparently it's a bug with MESA, I don't know what to do anymore. </div>

**Comment by diogopessoa** [comment]
The AppCenter did not notify to restart the system? I think version 7 installs after restarting the machine.

**Comment by Kazekage-Gaara** [comment]
yes, i'm restart de machine, but when system start, the app center notify the same update again. Apparently not working fine or is another problem.

**Comment by diogopessoa** [comment]
Run in the terminal to see if it solve:

`sudo flatpak repair`

**Comment by Kazekage-Gaara** [comment]
[sudo] contraseña para kazekage:
[32/32] Verificando appcenter:runtime/org.gnome.Epiphany.Locale/x86_64/stable…
Comprobando remotos...
Podando objetos
error: No such metadata object 6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d.dirtree

**Comment by diogopessoa** [comment]
I also faced a similar issue with the AppCenter when trying to install Fragments:

![photo_2023-02-05_11-22-46](https://user-images.githubusercontent.com/12633864/216825197-18c56053-a303-4e14-a1a9-2a9453d94a00.jpg)

But after to running the command  `sudo flatpak repair` I was able to install.

On the elementary telegram group, I saw other people reporting AppCenter problems when trying to install flatpak apps.

System:
elementary OS 7.0 Horus
intel i5 8gB Ram
