### ISSUE TITLE
App Store Shows a Constant Update Message

### ISSUE THREAD

**Issue by Imauny** [elementary/appcenter#1988]
### What Happened?

When i open the app store to check for updates, i see that it says a 137 MB of data needed to download an update for flatpak run time. When i click download, its initiated and then it ask again for the same amount to be downloaded. I exited the store, rebooted my laptop and retry and it stills shows the app that needs update and even though I've allowed it to do so multiple times it keeps showing up.

### Steps to Reproduce

Clicked on updates, then i went and update the app that needs updating. It shows something like it's installing and then it refreshes and shows me that same update over and over again.

### Expected Behavior

To make the update and install without showing up again as a download needed.

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Hardware Info

HP LAPTOP 14

**Comment by Imauny** [comment]
I'm actually using the latest stable release of Elementary OS 7.

**Comment by Imauny** [comment]
![Screenshot from 2023-02-05 11 41 43](https://user-images.githubusercontent.com/90160506/216832364-8f86f2b0-5cf1-409f-a416-6bfc56adfae0.png)

**Comment by darkneofire** [comment]
I recently installed Elementary OS 7 and the update problem persists. Also when browsing by category education, office or system in the store, the app crash it and close.

**Comment by meisenzahl** [comment]
This should be fixed by https://github.com/elementary/appcenter/pull/1983.
