### ISSUE TITLE
App Center Crash on Category View Click after fresh ISO install

### ISSUE THREAD

**Issue by yetimaan** [elementary/appcenter#1989]
### What Happened?

After a fresh, clean installation of the eOS7 01292023 ISO, the App Center crashes when clicking the "Office" category among one or two other categories.

Solution:

I ran `sudo flatpak repair` and `sudo flatpak update`. Many apps needed repairing and a library updated. I've had no issues in eOS7 since.

### Steps to Reproduce

1. Clean install using eOS7 01292023 ISO
2. Update OS using App Center, Reboot
3. Run `flatpak update` to ensure up to date (notice a flatpak library tries to update but is corrupt)
4. Run App Center and click "Office" category
5. Crash

### Expected Behavior

After fresh install, all flatpak llibraries and applications are not corrupt and functional.

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Hardware Info

    eeeee  eeeeeeeeeeee   eeeee       OS: elementary OS 7 Horus x86_64 
  eeee   eeeee       eee     eeee     Host: Thelio thelio-r2 
 eeee   eeee          eee     eeee    Kernel: 5.15.0-58-generic 
eee    eee            eee       eee   Uptime: 1 day, 6 hours, 36 mins 
eee   eee            eee        eee   Packages: 1785 (dpkg), 54 (flatpak) 
ee    eee           eeee       eeee   Shell: zsh 5.8.1 
ee    eee         eeeee      eeeeee   Resolution: 3840x2160 
ee    eee       eeeee      eeeee ee   DE: Pantheon 
eee   eeee   eeeeee      eeeee  eee   WM: Mutter(Gala) 
eee    eeeeeeeeee     eeeeee    eee   Theme: io.elementary.stylesheet.blueberry [GTK3] 
 eeeeeeeeeeeeeeeeeeeeeeee    eeeee    Icons: elementary [GTK3] 
  eeeeeeee eeeeeeeeeeee      eeee     Terminal: tilix 
    eeeee                 eeeee       CPU: AMD Ryzen 7 5700G with Radeon Graphics (16) @ 4.673GHz 
      eeeeeee         eeeeeee         GPU: NVIDIA GeForce RTX 2060 SUPER 
         eeeeeeeeeeeeeeeee            Memory: 7695MiB / 15861MiB

**Comment by darkneofire** [comment]
I recently installed Elementary OS 7 and when browsing by category education, office or system in the store, the app crash it and close.

**Comment by mluizvitor** [comment]
I can confirm the same behavior.

> I ran `sudo flatpak repair` and `sudo flatpak update`. Many apps needed repairing and a library updated. I've had no issues in eOS7 since.

👆🏻 solved the crash
