### ISSUE TITLE
AppCenter will crash if `System` is clicked.

### ISSUE THREAD

**Issue by sauntor** [elementary/appcenter#2000]
![屏幕截图 2023-02-09 01 49 36@2x](https://user-images.githubusercontent.com/2825145/217614233-f6dd37c2-d518-49e6-85f7-988fe45dda73.png)
### What Happened?

If you click the `System` cell in AppCenter,  it will crash, the output log is as the following:
```text
(io.elementary.appcenter:2031): Gtk-WARNING **: 01:48:51.508: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 16
Segment Fault
```

### Steps to Reproduce

1. Click `AppCenter` on the Dock (a.k. `Plank`) (or use terminal: io.elementary.appcenter)
2. Click the `System` cell

### Expected Behavior

apps related to system wide/settings should be listed

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Nvidia GTX 1050 (3860x2160 with hidpi scale set to x2), with driver installed(nvidia-driver-525)

**Comment by sauntor** [comment]
This bug will occur too when no nvidia driver is installed

**Comment by meisenzahl** [comment]
I'm confident that the recent update of AppCenter fixed the issue. @sauntor are you still able to produce a crash after an update of AppCenter?

**Comment by sauntor** [comment]
yes, it has been fixed
