### ISSUE TITLE
Rearrangement of Application page

### ISSUE THREAD

**Issue by aitor-gomila** [elementary/appcenter#2018]
### Problem

AppCenter tags occupy too much space and too much scrolling needs to be done to reach the Repository/Website sections. Specially when window is not in fullscreen.

### Proposal

I put important links to the top and made tags openable/closable. Maybe we can leave the latest tag open by default.

![Elementary AppCenter Mockup 1](https://user-images.githubusercontent.com/46191980/233145118-bebf1614-6958-4ce0-ad4e-aa72ee0f2e08.png)

Open to suggestions

**Comment by danirabbit** [comment]
I'm not sure it makes sense to have these links so far up. We've received other feedback that the screenshots and description is already too far down and that would make this worse. But I can see an argument for moving the releases down to be at the bottom. Maybe putting them on cards and laying them out horizontally would make things better in terms of not having to scroll too far?

**Comment by aitor-gomila** [comment]
I think the current design for tags give useful info, so I think making them expandable (like in the screenshot) would be better. Could the screenshots and appbar (where download button is) adapt to other resolutions so things are easier to see?

**Comment by danirabbit** [comment]
I'd really like to avoid using expanders, typically people just never expand them so whatever is behind them is lost information.

Can you be more specific with what you mean by "adapt to other resolutions"? What specifically would make "things easier to see"? Which things?

**Comment by aitor-gomila** [comment]
Moved to #2019
