### ISSUE TITLE
Multiple updates and multiple reboots daily

### ISSUE THREAD

**Issue by amgschnappi** [elementary/appcenter#2022]
### What Happened?

Multiple updates and multiple reboots daily

### Steps to Reproduce

Everyday there are some or the other updates. Many updates need reboot.

If we take a look at https://www.reddit.com/r/elementaryos/comments/12zau4y/rant_arrgh_how_do_i_stop_this_daily_update_checks/ we can see that from 26 to 28 April, there were 4 updates and 3 reboots.

1. https://imgur.com/a/MX4UM69
2. https://imgur.com/a/UxRTjaR
3. https://imgur.com/a/Fv2cM6n
4. https://imgur.com/a/J2PMRs6

### Expected Behavior

Very less updates without frequent reboots.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
This looks like a period of time when lots of upstream security updates just happened to be released a few days in a row. This isn't a thing that we should try to stop. You can choose not to install the updates, but getting security updates to folks ASAP is a good thing.

Closing as "Design conflict" since we don't want to slow or discourage applying upstream security updates

**Comment by danirabbit** [comment]
@janxkoci just about anything that is security related is going to require to restart services etc anyways so you will already need to reboot to apply security updates

**Comment by janxkoci** [comment]
@danirabbit But that can only be true for **offline updates** - e.g. our HPC servers (Debian or CentOS) definitely don't need to be rebooted every time there is a security update, and our admins take security _very_ seriously. Heck - Ubuntu can now update kernels without rebooting, with LivePatch! Not to mention that on desktops these days even music players (spotify) and text editors (vscode) get security updates (although most elementary users will probably get these from flatpak).

**Comment by danirabbit** [comment]
@janxkoci all system updates are offline. They have been offline for a while. They will continue to be offline. This is a desktop operating system not a server operating system. It is normal and expected to restart the operating system

**Comment by janxkoci** [comment]
> all system updates are offline

Maybe on _elementary OS 7_, but this was never normal on Linux. Offline updates are a new thing, not a norm! I know I will not change your mind, but know that users are upset about this change.

One question, if I may - what was the specific problem offline updates are solving?

It's just that I don't see why updates would fail at the time I choose to run them. On the other hand I can see easily why they could fail during the next boot - I just came back from a short vacation and my laptop had lower battery then expected. Booting started to apply updates I forgot about, from before the vacation, and when the progress was stuck at 50% for a few minutes I just happened to notice the red LED light at the side of the chassis, and rushed to untangle a charger. I mean is this really something I have to worry about now?

It just feels so much like - _Windows_ :confused:

**Comment by danirabbit** [comment]
@janxkoci this reddit post has some good information: https://www.reddit.com/r/linux/comments/3lzt0n/why_are_offline_updates_better_than_online_updates/?rdt=45765

This is also how updates are applied in Fedora, any modern atomic distro, other mainstream operating systems like iOS.

Updates are applied atomically which makes them fail more safely in the event of power loss etc

**Comment by janxkoci** [comment]
So pretty much what I already suspected. To quote one of the comments:

> While there may be benefits, I find it hard to respect the idea of off-line updates. Live updates have been working very well for me for well over a decade now on Linux and BSD, so being asked to reboot for anything other than a kernel update feels like a huge step backward.

The benefits seem mostly related to desktop (workstation), as these machines can easily suffer sudden power loss. But with laptops it's the opposite - I can be sure of my battery and network status when I click "update", but not necessarily the next time I boot.
