### ISSUE TITLE
AppCenter doesn't update runtimes and some Flatpak apps (FileRoller, Evince and Web)

### ISSUE THREAD

**Issue by Odi-3** [elementary/appcenter#2027]
### What Happened?

AppCenter doesn't update runtimes and some Flatpak apps (FileRoller, Evince and Web).

### Steps to Reproduce

1. Open AppCenter
2. Try to update all

### Expected Behavior

AppCenter can update everything

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by Odi-3** [comment]
Giving `flatpak update` in terminal some errors appear:
![eOS-terminal-flatpakupdates](https://user-images.githubusercontent.com/122830882/235913851-71ec0ae6-3507-48a0-8f33-769b8ef8a7cc.jpg)

**Comment by vjr** [comment]
Run `sudo flatpak repair` and see?

**Comment by Odi-3** [comment]
Thank you! It works again :)

**Comment by aitor-gomila** [comment]
@Odi-3 could you close the issue?
