### ISSUE TITLE
Warn if apps can send notifications directly

### ISSUE THREAD

**Issue by danirabbit** [elementary/appcenter#2047]
### Problem

I've seen several apps with:

```
--talk-name=org.freedesktop.Notifications"
```

They should be using the notifications portal so that they can't spoof being another app and so that users can disable them

### Proposal

Warn that this app can send notifications without permission and without identifying themselves

**Comment by lenemter** [comment]
Fixed in https://github.com/elementary/appcenter/pull/2078
