### ISSUE TITLE
Date & Time settings: Show week numbers from either Monday or Sunday as start of the week

### ISSUE THREAD

**Issue by Invarianz** [elementary/appcenter#2066]
### Problem

It's possible to show the current week numbers in the calendar app and in the top bar.
However, there are two possible conventions when defining the start of a week. Either Monday or Sunday.
Here in Germany it is common to use Monday as start of the week and consequently the current calendar week can be different from the convention with a start on Sunday.

### Proposal

Add an option in Date & Time settings to choose between Monday and Sunday as start of the week.

**Comment by tintou** [comment]
The selection depends on the locale you're using, in Germany de_DE should already default to Monday

**Comment by Invarianz** [comment]
Thanks! I changed the "Formats" under "Language & Region" to Germany and now everything works as expected.
As a small add-on I discovered an additional bug when doing so related to the browser.
When setting the format by clicking on the "Set Language" button and restarting the (AppCentre) Epiphany browser stopped working and crashed constantly. Only setting via "Set System Language" resolved this issue.
I'm not sure if this is related to Elementary specifically or a Flatpak issue. If this belongs to a different issue I would be happy if you could attach this thread.

Thanks again!
