### ISSUE TITLE
Make AppCenter flatpak only

### ISSUE THREAD

**Issue by leolost2605** [elementary/appcenter#2107]
Currently AppCenter supplies apps via flatpak but also OS updates via packagekit and drivers via ubuntu drivers. This has lead to quite a bit of complexity and thus over time to some big issues (I regularly experience crashes) making AppCenter somewhat unreliable which in such a vital component like OS updates isn't very good (also e.g. see #2096 which can prevent one from updating at all).

This issue therefore suggests to make appcenter flatpak only and move os updates to settings daemon/settings. This would in the future reduce the maintenance effort by a lot especially because we don't have to try and force everything in a one-things-fits-all kind of thing with the BackendInterface where half of the methods is only implemented/actually used by one or two of the backends. This also holds true when we might want to switch to something like ostree.
Disadvantages here would be that native apps like mail or settings can't be viewed in appcenter but since they can't be uninstalled anyways (see e.g. #2062) that's not a big loss I think.

Like I said it's only a thought that crossed my mind but if it's something that would be accepted I'd start work on the os updates in the settings daemon (I kinda fell in love with packagekit since working with it on the extension manager lol) 🤷

**Comment by danirabbit** [comment]
I thought we already had an issue or discussion somewhere for this 🤔 @meisenzahl has already begun on some work with upgrades in settings daemon, I think. But yeah I think generally that’s the best path forward long term is to move drivers and OS updates out of AppCenter and have AppCenter only be for Flatpak apps.

I think redoing drivers would probably have the biggest immediate impact. IIRC it’s currently very Ubuntu specific and the design of presenting drivers as updates is not very good. Having driver management in the System plug would make more sense with where folks expect it to be. I thought @donadigo maybe had some work on using a cross-distro driver install method but I can’t remember
