### ISSUE TITLE
Quit keyboard shortcut closes the window but not the application

### ISSUE THREAD

**Issue by zeebok** [elementary/appcenter#2198]
### What Happened?

If I close AppCenter with Ctrl+Q the process still remains

### Steps to Reproduce

1. Open the app via GUI or terminal
2. Press Ctrl+Q
3. Check active processes

### Expected Behavior

This made sense when AppCenter had the daemon always running but since that seems to have gone away (and I might be wrong about that), I would think the shortcut would quit the application entirely

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by leolost2605** [comment]
AFAIK the daemon is still there but maybe I missed something? For flatpak auto updating etc.. We are only launching it via the portal now
Does closing the window via gui end the process for you? Because I think it should neither no?

**Comment by zeebok** [comment]
Sorry it took so long to get back. So if I grep for 'appcenter' in `ps aux` I only get the application (maybe the daemon has some other name?) and if I close the app via the GUI window controls then `ps aux` returns nothing. If I close with the keyboard shortcut `ps aux` still reports the appcenter PID as running. 

I would say the issue is that it is inconsistent. Whether it should still be running or not, I am not entirely sure.

**Comment by zeebok** [comment]
That did the trick, thanks!
