### ISSUE TITLE
Release notes can overflow

### ISSUE THREAD

**Issue by lenemter** [elementary/appcenter#2204]
### What Happened?

![Screenshot from 2024-08-10 23 08 10](https://github.com/user-attachments/assets/fb3df182-a972-4732-b8bd-1d7d3f99dfdf)

### Steps to Reproduce

-

### Expected Behavior

-

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
Fixed in #2227
