### ISSUE TITLE
Appcenter still reserves space for system updates in eOS 8

### ISSUE THREAD

**Issue by teamcons** [elementary/appcenter#2215]
### What Happened?

Appcenter, when maximized fullscreen or on the side, display a large blank space before the apps - for where system updates once were.

![Bildschirmfoto von 2024-10-30 20 47 14](https://github.com/user-attachments/assets/4b9f1f51-e8cb-4583-b250-735cc4741f1f)

### Steps to Reproduce

open appcenter
maximize, or tile to one side

### Expected Behavior

For the list of apps to start at the top, with no strange empty wasted space

### OS Version

8.x (Early Access)

### Session Type

Secure Session (Wayland)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
Hrm you should see like a loading placeholder here or like a banner that says "Everything up to date"

**Comment by teamcons** [comment]
No. Never. It is always empty

When there is an update, the padding is a bit brutal

![Bildschirmfoto von 2024-11-04 21 08 31](https://github.com/user-attachments/assets/e39be80e-ba3b-4579-ab71-8bb0d7e57349)

**Comment by teamcons** [comment]
When updates finishes, the banner "no update" flashes in the middle for half a second.
Even if the banner stayed, it does not fill the giant empty blank space of appcenter. So its disappearance may be a second, unrelated bug (i legit didnt know there was a banner, i thought appcenter just... doesnt display anything when theres no update)
