### ISSUE TITLE
Spice-Up not showing in search results

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#222]
When I search for `spice-up`, (or any substring of it), Spice-Up doesn't show in search results. However, if I search for `com.g` (as in the start of `com.github.philip-scott.spice-up`, it does appear.

**Comment by davidmhewitt** [comment]
The problem seems to be with AppStream or Spice-Up's metadata. The AppStream CLI returns the same results for the same queries.

**Comment by davidmhewitt** [comment]
Removing the dash from the package name in the AppStream metadata makes AppStream be able to find the package when searching for 'spice'.

Unsure if this is intentional behaviour in AppStream, a bug in AppStream or a problem with the way the metadata is formatted.

**Comment by danrabbit** [comment]
Looks like this was an upstream bug in appstream. Fixed in this commit: https://github.com/ximion/appstream/commit/82b7032cb058c4b16d6754af6d9af8dfeaed4691
