### ISSUE TITLE
Visual bug in release widgets

### ISSUE THREAD

**Issue by alainm23** [elementary/appcenter#2224]
### What Happened?

![image](https://github.com/user-attachments/assets/1362285f-472b-44d4-a51d-e490152983fe)
![image](https://github.com/user-attachments/assets/2b28646d-46b7-444a-b9d4-b44623a697ce)

### Steps to Reproduce

Open App Detail

### Expected Behavior

-

### OS Version

8.x (Circe)

### Session Type

Secure Session (Wayland)

### Software Version

Latest release (I have run all updates)

**Comment by edwood-grant** [comment]
This seems to happen only when using the cute looking bug list styles. 

Here's as screenshot from [Calendar](https://appcenter.elementary.io/io.elementary.calendar/):
![Captura de pantalla de 2024-12-09 07 37 48](https://github.com/user-attachments/assets/2a2b891c-cee5-49a9-b20d-e4321aefae56)

And [Mail](https://appcenter.elementary.io/io.elementary.calendar/):
![Captura de pantalla de 2024-12-09 07 44 09](https://github.com/user-attachments/assets/e366916c-39cc-4133-8990-d3365bdf5333)

I contrast to, for example, [Reco](https://appcenter.elementary.io/com.github.ryonakano.reco/), which works as expected:
![Captura de pantalla de 2024-12-09 07 40 46](https://github.com/user-attachments/assets/c09df652-6d7e-4c16-850b-cf7318688bde)

You can somewhat make it look OK if you shrink the window to one column, but it doesn't work perfectly for every application.

**Comment by danirabbit** [comment]
Duplicate of #2204
