### ISSUE TITLE
Name missing from backers.md

### ISSUE THREAD

**Issue by mikeanthonywild** [elementary/appcenter#232]
Any chance I could get my name added to `backers.md` - I was part of the $10 tier, but my name seems to be missing (I double-checked the donation settings weren't set to anonymous).

**Comment by danrabbit** [comment]
Hey Mike, looks like you didn't claim any perks when you backed the campaign. I've gone ahead and added your name since we have your permission now :)

**Comment by mikeanthonywild** [comment]
Oops I must have missed that step - thank you :)
