### ISSUE TITLE
Appcenter crashes while updating

### ISSUE THREAD

**Issue by matzipan** [elementary/appcenter#234]
```
ERROR:/build/appcenter-CVG1ZS/appcenter-0.1.5+r477+pkg51~daily~ubuntu0.4.1/src/Views/AppListView.vala:310:app_center_views_app_list_update_view_finish_updating_all_apps: assertion failed: (updating_all_apps && packages_changing == 0)
Aborted (core dumped)
```

**Comment by danrabbit** [comment]
Can you get the backtrace please?

**Comment by matzipan** [comment]
I don't have any updates to perform right now... Will try next time I get some, probably tomorrow.

**Comment by danrabbit** [comment]
Alright, going to close as incomplete, feel free to reopen with more info :)

**Comment by matzipan** [comment]
As per Adam's question, it was updating three things: one was elementary, one was Files but the third I can't remember.
