### ISSUE TITLE
Search doesn't work with substrings

### ISSUE THREAD

**Issue by Tomires** [elementary/appcenter#240]
I have searched for "torrent" and the only result displayed was for an application that helps people have sex. Judging by the Internet section, there are at least 2 torrent clients available on the AppCenter.

![screenshot from 2017-04-19 20 40 09](https://cloud.githubusercontent.com/assets/7209990/25206548/e8eccaac-2568-11e7-85fd-e06167fea739.png)

There is also an inconsistency when searching from the category view. After pressing the delete/backspace icon, the window header changes from displaying name of the category to a toggle usually displayed on the main screen.

![image](https://cloud.githubusercontent.com/assets/7209990/25206731/12a6f6f0-256a-11e7-9c7f-59e9462bcbb0.png)

**Comment by cassidyjames** [comment]
As a further note, it looks like "torrent" apps don't include the literal string "torrent", but include "BitTorrent". Our search should be smarter about searching partial strings, but I fear this may be an AppStream limitation.

**Comment by DaviTeodoro** [comment]
Is it possible to create some kind of tag system where the app developer could add common search terms?

**Comment by donadigo** [comment]
@DaviTeodoro AppStream already has a `keyword` key for including the keywords for a component. AppCenter uses `search ()` on `AppStream.Pool` but it could be possible to use `search_matches` on each component.

**Comment by cassidyjames** [comment]
The first part of this report is related to #26, but the second half sound valid: that search does not work on substrings (i.e. searching "torrent" does not return apps with the word "BitTorrent" in them).

**Comment by Ikki-Dai** [comment]
Hi,

I have similar issues. while i click the app icons which provide in https://appcenter.elementary.io and then browse pops and tell me that it can be open in appcenter, but appcenter shows ''No Result''

I notice that  "com.github...." in search box could be the full name

![image](https://user-images.githubusercontent.com/16415439/50905731-71308f80-145e-11e9-82ba-73901174b76b.png)

**Comment by Ikki-Dai** [comment]
@cassidyjames,

I'm on Juno now. nearly all of recommended apps on appcenter's website are unavailable in appcenter, but the others are available

**Comment by cassidyjames** [comment]
@Ikki-Dai are they available when you browse from the AppCenter home page, or they never show up? Regardless, that's an entirely separate issue from this substring one and should be filed as such.

**Comment by Ikki-Dai** [comment]
@cassidyjames 

they are not available from AppCenter home page now, but they were shown a few months ago.

**Comment by peteruithoven** [comment]
I get a completely different result than @Tomires:
![screenshot from 2019-01-23 14 18 24](https://user-images.githubusercontent.com/523210/51609199-c4ecaf80-1f19-11e9-97bb-2d8d20f04c6c.png)
