### ISSUE TITLE
Blacklist apps

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#242]
There are a number of apps from the repos that are known broken. With the current AppCenter, there's nothing stopping users from installing those and having a bad experience. We should consider a client-side blacklist for apps as long as we're on top of the Ubuntu repositories.

Similar but distinct from #233, as that handles marking all apps from the repo, whereas this is a proposal to blacklist certain apps completely.

**Comment by cassidyjames** [comment]
Another example of a type app that should be blacklisted: QHaveDate. It has an inappropriate icon and description, and shows up in all sorts of search results due to the large amount of keywords.

**Comment by Philip-Scott** [comment]
@cassidyjames duplicate of https://github.com/elementary/appcenter/issues/26 ;) We can do it, but who would maintain that list?

**Comment by cassidyjames** [comment]
@Philip-Scott derp, my bad. I imaging we would maintain it in the AppCenter repo. It shouldn't be too insane since we're moving toward apps coming from Houston, but there are some really, really bad results we should get out of there ASAP.

**Comment by cassidyjames** [comment]
@Philip-Scott is that actually the same issue? I know it's named similarly, but that sounds like it's intended for console apps and not necessarily flagging broken or inappropriate apps.

**Comment by Philip-Scott** [comment]
Yeah, its the same. removing console apps was just one use for it and the `compulsory_for_desktop` thing was just an idea on how to solve it

**Comment by Philip-Scott** [comment]
It's a black list after all ;)
