### ISSUE TITLE
The date placeholder in the StripeDialog is misleading

### ISSUE THREAD

**Issue by matzipan** [elementary/appcenter#250]
Hey guys,

So I just tried to buy something in Appcenter (and I succeeded). However, the placeholder in the expiry [date field](https://github.com/elementary/appcenter/blob/51480c8013ec8b53ee7ec957213cf0813a14dbc2/src/Dialogs/StripeDialog.vala#L93) is a bit misleading.

The reason for this is that it leads you to believe the format is "xx/yy", when the actual accepted format is "xxyy".

**Comment by btkostner** [comment]
I second this. I think we should require a slash between the two, and if it's 4 numbers without a slack, insert one on unfocus.

**Comment by dahenson** [comment]
I can confirm this, and felt kind of weird putting 4 numbers in. Crossed my fingers and hoped it would work. This is probably a showstopper for some users who get confused and just give up.

**Comment by peteruithoven** [comment]
Why not use 2 fields for this? This way no one has to think about a separator.

**Comment by peteruithoven** [comment]
I understand from the [Linux Action Special](https://youtu.be/5z0MWGU56Fk) that this was modelled after Stripe connect. I think this is a demo of how that works: https://stripe.com/docs/checkout
They seem to add the `/` character while typing.

**Comment by peteruithoven** [comment]
I've been tinkering with a regular expression, but this adds the `/` in the actual text itself. 

```
var regex = new Regex ("""^(\d{2})\/?(\d{0,2})$""");
var input = card_expiration_entry.text;
card_expiration_entry.text = regex.replace(input, input.length, 0, """\1/\2""");
```

Implementing it like that demo would be much easier if there would be much easier if there was a way to have the visual representation separated from the  actual input. Is there a good way to do that?
