### ISSUE TITLE
New Version shown without GH Release

### ISSUE THREAD

**Issue by babluboy** [elementary/appcenter#252]
Yesterday I pushed a version of Bookworm code in GH with the version 0.6 but without releasing the same on GH. Today I see that Appcenter is asking me to update bookworm to 0.6...Not sure if this is a bug or I should not have pushed 0.6 to the master branch from where I had made the last release (0.5.4)
![screenshot from 2017-05-01 10 39 37](https://cloud.githubusercontent.com/assets/14061478/25579214/aa8da908-2e6d-11e7-92bd-3fea2de35ec7.jpeg)

**Comment by btkostner** [comment]
I can tell you that you shouldn't have a problem pushing code to master after you make a release. Houston checks out the release tag during build.

**Comment by babluboy** [comment]
@btkostner Guess you are right. Not sure how the 0.6 is showing up on Appcenter though...I thought its due to the build I'm doing on my machine, but its the same case in a VM also....

**Comment by btkostner** [comment]
Try doing `apt-cache showpkg <package>`. It should show what source list the package is from.

**Comment by btkostner** [comment]
For what it's worth, it is showing `0.5.4` to me, so I guess you have a ppa installed.

**Comment by babluboy** [comment]
@btkostner Yes, there was a PPA installed. I have now removed it and hopefully this should not happen after the next release. I guess we can close this issue as this was expected behavior ?

Here is the output of the showpkg command
`Package: bookworm`
`Versions: 
0.1-0~68~ubuntu0.4.1 (/var/lib/apt/lists/ppa.launchpad.net_bablu-boy_bookworm-daily_ubuntu_dists_xenial_main_binary-amd64_Packages)`
 `Description Language:` 
                 `File: /var/lib/apt/lists/ppa.launchpad.net_bablu-boy_bookworm-daily_ubuntu_dists_xenial_main_binary-amd64_Packages`
                  `MD5: 60f54b135b7a92a86a2a9b31bd87c3cb`
 `Description Language:` 
                 `File: /var/lib/apt/lists/ppa.launchpad.net_bablu-boy_bookworm-daily_ubuntu_dists_xenial_main_binary-i386_Packages`
                  `MD5: 60f54b135b7a92a86a2a9b31bd87c3cb`
 `Description Language: en`
                 `File: /var/lib/apt/lists/ppa.launchpad.net_bablu-boy_bookworm-daily_ubuntu_dists_xenial_main_i18n_Translation-en`
                  `MD5: 60f54b135b7a92a86a2a9b31bd87c3cb`


`Reverse Depends: 
  bookworm:i386,bookworm
Dependencies: 
0.1-0~68~ubuntu0.4.1 - dconf-gsettings-backend (16 (null)) gsettings-backend (0 (null)) libc6 (2 2.14) libgdk-pixbuf2.0-0 (2 2.22.0) libgee-0.8-2 (2 0.8.3) libglib2.0-0 (2 2.39.90) libgranite2 (2 0.2.0) libgtk-3-0 (2 3.17.9) libpango-1.0-0 (2 1.14.0) libsoup2.4-1 (2 2.4.0) libsqlite3-0 (2 3.5.9) libwebkit2gtk-4.0-37 (2 2.15.1) unzip (0 (null)) bookworm:i386 (32 (null)) 
Provides: 
0.1-0~68~ubuntu0.4.1 - 
Reverse Provides:`
