### ISSUE TITLE
Install app with language pack

### ISSUE THREAD

**Issue by snowparrot** [elementary/appcenter#254]
If you install firefox or libreoffice using the German language in elementary os
German languages aren't installed. You have to install manuelly.

I assume it's also the case in other languages.

Expected behaviour:
Install automatically the language pack of an app.

**Comment by Angedestenebres** [comment]
I totally agree with you.

In addition for libreoffice, there is also missing gtk package and by default your libreoffice looks like a Windows 95 apps ^^'

See screen:
![Capture d'écran du 2019-03-03 11 29 09-6ac6f6](https://user-images.githubusercontent.com/21110485/74586853-0dc34a80-4fec-11ea-851f-55596814860e.png)

**Comment by danrabbit** [comment]
Closing since we only support install Flatpak apps now and these don't have langpacks
