### ISSUE TITLE
Font installation should show the text in the font you'd be installing.

### ISSUE THREAD

**Issue by desiderantes** [elementary/appcenter#259]
The font icon and the preview pic should show how the font looks, with some example text.

**Comment by danrabbit** [comment]
For context, here's what fonts look like today:

![Screenshot from 2020-04-19 12 36 12@2x](https://user-images.githubusercontent.com/7277719/79697931-64424480-823a-11ea-808e-a5bfb0dba4ec.png)

**Comment by cassidyjames** [comment]
We just show the icon and screenshot provided by the AppStream data afaik, and even so, we probably don't really want fonts showing up in the app store. They could belong in a font app. 😛

**Comment by danrabbit** [comment]
I’m gonna close this since it sounds like we don’t want to show fonts in AppCenter at all. These could be shown in the fonts app instead
