### ISSUE TITLE
Always restores state of search from Slingshot [$15]

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#260]
1. Search for a string in AppCenter from Slingshot
2. Cancel the search in AppCenter with Esc or clearing the search box (returning to the home screen)
3. Close AppCenter
4. Re-open AppCenter

**Expected result:**
AppCenter restores to the last state, i.e. the home screen

**Actual result:**
AppCenter restores to the last search from Slingshot

This happens no matter how much/little you browse around AppCenter between steps 2 and 3.

---
There is a bounty on this issue in [Bountysource](https://www.bountysource.com/issues/44938072-always-restores-state-of-search-from-slingshot)

**Comment by alcinnz** [comment]
If it helps narrow down the bug, I've found that a workaround is to kill AppCenter when it starts doing this. 

Just my 2cents.

**Comment by donadigo** [comment]
@alcinnz: the bug is already fixed in my branch, just waiting for review.
