### ISSUE TITLE
Missing the Icon for "Report a Problem"

### ISSUE THREAD

**Issue by babluboy** [elementary/appcenter#263]
Was missing the icon for "Report a Problem" on Appcenter. Downloaded from master and built now, but the problem persists. Anything broken on my system ?
I'm on the default Loki theme.
![screenshot from 2017-05-10 09 29 38](https://cloud.githubusercontent.com/assets/14061478/25889942/84ebbecc-3563-11e7-8a8d-8d36324c2154.jpeg)

**Comment by danrabbit** [comment]
If you're running AppCenter from master, you'll need to also be running icons from master ;)

**Comment by babluboy** [comment]
Thanks...didn't remember to pick the icons from master
