### ISSUE TITLE
When no updates available the "Searching for updates" never ending

### ISSUE THREAD

**Issue by alons45** [elementary/appcenter#278]
![neverending](https://cloud.githubusercontent.com/assets/1877511/26164768/4c9a5a8e-3af3-11e7-86d4-ebb509e51b96.png)

**Comment by cassidyjames** [comment]
@alons45 are you running in a VM?

**Comment by alons45** [comment]
@cassidyjames not, but this problem not happen more, with last upgrade (0.4.1), sorry.
