### ISSUE TITLE
Always display a way to pay [$60]

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#281]
If someone already installed an app but wants to come back to the AppCenter listing, we should let them pay the developer there.

**Comment by nloomans** [comment]
I've started working on it! I'm currently developing it as a donate button, you can already see what that looks like in the repo. When the button is pressed, it will show a popover menu, the same as used in the HumbleButton, but with an added pay button.

What do you all think?

**Comment by babluboy** [comment]
This is a nice idea 👍...friend of mine installs apps for $0 to try out and if he likes using it he wants to donate...this would solve that scenario of pay later...

A screen shot here will be great 😀

**Comment by nloomans** [comment]
Sure, here is how the donate button currently looks like, the text is slightly smaller but that will be fixed.
![Screenshot of AppCenter with donate button](https://user-images.githubusercontent.com/7829481/27767893-d3bf7b4e-5f05-11e7-88ee-bf967de72ef7.png)

The plan is that when you click on it you get an popover just like this one, but with an added pay button on the right side.
![Popover](https://user-images.githubusercontent.com/7829481/27767901-0039ddea-5f06-11e7-92f6-9c563199c587.png)

**Comment by babluboy** [comment]
👍

**Comment by nloomans** [comment]
Status update: Made some progress today, it will probably be finished tomorrow.

I've moved the amount modifier to a separate class, and added a standalone option. The original pay button is HumbleButton is visually untouched, but now uses the same separate class.
![screenshot from 2017-07-02 22 01 37](https://user-images.githubusercontent.com/7829481/27773105-8a657760-5f72-11e7-9bd2-afa4ba1d2490.png)

All I still need to do is fix the error dialog so it doesn't show "Pay later" anymore when donating.

Any feedback?

**Comment by Philip-Scott** [comment]
"Donate" isn't really the correct word though, since both elementary and the developer are not "non-profit organizations" (And donations also mean that they're tax deductible) 

Maybe @elementary/ux would like to comment about copy, placement and other things? :)

**Comment by danrabbit** [comment]
We definitely want to avoid the word "donate" since like Felipe said it implies tax deduction, which buyers in AppCenter are not eligible for. We've had this bite us in the past with customers feeling swindled due to the misunderstanding

**Comment by stiffler17** [comment]
Maybe some version of  "contribution" or "financial contribution"?

**Comment by bigfatbird** [comment]
Does this default to the suggested price from the developer? 

i.e. if a developer thinks the app is worth 5$ the dropdown should default to 5$ and so on!

**Comment by nloomans** [comment]
@bigfatbird Just checked and it currently does not. It should be noted that the only "default" there is, is the custom amount input. Do you think it would be worth it to implement that?

I am moving the ETA as there are current issues that still need to be discussed, and I am also quite busy.

**Comment by bigfatbird** [comment]
I don't know. Sometimes people download the app without paying just to return to pay later. 

It could be a good indicator what a developer expects you to pay. I don't know where AppCenter fetches the price information, this might come from the houston backend? @btkostner

**Comment by nloomans** [comment]
Some other issues that I didn't think of:
 - the email that is send after a purchase doesn't make sense when "donating" (still not sure what a better word would be). [Image](https://user-images.githubusercontent.com/7829481/27841385-e435a0a0-6100-11e7-8476-2a9c257b4c53.png)

 - There is no in-app feedback when "donating" that the "donation" succeeded, I mean that the verifing box just closes itself after the "donation" without explicitly telling you it succeeded.

**Comment by djsmithumn** [comment]
Donation is not the correct term to use here. Maybe "Pay"? Why not just keep the suggested amount, for example "$1.00", on the app pages in the AppCenter unless they have paid?

**Comment by djsmithumn** [comment]
Other terms are "Compensate" "Fund" or "Reward".

**Comment by btkostner** [comment]
The suggested price is from the appstream data. Use [this function](https://github.com/elementary/appcenter/blob/master/src/Core/Package.vala#L459) to get it.

**Comment by lewisgoddard** [comment]
"Purchase" is the word we usually use, which brings up the idea of not being asked to pay twice for the same thing (which I think is what UX wants).

**Comment by btkostner** [comment]
So, (talking with @cassidyjames), we want to show a purchase button in the update list if the user has not already purchased it (#306). We also want to add a "Fund" button in the footer that would always show with the similar style as all the other footer links.

**Comment by danrabbit** [comment]
Something to consider also is what we do about the appstream donate tag. Does this override that? Do we show both?

My personal feeling is we only show one and use the AppCenter (stripe) one if it’s available.
