### ISSUE TITLE
Sources error

### ISSUE THREAD

**Issue by CodeManS99** [elementary/appcenter#284]
An error seems to occur in some instances when one has updated to appcenter 0.2 after already having added the sources list that was sent out for testing. When an attempt is made to install any of the applications from the elementary sources a message like in the photo appears and the installation is canelled.
![vocal error](https://cloud.githubusercontent.com/assets/21191691/26188319/610255fc-3b53-11e7-80c1-131691b94dce.png)

Please list the problem and possible fix below it's a known issue.

**Comment by danrabbit** [comment]
You need to update your sources list (likely at `/etc/apt/sources.list`). `packages.elementary.io` uses `http` not `https`
