### ISSUE TITLE
Other payment options

### ISSUE THREAD

**Issue by JO0st** [elementary/appcenter#291]
There are no other payment options than a credit card. As not everybody has one it makes it impossible for them to give some money for an application. It should be possible to use the other payment options stripe offers, this will give most users an option they have available to pay.

**Comment by cassidyjames** [comment]
#229 and #280 are already filed. What specific payment method would you like to be added?

**Comment by peteruithoven** [comment]
This article might be interesting: https://ecommercenews.eu/online-payment-methods-in-europe/
For folks like me in the Netherlands for example almost everything online happens with iDEAL. Stripe's support for it seems to be in preview mode.

**Comment by TehSViN24** [comment]
Paysafecard would be perfect for me

**Comment by JO0st** [comment]
For the belgian market (where I am from) bancontact is ideal, but I think maestro allready enables most of europe (not sure though).

For me personally paypall is not my prefered method of online payment, but I do have an account there so I would be using that one when it is available and bancontact or maestro are not.

**Comment by cassidyjames** [comment]
Grab bag issues like this are not helpful to track. I've opened issues for individual payment methods, and anyone is welcome to do so as well.

**Comment by eljefuri** [comment]
@cassidyjames This is one of those general topics that probably needs a place to live and breathe over the long-term. Is this the place? It is definitely a problem that the VISA/Masterard network is strictly necessary to pay developers.
