### ISSUE TITLE
Update Notes

### ISSUE THREAD

**Issue by matthewjamesr** [elementary/appcenter#294]
Hello all! It is surprising to me that App Center does not display anything resembling a changelog/update list for pending updates for end-users to see what has changed. I realize this may be semi-difficult to currate but think it would be a great step forward.

**Comment by btkostner** [comment]
I'm going to mark this as a duplicate for issue #24

**Comment by matthewjamesr** [comment]
@btkostner Sorry did a quick glance and did not see it.

**Comment by btkostner** [comment]
No harm done 😉
