### ISSUE TITLE
Clicking on Updates available notification should open AppCentre updates section directly

### ISSUE THREAD

**Issue by uncertainquark** [elementary/appcenter#295]
Right now, clicking on the Update available notification dismissed the notification. It should open the AppCenter Updates section instead.

**Comment by kdekooter** [comment]
And AppCenter should actually display the updates as well. At the moment I have to close and restart AppCenter before it starts looking for updates.

**Comment by uncertainquark** [comment]
Is #329 related?

**Comment by danrabbit** [comment]
afaict this is working in the latest master. Closing as fixed
