### ISSUE TITLE
Allow to link to BountySource

### ISSUE THREAD

**Issue by tintou** [elementary/appcenter#300]
It would be nice if we could add a link to the BountySource of the App at the bottom of the App View

**Comment by danrabbit** [comment]
My initial reaction is that this is a duplicate of the issue tracker link. Any thoughts from others at @elementary/ux ?

**Comment by cassidyjames** [comment]
Yeah I think if the app is using bounties, that's going to be reflected​ in the issue tracker as well. Also, projects may well use other bounty platforms even though we use Bountysource at elementary.
