### ISSUE TITLE
Apps without icons

### ISSUE THREAD

**Issue by inad9300** [elementary/appcenter#301]
There are a number of applications for which the icons aren't properly loaded: Archive Manager, Chromium Web Browser, Vim, VirtualBox... All of them have a nice icon that displays correctly in the launcher.

![appcenter-no-icons](https://cloud.githubusercontent.com/assets/3440331/26275229/460ca120-3d5c-11e7-99f5-416905cfc33d.png)

In addition, when you go to see the details of those apps, the same "no icon available" icon appears but in a very small form, which is horrible looking.

![appcenter-horrible-non-icon](https://cloud.githubusercontent.com/assets/3440331/26275231/4d32b8e0-3d5c-11e7-9564-e8dd78f96c26.png)

On a related note, can someone explain to me why does Vim appear on the launcher? Clicking its icon has no effect whatsoever.

![vim](https://cloud.githubusercontent.com/assets/3440331/26275247/a151b430-3d5c-11e7-8fbe-a272e796b20f.png)

Also note how blurry is the little triangle over the launcher. It is like this with all _darkish_ backgrounds. The colour of the triangle's border seems different (lighter) than the border of the launcher itself.

Sorry to compress 4 issues in one, but there you have it.

**Comment by inad9300** [comment]
The "Recently Updated" section seems to suffer from the same kind of issues.

![appcenter-no-icons-recently-updated](https://cloud.githubusercontent.com/assets/3440331/26275322/ed94fe82-3d5d-11e7-9074-a8992b0566b8.png)

**Comment by maliktunga** [comment]
On my setup, the installed apps that lack an icon (under the Updates tab) are:

- AppStream CLI

- Music

- Plank

**Comment by inad9300** [comment]
Same for me, all those apps that you mention have the generic icon with the cog -- and only those, the other problematic ones display the icon with the forbidden sign.

**Comment by maliktunga** [comment]
You're right, there seems to be two categories of apps without icons: those with cogs and those with the "no" symbol. Here are a few:

# Cog

- Gfaim
- Plank
- Maps
- Music
- Steam
- XIA

# 'No'

- AbiWord
- Bacula Administration Tool
- BOINC Manager
- Books
- Brasero
- Bulk Rename
- Calendar
- CMake
- Comix
- Déjà Dup Backup Tool
- Evolution
- Hardware Lister
- Htop
- Install RELEASE (twice)
- MPlayer
- MusE
- MuseScore
- Security & Privacy
- Sudoku
- Taquin
- upstart-monitor
- Virtual Machine Manager
- Weather
- xdiagnose

**Comment by yeboahnanaosei** [comment]
@inad9300 At the time of writing this the blurry triangle seems to have been fixed

**Comment by yeboahnanaosei** [comment]
Update: it still persists. Hasn't been fixed

**Comment by davidmhewitt** [comment]
There have been a number of issues fixed in AppCenter and with individual apps and infrastructure recently that will have resolved the majority of these issues.

It's likely that if an app is missing an icon in AppCenter now, it isn't following the spec properly or simply doesn't provide an icon. So I'll close this issue now.
