### ISSUE TITLE
Searching for updates indefinitely

### ISSUE THREAD

**Issue by inad9300** [elementary/appcenter#302]
I don't know how to reproduce this issue, but sometimes the indicator "Searching for updates..." just stays there forever.
![appcenter-endless-loading](https://cloud.githubusercontent.com/assets/3440331/26275307/96fd9764-3d5d-11e7-9319-9fd034354b9f.png)

**Comment by harisvsulaiman** [comment]
I can attest to this. When there is nothing to update, the indicator is shown indefinitely.

**Comment by davidmhewitt** [comment]
I'm going to close this due to age and I haven't seen or heard reports of anything similar for a while. Please re-open if you still see this.
