### ISSUE TITLE
Allow apps in app center which are not written in vala.

### ISSUE THREAD

**Issue by harisvsulaiman** [elementary/appcenter#304]
There are apps which are not built on vala which are immensely useful, that when given the chance can integrate well with the ecosystem.
For Example
-  Tilix (primarily written in D)
-  Vscode (I, know Electron apps are evil! But this is an awesome example of electron done right.)
- GravitDesigner  (Possibly an sketch alternative, but built on electron(PS no perf issues whatsoever).- https:designer.io
- Sublime text 

Another alternative is allow packaging like snaps or flatpak.(Leaning towards snaps)

**Comment by harisvsulaiman** [comment]
Btw i think electron will accept pull requests to better integrate with a popular distro.

**Comment by donadigo** [comment]
We don't require the app to be written in Vala, it can be written in any language really as long as it's native and we only encourage to build apps with Vala. The only requirement is that the app must be a native Gtk+3 app and should integrate well with the system.

**Comment by harisvsulaiman** [comment]
@donadigo So a Kotlin-native based gtk3 app is acceptable?. What would be the correct process to include one in appcenter?
@danrabbit
