### ISSUE TITLE
Remember purchased apps [$50]

### ISSUE THREAD

**Issue by itoshkov** [elementary/appcenter#306]
If you "purchase" an app, uninstall it and then go back to that app in the app center, you won't see any indication that you've already payed for it. I know you may want to pay again for it, or you can just enter 0 for the payment, but for people coming from other app stores it would look like they have to repurchase.

Perhaps a way to fix this would be to pre-select with a $0 price for already payed for apps and still leave the option to give money to the developer again?

---
This issue has a bounty on [BountySource](https://www.bountysource.com/issues/45395334-remember-purchased-apps)

**Comment by cassidyjames** [comment]
We've talked about doing this with an account system, but honestly we could solve this case by caching a record of previously installed apps locally. Would it be sane to use Zeitgeist for this so it respects privacy settings (doesn't remember what you've installed if you've switched History off in Security & Privacy)?

**Comment by danrabbit** [comment]
As of #559 we now have a way to keep track of paid apps locally, so this should be fairly simple to implement
