### ISSUE TITLE
Where to click to buy an app?

### ISSUE THREAD

**Issue by itoshkov** [elementary/appcenter#307]
I opened the new App Center (Version: 0.2.1+r632+pkg53~ubuntu0.4.1.1) and clicked on the Nimbus app. I see the $1.00 price tag with the downward arrow next to it (see the screenshot), but it wasn't obvious to me that I had to click the price to purchase the app. To me it looked like a standard drop-down menu, where clicking on the text or on the arrow does the same thing.

I think it would be better to make it more obvious where is the action button. Maybe adding some text next to the price like "Purchase for $1.00" or "Install for Free"?
![app center - 1](https://cloud.githubusercontent.com/assets/360805/26276043/650e0a8a-3d77-11e7-9fc4-03373deb8f48.png)

**Comment by cassidyjames** [comment]
I think I agree that if there is room, “Install for $1.00” is more clear, and is a verby action. I believe Android and iOS do just the price, but then again they're designed for more space-constrained devices. I'd be up to see this.

**Comment by itoshkov** [comment]
Thanks for looking into this.

Yes, an least on Android it's only the price. But it doesn't have a down arrow next to it, so it's more obvious what it will do.

**Comment by cassidyjames** [comment]
Feedback from @elementary/ux?

**Comment by danrabbit** [comment]
Sam and I are both -1 on adding this label. Other app stores just show the price and it seems to work out okay. Leaving this report open because OP's concern could be solved in another way

**Comment by fatto** [comment]
![appcenter_buy](https://user-images.githubusercontent.com/1191682/41383984-bcba762c-6f73-11e8-98b1-4c8ff6bb9c75.png)
Maybe something like the elementary homepage?

**Comment by itoshkov** [comment]
Another idea is to replace the downward arrow with something better for conveying change. For example a pencil icon.
