### ISSUE TITLE
Missing app author

### ISSUE THREAD

**Issue by inad9300** [elementary/appcenter#312]
It looks like some of the apps are missing the author in 'Recently Updated' section. (It happens even if the AppCenter opens in a maximized state.)
![missing-author](https://cloud.githubusercontent.com/assets/3440331/26320053/b68782b4-3f21-11e7-92d6-60b8ec583f16.png)

**Comment by danrabbit** [comment]
This was a bug in Vocal and Nathan as addressed it in his latest release which will be published soon.

Marking as "invalid" for AppCenter
