### ISSUE TITLE
Placeholder text not visible on cursor focus

### ISSUE THREAD

**Issue by inad9300** [elementary/appcenter#313]
<p>It is not clear what some fields represent based solely on the icon. Placeholders are very useful, and should not disappear on focus, as this completely breaks your workflow. This is specially remarkable when a field is auto-focused, as is the case in the image shown below. In particular for this example too, the envelop icon is sometimes used for the physical address, and sometimes for the email address.

<p align="center"><img src="https://cloud.githubusercontent.com/assets/3440331/26320197/3a7c340c-3f22-11e7-998d-8100971c7f1e.png"></p>

<p>From all the browsers I know, only the old-and-dead Internet Explorer was doing that, and it was really annoying.

<p>Also, please consider allowing to change the price to pay for an app even after clicking on the "$1.00" button. Easing the payment process as much as possible will only be beneficial for the whole ecosystem. We don't want to prevent a person from giving $2 instead of $1 because of little inconveniences like this.

**Comment by cassidyjames** [comment]
This is a bug in upstream GTK, I don't think there's anything we can do about it here.

**Comment by cassidyjames** [comment]
Upstream bug report: https://bugzilla.gnome.org/show_bug.cgi?id=667502
