### ISSUE TITLE
Show "made for elementary" apps first in categories [$50]

### ISSUE THREAD

**Issue by harveycabaguio** [elementary/appcenter#319]
Aside from the "Recently Updated" section of the homepage, there isn't really a way to find apps made for elementary right now. In Categories those apps are drowned out by the Ubuntu repository apps. 

For now I think categories should have a "Designed for elementary" and "Other Apps" header.

---
There is a bounty on this issue in [Bountysource](https://www.bountysource.com/issues/45521747-show-made-for-elementary-apps-first-in-categories)

**Comment by danrabbit** [comment]
Not sure if duplicate, but sounds like an easy solution to #233
