### ISSUE TITLE
Non-curated logic not quite right

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#324]
It looks like it's not picking up all the right apps

![screenshot from 2017-05-27 10 05 12](https://cloud.githubusercontent.com/assets/611168/26522745/aad219ec-42c4-11e7-88f1-f8350fa3afbf.png)

**Comment by danrabbit** [comment]
Closing since it was pointed out on Slack that Cassidy is using the testing repo which means those apps haven't yet passed review ;p
