### ISSUE TITLE
Auth before payment

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#327]
Right now we ask for payment, then throw the authentication dialog. If possible, we should auth first. The case I'm trying to avoid is someone successfully paying, but then not knowing/remembering their password and so not being able to actually receive the purchased app.

**Comment by tintou** [comment]
It's currently not possible because the Auth dialog is handled internally by PackageKit

**Comment by Philip-Scott** [comment]
It would be possible if we started the download before showing the StripeDialog

**Comment by danrabbit** [comment]
I'm going to close this since we're migrating AppCenter to Flatpak and we don't require authentication for Flatpak installations
