### ISSUE TITLE
Clicking on "Application installed" notification should open the said Application

### ISSUE THREAD

**Issue by moonmehta** [elementary/appcenter#329]
Clicking on the said notification does nothing as of now. It should open the app instead.

![screenshot from 2017-06-03 12-24-22](https://cloud.githubusercontent.com/assets/22585732/26752291/30aca8de-486a-11e7-9c02-355ef4e57acf.png)

**Comment by uncertainquark** [comment]
The same applies to 3rd party apps. 

![Screenshot from 2019-04-17 17-17-36](https://user-images.githubusercontent.com/22585732/56285414-cc94ac80-6134-11e9-97ed-b2d1eb3e6ff2.png)

Seeing that the notification says "Application is ready to be used", it is confusing that upon clicking the notification, nothing happens.

**Comment by danirabbit** [comment]
Closing as a duplicate of #1546
