### ISSUE TITLE
AppCenter freeze on open info preview page of application

### ISSUE THREAD

**Issue by ruslankonev** [elementary/appcenter#334]
Not constantly, but often enough, the application freezes when displaying application pages. Probably due to underloading of the application image
![image](https://user-images.githubusercontent.com/2588730/27225221-e2a8d828-52a1-11e7-95d9-d2c2b8ff8f8f.png)

**Comment by nikzuzu** [comment]
my appcenter doesn't work.

**Comment by EvgeniiFrolov** [comment]
I am also affected in my elementary os virtualbox installation. Any way I can help? Using debug flag shows nothing. Can easily reproduce by opening several application entries sequentially. Simply one after another. Ans sooner or later the appcenter stops responding. Like on the 3rd or the 4th application entry.

**Comment by GitHaarek** [comment]
Confirming. With some apps it happens every time. You should be able to reproduce by searching for Cozy and clicking on it.

**Comment by GitHaarek** [comment]
Interesting. I just tried opening Cozy by clicking on the "Get it on AppCenter" button on it's GitHub page and now it opens just fine, also by searching for it.

**Comment by EvgeniiFrolov** [comment]
I don't experience the bug anymore. Seems to be resolved, doesn't it?

**Comment by GitHaarek** [comment]
I'm afraid not. It happens very often from my testing.
It rarely happens on the ISO before updating the packages, but after updating AppCenter to version 0.2.7 the issue occurs more often than not.

Without sudo, `io.elementary.appcenter --debug` shows nothing when it freeze. When run with sudo this is what I get:

> sudo io.elementary.appcenter --debug
> ** (process:1925): WARNING **: ComponentValidator.vala:38: Could not get the contents of blacklist file: Failed to open file '/etc/io.elementary.appcenter/appcenter.blacklist': No such file or directory
> [INFO 23:40:46.391943] Application.vala:154: AppCenter version: 0.2.7
> [INFO 23:40:46.391984] Application.vala:156: Kernel version: 4.10.0-38-generic
> [DEBUG 23:40:46.408658] [Gtk] Connecting to session manager
> [DEBUG 23:40:46.423977] Houston.vala:51: Requesting newest applications from https://developer.elementary.io/api/newest/project
> [DEBUG 23:40:46.424127] Houston.vala:51: Requesting newest applications from https://developer.elementary.io/api/newest/release
> [DEBUG 23:40:46.424167] Houston.vala:51: Requesting newest applications from https://developer.elementary.io/api/newest/downloads
> [DEBUG 23:40:46.428552] Settings.vala:163: Loading settings from schema 'io.elementary.appcenter.settings'
> [DEBUG 23:40:46.428760] [PackageKit] adding state 0x3ca2490
> [DEBUG 23:40:46.428803] [PackageKit] role now get-packages
> [DEBUG 23:40:46.527910] [PackageKit] notify::connected
> [DEBUG 23:40:46.555426] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:46.952473] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:46.952517] [PackageKit] remove state 0x3ca2490
> [DEBUG 23:40:47.306361] [PackageKit] adding state 0x7f60dc017840
> [DEBUG 23:40:47.306393] [PackageKit] role now search-name
> [DEBUG 23:40:47.306605] [PackageKit] adding state 0x7f60dc017e40
> [DEBUG 23:40:47.306639] [PackageKit] role now search-name
> [DEBUG 23:40:47.315463] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:47.315498] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:47.585154] [PackageKit] remove state 0x7f60dc017e40
> [DEBUG 23:40:47.585198] [PackageKit] adding state 0x7f60dc017f00
> [DEBUG 23:40:47.585214] [PackageKit] role now get-details
> [DEBUG 23:40:47.585324] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:47.593099] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:47.716397] [PackageKit] adding state 0x7f60d4004480
> [DEBUG 23:40:47.716425] [PackageKit] role now search-name
> [DEBUG 23:40:47.724694] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:47.916982] [PackageKit] remove state 0x7f60dc017840
> [DEBUG 23:40:47.917038] [PackageKit] adding state 0x7f60dc017900
> [DEBUG 23:40:47.917066] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:47.917096] [PackageKit] role now get-details
> [DEBUG 23:40:47.926014] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:48.143251] [PackageKit] remove state 0x7f60dc017f00
> [DEBUG 23:40:48.143833] [PackageKit] adding state 0x7f60d4004000
> [DEBUG 23:40:48.143852] [PackageKit] role now search-name
> [DEBUG 23:40:48.143987] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:48.150889] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:48.457128] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:48.457167] [PackageKit] remove state 0x7f60d4004480
> [DEBUG 23:40:48.457205] [PackageKit] adding state 0x7f60d4004540
> [DEBUG 23:40:48.457220] [PackageKit] role now get-details
> [DEBUG 23:40:48.466763] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:48.687110] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:48.687167] [PackageKit] remove state 0x7f60dc017900
> [DEBUG 23:40:48.687507] [PackageKit] adding state 0x7f60dc0179c0
> [DEBUG 23:40:48.687526] [PackageKit] role now search-name
> [DEBUG 23:40:48.695122] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:48.951717] [PackageKit] remove state 0x7f60d4004000
> [DEBUG 23:40:48.951759] [PackageKit] adding state 0x7f60d40040c0
> [DEBUG 23:40:48.951779] [PackageKit] role now get-details
> [DEBUG 23:40:48.951927] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:48.958532] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:49.170658] [PackageKit] remove state 0x7f60d4004540
> [DEBUG 23:40:49.170793] [PackageKit] adding state 0x7f60d4004600
> [DEBUG 23:40:49.170816] [PackageKit] role now search-name
> [DEBUG 23:40:49.170869] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:49.179749] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:49.448762] [PackageKit] remove state 0x7f60dc0179c0
> [DEBUG 23:40:49.448809] [PackageKit] adding state 0x7f60dc017a80
> [DEBUG 23:40:49.448832] [PackageKit] role now get-details
> [DEBUG 23:40:49.448861] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:49.455364] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:49.665059] [PackageKit] remove state 0x7f60d40040c0
> [DEBUG 23:40:49.665636] [PackageKit] adding state 0x7f60d4004180
> [DEBUG 23:40:49.665662] [PackageKit] role now search-name
> [DEBUG 23:40:49.665939] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:49.671669] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:49.924919] [PackageKit] remove state 0x7f60d4004600
> [DEBUG 23:40:49.924972] [PackageKit] adding state 0x7f60d40046c0
> [DEBUG 23:40:49.925013] [PackageKit] role now get-details
> [DEBUG 23:40:49.925064] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:49.935509] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:50.051532] [PackageKit] adding state 0x7f60d8004b20
> [DEBUG 23:40:50.051558] [PackageKit] role now search-name
> [DEBUG 23:40:50.061627] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:50.176732] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:50.176889] [PackageKit] remove state 0x7f60dc017a80
> [DEBUG 23:40:50.178126] [PackageKit] adding state 0x7f60dc017b40
> [DEBUG 23:40:50.178172] [PackageKit] role now search-name
> [DEBUG 23:40:50.185016] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:50.435307] [PackageKit] remove state 0x7f60d4004180
> [DEBUG 23:40:50.435346] [PackageKit] adding state 0x7f60d4004240
> [DEBUG 23:40:50.435360] [PackageKit] role now get-details
> [DEBUG 23:40:50.435459] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:50.442635] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:50.651816] [PackageKit] remove state 0x7f60d40046c0
> [DEBUG 23:40:50.651871] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:50.652346] [PackageKit] adding state 0x7f60d8004820
> [DEBUG 23:40:50.652367] [PackageKit] role now search-name
> [DEBUG 23:40:50.659495] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:50.912412] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:50.912529] [PackageKit] remove state 0x7f60d8004b20
> [DEBUG 23:40:50.912574] [PackageKit] adding state 0x7f60d8004be0
> [DEBUG 23:40:50.912592] [PackageKit] role now get-details
> [DEBUG 23:40:50.919366] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:51.166752] [PackageKit] remove state 0x7f60dc017b40
> [DEBUG 23:40:51.166791] [PackageKit] adding state 0x7f60dc017c00
> [DEBUG 23:40:51.166805] [PackageKit] role now get-details
> [DEBUG 23:40:51.166904] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:51.173572] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:51.385907] [PackageKit] remove state 0x7f60d4004240
> [DEBUG 23:40:51.386761] [PackageKit] adding state 0x7f60d4004300
> [DEBUG 23:40:51.386785] [PackageKit] role now search-name
> [DEBUG 23:40:51.386952] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:51.638583] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:51.677921] [PackageKit] remove state 0x7f60d8004820
> [DEBUG 23:40:51.677961] [PackageKit] adding state 0x7f60d80048e0
> [DEBUG 23:40:51.677978] [PackageKit] role now get-details
> [DEBUG 23:40:51.678132] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:51.686080] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:51.899010] [PackageKit] remove state 0x7f60d8004be0
> [DEBUG 23:40:51.902803] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:52.123427] [PackageKit] remove state 0x7f60dc017c00
> [DEBUG 23:40:52.123584] [PackageKit] adding state 0x7f60dc017cc0
> [DEBUG 23:40:52.123611] [PackageKit] role now search-name
> [DEBUG 23:40:52.123704] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:52.134457] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:52.390392] [PackageKit] remove state 0x7f60d4004300
> [DEBUG 23:40:52.390440] [PackageKit] adding state 0x7f60d40043c0
> [DEBUG 23:40:52.390458] [PackageKit] role now get-details
> [DEBUG 23:40:52.390530] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:52.398221] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:52.617051] [PackageKit] remove state 0x7f60d80048e0
> [DEBUG 23:40:52.617680] [PackageKit] adding state 0x7f60d80049a0
> [DEBUG 23:40:52.617708] [PackageKit] role now search-name
> [DEBUG 23:40:52.617888] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:52.624727] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:52.880662] [PackageKit] remove state 0x7f60dc017cc0
> [DEBUG 23:40:52.880713] [PackageKit] adding state 0x7f60dc017d80
> [DEBUG 23:40:52.880740] [PackageKit] role now get-details
> [DEBUG 23:40:52.880877] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:52.888522] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:53.097402] [PackageKit] remove state 0x7f60d40043c0
> [DEBUG 23:40:53.097852] [PackageKit] adding state 0x7f60d40043c0
> [DEBUG 23:40:53.097874] [PackageKit] role now search-name
> [DEBUG 23:40:53.098000] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:53.104494] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:53.361979] [PackageKit] remove state 0x7f60d80049a0
> [DEBUG 23:40:53.362019] [PackageKit] adding state 0x7f60d8004a60
> [DEBUG 23:40:53.362033] [PackageKit] role now get-details
> [DEBUG 23:40:53.362236] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:53.369201] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:53.578389] [PackageKit] remove state 0x7f60dc017d80
> [DEBUG 23:40:53.578573] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:53.579067] [PackageKit] adding state 0x7f60dc017d80
> [DEBUG 23:40:53.579095] [PackageKit] role now search-name
> [DEBUG 23:40:53.585812] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:53.846425] [PackageKit] remove state 0x7f60d40043c0
> [DEBUG 23:40:53.846480] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:53.846538] [PackageKit] adding state 0x7f60d4004300
> [DEBUG 23:40:53.846559] [PackageKit] role now get-details
> [DEBUG 23:40:53.854043] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:54.064861] [PackageKit] remove state 0x7f60d8004a60
> [DEBUG 23:40:54.064903] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:54.065342] [PackageKit] adding state 0x7f60d8004a60
> [DEBUG 23:40:54.065364] [PackageKit] role now search-name
> [DEBUG 23:40:54.072947] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:54.323702] [PackageKit] remove state 0x7f60dc017d80
> [DEBUG 23:40:54.323739] [PackageKit] adding state 0x7f60dc017cc0
> [DEBUG 23:40:54.323754] [PackageKit] role now get-details
> [DEBUG 23:40:54.323861] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:54.331304] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:54.541322] [PackageKit] remove state 0x7f60d4004300
> [DEBUG 23:40:54.542253] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:54.813037] [PackageKit] remove state 0x7f60d8004a60
> [DEBUG 23:40:54.813079] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:54.813104] [PackageKit] adding state 0x7f60d80049a0
> [DEBUG 23:40:54.813125] [PackageKit] role now get-details
> [DEBUG 23:40:54.820410] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:55.034879] [PackageKit] remove state 0x7f60dc017cc0
> [DEBUG 23:40:55.035002] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:55.040953] Client.vala:547: update cache called false
> [DEBUG 23:40:55.040978] Client.vala:573: New refresh task
> [DEBUG 23:40:55.041271] [PackageKit] adding state 0x3ca2490
> [DEBUG 23:40:55.041294] [PackageKit] role now refresh-cache
> [DEBUG 23:40:55.057566] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:55.256244] [PackageKit] remove state 0x7f60d80049a0
> [DEBUG 23:40:55.256400] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:56.015504] [PackageKit] remove state 0x3ca2490
> [DEBUG 23:40:56.015597] [PackageKit] adding state 0x3ca2490
> [DEBUG 23:40:56.015622] [PackageKit] role now get-updates
> [DEBUG 23:40:56.016928] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:56.030437] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:56.110391] [PackageKit] emit updates-changed
> [DEBUG 23:40:56.118546] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:57.243935] [PackageKit] remove state 0x3ca2490
> [DEBUG 23:40:57.243981] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:57.932038] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:57.942863] [PackageKit] emit transaction-list-changed
> [DEBUG 23:40:58.019124] [PackageKit] emit updates-changed
> [DEBUG 23:40:58.188003] [PackageKit] emit updates-changed
> [DEBUG 23:40:59.156838] [PackageKit] emit transaction-list-changed
> [DEBUG 23:41:06.007455] AppInfoView.vala:465: Operation not supported
> [DEBUG 23:41:06.007759] AppInfoView.vala:465: Operation not supported
> [DEBUG 23:41:06.007982] AppInfoView.vala:465: Operation not supported
> [DEBUG 23:41:06.008259] AppInfoView.vala:465: Operation not supported
> This is where it freeze

**Comment by mmstick** [comment]
This can be closed.
