### ISSUE TITLE
Share toast stays active until closed manually

### ISSUE THREAD

**Issue by btkostner** [elementary/appcenter#341]
I looked at the granite code and there was nothing about a timeout there, so I'm assuming it's left up to the application to impliment it's own timeout.

## What happens
Right now the share button in the app view copies text to the clipboard and activates a toast that reads "Link copied to clipboard". The toast stays active until I manually click the close button.

## What I expect to happen
The toast shows up when I click the share button, but after a short bit (10 seconds?) it automatically closes.

**Comment by danrabbit** [comment]
I'm going to mark this as blocked because I think if we want to add a duration we should do that in Granite so that it's consistent across apps

**Comment by danrabbit** [comment]
Gonna close here since there's a proposed fix in Granite
