### ISSUE TITLE
AppCenter said no connection while the computer has connection

### ISSUE THREAD

**Issue by kvdz** [elementary/appcenter#342]
see attachment.

it saids there is no connection while the image shows i have wifi connection and the speed test shows it had a relative good wifi connection in speed. 

![screenshot from 2017-06-24 18-11-33](https://user-images.githubusercontent.com/4341214/27510017-01074918-5909-11e7-9b86-0eada41952fe.png)

**Comment by kvdz** [comment]
this restricts  any user for using it, a reboot doesn't solve it.  so it has to do with the connection detection of appcenter. i have a clean installation of 0.4.1

**Comment by kvdz** [comment]
here is the debug output off appcenter:

[INFO 13:30:04.107829] Application.vala:153: App Center version: 0.2.3
[INFO 13:30:04.107871] Application.vala:155: Kernel version: 4.4.0-81-generic
[WARNING 13:30:04.120971] [Gtk] Theme parsing error: gtk-widgets.css:2049:14: 'min-height' is not a valid property name
[WARNING 13:30:04.121024] [Gtk] Theme parsing error: gtk-widgets.css:2050:13: 'min-width' is not a valid property name
[WARNING 13:30:04.121078] [Gtk] Theme parsing error: gtk-widgets.css:2055:13: 'min-width' is not a valid property name
[WARNING 13:30:04.121428] [Gtk] Theme parsing error: gtk-widgets.css:2265:14: 'min-height' is not a valid property name
[WARNING 13:30:04.121467] [Gtk] Theme parsing error: gtk-widgets.css:2266:13: 'min-width' is not a valid property name
kay@kay-N55SF:~/Documents/elementary/project/wingpanel-indicator-power/build$ appcenter -d
[INFO 13:30:15.781796] Application.vala:153: App Center version: 0.2.3
[INFO 13:30:15.781836] Application.vala:155: Kernel version: 4.4.0-81-generic
[WARNING 13:30:15.799485] [Gtk] Theme parsing error: gtk-widgets.css:2049:14: 'min-height' is not a valid property name
[WARNING 13:30:15.799552] [Gtk] Theme parsing error: gtk-widgets.css:2050:13: 'min-width' is not a valid property name
[WARNING 13:30:15.799631] [Gtk] Theme parsing error: gtk-widgets.css:2055:13: 'min-width' is not a valid property name
[WARNING 13:30:15.800004] [Gtk] Theme parsing error: gtk-widgets.css:2265:14: 'min-height' is not a valid property name
[WARNING 13:30:15.800061] [Gtk] Theme parsing error: gtk-widgets.css:2266:13: 'min-width' is not a valid property name
[DEBUG 13:30:15.822466] [Gtk] Connecting to session manager
[DEBUG 13:30:15.852041] Houston.vala:51: Requesting newest applications from https://developer.elementary.io/api/newest/project
[DEBUG 13:30:15.852923] Houston.vala:51: Requesting newest applications from https://developer.elementary.io/api/newest/release
[DEBUG 13:30:15.853223] Houston.vala:51: Requesting newest applications from https://developer.elementary.io/api/newest/downloads
[DEBUG 13:30:15.865734] Settings.vala:163: Loading settings from schema 'io.elementary.appcenter.settings'
[DEBUG 13:30:15.866182] [PackageKit] adding state 0x34273f0
[DEBUG 13:30:15.866269] [PackageKit] role now get-packages
[DEBUG 13:30:16.043650] [PackageKit] notify::connected
[DEBUG 13:30:16.065893] [PackageKit] emit transaction-list-changed
[DEBUG 13:30:16.563688] Client.vala:513: update cache called false
[DEBUG 13:30:16.702366] [PackageKit] emit transaction-list-changed
[DEBUG 13:30:16.702427] [PackageKit] remove state 0x34273f0
[DEBUG 13:30:23.407365] [PackageKit] adding state 0x7f49ac002810
[DEBUG 13:30:23.407502] [PackageKit] role now search-name
[DEBUG 13:30:23.414965] [PackageKit] emit transaction-list-changed
[DEBUG 13:30:23.873190] [PackageKit] remove state 0x7f49ac002810
[DEBUG 13:30:23.873253] [PackageKit] emit transaction-list-changed
[DEBUG 13:30:23.873312] [PackageKit] adding state 0x7f49ac0028d0
[DEBUG 13:30:23.873347] [PackageKit] role now get-details
[DEBUG 13:30:23.880678] [PackageKit] emit transaction-list-changed
[DEBUG 13:30:24.269538] [PackageKit] remove state 0x7f49ac0028d0
[DEBUG 13:30:24.269601] [PackageKit] emit transaction-list-changed
[DEBUG 13:30:24.269864] [PackageKit] adding state 0x7f49ac002990
[DEBUG 13:30:24.269936] [PackageKit] role now search-name
[DEBUG 13:30:24.277390] [PackageKit] emit transaction-list-changed
[DEBUG 13:30:24.733923] [PackageKit] remove state 0x7f49ac002990
[DEBUG 13:30:24.734055] [PackageKit] emit transaction-list-changed
[DEBUG 13:30:24.734104] [PackageKit] adding state 0x7f49ac002a50
[DEBUG 13:30:24.734148] [PackageKit] role now get-details
[DEBUG 13:30:24.743359] [PackageKit] emit transaction-list-changed
[DEBUG 13:30:25.109943] [PackageKit] remove state 0x7f49ac002a50
[DEBUG 13:30:25.110006] [PackageKit] emit transaction-list-changed
[DEBUG 13:30:25.110149] [PackageKit] adding state 0x7f49ac002b10
[DEBUG 13:30:25.110182] [PackageKit] role now search-name
[DEBUG 13:30:25.119295] [PackageKit] emit transaction-list-changed
[DEBUG 13:30:25.574327] [PackageKit] emit transaction-list-changed
[DEBUG 13:30:25.574459] [PackageKit] remove state 0x7f49ac002b10
[DEBUG 13:30:25.574562] [PackageKit] adding state 0x7f49ac002bd0
[DEBUG 13:30:25.574594] [PackageKit] role now get-details
[DEBUG 13:30:25.582716] [PackageKit] emit transaction-list-changed
[DEBUG 13:30:25.948468] [PackageKit] emit transaction-list-changed
[DEBUG 13:30:25.948742] [PackageKit] remove state 0x7f49ac002bd0
[DEBUG 13:30:25.948966] [PackageKit] adding state 0x7f49ac002c90
[DEBUG 13:30:25.948999] [PackageKit] role now search-name
[DEBUG 13:30:25.957935] [PackageKit] emit transaction-list-changed
[DEBUG 13:30:26.408085] [PackageKit] remove state 0x7f49ac002c90
[DEBUG 13:30:26.408349] [PackageKit] emit transaction-list-changed
[DEBUG 13:30:26.408450] [PackageKit] adding state 0x7f49ac002d50
[DEBUG 13:30:26.408497] [PackageKit] role now get-details
[DEBUG 13:30:26.416510] [PackageKit] emit transaction-list-changed
[DEBUG 13:30:26.785560] [PackageKit] remove state 0x7f49ac002d50
[DEBUG 13:30:26.785764] [PackageKit] emit transaction-list-changed

**Comment by donadigo** [comment]
Looks like we should use `can_reach_async` in `NetworkManager` rather than `network_available`.

**Comment by DDieter** [comment]
@kvdz Does this still happen for you? I can't reproduce the issue so maybe it only happens in some specific case.

**Comment by keyxmakerx** [comment]
I still have this issue. :/

**Comment by keyxmakerx** [comment]
Has there been any progress with this issue? I'm willing to help out as much as I can, but the issue is still ongoing for me. At this time, I can't find the reason for the issue other then it may have something to do with multiple NIC's.

**Comment by DDieter** [comment]
Unfortunately not because the issue is hard to reproduce as it only happens with some specific configuration.

Have you been able to update appcenter and other apps with the command line? If not could you open the terminal and run `sudo apt update && sudo apt upgrade` and see if this possibly fixes the issue.

Could you open the sharing plug in switchboard to check if the same issue occurs there?

What is your network configuration? Hardware? Wifi, ethernet and/or VPN?

**Comment by danrabbit** [comment]
This StackExchange question leads me to believe this is actually a problem in Network Manager which would make it "Invalid" for AppCenter: https://elementaryos.stackexchange.com/questions/12099/no-internet-connection-within-appcenter

**Comment by mmstick** [comment]
Why bother with an implementation detail like NetworkManager, anyway? Should be able to just ping a server to know whether you have a connection to it or not.

**Comment by kvdz** [comment]
@danrabbit  it doesn't matter i reset/reboot it happend every time! that made me believe it was not the networkmanager.

**Comment by cassidyjames** [comment]
Since we now allow browsing and everything without a network connection, this should no longer be an issue.
