### ISSUE TITLE
Apps from elementary PPA should be marked as curated

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#351]
our default apps from our PPA should appear under the curated section

**Comment by danrabbit** [comment]
It looks like daily repo apps report their origin as `daily-xenial-main`. I'm gonna guess `stable-xenial-main` works for stable channel. It's worth testing.

Another alternative is that we somehow get this data built into the appcenter repo instead. Pinging @btkostner to see how likely that could be.

**Comment by zeebok** [comment]
I just tried having it place apps from `stable-xenial-main` with the other curated apps, and it does work.
