### ISSUE TITLE
Fallback cyrillic fonts

### ISSUE THREAD

**Issue by png2378** [elementary/appcenter#352]
We need fallback cyrillic fonts for HVD Bodedo and Limelight.

My suggestion is [Pangolin](https://fonts.google.com/specimen/Pangolin) for HVD Bodedo (Open Font License) and [20DB](https://www.fontsquirrel.com/fonts/20-db) for Limelight ([free](http://www.typetype.ru/faq/) for commercial use).

**Comment by danirabbit** [comment]
Closing as duplicate on #736 since that has a screenshot
