### ISSUE TITLE
Clear search using navigation buttons

### ISSUE THREAD

**Issue by ThisisDaan** [elementary/appcenter#359]
I thought it was a bit confusing that when you try to search for something it doesn't show a back button or add an extra tab like (Home | Updates | Search)

To be able to get back to the home or updates page you have to clear your search.
![example](https://user-images.githubusercontent.com/29415341/27618426-5265e15e-5bb4-11e7-9e72-5253a91a0b06.png)

**Comment by cassidyjames** [comment]
I agree, I came here to file this just now. :smile: I always aim for the non-existent back button to go back from a search.

**Comment by dar5hak** [comment]
Taking this up.
