### ISSUE TITLE
Screenshot carousel dots are not easily discoverable as click targets

### ISSUE THREAD

**Issue by dahenson** [elementary/appcenter#365]
Warning:
Possible opinion ahead. Proceed with caution.

The screenshot carousel is an awesome idea, but it took me a while to realize that I could click on the dots below the screenshot to see other screenshots. In my opinion, dots are a decent indicator on a touch interface where horizontal swiping is an acceptible gesture, but it doesn't fly for a mouse-driven interface.

I propose adding some arrows that are more obvious as click targets to cycle the screenshot, especially if that carousel is not going to change on a timer like the front page banner.

**Comment by cassidyjames** [comment]
I agree that just the dots is not ideal. On a laptop a horizontal scroll might work fine, but I'm not sure if that's technically feasible. I'd be open to left/right arrows.

**Comment by linuxr01** [comment]
Please add left an right arrows like mac os
<img width="916" alt="Bildschirmfoto 2019-07-07 um 09 47 38" src="https://user-images.githubusercontent.com/49744994/60765561-bf84bb00-a09c-11e9-9aed-eb2898186f1e.png">
<img width="891" alt="Bildschirmfoto 2019-07-07 um 09 47 55" src="https://user-images.githubusercontent.com/49744994/60765563-c4496f00-a09c-11e9-962d-ab781fac5879.png">
