### ISSUE TITLE
Cover SPDX licenses

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#366]
According to the [AppStream spec](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-metadata_license), valid `<metadata_license />`s correspond to the licenses listed at [spdx.org/licenses](https://spdx.org/licenses/). We should consider adding those licenses and their corresponding license links to the license logic in AppCenter.

**Comment by danrabbit** [comment]
While the SPDX list is super comprehensive, I really prefer something like chooosealicense because it gives a nice easy summary and helps you understand the license.

What do you think about continuing to link to choosealicense for common licenses and then falling back to SPDX for other licenses?

**Comment by Conan-Kudo** [comment]
Insofar as getting simple understandings of licenses, I'd suggest [TLDRLegal](https://tldrlegal.com/) (which is being used by GitHub as well!), but full license texts should definitely come from SPDX.

**Comment by danirabbit** [comment]
Fixed in #2151 we're getting this from AppStream now
