### ISSUE TITLE
Maximize does not fill screen on Wayland

### ISSUE THREAD

**Issue by ryanleesipes** [elementary/appcenter#367]
I'm not sure why this behavior is happening, but maximizing the window does not fill the screen. I am using Wayland, so perhaps that is the problem. But all other elementary OS apps seem to be fine. Tried on multiple resolutions (3k, 1080, 1050) - still only takes up three-quarters of the screen - neglecting the right-hand side.

![screenshot from 2017-06-29 11-28-35](https://user-images.githubusercontent.com/2141621/27701554-6fa3a6b0-5cbe-11e7-98c9-e8c7f1a89031.png)

**Comment by cassidyjames** [comment]
Can't reproduce here, but I'm on X. You might be right in that it's Wayland-related.

**Comment by cassidyjames** [comment]
Tested in a Wayland session and can reproduce. Not sure if it's Wayland, GNOME Shell, or Mutter's fault, but it's being restricted to the window's max size while appearing to attempt to maximize.

**Comment by cassidyjames** [comment]
All that said, I do think the max size setting on AppCenter is bizarre when we still allow maximizing, so I would be in favor or removing that.
