### ISSUE TITLE
Cannot redirect to an app when in Updates view

### ISSUE THREAD

**Issue by donadigo** [elementary/appcenter#369]
Steps to reproduce:

1. Open AppCenter
2. Switch to updates tab
3. Open a link in a web browser like https://appcenter.elementary.io/com.github.ronnydo.colorpicker.desktop
3. Hit "open"
- AppCenter doesn't show any app

In addition to that, you can hit "Homepage" button. This will not switch anywhere, but it will show you a the stack switcher. When you hit "Homepage" button in the switcher again, the app will show but without the back button so you can't go back to homepage.

**Comment by danrabbit** [comment]
Oh god
