### ISSUE TITLE
Twitter Share Dialogue should have a hashtag

### ISSUE THREAD

**Issue by bigfatbird** [elementary/appcenter#384]
Many people use hashtgags on twitter for greater discoverability or to mute some noisy topics.

It should have a hashtag when you share something from AppCenter..

Bonus: AppCenter should reference its own or the elementary LLC twitter account maybe!

**Comment by danrabbit** [comment]
Wanna make a note that we should do this in a service-agnostic way, which means we should add a tag property to the share popover API and not just hardcode into the Twitter URI string.

**Comment by danirabbit** [comment]
Closing since we removed the share widget
