### ISSUE TITLE
Paid apps show price instead of update button on the app page when update is available

### ISSUE THREAD

**Issue by nloomans** [elementary/appcenter#385]
### Update Screen
![Update Screen](https://user-images.githubusercontent.com/7829481/27841096-cb11535a-60fe-11e7-9f29-d09c093f1b5c.png)
### App Screen
![App Screen](https://user-images.githubusercontent.com/7829481/27841100-cf811ab0-60fe-11e7-865c-04fa3c8a2101.png)

**Comment by danrabbit** [comment]
OP can you still reproduce this issue after updating to latest? I am not experiencing this

**Comment by nloomans** [comment]
Sorry but I do not run Elementary OS any more (nothing personal, it's just that I distro hop at least every 3 months.) So I am unable to check if I'm able to reproduce this...

**Comment by davidmhewitt** [comment]
I'm cleaning up the issue tracker and we haven't had any recent reports of things like this, so I'll assume this is fixed and close the issue.
