### ISSUE TITLE
Add an elementary-apps specific category

### ISSUE THREAD

**Issue by aggalex** [elementary/appcenter#386]
I like elementary apps, and in my system I prefer to use these instead of normal gtk 2 or lower or without CSD apps. But it's always a pain to seek and find the right apps. To solve this, I would suggest making an elementary-specific category for elementary apps to sit in, along with their respective categories they already are in.

**Comment by danrabbit** [comment]
This a “won’t fix”. We’ll be progressively demoting non-curated apps instead

**Comment by aggalex** [comment]
A very good way to demote non-curated apps is to make a curated apps category. After all, that's where I'd head all the time
