### ISSUE TITLE
Installation queue UI

### ISSUE THREAD

**Issue by ghost** [elementary/appcenter#387]
Hey!
Can you guys add an installation queue where it says "Hey, these apps are installing" instead of having to click around to find the status of each app.
‪Thanks, Ben

**Comment by lewisgoddard** [comment]
I don't see why these shouldn't be listed in the updates section, it's a similar process. Most of the logic should already be there.

**Comment by aggalex** [comment]
There is a spinner spinning up in the header bar, you could make it be a button for a popup with the installing app's name, icon and a progress bar indicating the installation progress. Clicking on the app's name or icon could also redirect you to the app's appcenter page

**Comment by Omerntosi** [comment]
Yeah, I'd really like to see this

**Comment by megatux** [comment]
My two cents here. The location of the "progress indicator spin" is bad. Next to the search bar seems to be an indicator of a "search in progress" and not something totally unrelated, like an internal background operation. A Job queue UI could fix this but in the mean time I would like to see the spin elsewhere.

**Comment by cassidyjames** [comment]
I think this could also be solved/mitigated by #624

**Comment by cassidyjames** [comment]
Closing in favor of #264. It's simpler, isn't introducing new UI, and seems to be how others expected it to work anyway.
