### ISSUE TITLE
Badge notification in Plank isn't removed after updating

### ISSUE THREAD

**Issue by Smaloki** [elementary/appcenter#390]
After running updates, the badge displaying the amount of updates available is not updated/removed. Appears to affect only the icon in Plank, not in Slingshot. Seems as though this issue can only be fixed by restarting Plank entirely. As far as I'm aware, it started occurring after version 0.2.4 was released.

![screenshot from 2017-07-07 20-05-06](https://user-images.githubusercontent.com/20471287/27970754-300289e8-6350-11e7-875d-3922a62d0bd6.png)

**Comment by cassidyjames** [comment]
I've noticed this lately as well.

**Comment by drakofrost** [comment]
I was about to open the same bug report, whenever there's an update, the app center gets stuck in the dock, even though it's not pinned. The bubble with the number of updates also remains, even though the updates are already installed.

Pinning and unpinning the app center makes the icon go away, but it's annoying.

**Comment by Aberrantfox** [comment]
I get the same issue on latest

**Comment by Warkanlock** [comment]
same issue here. Any news?
