### ISSUE TITLE
Add Telegram share

### ISSUE THREAD

**Issue by png2378** [elementary/appcenter#392]
Because it's a hottest messaging app.

**Comment by artemanufrij** [comment]
I confirm with @png2378. it's my favorite desktop/mobile messenger

**Comment by leonardo-lemos** [comment]
+1 on this. It's the most used messaging app in Russia, and it's used around the world.

**Comment by danrabbit** [comment]
Please don’t make “me too” comments. Use reactions to cut down on email and notifications

**Comment by danrabbit** [comment]
Looks like Telegram does offer share URLs like [`https://t.me/share/url?url=`](https://telegram.wiki/general/websharing)

Assigning to @snwh for an icon :)
