### ISSUE TITLE
Add tooltip to loading spinner

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#394]
It might not be clear what exactly is loading when the spinner in the headerbar is going. We could reveal some more information as a tooltip for those curious.

**Comment by cassidyjames** [comment]
All we have a concept of right now is "working" or not. Is it worth adding a single tooltip, or should we add multiple states (i.e. "Loading trending apps", "Checking for updates", etc.)?

**Comment by megatux** [comment]
Also the position of the spinner so close to the search input makes it more confused of its real meaning.

**Comment by megatux** [comment]
"Loading trending apps", "Checking for updates", etc, sound good to me. Are these fetching processes made in serial or parallel ?
