### ISSUE TITLE
More descriptive subtitle in payment dialog

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#395]
Right now the payment dialog just lists:

>**AppCenter**
>App Name

We could provide some more detail here and make this look a little nicer while we're at it. At the very least, we could reiterate the chosen payment amount, and add _what_ the user is doing to the app name. i.e.:

>**AppCenter**
>Pay **$5** for App Name

**Comment by danrabbit** [comment]
Yeah we originally based this directly off the stripe dialog. It would probably be better to make it follow our HIG for dialogs

**Comment by cassidyjames** [comment]
@danrabbit oh yeah that's... duh. In this case, the primary text could be "Pay $5 for App Name", then what do we want to do for a secondary label?

**Comment by cassidyjames** [comment]
Doing something more HIG-compliant like:

>**Pay $5 for AppName**
>This is a one time payment. Your email address is only used to send you a receipt.
