### ISSUE TITLE
"by [author]" in app description isnt transable

### ISSUE THREAD

**Issue by snowparrot** [elementary/appcenter#399]
(DISCLAIMER: I am a German native speak but I just learn Polish. Therefore there might be errors in the Polish part)

Translating the "by" in the app description leads to various problems at least in Polish and German. I will give some explains below but generally speaking there isnt one translation for "by" or even author must change due to grammar. Worth noting I just know German and Polish as an example but highly likely there are more languages.

The German translation in the app center is "von". Though it is right in terms of names ("von Benjamin Müller") if we take "SuSe GmbH" (GmbH is a company but I dont know the American equivalent) you have to use "von der SuSe GmbH" for "by Suse GmbH". If the author calls themself "Team GIMP" the right translation is "vom Team GIMP".

The Polish translation in the app center is "od". But after "od" noun have to change. Take the non-elementary connected polish name "Adam Bieńkowski" then it will change into "od Adama Bieńkowskiego".

**Comment by cassidyjames** [comment]
That's a great point! I would be fine just dropping the “by” personally; it's fairly common practice to have an app name followed by the developer; both the Google Play Store and iOS App Store list the developer directly beneath the app name.

**Comment by cassidyjames** [comment]
Thanks for the report @snowparrot. We've merged a fix in (just removing the "by") and it will likely be released with the next stable release of AppCenter.
