### ISSUE TITLE
Add Vkontakte share

### ISSUE THREAD

**Issue by ignishub** [elementary/appcenter#406]
https://vk.com/dev/widget_share

**Comment by png2378** [comment]
I don't think that this is necessary, because VK doesn't have popularity outside the CIS.

**Comment by viktor-vasilev** [comment]
Its not that necessary - true. But we can make sub menu or sumethig like that with other optional sharing options. Just becouse its not popular outside CIS it doesnt mean that we dont want to share and spread the popelarity of elementary and linux

**Comment by Philip-Scott** [comment]
I also agree with @png2378, sadly, we can't possibly add all social networks out there. There's always the copy link button you can use which doesn't depend on any platform :)
 
![screenshot from 2017-07-19 19 18 37](https://user-images.githubusercontent.com/10786508/28395080-17674f7a-6cb7-11e7-8fa9-4465de0ad754.png)

**Comment by danrabbit** [comment]
Just gonna leave a comment that it might be an opportunity to integrate some kind of locale detection into this widget. I think we’ll want to do the same for CJK social networks also. If we can be smart about showing these networks I think it could be useful for l10n

**Comment by tintou** [comment]
Well, once the Online Accounts integration will be available only configured accounts might show there…

**Comment by danirabbit** [comment]
Closing since we removed this share widget
