### ISSUE TITLE
"Update All" silently update not listed packages

### ISSUE THREAD

**Issue by williamledoux** [elementary/appcenter#413]
Today my upgradable package were
```
wildo@willdo-server:/configs/wildo$ apt list --upgradable
elementary-tweaks/xenial
gitlab-ce/xenial
google-chrome-stable/stable
imagemagick/xenial-updates,xenial-security
imagemagick-6.q16/xenial-updates,xenial-security
imagemagick-common/xenial-updates,xenial-updates,xenial-security,xenial-security
libmagickcore-6.q16-2/xenial-updates,xenial-security
libmagickcore-6.q16-2-extra/xenial-updates,xenial-security
libmagickwand-6.q16-2/xenial-updates,xenial-security
libruby2.3/xenial-updates,xenial-security
linux-libc-dev/xenial-updates,xenial-security
ruby2.3/xenial-updates,xenial-security
xserver-common/xenial-updates,xenial-updates,xenial-security,xenial-security
xserver-xorg-core-hwe-16.04/xenial-updates,xenial-security
```

But in the AppCenter I only see "Operating System Updates" and "ImageMagick" (twice, but there is an issue for it already). So, if I choose "Update All", I expect that all listed packages will update, but not packages that were not listed.

When I did it, though, google chrome and gitlab were updated, and they are clearly nor falling under operating system nor image magick in my opinion.

So the questions are:

1. Why did gitlab and chrome did not show up in the list ?
2. Why were they updated while not listed ?

More generally, all 'not app' packages seems to be hidden in AppCenter, for instance if I search for "mongodb" I get no result but I get some with apt command. 
With the previous software center, I could both use it as an app center and as a true package manager.
Now I can only do properly half of the job with AppCenter and must use the terminal for all the less casual stuff, so I end up not using AppCenter at all..

**Comment by lewisgoddard** [comment]
GitLab and Chrome don't show in the list because AppCenter has no listing for them, as they are not distributed via AppCenter. If something isn't listed in AppCenter as an actual listing (like Google Chrome or GitLab) then they will fall under "Operating System Updates", which just works as a catch all for any non-appcenter packages.

**Comment by davidmhewitt** [comment]
Further to this, when you accept the "Operating System Updates", it is the equivalent of performing an update on all installed packages that are not separately listed.

If you wish to keep specific versions of packages for some reason, I believe you should be able to mark certain packages as held with the `sudo apt-mark hold <package-name>` command.

**Comment by williamledoux** [comment]
Thanks for the clarifications. 
It make me think that "Other System Updates" instead of "Operating System Updates" would be closer to what will actually happen.

Personally, I like to see the list of all updated packages so I'll stick with software-monitor.
