### ISSUE TITLE
Problems with Dropbox 

### ISSUE THREAD

**Issue by Mago7891** [elementary/appcenter#414]
I am having some problems with Dropbox. I have installed it but it doesn't open.

There also a bad icon on the top

What can I do ?

![bdhud](https://user-images.githubusercontent.com/14804840/28678645-38514be2-72f1-11e7-921d-c38965c31126.png)

**Comment by leonardo-lemos** [comment]
This isn't an issue related with AppCenter, please, get help using the elementary OS Stack Exchange page: https://elementaryos.stackexchange.com/
