### ISSUE TITLE
Searching for fewer than three alphanumeric characters just returns all apps

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#423]
This can probably be generalized, but searching for certain strings like `()` just returns all apps in AppCenter, with no meaningful search or ordering performed.

**Comment by cassidyjames** [comment]
Also, `""` and `  `. It looks like it performs the search once there are two characters in the search, but only alphanumeric characters are used for the actual filtering.

**Comment by cassidyjames** [comment]
...I take that back. After some further testing, it appears this issue is for _any two characters_. I think by only searching once we hit three characters would probably fix this.

**Comment by cassidyjames** [comment]
More testing: it happens with any search string that contains fewer than three _alphanumeric_ characters.

**Comment by Philip-Scott** [comment]
Soo `Needs Design` i guess? Because it could be weird if you start typing and noting happens...
