### ISSUE TITLE
Icon badge number not cleared after applying updates

### ISSUE THREAD

**Issue by emanchado** [elementary/appcenter#430]
When there are updates available, the AppCenter icon appears automatically with a "badge number" (the number of updates inside a red circle on the top-right). Since a week or two ago (last AppCenter upgrade?) the badge always stays for me. I apply all updates as usual and close AppCenter but the icon stays there in the dock, with the badge number still indicating there are updates (but there aren't anymore, as I have installed them all).

I'm a programmer and familiar with the command-line and whatnot so I can help debug this and do experiments or run custom versions of AppCenter or whatever you need.

**Comment by peteruithoven** [comment]
Duplicate of https://github.com/elementary/appcenter/issues/390?

**Comment by emanchado** [comment]
Bah, sorry. I missed that bug somehow (I guess "Plank" threw me off). I'll assume it's the same thing.
