### ISSUE TITLE
Show optional details for Operating System Updates

### ISSUE THREAD

**Issue by cameralibre** [elementary/appcenter#433]
This is a feature request  - so I'm unsure if it should be posted here or Bountysource, or StackExchange. I couldn't find a clear explanation of where to go on the website. 
I'm happy to post a bounty, but I'm unsure if the lack of this feature is a conscious design decision.

**I would like there to be optional 'details' information for the 'Operating System Updates' catchall in AppCenter.**

I would like to know what I'm updating so that:
- I have a general understanding of the state of development of the programs I'm running
- to find out if some new update of a favorite program has landed
- to know how critical/useful the updates are, if they are likely to affect the performance of my system, and therefore if it is important to update now, or if it can wait. 

Currently I switch to the terminal and check with apt, but I would much prefer to see this information in the AppCenter - it is more convenient, immediate and the information is presented in a structured, visually clear way.

But perhaps showing this information goes against elementary's design approach of simplifying the interface, in which case I guess a bounty wouldn't be welcome. 

Can somebody confirm if this is possible, or if it is a conscious decision not to provide this information?

**Comment by peteruithoven** [comment]
Part of this seems to be covered in the following issue https://github.com/elementary/appcenter/issues/296 ?

**Comment by cassidyjames** [comment]
This seems related to changelogs, but not the same. One way to solve this might be to basically set a "changelog" for the OS updates to a list of packages and versions? That's fairly technical but would be comprehensive.

**Comment by cassidyjames** [comment]
Thoughts from @elementary/ux?

**Comment by danrabbit** [comment]
Yeah there's probably not going to be a good way to get a human-readable changelog for this. I know @davidmhewitt had a branch that did the package list thing at one point.

I think maybe a good middle ground would be showing something generic on the UpdatesListView like "Security & Stability updates. Platform libraries" etc. And then in the appinfoview show a list of packages and versions.

**Comment by harveycabaguio** [comment]
I don't know how feasible it would be but it might be smart if the medium article for the  bigger updates could be embedded to this page.

**Comment by cassidyjames** [comment]
@jackpot51 implemented something like this in the Pop!_Shop fork.

Relevant commits I see:
- https://github.com/system76/pop-shop/commit/8051303927972b16edd41c4d846af28642843002
- https://github.com/system76/pop-shop/commit/56029b79f3cdd5014de5ff04107c05d5d8ec7a0d
- https://github.com/system76/pop-shop/commit/7c31b3d75129fe20a46e3cf1f9a12e60d2b9cc78

**Comment by danrabbit** [comment]
@cassidyjames any reason he didn’t make a PR? :p

**Comment by jackpot51** [comment]
@danrabbit if you are interested I can submit a PR

**Comment by danrabbit** [comment]
@jackpot51 Definitely dude. If we can work together on a single codebase as much as possible I think that would be beneficial for everyone. Let's at least give it a shot ;p

**Comment by jackpot51** [comment]
Cool, I will work on it tomorrow

**Comment by jackpot51** [comment]
Got busy on Friday, taking care of it now.

**Comment by jackpot51** [comment]
I linked this issue from a possible solution, https://github.com/elementary/appcenter/pull/518

**Comment by codygarver** [comment]
Closed via #518. Requests for related changes should be new issues.
