### ISSUE TITLE
Show downloads count

### ISSUE THREAD

**Issue by donadigo** [elementary/appcenter#450]
It would be nice to have a downloads count on the app page, I'm thinking something alike the Android implementation. The number would be rounded to tens, hundreds and so on.

**Comment by danrabbit** [comment]
Do the raw downloads really convey anything? It seems like a number with no context to me. FWIW the iOS appstore shows a ranking for category instead of the raw number.

**Comment by danrabbit** [comment]
Closing this since we never reached a conclusion about what question this data is trying to answer
