### ISSUE TITLE
Show other apps by author

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#451]
![screenshot from 2017-08-11 11 52 23](https://user-images.githubusercontent.com/7277719/29227705-c2e170c0-7e8b-11e7-9157-5c0364e7da9e.png)

I started prototyping this a bit here: https://github.com/elementary/appcenter/tree/apps-by-author

- [x] I think in the interest of keeping the AppInfoView from growing forever it would probably be a good idea to break this out into its own widget that takes an author as a construction argument.

- [x] Something that I think I'd also like to do as a pre-req is to move the function for opening the app page from the homepage into the carousel itself

- [x] We'll need to also handle if there are no other apps by this author

**Comment by ypoz** [comment]
There's a graphical glitch with the horizontal line just on top of this widget, easily reproducible by resizing the window vertically so both of those are off the viewport, then navigating to application view and resizing again, slowly revealing the line and the widget.
