### ISSUE TITLE
Package ID not valid for all AppCenter repo apps

### ISSUE THREAD

**Issue by harisvsulaiman** [elementary/appcenter#460]
This summarizes the issue. Only newer apps are affected.
![image](https://user-images.githubusercontent.com/29329325/29414819-94c9dffe-837e-11e7-947d-a67cd09b9f5a.png)

**Comment by echarrod** [comment]
Why was this closed? What is the solution?

**Comment by TCMiranda** [comment]
Seems that a `sudo apt update` should fix it.

**Comment by hdmjunior** [comment]
I have exactly the same problem and I couldn't report the bug directly through the AppCenter link (watchpad). So I'm here!
