### ISSUE TITLE
Recently updated carousel wraps at 4 items on small screens

### ISSUE THREAD

**Issue by artemanufrij** [elementary/appcenter#462]
![screenshot](https://user-images.githubusercontent.com/16517095/29429836-4bf3d1cc-8392-11e7-814c-83eef8b52b4a.png)

**Comment by cassidyjames** [comment]
It looks like this depends on the length of the strings; here, URM Simulator's author name is pretty long and causing it to wrap.

**Comment by danrabbit** [comment]
Hm I think truncating these names is probably not desirable so maybe the solution is to add these labels to a sizegroup to ensure that we wrap both carousels at the same number of items

**Comment by danrabbit** [comment]
The way this is done was rewritten so things are nicely aligned no matter your window size
