### ISSUE TITLE
appstream - links can't open in firefox

### ISSUE THREAD

**Issue by snowparrot** [elementary/appcenter#463]
(I am fully aware it might not be the fault of the appcenter team. Just leave it as a remark)

Links like appstream://com.github.danrabbit.harvey.desktop can't be opened on firefox. 
Firefox sends the message it can't open the link.

Expected behaviour: Open appcenter.

**Comment by danrabbit** [comment]
Closing as invalid. Please report an issue against Firefox. There's nothing we can do in AppCenter to make Firefox respect system URL handlers
