### ISSUE TITLE
Screenshots are being stretched

### ISSUE THREAD

**Issue by btkostner** [elementary/appcenter#470]
Currently:

![screenshot from 2017-09-06 19 19 04](https://user-images.githubusercontent.com/3385679/30143145-2ac0a3b6-9339-11e7-9865-fd3f65cf27dd.png)

Expected (from [GitHub README](https://github.com/stsdc/monitor)):

![screenshot from 2017-09-06 19 19 13](https://user-images.githubusercontent.com/3385679/30143160-3fe0f174-9339-11e7-9c32-d29692b6a4ab.png)

Difference:

![appcenter](https://user-images.githubusercontent.com/3385679/30143174-4da52866-9339-11e7-8001-23f3104edca0.png)

Confirmed that the screenshot being used is the same and that AppCenter is serving the correct image.
This URL could change, but here is the raw AppStream version:
https://appstream.elementary.io/appcenter/media/pool/com/github/stsdc.monitor.desktop/AC70FDD191D197674F7D0001F16A2BF2/screenshots/image-1_orig.png

**Comment by davidmhewitt** [comment]
The screenshots in AppCenter are being scaled to fit the maximum width of 800px but not disproportionately as far as I can tell. Aspect ratio seems to be preserved with all the examples I've looked at.

Can someone confirm if this was/is still an issue?

**Comment by cassidyjames** [comment]
I can confirm from these screenshots that it's not stretched, just scaled while preserving aspect ratio. Is the issue that it's scaling _up_?

**Comment by danrabbit** [comment]
Yes, instead of scaling up, we should center
