### ISSUE TITLE
Update notification

### ISSUE THREAD

**Issue by frankqn** [elementary/appcenter#471]
AppCenter's automatic update notification doesn't work anymore for a few days caused by missing file /usr/share/applications/io.elementary.appcenter-daemon.desktop.

**Comment by png2378** [comment]
I can confirm this bug on a fresh installation (assume @davidmhewitt can confirm too).

I also found a workaround for solving this problem - you must create `io.elementary.appcenter-daemon.desktop` file in `/usr/share/applications` folder with the following content:

```
[Desktop Entry]
Name=AppCenter Daemon
Exec=appcenter -s
Icon=system-software-install
Terminal=false
Type=Application
NoDisplay=true
X-GNOME-AutoRestart=true
X-GNOME-Autostart-Phase=Applications
```
