### ISSUE TITLE
Fullscreen not working on low resolution

### ISSUE THREAD

**Issue by inad9300** [elementary/appcenter#472]
I get this outcome when trying to maximize AppCenter on a 1024x600 netbook:

![non-fullscreen](https://user-images.githubusercontent.com/3440331/30240566-2cb9f8ca-9573-11e7-84ec-127b50a4e8b9.png)

**Comment by danrabbit** [comment]
1024x600 is lower than the required minimum display resolution of elementary OS. We only support 1024x768 and above

**Comment by inad9300** [comment]
It would seem to me that you would have to take explicit action not to support resolutions under that "minimum" (officially phrased as "recommended"). Why artificially imposing such restriction? Particularly for the AppStore, and particularly for the height, it makes no sense. Just let us scroll!

But regardless of the dimension and of the application, if users find it useful to resize a window beyond what you have determined "acceptable", just let them do it. Use cases are diverse. Usefulness should come before prettiness.
