### ISSUE TITLE
Appcenter using the wrong language (french)

### ISSUE THREAD

**Issue by jos-henson** [elementary/appcenter#481]
I have a weird bug persistent for over a week now on two separate machines (it appeared on different days despite both being updated daily) 

**The bug?** - Appcenter (including all notifications) is now in French

I have never used French as my OS language, nor am I located/have travelled to that region. I use English (UK) and am located in Slovakia.

The rest of the operating system respects my system wide language settings/preferences (which is English UK - and I have tried to change this to something else and back again but the problem persists)

I have also tried to purge my appcenter and appstream packages and reinstalled, but no luck there either, although temporarily I did fix the issue but it reverted soon after and unfortunately I was trying so many different variations of the same sort of thing I can't recall exactly what 'fixed' it (albeit temporarily)

Any ideas about what might be going on?

Happy to provide any debug system information that is needed/helpful, but apologies, I may need some gentle hand-holding in order to do so but promise I am actually quite tech/linux literate so will be able to gather the required information and logs etc.

Many thanks!

![ca0nh](https://user-images.githubusercontent.com/20843349/30438463-957cfc66-9971-11e7-9123-486b0c6e72fb.png)

**Comment by cassidyjames** [comment]
@matzipan I see you confirmed this bug. Do you have more information about when it crops up, what locales, and/or how to reproduce it? As-is I cannot reproduce.

**Comment by lewisgoddard** [comment]
![image](https://user-images.githubusercontent.com/831389/30498515-fbcd2db4-9a4e-11e7-9cf3-a414a426abf3.png)

My system locale is also set to English (UK) and now AppCenter and most things in it are in French. It is pretty much constant, I think anything that can be translated into French within that app is.

**Comment by DDieter** [comment]
Seems like something went wrong in the latest translations: https://github.com/elementary/appcenter/commits/master/po/en_GB.po

**Comment by lewisgoddard** [comment]
You're right, the en_GB are wrong on weblate https://weblate.elementary.io/projects/appcenter/appcenter/en_GB/

**Comment by davidmhewitt** [comment]
I've just reverted all of the incorrect translations in Weblate, this should now fix itself once Weblate pushes the new translations in.

**Comment by jos-henson** [comment]
Thanks to everyone who helped sort out this issue, great work! :-)
