### ISSUE TITLE
Duplicated entry in 'Updates' tab

### ISSUE THREAD

**Issue by inad9300** [elementary/appcenter#483]
It just happened... Maybe the update(s) fix(es) it?

![whaaat](https://user-images.githubusercontent.com/3440331/30497389-f87e0c42-9a52-11e7-8049-98ae07e199f9.png)

**Comment by sadzebra** [comment]
I had this today, When i first went to the update section it had two updates (Two different apps), I installed the first, click on another app and then went back to the updates section where the first update had gone (Because it has been updated) and the OS update was now duplicated.

**Comment by davidmhewitt** [comment]
I haven't seen this issue or heard of any more reports of it in a long time, so I'll close this issue now.
