### ISSUE TITLE
Crappy icon quality in highlighted apps

### ISSUE THREAD

**Issue by inad9300** [elementary/appcenter#484]
I thought this was an evident first-version mistake, but since the AppCenter keeps being updated and this doesn't get solved, I'm creating an issue for it.

As you can see in the screenshot below, the icons of the highlighted apps are of a really bad quality, effectively giving you a very unprofessional impression. They look resized from a smaller size and you can appreciate all the pixels in them. Please, use bigger/better icons if available, and do not over-resize them if not -- and start asking for them in this latter case, the developers sure want to give the best impression, and this is a very important part.

![crap](https://user-images.githubusercontent.com/3440331/30498568-87cd9c1a-9a57-11e7-8f46-b843efdfcf69.png)

**Comment by stsdc** [comment]
@inad9300 #279
