### ISSUE TITLE
Implement MimeTypes PackageKit interface

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#485]
[This interface](https://git.gnome.org/browse/gnome-software/tree/src/org.freedesktop.PackageKit.Modify2.xml#n188) will let us install unrecognized filetypes in AppCenter, similar to how GNOME Software handles it. Once this is implemented, we should talk to upstream GTK+ about using the session interface—which GNOME Software already implements—instead of [hardcoding the GNOME Software binary in the app chooser widget](https://github.com/GNOME/gtk/blob/4724a89022ef1bec93b1a42d4cf2fec7191ed712/gtk/gtkappchooserdialog.c#L451).

**Comment by danirabbit** [comment]
I'm going to close this since our long time goal is to remove packagekit from AppCenter
