### ISSUE TITLE
AppCenter as a game store and platform

### ISSUE THREAD

**Issue by mrnhmath** [elementary/appcenter#489]
We should advertise and support games in our application store too. Linux gaming is becoming more and more relevant and this could make eOS a better gaming platform, standing out of other distros. What do we need?

**Comment by danrabbit** [comment]
There is a Games section in AppCenter and they are "supported" the same as any other app. Is there some specific problem or action to be taken here?

**Comment by danrabbit** [comment]
Closing as "incomplete" since OP hasn't responded with more specific information
