### ISSUE TITLE
Incomplete uninstallation process

### ISSUE THREAD

**Issue by inad9300** [elementary/appcenter#490]
I've installed the Clipped application by @davidmhewitt, and later uninstalled it simply because it was not working on the most basic of scenarios (like having the focus on Firefox' URL bar, opening Clipped and trying to select one of the items in the history).

However, after uninstalling it through AppCenter, the application still appears in the Startup list, and is in fact marked to be opened when the system starts.

![buggy-clipped-uninstallation](https://user-images.githubusercontent.com/3440331/30928730-a5c4abdc-a3bc-11e7-986c-f582f1045751.png)

By the way, notice how once an application is selected, it becomes hard or impossible to tell whether the switch is on or off.

![shitty-app-selection](https://user-images.githubusercontent.com/3440331/30928877-17d2ea2c-a3bd-11e7-840e-38f7f6f06ab2.png)

**Comment by davidmhewitt** [comment]
Could you please file this as a bug against clipped too? There might be something more that could be done with appcenter/Houston to make sure applications uninstall properly.

But I should probably figure out how to uninstall that stuff with clipped too if possible.

**Comment by danrabbit** [comment]
I don't think this is within the scope of app center. We just tell packagekit to uninstall and that trusts that the packaging/build system do the right thing

**Comment by inad9300** [comment]
@davidmhewitt I've opened https://github.com/davidmhewitt/clipped/issues/18 and https://github.com/davidmhewitt/clipped/issues/17. (I had to drag-and-drop those links, because the system's `Ctrl + V` no longer works, even after having uninstalled the application...)

**Comment by davidmhewitt** [comment]
I'm going to close this because as discussed above, there's not anything AppCenter can do here, it's down to the package to remove itself properly.
