### ISSUE TITLE
Selected View "Button" on Headerbar View Selector can be toggled off

### ISSUE THREAD

**Issue by lainsce** [elementary/appcenter#491]
When I click on "Home", the default selected view in the headerbar, that shouldn't be actionable, is toggled off, just like a normal toggleable button.

![Imgur](https://i.imgur.com/U68As2W.png)

**Comment by lewisgoddard** [comment]
This also happens if you click "Updates" on the updates view.

**Comment by lainsce** [comment]
Can confirm later versions don't have this problem anymore, closing issue.
