### ISSUE TITLE
Appcenter is not working

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/appcenter#492]
It shows that there are updates available, but fails to download/install them.

![gifout](https://user-images.githubusercontent.com/6054951/31019795-44731368-a507-11e7-8955-2d32b432c08b.gif)

`sudo apt update` & `sudo apt upgrade` work just fine.

**Comment by Gabriel-p** [comment]
Still experiencing this issue.

**Comment by ypoz** [comment]
Your system may have been interrupted during a package installation, resulting in package manager backend breakage. Try updating your packages manually by typing the following lines in the Terminal app then entering your password if asked:
```shell
sudo apt update
sudo apt upgrade
```
If there's an error on that end, you will likely be presented with instructions for a quick fix. Please post any errors reported by these commands here.

If this fails, try reproducing the issue while running AppCenter in a debug mode and then copy its output to a GitHub Gist (gists.github.com) and posting the gist link here. The debug mode can be triggered using the following command in a Terminal:
```shell
sudo killall -9 io.elementary.appcenter\
io.elementary.appcenter -d
```

**Comment by Gabriel-p** [comment]
It fixed itself apparently. Thank you.
