### ISSUE TITLE
Appcenter punishes disk IO when pantheon starts

### ISSUE THREAD

**Issue by Nine-H** [elementary/appcenter#495]
My notebook starts pantheon _significantly_ faster with appcenter disabled in xdg-autostart. it also stays cooler and is more responsive. it's a sandy bridge machine with a HDD.

Appcenter wants to start a daemon and update apt sources immediately at login, and this stresses disk and network while other disk intensive processes are starting and other software and services want to access the network. This makes loki feel _really_ bad on older hardware (I'm not upgrading my notebook: all I do is edit text files and google docs).

There's a few possible ways to solve this:

- kill itself if the machine has a battery
- allow appcenter autostart ("Check for updates") to be disabled in swichboard/apps
- automatically not even try to run if the system is a potato
- wait until everything else is loaded
- only run and update package lists on demand
- all of the above

**Comment by matzipan** [comment]
I think a sort of deferred loading would be a good solution.

**Comment by peteruithoven** [comment]
"potato"?

**Comment by Nine-H** [comment]
I don't know what the industry term is but I think American techies say "toaster". legacy, or budget systems that use low spec drives, weaker chipsets, slower ram, integrated graphics or low clockspeeds.

**Comment by bksubhuti** [comment]
I don't like it either.

**Comment by davidmhewitt** [comment]
AppCenter was set to load 60 seconds after the rest of the desktop environment in this commit:
https://github.com/elementary/appcenter/commit/a3c96a9ba8557e013016f44dae44926ec916b0ef

There are also other issues open about not running the update check on every start (which currently happens) which would also help with this.

I'll close this as I think the delay already helps with a significant portion of this issue.
