### ISSUE TITLE
 AppCenter installations fail with proxy 

### ISSUE THREAD

**Issue by Juankz** [elementary/appcenter#508]
Saw the bug reported first in [launchpad](https://bugs.launchpad.net/elementaryos/+bug/1726134) a days ago. I had the same problem described as follows:

"As per the title: having proxy active would have the App Center / Software Center (both btw) failing to establish connection with the repository when trying to install a package.
The error shows "Cannot initiate the connection to 8118:80 (0.0.31.182). - connect (22: invalid argument)". In this context, 8118 is the port on which my proxy operates.
Please note that apt-get from the terminal keeps working ok."

In addition, I switched to a different network and disabled proxy from settings panel. And the error message persisted. My temporary solution was to reinstall appcenter.

**Comment by geodro** [comment]
Any updates on this?
