### ISSUE TITLE
Appcenter GUI is stuck when you launch a second application install

### ISSUE THREAD

**Issue by jcdubois** [elementary/appcenter#509]
In the AppCenter you can launch an application installation and then go back and continue to browse the application list. The selected application continue to download and install in the background which is nice.

But if you select a second application to install the Appcenter GUI will get stuck until the application in the background is finished to install.

When the background application is installed the Appcenter GUI is released and become responsive again.

I think this behavior is not correct. The Appcenter should either prevent browsing until the selected application is installed or allow further application selection to be queued for installation without freezing the Appcenter GUI.

**Comment by mmstick** [comment]
This can be cosed.
