### ISSUE TITLE
Wrong update count after app removing

### ISSUE THREAD

**Issue by marzochi** [elementary/appcenter#523]
There are 2 updates and entries, but I removed some applications. After seems 5 entries but update count is 2.

![image](https://user-images.githubusercontent.com/8195419/32298547-9befbb84-bf63-11e7-84bc-0477a78ca834.png)

**Comment by jeremypw** [comment]
Maybe related to #483

**Comment by davidmhewitt** [comment]
This does seem to be a duplicate of #483 , additionally I haven't seen this issue or had any more reports of it for a long time, so I'll close.
