### ISSUE TITLE
AppCenter sometimes opens to the Updates view

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#529]
When opening AppCenter by clicking its icon in the dock, it's now opening to the Updates view instead of the Home view.

If I manually kill AppCenter, it doesn't continue doing this. I will try to figure out what causes it, but I'm seeing it in AppCenter on elementary OS and in Pop!_Shop on Pop!_OS.

**Comment by cassidyjames** [comment]
It seems like you can reproduce it like this:

1. Log into your OS, 
2. Click an update notification, opening the app
3. Close the app

Now all subsequent openings of AppCenter open to the updates view, even after running the updates. Killing AppCenter and re-launching seems to temporarily fix it so it opens to the home view again.

**Comment by edwood-grant** [comment]
Should be fixed by #2237
