### ISSUE TITLE
UI Issue in Application Info on Cold Start

### ISSUE THREAD

**Issue by arshubham** [elementary/appcenter#538]
It generally happens when opening appcenter by a link from the web and usually corrects itself after scrolling a few times. 
![screenshot from 2017-11-12 17 19 06](https://user-images.githubusercontent.com/14235191/32699371-7aa99d3a-c7da-11e7-84ec-e6a509be9559.png)

**Comment by snowparrot** [comment]
Addition: Also possible after normal opening

**Comment by arshubham** [comment]
Haven't seen this for long in juno. I'll close this now. @snowparrot Tell me if you would like to reopen this or is the problem solved?

**Comment by eljefuri** [comment]
This is still an issue and is not exclusive to a "cold open".

**Comment by arshubham** [comment]
yeah just confirmed it. Somehow I missed it it juno. Never opened app center in such a hurry. 😀
