### ISSUE TITLE
First party apps grouped under OS Updates

### ISSUE THREAD

**Issue by arshubham** [elementary/appcenter#545]
They are not shown in updates view or while searching. When updates are available they are grouped under OS Updates.

I am using latest appcenter from daily ppa.

**Comment by cassidyjames** [comment]
@arshubham is this still occurring? Could you give an example of an app that you're not seeing in AppCenter?

**Comment by arshubham** [comment]
@cassidyjames not an issue now on stable loki. No idea about juno as it was an issue with daily repo earlier . where sometimes apps like music and videos were not searchable or or shown as a separate entry

**Comment by cassidyjames** [comment]
Alright, I think this was solved in packaging or by shipping AppStream data with the apps. Thanks for reporting and following up!
