### ISSUE TITLE
Change "Updates" to "Installed"

### ISSUE THREAD

**Issue by winuxue** [elementary/appcenter#548]
Create a new Tab for installed apps would be great where we can uninstall the ones those we don't need any more.

**Comment by cassidyjames** [comment]
The "Updates" tab lists installed apps. I agree that it could be unintuitive that you need to go to "updates" to uninstall things (especially when the system doesn't have any pending updates). But we do also let you secondary-click apps in the app launcher to uninstall them.

**Comment by cassidyjames** [comment]
@elementary/ux would it make sense to rename that tab to "Installed and Updates" or something? That seems a little verbose for a tab label, though. Or when there are no updates, just change the label to "Installed"? But then it might not be clear why the label is changing.

**Comment by mrnhmath** [comment]
It could be part of something bigger, like a button that brings a menu listing options for Downloads and Updates, My Library, View Account, Settings... Windows Store does this.

![capturar](https://user-images.githubusercontent.com/13562431/33504158-862bea9e-d6cd-11e7-900d-498676e40a97.JPG)

**Comment by winuxue** [comment]
@cassidyjames i think have a single tab "Installed and Updates" with the same behavior that it takes at this moment could be confusing, maybe would be great separate in 2 tabs. one only for updates and the other with the list of the installed apps

**Comment by harveycabaguio** [comment]
Google Play uses "Your apps" or something to that effect. That might be better with a counter badge for actionable items like updates.

**Comment by cassidyjames** [comment]
@harveycabaguio yeah, but they also separate that section into subsections like Updates (which shows any pending updates plus recently updated apps), Installed, and Library (which is a record on your account of every app you've ever installed). We don't have quite that much to stuff in AppCenter, and I don't know that we want to complicate it.

On the other hand, iOS App Store is more similar to AppCenter, but they don't let you uninstall from the store at all as far as I can tell.

**Comment by harveycabaguio** [comment]
We do a similar thing by separating them with headers, so I think it would be fine.

**Comment by cassidyjames** [comment]
@danrabbit what are your thoughts on changing "Updates" to "Installed"?

**Comment by danrabbit** [comment]
I'm not a huge fan of renaming to "Installed". I think "Updates" is something you want to find and do a lot more frequently. Maybe if we had automatic updates then that would flip, but I'm worried that if this label changes we have a case where AppCenter is saying there are updates to be installed but when you open it there isn't any explicit labeling saying "Go here to solve the thing"

**Comment by cassidyjames** [comment]
@danrabbit hm, perhaps. I think that's heavily alleviated by #633, though. My main concern with it always being "updates" is that when there _aren't_ any updates, it's a big page of everything that's installed on your machine. So Updates is a temporary state, while Installed is always true.

**Comment by danrabbit** [comment]
That's an interesting point. I think I'd be a more okay with it depending on #633, but I don't have super strong feelings about it

**Comment by cassidyjames** [comment]
Gonna consider it blocked by #633 and #635, then.

**Comment by cassidyjames** [comment]
#635 was merged, so unblocking.
