### ISSUE TITLE
Appcenter is empty and cannot be updated

### ISSUE THREAD

**Issue by Hazem94** [elementary/appcenter#557]
Whenever I run:
`sudo apt update`, I get this message: 
```
Err:4 http://packages.elementary.io/appcenter xenial Release                               
  403  Forbidden [IP: 104.28.4.44 80]
```
Although it's a fresh version.
Almost apps cannot be installed due to this issue. 
Hope you fix before moving to another distro.

**Comment by btkostner** [comment]
Is the network you are on public, like a school? This should only happen when our server detects abuse like a ddos attack.

**Comment by Hazem94** [comment]
Yes, I'm using a college network. But it was working fine. Only today I started to see this message indicating app center problem. And my friend is using the same network without any problem.

**Comment by btkostner** [comment]
It looks like that IP is not being blocked from our servers. If your friend is on the same network without a problem, then there is something on the college network blocking access.

**Comment by Hazem94** [comment]
So,  any suggested solution, please?  I have finals and my time is very limited. In addition,  I loved ElementaryOS and don't want to leave it ):

**Comment by btkostner** [comment]
The first thing I would do is try connecting from a different network. If that works then you will need to contact your school it and ask them to unblock `http://packages.elementary.io` for you.

I'm going to close this issue as it it's not an issue with AppCenter, but feel free to keep on commenting here for more help.

**Comment by Hazem94** [comment]
Thanks a lot, :-)  it's solved. But, in the AppCenter the apps are really a lot less than before. Can you tell me if I can restore or add the ones which were disappeared?
