### ISSUE TITLE
include "AppCenter Spotlight" within AppCenter

### ISSUE THREAD

**Issue by alainm23** [elementary/appcenter#566]
"AppCenter Spotlight" is one of the best things about elementary in Medium, but many of the users do not follow elementary in their social networks, therefore they do not find out about these small articles.
Maybe if it could be included within the application itself, like a banner that redirects to the website. it's an idea

**Comment by cassidyjames** [comment]
Thanks for the issue! We've actually filed this at https://github.com/elementary/appcenter/issues/389 :wink:
