### ISSUE TITLE
Add "Communication" category

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#571]
Instead of dumping this all just into "Internet", we could surface a "Messaging" metacategory on the home page. This would include "Chat", "InstantMessaging", "IRCClient", "VideoConference", "Email", "Telephony", "ContactManagement".

We can use the internet-chat icon.

**Comment by danrabbit** [comment]
Is this a super useful category since most messaging protocols are closed down these days? Can you give a few examples of apps that fit into this category?

**Comment by cassidyjames** [comment]
I also debated including Mail in here. Right now it's Empathy, Contacts type apps, IRC clients like Polari, Mumble, etc. Eventually I'd love to see some Matrix clients as well.

**Comment by cassidyjames** [comment]
Communication might be a better title since it includes Mail, but I think it's worth pulling out of the Internet category black hole.

**Comment by Mikerr1111** [comment]
Some recommendations I have would be  Skype, Discord, and Hiri. Though, I would probably Discord over Skype better audio quality on Linux.

**Comment by cassidyjames** [comment]
@Mikerr1111 just for clarification, this is about the logic that the store uses to categorize apps (using existing metadata), not picking specific apps.
