### ISSUE TITLE
Add Language & Literature category

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#574]
Could use "Languages", "Literature", "Dictionary", "OCR", "Translation" categories. For the icon, something that looks like the preferences-desktop-locale icon would work (probably would want to symlink a more appropriately namespaced icon).

**Comment by cassidyjames** [comment]
Unless we combine with #572 into a "Writing & Language" category

**Comment by Mikerr1111** [comment]
When you say Language are you talking about apps for translations? Also wouldn't Writing just be part of the Office Section?

**Comment by cassidyjames** [comment]
@Mikerr1111 yes, Language includes translation and dictionary type apps. To me writing is separate from office; office implies a traditional "office suite" sort of workflow: word processing, spreadsheets, printing, presentations, lots of toolbars…

Writing implies a focus on, well, writing. A word processor might belong in both (which is fine for them to), but they're separate enough intents that I think separating them out is useful.

**Comment by cassidyjames** [comment]
Closing in favor of #572
