### ISSUE TITLE
Add Finance category

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#575]
Would include "Finance", "Economy" categories.

**Comment by Mikerr1111** [comment]
Would Accounting be part of the Finance category too?

**Comment by Mikerr1111** [comment]
Some useful apps in that section would be Appgen MyBooks, Nolapro, and Gnucash

**Comment by cassidyjames** [comment]
@Mikerr1111 yeah, I imagine accounting-related things would go here, too.
