### ISSUE TITLE
Add Media Production category

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#576]
Would include "AudioVideoEditing", "Recorder", "Midi", "Mixer", "Sequencer" categories. Could use applications-multimedia icon.

**Comment by cassidyjames** [comment]
Or "Media Production"

**Comment by Mikerr1111** [comment]
Some apps I recommend in this section would be OBS, Bitwig, LMMS, VLC, Audacity, Hydrogen, Muse, and Jack Audio Connection Kit (JACK).

**Comment by cassidyjames** [comment]
@Mikerr1111 we don't set these per-app, but we group certain FreeDesktop.org categories in. 

The implementation in #577 should be split out into its own thing after string freeze is up.

**Comment by cassidyjames** [comment]
Closed by #888
