### ISSUE TITLE
AppCenter not showing any apps or results

### ISSUE THREAD

**Issue by andbuitra** [elementary/appcenter#581]
Hello.

AppCenter is not showing any apps or results for any app I search. The updates are being shown tho. I ran the store on debug and no error message was shown at any time except for a yaml file but I honestly don't know if that might be the issue. The log is the following if useful

➜  ~ io.elementary.appcenter -d

** (process:15690): CRITICAL **: Client.vala:97: Metadata files have errors: /var/lib/app-info/yaml/co.archive.ubuntu.com_ubuntu_dists_xenial_multiverse_dep11_Components-amd64.yml.gz
[INFO 21:54:28.180822] Application.vala:154: AppCenter version: 0.2.7
[INFO 21:54:28.180868] Application.vala:156: Kernel version: 4.13.0-26-generic
[DEBUG 21:54:28.236027] [Gtk] Connecting to session manager
[DEBUG 21:54:28.266653] Houston.vala:51: Requesting newest applications from https://developer.elementary.io/api/newest/project
[DEBUG 21:54:28.266895] Houston.vala:51: Requesting newest applications from https://developer.elementary.io/api/newest/release
[DEBUG 21:54:28.266941] Houston.vala:51: Requesting newest applications from https://developer.elementary.io/api/newest/downloads
[DEBUG 21:54:28.272394] Settings.vala:163: Loading settings from schema 'io.elementary.appcenter.settings'
[DEBUG 21:54:28.272786] [PackageKit] adding state 0x16433f0
[DEBUG 21:54:28.272839] [PackageKit] role now get-packages
[DEBUG 21:54:28.443804] [PackageKit] notify::connected
[DEBUG 21:54:28.473525] [PackageKit] emit transaction-list-changed
[DEBUG 21:54:29.449743] [PackageKit] remove state 0x16433f0
[DEBUG 21:54:29.449781] [PackageKit] emit transaction-list-changed
[DEBUG 21:54:29.700354] Client.vala:547: update cache called false
[DEBUG 21:54:29.700561] Client.vala:573: New refresh task
[DEBUG 21:54:29.700763] [PackageKit] adding state 0x1e0e000
[DEBUG 21:54:29.700897] [PackageKit] role now refresh-cache
[DEBUG 21:54:29.721924] [PackageKit] emit transaction-list-changed
[DEBUG 21:54:31.447900] Stemming language is: en
[DEBUG 21:54:31.447987] Searching for: asd
[DEBUG 21:54:31.890465] Searching for: asdasd
[DEBUG 21:54:37.749727] [PackageKit] emit transaction-list-changed
[DEBUG 21:54:37.749833] [PackageKit] remove state 0x1e0e000
[DEBUG 21:54:37.749939] [PackageKit] adding state 0x1e0e180
[DEBUG 21:54:37.749973] [PackageKit] role now get-updates
[DEBUG 21:54:37.765092] [PackageKit] emit transaction-list-changed
[DEBUG 21:54:37.843810] [PackageKit] emit updates-changed
[DEBUG 21:54:40.375747] [PackageKit] emit updates-changed
[DEBUG 21:54:41.231459] [PackageKit] adding state 0x1e0e600
[DEBUG 21:54:41.231494] [PackageKit] role now search-name
[DEBUG 21:54:41.247383] [PackageKit] emit transaction-list-changed
[DEBUG 21:54:42.729576] [PackageKit] emit transaction-list-changed
[DEBUG 21:54:42.729670] [PackageKit] remove state 0x1e0e180
[DEBUG 21:54:42.729762] [PackageKit] adding state 0x1e0e240
[DEBUG 21:54:42.729806] [PackageKit] role now get-details
[DEBUG 21:54:42.748364] [PackageKit] emit transaction-list-changed
[DEBUG 21:54:43.968401] [PackageKit] remove state 0x1e0e600
[DEBUG 21:54:43.970301] [PackageKit] adding state 0x1e0e6c0
[DEBUG 21:54:43.970358] [PackageKit] role now get-details
[DEBUG 21:54:43.970791] [PackageKit] emit transaction-list-changed
[DEBUG 21:54:43.991240] [PackageKit] emit transaction-list-changed
[DEBUG 21:54:45.248886] [PackageKit] remove state 0x1e0e240
[DEBUG 21:54:45.248973] [PackageKit] emit transaction-list-changed
[DEBUG 21:54:46.315328] [PackageKit] emit transaction-list-changed
[DEBUG 21:54:46.315469] [PackageKit] remove state 0x1e0e6c0
[DEBUG 21:54:46.315769] [PackageKit] adding state 0x7f7bd400b040
[DEBUG 21:54:46.315868] [PackageKit] role now search-name
[DEBUG 21:54:46.334261] [PackageKit] emit transaction-list-changed
[DEBUG 21:54:47.535674] [PackageKit] remove state 0x7f7bd400b040
[DEBUG 21:54:47.535741] [PackageKit] emit transaction-list-changed
[DEBUG 21:54:47.535796] [PackageKit] adding state 0x7f7bd400b100
[DEBUG 21:54:47.535843] [PackageKit] role now get-details
[DEBUG 21:54:47.557386] [PackageKit] emit transaction-list-changed
[DEBUG 21:54:48.675107] [PackageKit] remove state 0x7f7bd400b100
[DEBUG 21:54:48.698778] [PackageKit] emit transaction-list-changed
[DEBUG 21:55:13.119214] Searching for: qui
[DEBUG 21:55:13.399438] Searching for: quilt
[DEBUG 21:55:13.581314] Searching for: quilt
[DEBUG 21:55:13.766372] Searching for: quilter
[DEBUG 21:55:14.110732] Searching for: quilt

After that I closed the store.

**Comment by hamedghadiyani1372** [comment]
L

**Comment by samik-saha** [comment]
I am having the same issue.

**Comment by andbuitra** [comment]
@samik-saha Are you still using Loki?

**Comment by samik-saha** [comment]
yes, I just installed 4.1 (Loki)

**Comment by andbuitra** [comment]
I didn't solve it back in the day but I think it was due to some faulty repos. I haven't had the same issue again and with elementary team looking forward to Juno (in which I don't have problems so far) I think we should close this down. Maybe it got fixed somewhere else and we don't even know about it :)
