### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by alainm23** [elementary/appcenter#582]
![captura realizada el 2018-01-27 07 30 29](https://user-images.githubusercontent.com/33765137/35471980-62b4b648-0334-11e8-8853-0a6173ef18b2.png)

Someone translated this string incorrectly

```
po > es.po

633 #. / This amount will be US Dollars. Some languages might need a "$%dUSD"
634 #: ../src/Widgets/HumbleButton.vala:141
635 msgid "$%d.00"
636 msgstr "Este monto será en Dolares. Algunos idiomas podrían necesitar USD"
```

**Comment by btkostner** [comment]
Looks like this was corrected in weblate. It will sync to master soon.

https://l10n.elementary.io/translate/appcenter/appcenter/es/?q=%24%25d.00&search=ftx&source=1&target=1&type=all&offset=1
