### ISSUE TITLE
Updates flag not working

### ISSUE THREAD

**Issue by ryonakano** [elementary/appcenter#595]
![screenshot from 2018-02-04 13 41 01](https://user-images.githubusercontent.com/26003928/35778166-c8f31d9e-09fd-11e8-8be9-b2e9bcff077d.png)

Currently, Clicking "Check for updates" in Dock or Application-menu opens "Home" tab.
Because we click it in order to check for updates, "Check for updates" should open "Updates" tab by default.

**Comment by memnoth** [comment]
I suggest that "Check for updates" should be removed since AppCenter is run in background and It automatically notifies us if there are updates.

**Comment by cassidyjames** [comment]
This is supposed to work with the command line flag, but it appears that flag is broken (as also reported at https://github.com/elementary/switchboard-plug-about/issues/44)

**Comment by danrabbit** [comment]
Afaict this is working now

**Comment by ryonakano** [comment]
@danrabbit I think this is not working correctly in Juno Beta1, it still opens "Home" tab
