### ISSUE TITLE
[Feature] appimage for AppCenter

### ISSUE THREAD

**Issue by lil5** [elementary/appcenter#600]
I :heart: the idea behind elementary os' AppCenter. It brings back a side of GPL most forget:FLOSS ≠ free as in beer (but can be). [#DoesTheGPLAllowMoney](https://www.gnu.org/licenses/gpl-faq.html#DoesTheGPLAllowMoney)

I just find the distro (elementary os) unusable and unconfigurable. Sorry but yeah that's my preference (more of an xfce guy).

It would be really cool for this project to be Linux distro agnostic. I believe many people want to use features added in AppCenter but dislike elementary os.

**Comment by danrabbit** [comment]
AppImage in particular isn’t something we would do. If we endorsed a packaging format besides deb, it would be a secure confined format like Flatpak or Snap.

Closing this as “Won’t Fix”

**Comment by lil5** [comment]
https://askubuntu.com/questions/955227/how-to-install-elementary-os-appcenter-on-ubuntu

You can use this ugly PPA hack to run AppCenter but this only works on Ubuntu based distros

**Comment by lil5** [comment]
In the long run that would mean adding support for the following;
- pure Debian repositories
- RPM
- AUR
- QT version for qt flavors

**Comment by lil5** [comment]
@danrabbit

> uses packagekit, so it is theoretically already distribution agnostic.

_Theoretically_ but as it stands right now this application is only available on an Ubuntu based distro via PPA or evolution os, without a deb or flatpack or whatever, limits availability.

Alienating the rest of the Linux distros (shout out to Debian here) removes a large possibility for more paying users.

**Comment by danrabbit** [comment]
The responsibility of packaging software for your distro of choice falls on your distro’s maintainers. There’s nothing elementary can do to force your distro to begin maintaining an AppCenter package
