### ISSUE TITLE
Payments are intermittently failing

### ISSUE THREAD

**Issue by joedborg** [elementary/appcenter#602]
This is the first time I've tried to pay for things through the store.  The payment processing seems to be intermittent, throwing the attached error a few times until eventually going through after a few attempts.

![screenshot from 2018-02-08 19 15 20](https://user-images.githubusercontent.com/1426404/35993228-8d3bab5e-0d04-11e8-9851-1d17c057f146.png)

**Comment by cassidyjames** [comment]
@joedborg do you have a(n approximate) timestamp of when it was failing? 

@btkostner have we had any Houston outages recently that would cause this?

**Comment by joedborg** [comment]
```
DISTRIB_ID="elementary"
DISTRIB_RELEASE=0.4.1
DISTRIB_CODENAME=loki
DISTRIB_DESCRIPTION="elementary OS 0.4.1 Loki"
NAME="elementary OS"
VERSION="0.4.1 Loki"
ID="elementary"
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 0.4.1 Loki"
VERSION_ID="0.4.1"
HOME_URL="http://elementary.io/"
SUPPORT_URL="http://elementary.io/support/"
BUG_REPORT_URL="https://github.com/elementary/"
VERSION_CODENAME=loki
UBUNTU_CODENAME=loki
```

**Comment by joedborg** [comment]
Hey @cassidyjames, thanks for the rapid reply.  For me, it's currently happening.  It appears others have been having the same issue as well: https://elementaryos.stackexchange.com/questions/12729/cant-get-payment-to-go-through-in-the-last-week-or-so

**Comment by btkostner** [comment]
I'm seeing multiple payments today on houston. What app are you trying to pay for and where is your card from?

**Comment by btkostner** [comment]
I'm trying to debug right now, but not seeing anything alarming. Next time you want to pay for an app could you please run these commands in terminal:

```
sudo killall io.elementary.appcenter
io.elementary.appcenter -d
```

This should launch appcenter in debug mode so you can see more information about the error.

**Comment by joedborg** [comment]
I've redacted some stuff obviously, replacing with `%%`:
`StripeDialog.vala:395: Stripe data:{  "error": {    "type": "invalid_request_error",    "message": "Invalid UTF-8 characters found in POST body: \"%%\u0026payment_user_agent=Stripe checkout\u0026amount=100\u0026card[number]=%%\u0026card[cvc]=%%\u0026card[exp_month]=%%\u0026card[exp_year]=%%\u0026key= R;\\x864\\u007F\u0026currency=USD\".  For assistance, please contact support@stripe.com.",    "code": "invalid_utf8_in_post_body"  }}`

It's odd as I'm not changing any characters, just keep clicking "Retry" until it works.

**Comment by btkostner** [comment]
I just submitted PR #605 that might help. Considering that you are able to make it work just by hitting the "Retry" button repeatetly, it _might_ not be an AppCenter issue, but something with Stripe. If this keeps on happening after the PR, I'll open a conversation with Stripe and see if they have any ideas.

**Comment by btkostner** [comment]
I'm going to close this now that the PR has been merged. If this still occurs after the next release, please feel free to re-open the issue.

**Comment by joedborg** [comment]
Will do, thanks @btkostner
