### ISSUE TITLE
There is a bug with ko.po

### ISSUE THREAD

**Issue by memnoth** [elementary/appcenter#604]
```
...
#: ../src/Dialogs/StripeDialog.vala:78
msgid "Pay $%d for %s"
msgstr "%s에 %d$ 지급합니다"
...
```
Format specifiers of msgstr must be in the same position as msgid. It makes an error as below,
```
Thread 1 "io.elementary.a" received signal SIGSEGV, Segmentation fault.
0x00007ffff51bdcc0 in _IO_vfprintf_internal (s=s@entry=0x7fffffffae10, format=<optimized out>, 
    format@entry=0x7ffff7ff57b6 "%s에 %d$ 지급합니다", ap=ap@entry=0x7fffffffaf70) at vfprintf.c:1632
1632	vfprintf.c: No such file or directory.
```

**Comment by bagjunggyu** [comment]
I switched its order, https://l10n.elementary.io/translate/appcenter/appcenter/ko/?checksum=24d84bb20de41a3b , can you test if it is resolved? With the edited appcenter.mo file ? 
https://l10n.elementary.io/download/appcenter/appcenter/ko/mo/

**Comment by memnoth** [comment]
Thank you for that, I am gonna test it as soon as possible.
Also you could test it to click donate button in appcenter :)

**Comment by memnoth** [comment]
It works very well :+1:

**Comment by bagjunggyu** [comment]
I think it is resolved, can you close this issue ?
