### ISSUE TITLE
Plank should not be listed among curated apps

### ISSUE THREAD

**Issue by jlnr** [elementary/appcenter#610]
Running Loki 0.4.1, I can see Plank in the Utilities (Accessories?) category, right among the curated apps. It has a question mark for an icon and the screenshots don't match the UI in elementaryOS. I can uninstall it, which would probably bork my installation.

Expected behavior: Plank should be considered a park of the system and not an app that can be uninstalled.

**Comment by donadigo** [comment]
It's already blacklisted in the default settings package but I believe it wasn't released to stable yet.

**Comment by danrabbit** [comment]
Closing this issue since it's `Fix Committed` in default settings: https://github.com/elementary/default-settings/blob/master/appcenter.blacklist
