### ISSUE TITLE
External link to AppCenter is sometimes broken

### ISSUE THREAD

**Issue by artemanufrij** [elementary/appcenter#611]
Here is an example:
link to screencaster:
https://appcenter.elementary.io/com.github.artemanufrij.screencaster

`.desktop` was added into search box -> no result

![appcenter](https://user-images.githubusercontent.com/16517095/36073278-0c0fb8be-0f2e-11e8-81ac-ec9db8e83773.png)

**Comment by peteruithoven** [comment]
It's `screencast` not `screencaster`:  https://appcenter.elementary.io/com.github.artemanufrij.screencast

**Comment by artemanufrij** [comment]
@peteruithoven you are right! Thanks for check it!

**Comment by peteruithoven** [comment]
Maybe the following sentence is confusing, because it doesn't seem true in this case.
> This app is available in AppCenter,
