### ISSUE TITLE
Most apps in AppCenter have blurry icons in the full app view

### ISSUE THREAD

**Issue by jtrees** [elementary/appcenter#617]
Most apps in AppCenter appear to have blurry icons in the full app view and in the banner view on the AppCenter Home tab. At first I thought, this was an app-specific issue, derived from not providing enough icon sizes (e.g. https://github.com/artemanufrij/playmymusic/issues/64), but it turns out even adding a 128x128 icon does not solve the issue.

![screenshot](https://preview.ibb.co/bJQiW6/Screenshot_from_2018_01_30_09_15_35.png)

The core elementary apps (such as Calculator, Files and Photos) do not seem to be affected by this but even the apps by @danrabbit (Harvey and Nimbus) have blurry icons.

After researching a bit, my guess is that AppCenter demands to have HiDPI icons (`app@2x`, etc.) even on non-HiDPI screens. I have not been able to confirm this yet though.

**Comment by peteruithoven** [comment]
I'm afraid this is a duplicate?
https://github.com/elementary/appcenter/issues/279
https://github.com/elementary/houston/issues/541

**Comment by jtrees** [comment]
Oh I must have missed that, since I was only looking for open issues. Obviously the core apps get around the underlying issue though so is it really a purely upstream bug or is an AppCenter fix/workaround possible?

**Comment by btkostner** [comment]
Closing as duplicate

**Comment by micahilbery** [comment]
The Default apps don't have the problem because their icons are already installed on the system. We can't just install the icons of every possible app available so yes I'm afraid it's purely upstream.
