### ISSUE TITLE
Fails to compile against latest Vala + PackageKit

### ISSUE THREAD

**Issue by decathorpe** [elementary/appcenter#619]
```
src/Core/Client.vala:226.44-226.79: error: Access to instance member `Pk.Exit.enum_to_string' denied
            throw new GLib.IOError.FAILED (Pk.Exit.enum_to_string (exit_status));
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Core/Client.vala:226.19-226.80: error: Invalid type for argument 1
            throw new GLib.IOError.FAILED (Pk.Exit.enum_to_string (exit_status));
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

A full build log can be found [here](https://copr-be.cloud.fedoraproject.org/results/decathorpe/elementary-nightly/fedora-rawhide-x86_64/00717215-appcenter/build.log.gz) for git master / nightly and [here](https://kojipkgs.fedoraproject.org/work/tasks/1725/25151725/build.log) for the last stable release.

**Comment by tintou** [comment]
Renaming as it's mainly because Vala is now smarter with enums recognition now so the issue is not directly linked to GNOME version :)
