### ISSUE TITLE
Disable notifications in live session

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#622]
Similar to but distinct from #62. We should disable all update notifications when running in the live session (and possibly in the guest session as @Philip-Scott mentioned, though I'm less sure about that) since there's not really anything a user can do.

Downstream issue: https://github.com/pop-os/shop/issues/49

**Comment by danrabbit** [comment]
Possible duplication of https://github.com/elementary/os/issues/11 ?

**Comment by cassidyjames** [comment]
Ah yeah possibly. Though does the daemon start when the GUI starts anyway, or are they totally separate?

**Comment by donadigo** [comment]
The daemon and GUI is the same process, the daemon starts at the session startup, and when you launch AppCenter, it gets invoked without any arguments to show the window.

**Comment by cassidyjames** [comment]
@donadigo so even if we disable the daemon from _starting_ in the live session, as soon as someone opens AppCenter once, they'd get notifications for updates?

**Comment by meisenzahl** [comment]
https://github.com/elementary/appcenter/pull/1963 prevents an update of the cache. Therefore, the issue should then probably no longer occur.

**Comment by danirabbit** [comment]
Gonna close since it sounds like this was fixed
