### ISSUE TITLE
Locally cache viewed screenshots

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#627]
Instead of re-downloading screenshots every time, we should be more conscious about bandwidth and load time and cache _viewed_ screenshots (not all screenshots in AppStream, because that would be huge) to disk once they've been downloaded. We should be able to check cache headers to see if we need to re-download once they've been downloaded once.

**Comment by mmstick** [comment]
Almost finished with this. Expect a PR by the end of the day.

**Comment by mmstick** [comment]
Still working on this. Have a solution which verifies & fetches screenshots in parallel.
