### ISSUE TITLE
Show uninstall button on updates page

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#632]
Splitting out from #548. It might be useful to show an Uninstall button for apps on the updates/installed page.

**Comment by danrabbit** [comment]
Should this show only for apps that don't have updates?

**Comment by cassidyjames** [comment]
@danrabbit probably, as I don't think we want two buttons in the row. And since we already separate them into sections, I think it'd feel natural.

**Comment by snowparrot** [comment]
Please consider in later versions that updates are sometimes only possible if you pay something or fill in 0 Dollars. If this context there is a need for a second uninstall button as some beginners might think "I just can pay but I cant uninstall".

**Comment by danrabbit** [comment]
I'm gonna punt since this is an enhancement and not a release blocker

**Comment by danrabbit** [comment]
I'm gonna make a call here, we probably don't need to show uninstall buttons in list views. This isn't an action that you're likely to be doing across multiple apps in sucession, unlike "Upgrade" or "Install". Uninstall is always available from AppInfo views
