### ISSUE TITLE
Add badge for updates to tab

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#633]
Splitting out from #548. Something @harveycabaguio suggested.

**Comment by danrabbit** [comment]
With a bit of custom CSS, it can be done :)

![screenshot from 2018-03-02 12 21 56](https://user-images.githubusercontent.com/7277719/36920059-566617a6-1e14-11e8-9fb6-72860f9206c9.png)

**Comment by cassidyjames** [comment]
@danrabbit it looks like the right edge is being clipped a tiny bit, but _daaaamn_ that's fresh.
