### ISSUE TITLE
Show uninstall buttons in search listings

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#634]
If you're viewing a list of apps, is it useful to show an "uninstall" button alonside any apps that are installed? 

I'm not super convinced it should be on the category listings since if you're browsing for an app, you're probably not looking to uninstall one. 

On the other hand, if you're _searching_ for an app _in order to uninstall it_, it might be really handy to bubble that action up to the list instead of having to go into the app's page itself.

Brought up due to some WIP changes in Pop!\_Shop downstream. https://github.com/pop-os/shop/pull/54/files#diff-8a3694d1b620c25ea491262722dd3d6aR64

**Comment by danrabbit** [comment]
My gut reaction is that on the categories page the user is browsing, so they're not necessarily looking for apps they've already installed.

I agree though that in the case of search they could be looking for an app they have installed already

**Comment by cassidyjames** [comment]
Yeah I agree. The problem is that right now those are the same view.

**Comment by isantop** [comment]
Should AppCenter show apps that are already installed when browsing the categories page?

**Comment by cassidyjames** [comment]
@isantop I think so, since it might feel weird if you're browsing and expect to see an app that's installed and suddenly it's not any more. Basically, it's still on the store shelves even though you bought a copy. 

But I don't think uninstalling is the **primary** action for this list, and I don't really like mixing actions (especially opposite ones) in the same list.

**Comment by danrabbit** [comment]
I'm gonna punt since this is an enhancement and not a release blocker

**Comment by danrabbit** [comment]
I'm gonna make a call here, we probably don't need to show uninstall buttons in list views. This isn't an action that you're likely to be doing across multiple apps in sucession, unlike "Upgrade" or "Install". Uninstall is always available from AppInfo views
