### ISSUE TITLE
Allow spaces in the card entry

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#640]
We should allow spaces when entering a card, and just ignore them when submitting. Cards are almost always formatted with spaces, and it lets users better self-validate their number.

More info! https://baymard.com/blog/credit-card-field-auto-format-spaces

Note that _auto_ formatting is out of scope of this issue.

**Comment by tintou** [comment]
#646 might be an answer to this, it automatically validates the format and hitting space isn't misbehaving there

**Comment by cassidyjames** [comment]
Superseded by #646
