### ISSUE TITLE
No changelog for elementary apps

### ISSUE THREAD

**Issue by snowparrot** [elementary/appcenter#644]
On the app page for elementary apps (like calendar, videos, etc.) there is no changelog like on other apps.

expected behaviour: There is a changelog on the app page.

**Comment by cassidyjames** [comment]
Is this just because those apps are not shipping release changes in their appdata?

**Comment by danrabbit** [comment]
@cassidyjames I think the bigger problem is that appdata isn't being updated for launchpad PPAs. Once/If we publish all 1st party apps through Houston it'll be solved.

In any case, this can't be solved within the scope of AppCenter itself
