### ISSUE TITLE
Why not enlightment?

### ISSUE THREAD

**Issue by xor256** [elementary/appcenter#654]
Why ugly gtk?
please tell me in few numbers

**Comment by cassidyjames** [comment]
elementary OS [uses many GTK+ and GNOME technologies](https://elementary.io/open-source) under the hood, and there's no significant reason to switch to an entirely different stack. In fact, there are several aspects of GTK+ that we like and use extensively. GTK has proven to be the best choice for us in the past ten years of design development, and we expect it to remain the best choice for the foreseeable future.

Also, this issue has nothing to do with AppCenter itself as this is an elementary-wide question.
