### ISSUE TITLE
"Failed to Fetch Updates" dialog has no title set

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#670]
While we don't show the title in elementary OS, it shows on the dock and in downstreams. We should set it to something sane.

![screenshot from 2018-03-30 09-47-55](https://user-images.githubusercontent.com/611168/38143876-afe7cb20-33ff-11e8-842e-bc2bbdfe72da.png)

**Comment by danrabbit** [comment]
I think this is a Granite.MessageDialog right? Recently fixed a bug in Granite that stopped subclasses from inheriting the skip taskbar hint. Maybe we should set a null title string in Granite as well

**Comment by cassidyjames** [comment]
@danrabbit it looks like it's literally NULL right now, but an empty string works.
