### ISSUE TITLE
AppCenter freezes on run

### ISSUE THREAD

**Issue by jwinnie** [elementary/appcenter#699]
AppCenter freezes whenever it is run. One must wait a while before it fully loads.

<details>
<summary>Output of <code>io.elementary.appcenter -d</code> until AppCenter loads apps</summary>
<pre><code>
[DEBUG 15:02:01.802727] [Gtk] Connecting to session manager
[DEBUG 15:02:01.829241] Houston.vala:51: Requesting newest applications from https://developer.elementary.io/api/newest/project
[DEBUG 15:02:01.829471] Houston.vala:51: Requesting newest applications from https://developer.elementary.io/api/newest/release
[DEBUG 15:02:01.829525] Houston.vala:51: Requesting newest applications from https://developer.elementary.io/api/newest/downloads
[DEBUG 15:02:01.833971] Settings.vala:163: Loading settings from schema 'io.elementary.appcenter.settings'
[DEBUG 15:02:01.859317] [PackageKit] adding state 0x2f996d0
[DEBUG 15:02:01.859406] [PackageKit] role now get-packages
[DEBUG 15:02:02.026083] [PackageKit] notify::connected
[DEBUG 15:02:02.068242] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:02.602458] [PackageKit] adding state 0x3239990
[DEBUG 15:02:02.603726] [PackageKit] adding state 0x7f4a8c003800
[DEBUG 15:02:02.603787] [PackageKit] role now search-name
[DEBUG 15:02:02.603885] [PackageKit] role now search-name
[DEBUG 15:02:02.712492] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:02.712554] [PackageKit] remove state 0x2f996d0
[DEBUG 15:02:02.833776] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:02.834091] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:03.012609] [PackageKit] adding state 0x7f4a8c003e00
[DEBUG 15:02:03.012671] [PackageKit] role now search-name
[DEBUG 15:02:03.026114] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:03.258382] [PackageKit] remove state 0x7f4a8c003800
[DEBUG 15:02:03.258467] [PackageKit] adding state 0x7f4a8c0038c0
[DEBUG 15:02:03.258495] [PackageKit] role now get-details
[DEBUG 15:02:03.258715] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:03.278263] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:03.759144] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:03.759254] [PackageKit] remove state 0x3239990
[DEBUG 15:02:03.759320] [PackageKit] adding state 0x3239a50
[DEBUG 15:02:03.759369] [PackageKit] role now get-details
[DEBUG 15:02:03.778469] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:04.268176] [PackageKit] remove state 0x7f4a8c003e00
[DEBUG 15:02:04.268255] [PackageKit] adding state 0x7f4a8c003ec0
[DEBUG 15:02:04.268299] [PackageKit] role now get-details
[DEBUG 15:02:04.268345] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:04.283215] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:04.710872] [PackageKit] remove state 0x7f4a8c0038c0
[DEBUG 15:02:04.711249] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:04.711625] [PackageKit] adding state 0x7f4a8c003980
[DEBUG 15:02:04.711678] [PackageKit] role now search-name
[DEBUG 15:02:04.732031] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:05.128098] [PackageKit] remove state 0x3239a50
[DEBUG 15:02:05.128916] [PackageKit] adding state 0x3239b10
[DEBUG 15:02:05.128952] [PackageKit] role now search-name
[DEBUG 15:02:05.129040] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:05.147913] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:05.567656] [PackageKit] remove state 0x7f4a8c003ec0
[DEBUG 15:02:05.567817] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:05.567902] [PackageKit] adding state 0x7f4a80006020
[DEBUG 15:02:05.567940] [PackageKit] role now search-name
[DEBUG 15:02:05.581784] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:06.049883] [PackageKit] remove state 0x7f4a8c003980
[DEBUG 15:02:06.049963] [PackageKit] adding state 0x7f4a8c003a40
[DEBUG 15:02:06.049995] [PackageKit] role now get-details
[DEBUG 15:02:06.050533] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:06.077645] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:06.545093] [PackageKit] remove state 0x3239b10
[DEBUG 15:02:06.545212] [PackageKit] adding state 0x3239bd0
[DEBUG 15:02:06.545251] [PackageKit] role now get-details
[DEBUG 15:02:06.545362] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:06.563542] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:07.064599] [PackageKit] remove state 0x7f4a80006020
[DEBUG 15:02:07.064682] [PackageKit] adding state 0x7f4a800060e0
[DEBUG 15:02:07.064716] [PackageKit] role now get-details
[DEBUG 15:02:07.064856] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:07.082626] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:07.493109] [PackageKit] remove state 0x7f4a8c003a40
[DEBUG 15:02:07.493271] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:07.493590] [PackageKit] adding state 0x7f4a8c003b00
[DEBUG 15:02:07.493635] [PackageKit] role now search-name
[DEBUG 15:02:07.513770] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:07.909310] [PackageKit] remove state 0x3239bd0
[DEBUG 15:02:07.909397] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:07.910199] [PackageKit] adding state 0x3239c90
[DEBUG 15:02:07.910234] [PackageKit] role now search-name
[DEBUG 15:02:07.924945] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:08.310585] [PackageKit] remove state 0x7f4a800060e0
[DEBUG 15:02:08.310978] [PackageKit] adding state 0x7f4a800061a0
[DEBUG 15:02:08.311009] [PackageKit] role now search-name
[DEBUG 15:02:08.311099] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:08.326955] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:08.766986] [PackageKit] remove state 0x7f4a8c003b00
[DEBUG 15:02:08.767060] [PackageKit] adding state 0x7f4a8c003bc0
[DEBUG 15:02:08.767092] [PackageKit] role now get-details
[DEBUG 15:02:08.767174] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:08.786230] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:09.204827] [PackageKit] remove state 0x3239c90
[DEBUG 15:02:09.205167] [PackageKit] adding state 0x3239d50
[DEBUG 15:02:09.205342] [PackageKit] role now get-details
[DEBUG 15:02:09.205570] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:09.225006] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:09.651911] [PackageKit] remove state 0x7f4a800061a0
[DEBUG 15:02:09.651992] [PackageKit] adding state 0x7f4a80006260
[DEBUG 15:02:09.652026] [PackageKit] role now get-details
[DEBUG 15:02:09.652110] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:09.667014] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:10.051184] [PackageKit] remove state 0x7f4a8c003bc0
[DEBUG 15:02:10.051495] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:10.051528] [PackageKit] adding state 0x7f4a8c003c80
[DEBUG 15:02:10.051559] [PackageKit] role now search-name
[DEBUG 15:02:10.065837] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:10.451238] [PackageKit] remove state 0x3239d50
[DEBUG 15:02:10.451510] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:10.451541] [PackageKit] adding state 0x3239e10
[DEBUG 15:02:10.451578] [PackageKit] role now search-name
[DEBUG 15:02:10.474843] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:10.824239] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:10.824464] [PackageKit] remove state 0x7f4a80006260
[DEBUG 15:02:10.825257] [PackageKit] adding state 0x7f4a80006320
[DEBUG 15:02:10.825290] [PackageKit] role now search-name
[DEBUG 15:02:10.849596] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:11.280758] [PackageKit] remove state 0x7f4a8c003c80
[DEBUG 15:02:11.280846] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:11.280880] [PackageKit] adding state 0x7f4a8c003d40
[DEBUG 15:02:11.280917] [PackageKit] role now get-details
[DEBUG 15:02:11.299509] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:11.736989] [PackageKit] remove state 0x3239e10
[DEBUG 15:02:11.737063] [PackageKit] adding state 0x3239ed0
[DEBUG 15:02:11.737096] [PackageKit] role now get-details
[DEBUG 15:02:11.737517] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:11.762568] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:12.201042] [PackageKit] remove state 0x7f4a80006320
[DEBUG 15:02:12.201129] [PackageKit] adding state 0x7f4a800063e0
[DEBUG 15:02:12.201165] [PackageKit] role now get-details
[DEBUG 15:02:12.201227] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:12.229587] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:12.609343] [PackageKit] remove state 0x7f4a8c003d40
[DEBUG 15:02:12.610204] [PackageKit] adding state 0x7f4a8c003d40
[DEBUG 15:02:12.610244] [PackageKit] role now search-name
[DEBUG 15:02:12.610345] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:12.635333] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:12.993564] [PackageKit] remove state 0x3239ed0
[DEBUG 15:02:12.993776] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:12.994087] [PackageKit] adding state 0x3239ed0
[DEBUG 15:02:12.994113] [PackageKit] role now search-name
[DEBUG 15:02:13.007340] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:13.374304] [PackageKit] remove state 0x7f4a800063e0
[DEBUG 15:02:13.375350] [PackageKit] adding state 0x7f4a800063e0
[DEBUG 15:02:13.375389] [PackageKit] role now search-name
[DEBUG 15:02:13.375520] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:13.389920] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:13.829716] [PackageKit] remove state 0x7f4a8c003d40
[DEBUG 15:02:13.829818] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:13.829869] [PackageKit] adding state 0x7f4a8c003c80
[DEBUG 15:02:13.829901] [PackageKit] role now get-details
[DEBUG 15:02:13.848790] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:14.284026] [PackageKit] remove state 0x3239ed0
[DEBUG 15:02:14.284106] [PackageKit] adding state 0x3239e10
[DEBUG 15:02:14.284156] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:14.284185] [PackageKit] role now get-details
[DEBUG 15:02:14.297841] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:14.750578] [PackageKit] remove state 0x7f4a800063e0
[DEBUG 15:02:14.750671] [PackageKit] adding state 0x7f4a80006320
[DEBUG 15:02:14.750707] [PackageKit] role now get-details
[DEBUG 15:02:14.750819] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:14.765083] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:15.149644] [PackageKit] remove state 0x7f4a8c003c80
[DEBUG 15:02:15.149870] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:15.164383] Client.vala:569: update cache called false
[DEBUG 15:02:15.164417] Client.vala:595: New refresh task
[DEBUG 15:02:15.164444] [PackageKit] adding state 0x32398d0
[DEBUG 15:02:15.164468] [PackageKit] role now refresh-cache
[DEBUG 15:02:15.197481] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:15.619993] [PackageKit] remove state 0x3239e10
[DEBUG 15:02:15.620384] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:16.040527] [PackageKit] remove state 0x7f4a80006320
[DEBUG 15:02:16.040607] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:17.284234] [PackageKit] remove state 0x32398d0
[DEBUG 15:02:17.284290] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:17.284413] [PackageKit] adding state 0x32398d0
[DEBUG 15:02:17.284436] [PackageKit] role now get-updates
[DEBUG 15:02:17.303877] [PackageKit] emit transaction-list-changed
[DEBUG 15:02:17.374235] [PackageKit] emit updates-changed
</pre></code>
</details>
<hr/>
Maybe AppCenter should display a large loading indicator before it is loaded instead of giving users a half-working half-loaded UI. GNOME Software does this.

**Comment by mmstick** [comment]
This should be closed.
