### ISSUE TITLE
Hit "Down" arrow key to focus list & improve keyboard navigation in search results

### ISSUE THREAD

**Issue by uncertainquark** [elementary/appcenter#704]
Up/Down keys should browse the apps in the search results.
![screenshot from 2018-05-03 12-03-12](https://user-images.githubusercontent.com/22585732/39562972-ec642bac-4ecb-11e8-9a34-3344567c1a58.png)

As with #669 & #703, it enhances usability.

**Comment by uncertainquark** [comment]
For what it's worth, the "Installed" apps tab supports up/down and "Enter/Select" keyboard navigation by default.

**Comment by uncertainquark** [comment]
I've found that after hitting `Ctrl`+`Tab`, full up/down and enter/select keyboard navigation starts working!

![Screenshot from 2019-04-17 17-01-07](https://user-images.githubusercontent.com/22585732/56284590-89d1d500-6132-11e9-834e-4a1d44323011.png)

**Comment by cassidyjames** [comment]
@uncertainquark just hitting <kbd>Tab</kbd> is enough, since it focuses the list (as opposed to the text entry). I could see the argument that hitting <kbd>Down</kbd> should focus the search results, as that's similar to what we do with the Applications Menu search.
