### ISSUE TITLE
 flatpak application support [$160]

### ISSUE THREAD

**Issue by EvertonCosmo** [elementary/appcenter#712]
Would be interesting an option that presents flatpak applications

**Comment by cassidyjames** [comment]
To clarify the scope here: This would ideally list apps from any Flatpak repos on the machine, and treat them like any other non-curated app results. 

In the future, we could potentially expand the curated flag to apply to a specific flatpak repo, i.e. if we were to host one ourselve.

**Comment by mmstick** [comment]
GNOME Software is able to do some neat things with it:

- Save Flatpak apps to a USB device
- Install apps from USB devices
- Designate a system as the main distributor of Flatpak apps
- Have other systems on the network get apps and system/app updates from it
- List apps found from specific sources (Internet, LAN, USB device(s))

Which was demoed at LAS recently.

**Comment by danrabbit** [comment]
@bilelmoussaoui I think I would be down for having flatpak *repository* support in AppCenter regardless of whether it's used out of the box in elementary OS. It would probably make the lives of our users who want to, for example, add FlatHub easier and I'm sure downstreams like Pop! would appreciate the feature as well.

**Comment by mmstick** [comment]
Flatpak support is one of the most requested features for Pop, so yes, that would be ideal.

**Comment by bilelmoussaoui** [comment]
WIP: https://github.com/bilelmoussaoui/appcenter/tree/flatpak
Just started hacking on it, nothing there for now. What I plan to implement:
Installing/uninstalling/updating/displaying apps/runtimes.

**Comment by davidmhewitt** [comment]
I think it's important to think carefully about the implementation of this.

Doing it properly will probably require some fairly significant refactoring of the AppCenter code base and abstracting out the PackageKit backend so any new backends can be implemented cleanly on top.

I think this is important to do to make the code-base more flexible for the future. What if we want an ostree backend in the future, or snap, or magical new backend that solves all the world's problems? Yes, it would be possible to graft Flatpak support on now, but would only make any other backends in the future more complex. So it's probably the right time to think about how to refactor first.

**Comment by bilelmoussaoui** [comment]
@davidmhewitt that's exactly what I'm planning to do. Abstract everything for now and have a set of "plugins", reimplement the current appcenter "plugin" aka PackageKit and add a Flatpak one after that.

**Comment by davidmhewitt** [comment]
@bilelmoussaoui Great, thanks!

Where possible, can you try and do this as separate branches/pull requests, rather than one large "Flatpak support" pull request that includes the refactoring. Should make it easier to review!

**Comment by bilelmoussaoui** [comment]
Will do that, the flatpak branch contains for now just the vapi & the meson build changes to build the flatpak plugin (in the future). Is there a IRC/Slack/Whatever channel if I ever have any questions related to the way things should be done?

**Comment by cassidyjames** [comment]
@bilelmoussaoui an easy place to start is the [elementary Community Slack workspace](https://join.slack.com/t/elementarycommunity/shared_invite/enQtMzU1NDU4OTE1MjY2LWUyOTBkZGNkZGM4MDgzZjE2ZjRiZDgwMDQ1ZTA0MzcxYjI0MDUyNGRlNDI5ZWViNDkwMzMwYzczMDY2ZjA0MTc) that's linked from elementary.io.
