### ISSUE TITLE
French translation for internet disconnected page is incorrect

### ISSUE THREAD

**Issue by brs17** [elementary/appcenter#714]
When disconnecting from the internet in the appcenter, an error appears. It seems that the French translation for this page is incorrect.

![appcenter](https://user-images.githubusercontent.com/7460774/39897921-b3ef297e-5471-11e8-907b-d5728acd459a.png)

Looks like it's picking up the screenshot unavailable text for the header.

Note: This issue was originally created downstream by @xolider in Pop!_OS's Pop!_Shop: https://github.com/pop-os/shop/issues/76

**Comment by tintou** [comment]
Bonjour ! Merci pour l'info !

You can contribute to the localization here https://l10n.elementary.io/projects/appcenter/appcenter/fr/
I'm unsure if pop is up-to-date with our localization though.

**Comment by cassidyjames** [comment]
@brs17 it was a merge conflict or something with Weblate, but it's been resolved. Hopefully other strings aren't also whack…
