### ISSUE TITLE
Appcenter Failed to Fetch Updates

### ISSUE THREAD

**Issue by btd1337** [elementary/appcenter#715]
```
W: GPG error: http://packages.elementary.io/appcenter xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A74F73EFFE70B91C
E: The repository 'http://packages.elementary.io/appcenter xenial InRelease' is not signed.
W: Updating from such a repository can't be done securely, and is therefore disabled by default.
W: See apt-secure(8) manpage for repository creation and user configuration details.
E: http://packages.elementary.io/appcenter xenial InRelease is not (yet) available (The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A74F73EFFE70B91C)

```

**Temporary solution:** 
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys KEY_ID`

Where **KEY_ID** = A74F73EFFE70B91C

![screenshot from 2018-05-19 13 35 19](https://user-images.githubusercontent.com/11943860/40270792-e306d348-5b69-11e8-8b44-276520ff33ab.png)

**Comment by cassidyjames** [comment]
@btkostner did something change with the repo that would cause this?

@btd1337, is this a relatively new install? Do you have unstable/daily repositories?

**Comment by btd1337** [comment]
I have daily repositories. Almost 3 months ago!

**Comment by btd1337** [comment]
My **sources.list**

\# deb cdrom:[elementary OS 0.4.1 _Loki_ - Stable amd64 (20170517)]/ bionic contrib main non-free

\# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
\# newer versions of the distribution.
deb http://br.archive.ubuntu.com/ubuntu/ bionic main restricted
\# deb-src http://br.archive.ubuntu.com/ubuntu/ bionic main restricted

\## Major bug fix updates produced after the final release of the
\## distribution.
deb http://br.archive.ubuntu.com/ubuntu/ bionic-updates main restricted
\# deb-src http://br.archive.ubuntu.com/ubuntu/ bionic-updates main restricted

\## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
\## team. Also, please note that software in universe WILL NOT receive any
\## review or updates from the Ubuntu security team.
deb http://br.archive.ubuntu.com/ubuntu/ bionic universe
\# deb-src http://br.archive.ubuntu.com/ubuntu/ bionic universe
deb http://br.archive.ubuntu.com/ubuntu/ bionic-updates universe
\# deb-src http://br.archive.ubuntu.com/ubuntu/ bionic-updates universe

\## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
\## team, and may not be under a free licence. Please satisfy yourself as to 
\## your rights to use the software. Also, please note that software in 
\## multiverse WILL NOT receive any review or updates from the Ubuntu
\## security team.
deb http://br.archive.ubuntu.com/ubuntu/ bionic multiverse
\# deb-src http://br.archive.ubuntu.com/ubuntu/ bionic multiverse
deb http://br.archive.ubuntu.com/ubuntu/ bionic-updates multiverse
\# deb-src http://br.archive.ubuntu.com/ubuntu/ bionic-updates multiverse

\## N.B. software from this repository may not have been tested as
\## extensively as that contained in the main release, although it includes
\## newer versions of some applications which may provide useful features.
\## Also, please note that software in backports WILL NOT receive any review
\## or updates from the Ubuntu security team.
deb http://br.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
\# deb-src http://br.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse

\## Uncomment the following two lines to add software from Canonical's
\## 'partner' repository.
\## This software is not part of Ubuntu, but is offered by Canonical and the
\## respective vendors as a service to Ubuntu users.
\# deb http://archive.canonical.com/ubuntu bionic partner
\# deb-src http://archive.canonical.com/ubuntu bionic partner

deb http://security.ubuntu.com/ubuntu bionic-security main restricted
\# deb-src http://security.ubuntu.com/ubuntu bionic-security main restricted
deb http://security.ubuntu.com/ubuntu bionic-security universe
\# deb-src http://security.ubuntu.com/ubuntu bionic-security universe
deb http://security.ubuntu.com/ubuntu bionic-security multiverse
\# deb-src http://security.ubuntu.com/ubuntu bionic-security multiverse

deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
\# deb-src [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

**Comment by btd1337** [comment]
My **elementary-os-ubuntu-daily-xenial.list**

deb http://ppa.launchpad.net/elementary-os/daily/ubuntu bionic main
\# deb-src http://ppa.launchpad.net/elementary-os/daily/ubuntu bionic main

**Comment by cassidyjames** [comment]
@btd1337 uuuuuh did you try to upgrade to Ubuntu 18.04 from elementary OS? That's not supported or prompted by the OS at all. You're no longer running elementary OS.

**Comment by btd1337** [comment]
@cassidyjames No, I updated from Loki to Juno, using daily PPA's.
