### ISSUE TITLE
[Feature Request] Pay with cryptocurrencies

### ISSUE THREAD

**Issue by armaccloud** [elementary/appcenter#716]
Hi,
Cryptocurrencies are being used more and more.
Can the option to pay with cryptocurrencies, such as Dash / Bitcoin / Ethereum be added to the app center?

**Comment by peteruithoven** [comment]
Seems like a duplicate of: https://github.com/elementary/appcenter/issues/229 ?
It probably depends on Stripe supporting cryptocurrencies.

**Comment by danrabbit** [comment]
Yes, duplicate of #229

**Comment by eljefuri** [comment]
This is not exclusively a duplicate of #229. Inadvertently or not, @armaccloud is making a point that a variety of payment methods should be supported. Most of the world does not use the Visa/MasterCard network.
