### ISSUE TITLE
daemon locks up apt and hogs network immediately upon log in

### ISSUE THREAD

**Issue by codygarver** [elementary/appcenter#721]
appcenter-daemon has no launch delay or any consideration for if it's a good time to check for updates. I don't want my web browser to compete with apt for network resources as soon if I start surfing immediately. I don't want to wait for appcenter-daemon to release apt if I jump into a Terminal and start trying to using apt.

Possible solutions are AppCenter could remember the last time it checked for updates OR some other kind of delay.

**Comment by mmstick** [comment]
Using a timestamp would be a good idea, I think. Perhaps only check once a day?

**Comment by davidmhewitt** [comment]
The daemon now autostarts 60 seconds after the rest of the session and only refreshes its cache if it's >24 hours since it last did it.
