### ISSUE TITLE
Integrate with GitHub issue tracker

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#723]
If an issue URL is a recognized/supported GitHub repository, we could integrate a native issue reporting flow similar to what you see in the Slack/GitHub integration.

This would probably require some sort of GitHub Online Accounts integration to file the issue on behalf of the user.

**Comment by danrabbit** [comment]
I was thinking about something similar for extending the Report an Issue dialog in System Settings → About. I think it would probably be worth it to split it out into its own app at that point. It would probably be useful for other downstreams that might not necessarily want to use Switchboard or AppCenter.

**Comment by danrabbit** [comment]
I'm gonna close this since Feedback is now its own app and any progress on this should happen there
