### ISSUE TITLE
Send message to developers after donating

### ISSUE THREAD

**Issue by jacobduba** [elementary/appcenter#724]
A nice little touch would be for users to be able to send a message after donating to the author of the project.

**Comment by cassidyjames** [comment]
@mooshoe interesting idea! Do you mean paying for an app when installing, using the "Fund" button in the footer, or both? 

The next question is how we'd actually send these messages; right now there's intentionally not much of a UI to the AppCenter Dashboard (where developers submit their apps), and I don't think we'd want to add UI for this sort of feature. We could use email to send them in one of a couple of ways:

1. Show a box in AppCenter itself, then have AppCenter hit a Houston (AppCenter Dashboard) API, and have Houston itself send an email with that message to the developer. This is the simplest for users, but probably the most complex to implement.

2. Either completely defer to #725, or in combination with it, show a button to email the developer in a success dialog for the payment. This is relatively easy to implement (assuming #725 were to be implemented), but could be more complex for users, e.g. if they have not set up a local email app yet.

**Comment by mooshoe** [comment]
Originally was talking about a little dialog paying for the app while 
installing and the message being routed through Houston, but I relieve 
that would take some time to program and then maintain.

#2 seems like a better option, how about a little GtkPopover menu that 
shows up after installing an application or visiting an installed app 
that gives hints, such as emailing the developer thanks, reporting 
bugs, or even for apps you haven't donated to and are installed, a 
little message suggesting the user should buy the app.
