### ISSUE TITLE
Open App center in the Updates tab when it is opened because of an available update message

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/appcenter#727]
Currently, whenever there are updates available the App Center appears in the dock. Upon opening it, it goes to the home screen that showcases some of the apps, just like when opens the app any other time. It would be better if it opened, in this case, straight into the Updates tab since that's the reason it was opened.

**Comment by danrabbit** [comment]
If you click the updates notification it will open to the Update view. I'm unsure that we should change the opening behavior when we can't be certain of the users' intent. That might feel a little non-deterministic.

@cassidyjames thoughts?

**Comment by cassidyjames** [comment]
Yeah I agree with @danrabbit that it might seem non-deterministic if we change the behavior based on the presence of updates. We have a desktop action for updates as well as the notification like you said.

**Comment by danrabbit** [comment]
Closing as “Design Conflict” since there are multiple ways to intentionally open directly to the updates view
