### ISSUE TITLE
Fonts of some categories don't support some diacritics

### ISSUE THREAD

**Issue by jendamarek** [elementary/appcenter#736]
In czech language a letter "ě" is used, that is not supported by those fonts. It looks ugly. (This will probably affect some other languages too)

![snimek z 2018-07-09 09 25 41](https://user-images.githubusercontent.com/16108101/42442728-fefc8f5c-835a-11e8-92b2-70c83255976b.png)

**Comment by danirabbit** [comment]
Adding info from #352 since this has a screenshot:

> We need fallback cyrillic fonts for HVD Bodedo and Limelight.
> My suggestion is [Pangolin](https://fonts.google.com/specimen/Pangolin) for HVD Bodedo (Open Font License) and [20DB](https://www.fontsquirrel.com/fonts/20-db) for Limelight ([free](http://www.typetype.ru/faq/) for commercial use).
