### ISSUE TITLE
AppCenter keep crashing and freezing  

### ISSUE THREAD

**Issue by karim-inabi** [elementary/appcenter#748]
this problem happen to me a lot so here is some help to fix it :
-when i try to download the new update its fine but when update and i search an app its freeze instantly .
- when i put two apps or more to download its crash.
-and when i download the driver ( dcmwl-kernel-source) (ver 6.30.223.271) for my ( BCM43142 ) the hole system crash like nothing work, forced to do a hard shutdown 
hope you fix it guys thank .

**Comment by mmstick** [comment]
Should this be closed now?
