### ISSUE TITLE
Keep popping apt-get update error

### ISSUE THREAD

**Issue by Himanshu-Mishr** [elementary/appcenter#749]
I have some issue with one of my docker ppa and it throws error while doing sudo apt-get update in terminal. But when I open AppCenter this error message is shown in a popup. Even if I "Ignore" or "Try again" it doesn't go away. It pops-up again with same error message.
![screenshot from 2018-07-26 10 23 08](https://user-images.githubusercontent.com/1938285/43242450-c4b1f460-90be-11e8-84c1-3cecede920b9.png)

**Comment by tintou** [comment]
You seems to have added PPAs to your installation, please make sure that the APT source has the right codename (it should be `bionic` for juno for instance)

**Comment by Himanshu-Mishr** [comment]
Hi @tintou , I know how to fix PPA related issues, my point here is about popup. It doesn't even close if click "Ignore", which it should. W.r.t to ppa which I will fix, but there are users out there who simply use ppa to install softwares, and some of them run into issue like above. So even if they want to fix it, there is no way in appcenter to do that. So do you expect them to browse and open terminal and run some fix?

**Comment by Garbee** [comment]
> So do you expect them to browse and open terminal and run some fix?

There is no GUI for adding PPAs so... Yes. You had to get into the terminal most likely to get it setup. So you should know how to use the terminal to fix the issue. Elementary only supports installing software from their repositories and through the Software Center. If you're explicitly side-stepping that, then its the "you broke it you buy it" mantra.
