### ISSUE TITLE
Disable share menu on non-curated apps

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#776]
Since our AppCenter web URL only shows results for curated apps now, we need to not show the "share" menu on non-curated footers.

**Comment by alexgleason** [comment]
@donadigo It does not, for example see Audacity: https://appcenter.elementary.io/audacity.desktop

I'm on 0.4. Share button gives me the above URL.

I imagine the service could forward users to the ugly Ubuntu page for it, eg https://packages.ubuntu.com/cosmic/audacity but more ideally render a nice looking page from this data.

Either way, probably better to disable the button for now.

**Comment by cassidyjames** [comment]
@donadigo 

>Since our AppCenter web URL only shows results for curated apps now

That is something fairly easy to test, and is called out in the original message. :wink: The revamped AppCenter website is no longer a generic redirect, but actually generates pages for each app from the AppCenter repo. Which means it does not work for non-curated apps.

I'm putting some work into making the 404 page better on the AppCenter website, but regardless, going forward URLs will just exist for curated apps. The AppCenter infrastructure just doesn't make sense for apps that we don't control whatsoever.

**Comment by danrabbit** [comment]
I kinda wish it still had the dumb redirect just because I feel like the value is in getting people using AppCenter instead of Terminal commands
