### ISSUE TITLE
No apps in header (on Loki)

### ISSUE THREAD

**Issue by peteruithoven** [elementary/appcenter#782]
Since a while no apps are shown in the header in the AppCenter. I'm on Loki. Is that normal? 
I forgot if it was a curated section of featured apps.
![screenshot from 2018-08-29 11 45 54](https://user-images.githubusercontent.com/523210/44780184-a4dedd00-ab81-11e8-9a36-654f6ae48e13.png)

**Comment by danrabbit** [comment]
This needs a backport of https://github.com/elementary/appcenter/commit/5b00623f9be5f20923934bc0c162905b2ae436b8

**Comment by danrabbit** [comment]
Closing because Loki is no longer supported
