### ISSUE TITLE
UI blocks on opening an app info view while updating repositories

### ISSUE THREAD

**Issue by mmstick** [elementary/appcenter#787]
There are two issues:

1. If the system does not contain any apt lists (located in `/var/lib/apt/lists/`), the app center seems to not request for an apt update to fech them.
2. If the system requires to fetch updated dist files from repos, the UI will freeze when opening an app view, which can easily last many minutes on a fast connection after a fresh install that requires updating everything.

I think this may be a source of frustration for a lot of people on fresh installations. I've been told that someone just installed Ubuntu and was happier with GNOME Software because of their first experience with AppCenter being that it freezes.

**Comment by mmstick** [comment]
In Views::AppInfoView, it seems to get caught on `set_up_package (128);`

**Comment by mmstick** [comment]
Seems to be caused by the overriden `update_state` method in Views::AppInfoView, on `get_app_download_size.begin ();`

**Comment by davidmhewitt** [comment]
I believe this was already an issue before the download size feature was implemented. It'll probably be to do with the fact that packagekit queues operations and only does one at a time.

**Comment by mmstick** [comment]
@davidmhewitt It does seem to be happening at `var deps = yield client.get_needed_deps_for_package (package, app_download_size_cancellable);` The UI should probably run this in the background and show the details that it can on the app info view, rather than freezing.

**Comment by mmstick** [comment]
I've fixed the hang in `get_app_download_size()`. There's another hang that I need to fix before I submit a PR for this, though.

**Comment by mmstick** [comment]
The usage of `yield` everywhere kind of makes this difficult to solve for the install button, since each yield is a blocking operation, but you can't use `yield` within a background thread's closure, in addition to the inability to use pass a reference to an atomic integer to an async method. Looking for workarounds.

**Comment by mmstick** [comment]
I've figured it out. PR coming soon.
