### ISSUE TITLE
Having trouble running changes after build with meson

### ISSUE THREAD

**Issue by liamkinne** [elementary/appcenter#794]
When I run ninja, it compiles and obviously is compiling my changes to the code, but when I run the app it doesn't show any of my changes.

I'm following the readme exactly and even when I run the /build/src/io.elementary.appcenter file, it doesn't work.

**Comment by davidmhewitt** [comment]
Hi Liam,

AppCenter runs as a daemon and only one instance can run at a time. So what's probably happening is the version that was running as a daemon before you made changes is being brought up when you try and run a new instance.

Try a `killall io.elementary.appcenter` first.

Hope that helps!
