### ISSUE TITLE
Revise email entry tooltip text

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#799]
This tooltip is currently, "Your email address is used to send a receipt. It is never stored and you will not be subscribed to a mailing list."

This is not entirely accurate as _Stripe_ technically stores the email address on the transaction, even though _we_ don't. It should probably be revised to something like, "Your email address is only used to send a receipt. You will not be subscribed to any mailing list."

**Comment by davidmhewitt** [comment]
Closing this issue as the PR has been merged. Please re-open if it was left open for some other reason.
