### ISSUE TITLE
Throw an explicit content warning dialog

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#808]
As a stopgap to more fine grained OARS data, we should just throw a dialog asking that the user is aware the app contains explicit data and they're sure they want to install it. Something like:

FooBar Contains Explicit Content
FooBar may contain content only suitable for adults or that may be sensitive or disturbing. In general, elementary does not review or endorse the content of this app.

[ ] Do not show this dialog again

[ Don't Install ] [ Install Anyway ]

**Comment by danrabbit** [comment]
Tags to watch for are:

violence-realistic
violence-bloodshed
violence-sexual
drugs-alcohol
drugs-narcotics
drugs-tobacco
sex-nudity
sex-themes
sex-prostitution
sex-appearance
language-profanity
language-humor, only if "intense"
language-discrimination
social-chat

**Comment by cassidyjames** [comment]
Marking this as critical since it is time-sensitive due to an app currently shipping in AppCenter.
