### ISSUE TITLE
Appcenter crashing upon launch

### ISSUE THREAD

**Issue by sujop** [elementary/appcenter#821]
The appcenter crashes upon launch.
The dmesg command shows the below error message.

 io.elementary.a[2487]: segfault at 0 ip 00007f38f599b5a1 sp 00007ffcf53c6498 error 4 in libc-2.27.so[7f38f580d000+1e7000]

**Comment by sujop** [comment]
Uninstalling Clipped resolved the problem.

**Comment by harisvsulaiman** [comment]
Why is that happening?
