### ISSUE TITLE
weblate not allowing to save translation

### ISSUE THREAD

**Issue by josprachi** [elementary/appcenter#822]
I logged in to weblate today, and selected app center and then translate button. It took me to translation page but when I pasted translated string, the save option is disabled saying "insufficient privileges for saving translations". how to save the translations

**Comment by ryonakano** [comment]
@josprachi By default, you're only able to suggest translations in Weblate. If you would like to save your translations, please [join the translators Slack](https://ele-l10n.slack.com/join/shared_invite/enQtMjkwMjI2Mzk5ODQxLWM3NWZlMjMxMTUyNzg0MjdiNTdkYTM5ZDA3NzE5YTIwMzZmZjhmZjg0MzQwMGE5MjVhMGU2Yjk2MDU1MGZiYTU) and message an admin your Weblate username and what language you want to translate.

**Comment by josprachi** [comment]
> @josprachi By default, you're only able to suggest translations in Weblate. If you would like to save your translations, please [join the translators Slack](https://ele-l10n.slack.com/join/shared_invite/enQtMjkwMjI2Mzk5ODQxLWM3NWZlMjMxMTUyNzg0MjdiNTdkYTM5ZDA3NzE5YTIwMzZmZjhmZjg0MzQwMGE5MjVhMGU2Yjk2MDU1MGZiYTU) and message an admin your Weblate username and what language you want to translate. Then you should be able to save your translation.

Thank you @ryonakano
