### ISSUE TITLE
Clicking on a specific app crashes the AppCenter

### ISSUE THREAD

**Issue by aleksandar-todorovic** [elementary/appcenter#823]
I can reliably crash AppCenter by going to the Accessories and clicking on [Clipped](https://appcenter.elementary.io/com.github.davidmhewitt.clipped/).

There seem to be some edge case that's causing AppCenter to break every time you click on it. The spin bar would last approximately two seconds before the AppCenter crashes, and the image for the app never loads. Terminal output only returns segmentation fault:

```
[1]    3560 segmentation fault  io.elementary.appcenter
```

As far as I can tell, this is the only app that crashes the AppCenter. There's no mention of that app in the issue tracker, so I'm assuming this is a brand new report.

**System:** Fully updated elementary OS Juno.

**Comment by aleksandar-todorovic** [comment]
Should have read two sentences below that a gdb output might help. Here it is:

```
Starting program: /usr/bin/io.elementary.appcenter 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe6b55700 (LWP 5537)]
[New Thread 0x7fffe6354700 (LWP 5538)]
[New Thread 0x7fffe5b53700 (LWP 5539)]
[New Thread 0x7fffd6991700 (LWP 5540)]
[New Thread 0x7fffcf383700 (LWP 5546)]
[New Thread 0x7fffce970700 (LWP 5548)]
[Thread 0x7fffce970700 (LWP 5548) exited]
[Thread 0x7fffcf383700 (LWP 5546) exited]
[New Thread 0x7fffcf383700 (LWP 5553)]
[New Thread 0x7fffce970700 (LWP 5554)]
[New Thread 0x7fffcdb5f700 (LWP 5578)]
[New Thread 0x7fffcd35e700 (LWP 5579)]
[New Thread 0x7fffccb5d700 (LWP 5581)]
[Thread 0x7fffcdb5f700 (LWP 5578) exited]
[New Thread 0x7fffcdb5f700 (LWP 5604)]
[Thread 0x7fffcdb5f700 (LWP 5604) exited]
[New Thread 0x7fffcdb5f700 (LWP 5605)]
[Thread 0x7fffcdb5f700 (LWP 5605) exited]

Thread 1 "io.elementary.a" received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
62	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
```

**Comment by peteruithoven** [comment]
I'm pretty sure they are working on this here: https://github.com/elementary/appcenter/pull/816

**Comment by aleksandar-todorovic** [comment]
You are correct. I only searched through issues (not pull requests), so I didn't catch that.

**Comment by davidmhewitt** [comment]
I'm going to re-open this just so we have a reference to it on Github as well as on reddit where the bug was originally reported.

Thanks for opening the issue.
