### ISSUE TITLE
Better icons for plugins

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#835]
In the updates view, plugins need better icons. Maybe some sort of badging system where we use the icon that it's a plugin of?

**Comment by davidmhewitt** [comment]
Either of these work?

![screenshot from 2018-10-07 20 10 41 2x](https://user-images.githubusercontent.com/3372394/46585783-28d39100-ca6d-11e8-98c8-8c55eccc3202.png)

![screenshot from 2018-10-07 20 13 46 2x](https://user-images.githubusercontent.com/3372394/46585808-8bc52800-ca6d-11e8-9a22-6d3fc55cc6fb.png)

**Comment by danrabbit** [comment]
I think I'm leaning toward the plugin icon with the app icon badge. Makes the actual app stand out more
