### ISSUE TITLE
Install button moved and cropped after failure?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/appcenter#837]
The pay / install button is moved and cropped to the right after an installation failed. 
![screenshot from 2018-10-04 23 41 31](https://user-images.githubusercontent.com/523210/46506546-f3446300-c834-11e8-9b17-282b6ae80219.png)

One easy way to reproduce it is to 
1. Start a new installation in Terminal `sudo apt install ...`
2. Not enter `Y` yet
3. Attempt to install the app

This will fail, a popup will be shown and from then on the pay / install button is moved and cropped. 

Pressing the Search (back) button will even show a moved / cropped install button in that view:
![screenshot from 2018-10-05 00 22 22](https://user-images.githubusercontent.com/523210/46506661-4b7b6500-c835-11e8-984b-3e9cd04e74a2.png)

The moving and cropping was also noticed in: #833

**Comment by jeremypw** [comment]
I am not sure this is the right solution.  It results in buttons of differing sizes - how different depends on the locale.  Need UX input on this.  Need a way of fixing all the button sizes to the widest one (whether visible or not)
