### ISSUE TITLE
After 1 uninstall missing padding in uninstall button 

### ISSUE THREAD

**Issue by peteruithoven** [elementary/appcenter#838]
Reproduce:
1. Install app
2. Uninstall app
3. Install app

![screenshot from 2018-10-05 00 30 07](https://user-images.githubusercontent.com/523210/46506840-f8ee7880-c835-11e8-921b-096b92ba882d.png)

**Comment by hannesschulze** [comment]
I think this issue isn't related to the padding of the button, but rather to the size group. Maybe the first time displaying the buttons, both of them use the size of the "Uninstall"-button. When displaying the buttons a second time, they just use the size of the "Open"-button. I think this is related to the SizeGroup that is being used to make these two buttons the same width.

![screenshot von 2018-10-11 22 03 51](https://user-images.githubusercontent.com/43932053/46830873-1aa1af80-cda2-11e8-902f-6332f82f70f0.png)

**Comment by peteruithoven** [comment]
@hannesschulze I think you're right! PR coming up...
