### ISSUE TITLE
Sort plugins below their respective app

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#854]
In search results, it would seem more relevant to bubble apps above their respective plugins. For example, searching for Gedit should probably return Gedit first, then its plugins. Right now the app itself is mixed in with its plugins which is crappy.

**Comment by davidmhewitt** [comment]
It's pretty easy to sort plugins lower than not plugins for the whole list, but not so easy to sort plugins under their associated apps and then have more plugin and not plugin results below. Is that an acceptable compromise?

**Comment by cassidyjames** [comment]
@davidmhewitt I guess if we fix plugins displaying on the respective app's page, I would be inclined to not even show plugins in the search results at all. So maybe that's a better way forward, anyway.

**Comment by davidmhewitt** [comment]
Indeed, I've already fixed that issue upstream in Appstream, we just need to either patch it or wait for a new release and backport that.
