### ISSUE TITLE
removing applications fails if backend doesn't support autoremove

### ISSUE THREAD

**Issue by decathorpe** [elementary/appcenter#860]
Attempting to uninstall a package results in this log message, if the backend doesn't support autoremove:

```
Package.vala:351: Operation failed for package Notejot - autoremove is not supported
```

The GUI silently fails to remove the app and simply does nothing. Maybe appcenter should fall back to attempting the removal without the `autoremove` option, or detect if the backend supports it?

**Comment by davidmhewitt** [comment]
There doesn't seem to be a way to dynamically detect whether the backend supports this via packagekit. It seems gnome-software achieves this for autoremove by making it a meson option and disabling autoremove at compile time if it's disabled.

I propose we go this route too.

**Comment by decathorpe** [comment]
:disappointed: yeah I guess if PackageKit doesn't expose this information about the backend, then a compile time switch will probably be the best we can do

Thanks for looking into this.

**Comment by Conan-Kudo** [comment]
I've made a PR to implement support for `autoremove` in the PackageKit DNF backend: https://github.com/PackageKit/PackageKit/pull/526

**Comment by danirabbit** [comment]
Closing since we don't use PackageKit anymore yay
