### ISSUE TITLE
Test if backend supports DependsOn before trying to calculate download size

### ISSUE THREAD

**Issue by decathorpe** [elementary/appcenter#861]
When opening the details page of an application in fedora, I get this warning message in the logs:

```
Client.vala:719: Error fetching dependencies for notejot;1.4.5-1.fc29;x86_64;updates-testing: DependsOn not supported by backend
```

What is this query supposed to achieve? Is the result used for anything? Is it important, or can the failure be ignored? It doesn't break installing the package.

**Comment by davidmhewitt** [comment]
This is used to calculate the total download size of a package (including not installed dependencies), so can safely be ignored.

However, I guess it would make sense to do some feature testing to see if that feature was available on the backend before trying to do it. I'll amend the issue title accordingly

**Comment by davidmhewitt** [comment]
There doesn't seem to be a way to dynamically detect whether the backend supports this via packagekit. It seems gnome-software achieves this for autoremove by making it a meson option and disabling autoremove at compile time if it's disabled.

I propose we go this route too.

**Comment by Conan-Kudo** [comment]
I'm hoping to implement `DependsOn` and `RequiredBy` for the DNF backend in PackageKit soon: https://github.com/PackageKit/PackageKit/pull/495
