### ISSUE TITLE
Non translated quantities overflow the payment dialog

### ISSUE THREAD

**Issue by febrezo** [elementary/appcenter#863]
Non translated messages are showing a clumsy dialog that makes it difficult to guess their purpose and that look bad. This is an example taken from the Spanish version:

![seleccion_118](https://user-images.githubusercontent.com/1590496/47045164-713c2e80-d192-11e8-84f4-609ba6a97717.png)

**Comment by Suzamax** [comment]
I think one solution is to remove everything, leaving only  the quantity. Someone mistranslated it.

**Comment by danrabbit** [comment]
Translation fix has been accepted in Weblate. This should be resolved on the next update to AppCenter
