### ISSUE TITLE
Searching applications by name doesn't work well

### ISSUE THREAD

**Issue by JMoerman** [elementary/appcenter#864]
My application _Go For It!_ ([com.github.jmoerman.go-for-it](https://github.com/JMoerman/Go-For-It)) is quite hard to find when searching by name. When searching for "go for it", it only shows up after around 20 other results. When searching for the last part "it!" (or "go for it!") it is, however, shown in the first place.
Other apps are also affected by this, but _Go For It!_ is the most heavily affected application I am aware of as for most users the app isn't really discoverable until the full name has been entered.

I do not know the cause of this but I guess that 

- the application name doesn't have higher priority than words in the description.
- Searching works by comparing individual words, word combinations and word order is not taken into account. 

Update: The situation seems to be better right now (first of februari, 2019), but there still is room for improvement.

**Comment by peteruithoven** [comment]
I must have missed this issue while writing https://github.com/elementary/appcenter/issues/942, I'm assuming this has the same underlying issue that David pointed out, so I'm closing this one. You could open an new issue at https://github.com/ximion/appstream if you have other issues with how that search works, like the priority of application name for example.

**Comment by JMoerman** [comment]
Thanks for pointing me to that issue! Searching is as bad as before again (well, its worse as now appcenter gets laggy, but that is probably be unrelated), so I'm looking forward to a proper fix.
