### ISSUE TITLE
deb & snap installations

### ISSUE THREAD

**Issue by saitam1** [elementary/appcenter#867]
Is it possible to have such an overview of all deb and snap installations like this:

![appcenter](https://user-images.githubusercontent.com/23245678/47139348-ddff1800-d2bb-11e8-9c9f-4a704b6e1d22.png)

It would kill all other distributions in the field of package installation management

**Comment by Conan-Kudo** [comment]
That's not the focus of AppCenter. As the name implies, the focus is on Applications, so splitting in that manner would be counterproductive.

**Comment by peteruithoven** [comment]
Also, people shouldn't have to know technical terms (/ extensions) like `deb` and `snap`. 

In regards to snap support: https://github.com/elementary/appcenter/issues/27
And Flatpak support: https://github.com/elementary/appcenter/issues/712

**Comment by saitam1** [comment]
But then at least it would make sense if deb and snap installations could be installed by the appcenter at all. Similar to Ubuntu Software, but better (no double installations, checking whether the same app is already installed via an other package manager, etc.)

**Comment by danrabbit** [comment]
AppCenter the app is intended to be a client for AppCenter the server. Since the server delivers deb packages, that's what AppCenter supports.

Sideloading apps from outside of the AppCenter ecosystem isn't within the scope of AppCenter. You can use apps like Eddy or Snaptastic to sideload apps.
