### ISSUE TITLE
AppCenter doesn't download system updates

### ISSUE THREAD

**Issue by MauricioFIUBA** [elementary/appcenter#875]
![image](https://user-images.githubusercontent.com/31808401/47514794-9ba77f00-d857-11e8-8146-81f1c7cb899e.png)
I click on the "Update" button, asks for my password and then says "wait", "loading cache" and nothing happens, just returns to the state of the image.

**Comment by peteruithoven** [comment]
Could you try running the following in Terminal:
```
sudo apt update
sudo apt upgrade
```
Do you see errors?

**Comment by MauricioFIUBA** [comment]
Thanks for the answer!, I restarted my laptop and it worked again. I do not know why it happened, but maybe is related that also updated apt.
![image](https://user-images.githubusercontent.com/31808401/47536439-4e96cd80-d896-11e8-9031-e98d73fa20ae.png)

Anyway, i close this issue.
