### ISSUE TITLE
UI: repetitive display of currency in the amount selection 

### ISSUE THREAD

**Issue by megatux** [elementary/appcenter#883]
Three times and so close each other is too much, IMHO:
![captura realizada el 2018-10-31 12 42 35](https://user-images.githubusercontent.com/850020/47800406-faaf3d00-dd0a-11e8-951d-1f2fc09fb8a2.png)

**Comment by megatux** [comment]
I see. Probably can be solved that way, but I guess it should be clear for all locales what is the intention. e.g. PUT the currency symbol above in the suggested price AND NOT in the other options, below.
I'll check the app code and .po files :+1:

**Comment by davidmhewitt** [comment]
I'll close this as it appears to have been resolved in the translations.
