### ISSUE TITLE
My app cannot open in AppCenter

### ISSUE THREAD

**Issue by panosx2** [elementary/appcenter#899]
i noticed that every time i try to open the page of my app in AppCenter (i use Loki) the AppCenter closes unexpectedly. However, i can install it if i don't try to open the page. The other users too, i guess.

https://github.com/panosx2/brightness: **Dimmer**

**Comment by davidmhewitt** [comment]
This does not appear to be an issue anymore on Juno, or at least it's not reproducible for me. So I'll close it due to the age of the issue.
