### ISSUE TITLE
Scrolling down quickly on a product page with "Other Apps by..." results in artifacts

### ISSUE THREAD

**Issue by eljefuri** [elementary/appcenter#910]
![screenshot from 2018-11-08 19-43-38](https://user-images.githubusercontent.com/44387419/48199529-de587380-e38e-11e8-9271-cd9f5351edd9.png)
![screenshot from 2018-11-08 19-43-39](https://user-images.githubusercontent.com/44387419/48199530-df89a080-e38e-11e8-8201-af4e0f9dae64.png)

**Comment by peteruithoven** [comment]
This was previously reported as an issue after a cold open: https://github.com/elementary/appcenter/issues/538

**Comment by eljefuri** [comment]
@peteruithoven I can confirm that this problem is still present and is not exclusive to a cold open.

**Comment by arshubham** [comment]
After a new install I noticed that this only happen on using nvidia GPU for me. I see no artifacts when using intel integrated graphics. @eljefuri can you confirm this?

**Comment by J0Ar** [comment]
**Type of graphic card is not relevant**
For me the issue occurred more often in the first days of appcenter but now has become very rare.
It is difficult to reproduce :/
Some screenshots and hardwareinfo… 
1¬![bildschirmfoto von 2018-12-28 11-20-59](https://user-images.githubusercontent.com/23266409/50513050-a66bd380-0a95-11e9-83e2-0acb8e669865.png)
2¬![bildschirmfoto von 2018-12-28 11-19-30](https://user-images.githubusercontent.com/23266409/50513053-a9ff5a80-0a95-11e9-89d8-bec3ca8c4b73.png)
Systeminfo¬![bildschirmfoto von 2018-12-28 11-38-58](https://user-images.githubusercontent.com/23266409/50513054-ac61b480-0a95-11e9-973f-9421b0a87dd0.png)

**Comment by NathanBnm** [comment]
> @arshubham It is happening for me with integrated (low-end) Intel graphics chips on multiple computers. None of them have any nvidia hardware.

I also have this configuration and I have the same problem. It seems to happen only when you scroll too fast to the bottom of the app page in AppCenter. When the page is completely loaded it's fixing the problem.

Here is a screenshot:

![Screenshot 2019-01-15 17 57 56](https://user-images.githubusercontent.com/45366162/51196982-a02c8280-18f0-11e9-8f29-aabaaaf2214d.png)

**Comment by terndrup** [comment]
This also happens on my machine. It appears that the size of the container is allocated before any screenshots are loaded. Once the images get loaded, they push the bottom links "License Homepage Translations etc." further down outside of the card. Triggering any sort of redraw (resizing window, window re-focus, navigate back and forth) fixes this issue.

**Comment by danirabbit** [comment]
I believe this has been resolved. I'm unable to reproduce it any longer. Please reopen if the issue can be reproduced in OS 7 :)
