### ISSUE TITLE
Patreon and AppCenter - bypass pay

### ISSUE THREAD

**Issue by rafaelcorsi** [elementary/appcenter#917]
Whenever I try to install (update) a elementary app and it asks me to pay for it I feel kind of bothered by the fact that **I donate in the Patreon**. I'm about to cancel my monthly donation to elementary and start paying for the apps in the AppCenter, with this I will have a better incoming.

Solution:

- The app shall connect the user to the Patreon and if it already contributes there, it shall bypass the "pay for the app".

**Comment by davidmhewitt** [comment]
These are two different things:

* The apps in AppCenter that you can pay for are often written by independant third-party developers that often aren't associated with the elementary project (think like the Apple/Android app stores; when you buy an app there, you're not giving much to Apple/Google, you're paying the developer of the app)/
* The patreon page you donate on is to support the development of _elementary OS itself_. You are helping to fund the elementary staff, hosting costs and development/updates to the OS and its default applications.

On this basis, I don't think this is a feature that would be considered as it takes potential income out of the hands of developers, which is opposite to the goal of the AppCenter. AppCenter is designed to try and get indie open-source developers paid for their work.

**Comment by cassidyjames** [comment]
I agree with @davidmhewitt, these are two very different things. Taking a revenue stream away from developers is a bad idea.
