### ISSUE TITLE
Appcenter won't check for updates nor show new apps

### ISSUE THREAD

**Issue by SubhadeepJasu** [elementary/appcenter#924]
Pretty much as said above, even when apt update and apt upgrade has been run. The loading icon in front of the search bar won't appear.

**Comment by peteruithoven** [comment]
What happens when you start AppCenter after running the following command to kill all AppCenter processes running in the background?
```
killall io.elementary.appcenter
```

**Comment by SubhadeepJasu** [comment]
AppCenter started working after a couple of restarts. Before last restart the app center was reinstalled using apt remove app-center and apt install app-center. Though the problem was solved let's keep this issue open until the root cause of the issue it found.

**Comment by NitroNils** [comment]
Had the same issue after fresh install.
Killed it with the killall-command and it now works.

**Comment by davidmhewitt** [comment]
I'm cleaning up the issue tracker and I feel it's best to close this issue as we never got the root cause. Please feel free to re-open or open a new issue with some further details if it's something you're still experiencing occasionally.
