### ISSUE TITLE
Better distinguish plugins in list views

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#929]
Right now plugins just show their name in list views, like in updates. I think it'd be nice to show the app name in a dim label next to the plugin name, or something to better associate them.

**Comment by danrabbit** [comment]
I kind of wonder if they should be grouped/collapsed in some way?

**Comment by davidmhewitt** [comment]
Once we get a newer version of appstream, all plugins will show on an apps page anyway instead of just one. I'd be tempted to remove plugins altogether from list views then.

**Comment by cassidyjames** [comment]
So then the question becomes: do we show the app in the list of updates even if just one of its plugins was updated? I guess that would make sense, but I'd be worried it's not clear what actually is being updated.

**Comment by davidmhewitt** [comment]
We've just discussed this on the call and I think the agreement was that we only show plugins in the installed view if they have updates available, otherwise they won't be shown in any list views and will only be visible/available from the page of the parent app.
