### ISSUE TITLE
Unable to pay for Torrential - Problem processing payment

### ISSUE THREAD

**Issue by ToroNZ** [elementary/appcenter#931]
Using Loki, first try AppCenter crashed, second try I got this error:

![image](https://user-images.githubusercontent.com/8522935/50469109-eab49080-0a0f-11e9-9337-bbae65f2631f.png)

Tried using a NZ based card. Can't see the payment taken out of my account so I'd say in never left my laptop :(

**Comment by davidmhewitt** [comment]
I'm going to close this issue as we haven't had many recent reports of crashes during payment or payment issues in general. It's possible that these were temporary issues or that Stripe didn't like the card provided.
