### ISSUE TITLE
Screenshots should be localized

### ISSUE THREAD

**Issue by bigfatbird** [elementary/appcenter#933]
Not sure if this belongs to houston or appcenter, but when you scroll apps and have set the OS language to something different than english a developer should be able to upload language specific screenshots.
It's inconvenient to browse your computer in German/Hindu/Japanese/whatever and AppCenter displaying an apps user interface in English.

Requires effort from the developer, for sure.

**Comment by tintou** [comment]
The screenshots are already translatable, it is up to the developers to provide them all:
[Link to the AppStream specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots)
```xml
<screenshots>
​  <screenshot type="default">
​    <caption>The FooBar main window.</caption>
​    <image type="source" width="1600" height="900">https://example.com/foobar/screenshot-1.png</image>
​    <image type="source" width="1600" height="900" xml:lang="de_DE">https://example.com/foobar/screenshot-1-de_DE.png</image>
​    <image type="source" width="1600" height="900" xml:lang="fr_FR">https://example.com/foobar/screenshot-1-fr_FR.png</image>
​  </screenshot>
​  <screenshot>
​    <caption>Foobar showing the frobnicate functionality.</caption>
​    <image type="source" width="1600" height="900">https://example.com/foobar/screenshot-2.png</image>
​    <image type="source" width="1600" height="900" xml:lang="de_DE">https://example.com/foobar/screenshot-2-de_DE.png</image>
​    <image type="source" width="1600" height="900" xml:lang="fr_FR">https://example.com/foobar/screenshot-2-fr_FR.png</image>
​  </screenshot>
</screenshots>
```

**Comment by bigfatbird** [comment]
Thank you. Gonna close this and hope developers start sing this feature a lot.
