### ISSUE TITLE
Updates not listed?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/appcenter#938]
The updates count in the Installed badge seems off with the contents off the Installed page:
![screenshot from 2019-01-21 19 28 29 1](https://user-images.githubusercontent.com/523210/51492718-14649b80-1db3-11e9-9c1e-5aa00b93747c.png)

Apt does report there are updates available:
```
$ apt list --upgradable
Listing... Done
com.github.bartzaalberg.snaptastic/bionic 0.7.0 amd64 [upgradable from: 0.6.0]
com.github.calo001.fondo/bionic 1.2.0 amd64 [upgradable from: 1.1.4]
com.github.philip-scott.spice-up/bionic 1.8.0 amd64 [upgradable from: 1.7.0]
```

Restarting AppCenter (not the background process) doesn't change anything.
Also killing that background process (`killall io.elementary.appcenter`) results in the same. 
Running `sudo appstreamcli refresh-cache --force` doesn't help.

Going to a specific app's page does show it's upgradable:
![screenshot from 2019-01-21 19 49 15](https://user-images.githubusercontent.com/523210/51493465-b9807380-1db5-11e9-9dec-68723dd38a3a.png)

**Comment by NathanBnm** [comment]
@peteruithoven I just noticed that I have the same problem, sometimes there is an update but no way to update from AppCenter but the notification icon appears anyway
