### ISSUE TITLE
Duplicated entries in Trending & Recently Updated apps

### ISSUE THREAD

**Issue by megatux** [elementary/appcenter#939]
Happened a few times to me :
![captura realizada el 2019-01-22 09 29 03](https://user-images.githubusercontent.com/850020/51560363-138b4280-1e63-11e9-9c1c-026414011a87.png)
and reported by someone else, too :
![screenshot from 2019-01-23 00-05-11](https://user-images.githubusercontent.com/850020/51560375-19812380-1e63-11e9-9aa7-eac3a49f951c.png)

**Comment by cassidyjames** [comment]
I occasionally get this as well. I'm assuming somehow the API is being hit twice, or the results are cached and then retrieved again? Regardless, we should probably just de-dupe the carousels anyway.
