### ISSUE TITLE
Search issues

### ISSUE THREAD

**Issue by peteruithoven** [elementary/appcenter#942]
There is something weird going on with the search on AppCenter. Searching:
- cal / calc / calcu / calcul / calculator: Expected results like Beemy, Calculator, Dippi. 
- calcula / calculat: only 2 irrelevant seeming results (these where included with the results above)
- calculato: No results

![screen record from 2019-01-23 14 12 25](https://user-images.githubusercontent.com/523210/51609577-c5397a80-1f1a-11e9-881a-b53e7a353aa8.gif)

Something similar happens while searching for "AppCenter":
- appc / appce: Results include AppCenter
- appcen / appcent / appcente / appcenter: No AppCenter

![screen record from 2019-01-23 14 27 06](https://user-images.githubusercontent.com/523210/51609690-0af64300-1f1b-11e9-9987-4a3d955a6ba7.gif)

This might be related to #240 but as you can see I do get relevant results when I search for "calcul".

**Comment by davidmhewitt** [comment]
This appears to be an issue with appstream as using the same search terms via the `appstreamcli` tool produces the same results.

i.e.
```
david@david-XPS-13-9343:~$ appstreamcli search calculato
Unable to find component matching calculato!
```

**Comment by peteruithoven** [comment]
@davidmhewitt interesting! 
In that case I'll close this one.
I've looked through their issue queue but couldn't find relevant open search issues so I've opened a new one: https://github.com/ximion/appstream/issues/216
Feel free to include additional information.
