### ISSUE TITLE
Changelog on "Installed" page is strangely narrow

### ISSUE THREAD

**Issue by bjorn** [elementary/appcenter#944]
The following changelog entry is heavily wrapping even though there seems to be really no need for this:

![screenshot from 2019-01-24 21-33-14](https://user-images.githubusercontent.com/531764/51707550-d02b0280-2021-11e9-9d99-ef54b621474f.png)

There's plenty of space on the right.

**Comment by Nikoos** [comment]
Hi,

Could it be possible to add the current changelog (or fix) provided in the installed version. For instance, when I looked at the Camera application page in AppCenter, could we have a link to a list of fixed issue for the deployed version (or maybe a link to a github release page) ?

Thanks for your hard work.

Nikos

**Comment by cassidyjames** [comment]
This should be fixed. @Nikoos please open a new issue for that.

![image](https://user-images.githubusercontent.com/611168/65837790-ce07fa80-e2b8-11e9-880a-b45df291ba98.png)

**Comment by Nikoos** [comment]
Sure will do. thanks @cassidyjames
