### ISSUE TITLE
SizeGroup Stack workaround

### ISSUE THREAD

**Issue by peteruithoven** [elementary/appcenter#951]
The AppCenter uses a workaround to make sure buttons in lists are of the same size, for example:
![screenshot from 2019-02-08 17-44-57](https://user-images.githubusercontent.com/523210/52492826-4f940680-2bca-11e9-99f0-a5d580916ff0.png)

The same logic is used to make the buttons in the app info page the same size:
![screenshot from 2019-02-08 17-47-21](https://user-images.githubusercontent.com/523210/52493736-794e2d00-2bcc-11e9-9a8a-2bdee450c7f4.png)

With GTK you can use a [SizeGroup](https://valadoc.org/gtk+-3.0/Gtk.SizeGroup.html) to give multiple widgets the same size, but this only works if the widgets are visible. One workaround is putting widgets in a [Stack](https://valadoc.org/gtk+-3.0/Gtk.Stack.html) and switching to an empty child. 
This is what we [started doing](https://github.com/elementary/appcenter/pull/886)  in AppCenter resulting in code like:
``` vala
var uninstall_button = new Gtk.Button.with_label (_("Uninstall"));
var uninstall_button_stack = new Gtk.Stack ();
uninstall_button_stack.add_named (uninstall_button, "CHILD");
uninstall_button_stack.add_named (new Gtk.EventBox (), "NONE");
uninstall_button_stack.hhomogeneous = false;

var action_button_group = new Gtk.SizeGroup (Gtk.SizeGroupMode.HORIZONTAL);
action_button_group.add_widget (action_button);
// other buttons that should have the same size

set_stack_visibility (uninstall_button_stack, false);

public static void set_stack_visibility (Gtk.Stack stack, bool show) {
  if (show) {
    stack.set_visible_child_name ("CHILD");
  } else {
    stack.set_visible_child_name ("NONE");
  }
}
```

## 1. Split up lists and info views
One way of solving this would be to:
1. Not reuse this button logic in the list and info view
2. Have the list view use a single stack, no grid, because we only want to show one button here anyway
3. Don't attempt to make the buttons in the info view the same size

## 2. HomogeneousGrid 
Another way might be to make a more reusable solution that we might even be able to port to Granite. Something like a HomogeneousGrid that automatically wraps attached children into Stacks and creates an easy way to show/hide children. 
One very hacky seeming way seems to listen to the show&hide signals of the children, undo that and then use it's stack to create the same effect. 
Another is to give HomogeneousGrid something like a dedicated `set_visible(child, visible)` function. 

## 3. Other workaround?
Or maybe there is a better workaround in general? Is there an relevant open issue at GTK maybe?

**Comment by danrabbit** [comment]
Closing since we no longer have these empty stack child stuff
