### ISSUE TITLE
Purchases export import GUI

### ISSUE THREAD

**Issue by peteruithoven** [elementary/appcenter#952]
At a certain point the AppCenter started asking people for money for updating apps that people had not payed for yet. The intent here is to remind people of the option and an update is a interesting moment because it has taken the developer effort to release this update.
More info: [About AppCenter Payments](https://medium.com/elementaryos/about-appcenter-payments-daa76a1a3b59)

One of the big issues with how this currently works is that purchases are "forgotten" when:
- Reinstalling to upgrade the OS (I understand that [being able to upgrade](https://github.com/elementary/appcenter/issues/3) would also solve this)
- Reinstalling the OS
- Using the OS on multiple devices

I understand, that an online account system in which these purchases are stored would be difficult with [elementary OS's goals on privacy](https://medium.com/elementaryos/privacy-and-elementary-os-95f9f2debe98) ([also see this comment](https://medium.com/@cassidyjames/we-dont-have-any-sort-of-centralized-account-service-at-this-point-but-we-do-realize-that-s-a-5e6827b7875)) and because of the amount of effort building a good online account system would take. 

It is currently already possible to export & import payments using the terminal ([info](https://github.com/elementary/appcenter/wiki/Saving-and-Restoring-Purchases)).
I'd like to suggest we also make this functionality available through the GUI of the AppCenter.

To clarify this functionality could exist next to the ability to export & import applications, see #448.

**Comment by davidmhewitt** [comment]
@danrabbit @cassidyjames Given that there's a plan to save purchases to an "elementary account" as part of the AppCenter for everyone sprint, is this still reasonable?

I guess there's the case of people that don't have/want an account. But designing and building a whole GUI for this when it can just happen automagically if they're signed in maybe seems more excessive now?

**Comment by danrabbit** [comment]
Yeah, I'm inclined to agree that leaning on accounts for this is the better solution and it's not worth investing time into an import/export design
