### ISSUE TITLE
master: drivers don't have installed state anymore

### ISSUE THREAD

**Issue by donadigo** [elementary/appcenter#967]
After #945 was merged the drivers don't have their state updated properly (installed drivers still show an install button). This is directly caused by the removal of those lines: https://github.com/elementary/appcenter/pull/945/files#diff-e1baf3dc151728b17805be49aeeb24c5L325

**Comment by davidmhewitt** [comment]
@donadigo I'm testing this with master right now and can't reproduce it, can you test and confirm that this is still an issue?

The lines you refer to being removed are just simply further down the file.

**Comment by donadigo** [comment]
I pulled master and it now seems to work, sorry for the confusion.
