### ISSUE TITLE
Err:7 http://archive.canonical.com juno Release  404  Not Found [IP: 91.189.91.15 80]

### ISSUE THREAD

**Issue by johann2882** [elementary/appcenter#968]
E: The repository 'http://archive.canonical.com juno Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by peteruithoven** [comment]
Thanks for reporting. This has happened to some people before, but no one has been able to share what they did to cause this. Did you use some kind of PPA management software? Did you install something using a .deb file? Please share anything that could be relevant in: https://github.com/elementary/appcenter/issues/914

For info on how to solve it see:
https://github.com/elementary/appcenter/issues/914
https://elementaryos.stackexchange.com/questions/16469/juno-sources-no-release-file
