### ISSUE TITLE
AppCenter shows flickering authentication screen so fast you can not enter a password

### ISSUE THREAD

**Issue by wkoppenhol** [elementary/appcenter#987]
Please help cant install via appcenter
or via terminal

elementary os 5 juno

**Comment by peteruithoven** [comment]
Could you share a screen recording?

Could you clarify what happens when using the terminal? Maybe also with a screen recording?

**Comment by davidmhewitt** [comment]
Closing this since we never received additional information from OP and haven't had any similar reports.
