### ISSUE TITLE
When OS update is detected computer freezes until computer is shutdown completely and turned back on.

### ISSUE THREAD

**Issue by tfinnm** [elementary/appcenter#990]
So far this has been observed only with epiphany open with at least two open tabs and at least one but not all a youtube tab. Only happens when app center in not actively open but when the AppCenter Daemon detects an OS update. Also only happens when one additional program other than epiphany is open, currently has happened multiple times with the default Files app and at least once with mine craft as the other app open. Seems to have no problems when any one of these conditions is not met.

**Comment by tfinnm** [comment]
elementary OS 5.0 Juno 64-bit

Quad-Core Intel® Pentium® CPU  N3700  @ 1.60GHz
3.9 GB memory   48.9 GB storage

**Comment by peteruithoven** [comment]
Just to clarify, this is after/during the notification is shown that there are updates available?
You're not actually updating at that point right?

**Comment by tfinnm** [comment]
it is before the notification, computer freezes before the notification can be shown.

**Comment by peteruithoven** [comment]
Ah that makes more sense. Retrieving updates is quite intense. You experience similar issues when you manually run update in the Terminal?
```
sudo apt update
```

There is a change that moving to flatpak is going to improve things, see: https://medium.com/elementaryos/elementary-appcenter-flatpak-b1f970a33861

In case you have flatpak installed, do you experience similar issues when running `flatpak update`? (Note for a fair comparison you shouldn't install the updates.

**Comment by tfinnm** [comment]
sudo apt update caused a minor jolt for a minute, but no where near as bad as with the app center. It also happened again a few minutes before your comment with only eclipse and epiphany open and no youtube tabs this time. Is there anyway to disable the app center dameon, I just dont think my computer can run it right and i end up runnning sudo apt update from time to time anyway so I wouldn't be losing out on any updates. I also do not have flatpak installed.

**Comment by peteruithoven** [comment]
Good to know that there is a difference. 

You could disable appcenter by doing something like: https://elementaryos.stackexchange.com/a/8630/3892

**Comment by peteruithoven** [comment]
Could you try running the version on github, which hasn't been released yet? It should contain some improvements. 
Instructions: https://github.com/elementary/appcenter#building-testing-and-installation

**Comment by tfinnm** [comment]
Disabling the daemon, doing a clean reboot again after the reboot required to disable it, then re-enabling it seems to have worked, for now, I must've messed something up. I'll close this issue and reopen it if this it turns out it is still happening. I'll also take a look at the latest version on Github, but I'm not entirely sure my elementary OS laptop is powerful enough to build it.
